export const COMMUNICATION_CONTEXT_IDENTIFIER_MARKETING_NOTIFICATION = 201;
export const COMMUNICATION_CONTEXT_IDENTIFIER_SMARTLIST = 202;
export const COMMUNICATION_CONTEXT_IDENTIFIER_OFFER = 203;
export const COMMUNICATION_CONTEXT_IDENTIFIER_MEMBER = 204;
export const COMMUNICATION_CONTEXT_IDENTIFIER_CADENCE = 205;
export const COMMUNICATION_CONTEXT_IDENTIFIER_FRANCHISE = 206;

export const COMMUNICATION_OBJECT_KEY_MEMBER = "member_id";
export const COMMUNICATION_OBJECT_KEY_SMARTLIST = "smartlist_id";
export const COMMUNICATION_OBJECT_KEY_FRANCHISE =
  "communication_sent_group_config_id";
export const COMMUNICATION_OBJECT_KEY_OFFER = "offer_id";
export const COMMUNICATION_OBJECT_KEY_NOTIFICATION_RULE =
  "notification_rule_id";
export const COMMUNICATION_OBJECT_KEY_MARKETING_NOTIFICATION =
  "marketing_notification_id";
export const COMMUNICATION_OBJECT_KEY_CADENCE_MARKETING_ACTION =
  "cadence_marketing_action_id";

export const COMMUNICATION_MAPPING_CONTEXT_IDENTIFIER_TO_OBJECT_KEY: {
  [key: number]: CommunicationObjectKey;
} = {
  [COMMUNICATION_CONTEXT_IDENTIFIER_MARKETING_NOTIFICATION]:
    COMMUNICATION_OBJECT_KEY_MARKETING_NOTIFICATION,
  [COMMUNICATION_CONTEXT_IDENTIFIER_SMARTLIST]:
    COMMUNICATION_OBJECT_KEY_SMARTLIST,
  [COMMUNICATION_CONTEXT_IDENTIFIER_OFFER]: COMMUNICATION_OBJECT_KEY_OFFER,
  [COMMUNICATION_CONTEXT_IDENTIFIER_MEMBER]: COMMUNICATION_OBJECT_KEY_MEMBER,
  [COMMUNICATION_CONTEXT_IDENTIFIER_CADENCE]:
    COMMUNICATION_OBJECT_KEY_CADENCE_MARKETING_ACTION,
  [COMMUNICATION_CONTEXT_IDENTIFIER_FRANCHISE]:
    COMMUNICATION_OBJECT_KEY_FRANCHISE,
};

export const COMMUNICATION_MAPPING_OBJECT_KEY_TO_CONTEXT_IDENTIFIER: Record<
  CommunicationObjectKey,
  number
> = {
  [COMMUNICATION_OBJECT_KEY_MARKETING_NOTIFICATION]:
    COMMUNICATION_CONTEXT_IDENTIFIER_MARKETING_NOTIFICATION,
  [COMMUNICATION_OBJECT_KEY_SMARTLIST]:
    COMMUNICATION_CONTEXT_IDENTIFIER_SMARTLIST,
  [COMMUNICATION_OBJECT_KEY_OFFER]: COMMUNICATION_CONTEXT_IDENTIFIER_OFFER,
  [COMMUNICATION_OBJECT_KEY_MEMBER]: COMMUNICATION_CONTEXT_IDENTIFIER_MEMBER,
  [COMMUNICATION_OBJECT_KEY_CADENCE_MARKETING_ACTION]:
    COMMUNICATION_CONTEXT_IDENTIFIER_CADENCE,
  [COMMUNICATION_OBJECT_KEY_FRANCHISE]:
    COMMUNICATION_CONTEXT_IDENTIFIER_FRANCHISE,
};

export type CommunicationObjectKey =
  | typeof COMMUNICATION_OBJECT_KEY_MARKETING_NOTIFICATION
  | typeof COMMUNICATION_OBJECT_KEY_SMARTLIST
  | typeof COMMUNICATION_OBJECT_KEY_OFFER
  | typeof COMMUNICATION_OBJECT_KEY_MEMBER
  | typeof COMMUNICATION_OBJECT_KEY_CADENCE_MARKETING_ACTION
  | typeof COMMUNICATION_OBJECT_KEY_FRANCHISE;
