import {
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
  COMMUNICATION_KIND_SMS,
} from '@bsport/common/lib/master-data/communication-kind.js';
import {
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
  COMMUNICATION_CHANNEL_SESSION,
  COMMUNICATION_CHANNEL_MARKETING_NOTIFICATION,
  COMMUNICATION_CHANNEL_NOTIFICATION_RULE,
  COMMUNICATION_CHANNEL_SMARTLIST,
  COMMUNICATION_CHANNEL_MESSAGE_DIRECT,
  COMMUNICATION_SEND_PARAMETER_AUTO,
  COMMUNICATION_SEND_PARAMETER_MANUAL,
  COMMUNICATION_SRC_OR_DST_SENT,
  COMMUNICATION_SRC_OR_DST_RECEIVED,
  COMMUNICATION_CHANNEL_CADENCE,
  COMMUNICATION_CHANNEL_FRANCHISE,
} from '@bsport/common/lib/master-data/communication-filters.js';
import { ChatThreadKinds } from '@bsport/common/lib/master-data/communication-inbox.js';

// CONTEXT
// TODO: use an enum to store this
export const CONTEXT_NOTIFICATION = 201;
export const CONTEXT_SMARTLIST = 202;
export const CONTEXT_OFFER = 203;
export const CONTEXT_MEMBER = 204;
export const CONTEXT_CADENCE = 205;
export const CONTEXT_FRANCHISE = 206;

// AVATAR GROUP DISPLAY
export const MAX_DISPLAY = 4;

// REFRESH THREAD
export const REFRESH_THREAD_TIMEOUT = 30; // seconds
export const REFRESH_THREAD_PAGINATION_SIZE = 5;

// --------- TO SEND MESSAGE ---------

// ACTION TYPE
export const WRITE_EMAIL = COMMUNICATION_KIND_EMAIL;
export const WRITE_SMS = COMMUNICATION_KIND_SMS;
export const WRITE_PUSH_NOTIFICATION = COMMUNICATION_KIND_PUSH_NOTIFICATION;

// SEND MESSAGE ENABLING
export const VALIDITY_INITIAL_VALUE = -1;
export const CAN_NOT_SEND_BECAUSE_MISSING_RECIPIENTS = 0;
export const CAN_NOT_SEND_BECAUSE_MISSING_CONTENT = 1;
export const CAN_NOT_SEND_BECAUSE_DIRECT_MEMBER_HAS_NOT_AN_EMAIL = 2;
export const CAN_NOT_SEND_BECAUSE_DIRECT_MEMBER_HAS_NOT_A_PHONE_NUMBER = 3;
export const CAN_SEND_MESSAGE = 4;

// SEND MESSAGE STATUS
export const COMMUNICATION_SENT_SENDING_PROCESSING = 1;
export const COMMUNICATION_SENT_SENDING_FAIL = 2;
export const COMMUNICATION_SENT_SENDING_SUCCESS = 3;

// TEXTFIELD CONTAINER IDENTIFIER
export const TEXTFIELD_MAIL_TITLE = 0;
export const TEXTFIELD_MAIL_CONTENT = 1;
export const TEXTFIELD_SMS_CONTENT = 2;
export const TEXTFIELD_NOTIFICATION_TITLE = 3;
export const TEXTFIELD_NOTIFICATION_CONTENT = 4;

// FILTERS IDENTIFIER
export const COMMUNICATION_FILTER_IDENTIFIER_KIND = 100;
export const COMMUNICATION_FILTER_IDENTIFIER_RECIPIENT = 101;
export const COMMUNICATION_FILTER_IDENTIFIER_CHANNEL = 102;
export const COMMUNICATION_FILTER_IDENTIFIER_SEND_PARAMETER = 103;
export const COMMUNICATION_FILTER_IDENTIFIER_SRC_OR_DST = 104;

// PAGINATION
export const PAGINATION_SIZE_RECIPIENTS = 8;

// MAX LENGTH OF WRITERS
export const MAX_LENGTH_SMS = 160;
export const MAX_LENGTH_AUTOMATIC_SMS = 70;
export const MAX_LENGTH_PUSH_CONTENT = 200;
export const MAX_LENGTH_PUSH_TITLE = 25;

// -----------------------------------

// --------- TO FILTER THREAD ---------

export const COMMUNICATION_FILTER_CHANNELS = {
  [COMMUNICATION_CHANNEL_SESSION]: 'offer_id',
  [COMMUNICATION_CHANNEL_MARKETING_NOTIFICATION]: 'marketing_notification_id',
  [COMMUNICATION_CHANNEL_SMARTLIST]: 'smartlist_id',
  [COMMUNICATION_CHANNEL_MESSAGE_DIRECT]: 'member_id',
  [COMMUNICATION_CHANNEL_NOTIFICATION_RULE]: 'notification_rule',
  [COMMUNICATION_CHANNEL_CADENCE]: 'cadence_marketing_action_id',
  [COMMUNICATION_CHANNEL_FRANCHISE]: 'communication_sent_group_config_id',
};

export const COMMUNICATION_FILTER_KINDS = [
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_SMS,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
];

export const COMMUNICATION_FILTER_SEND_PARAMETERS = [
  COMMUNICATION_SEND_PARAMETER_MANUAL,
  COMMUNICATION_SEND_PARAMETER_AUTO,
];

export const COMMUNICATION_FILTER_RECIPIENTS = [
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
];

export const COMMUNICATION_FILTER_SRC_OR_DST = [
  COMMUNICATION_SRC_OR_DST_SENT,
  COMMUNICATION_SRC_OR_DST_RECEIVED,
];
// ------------------------------------

// COMPANY COMMUNICATION PROVIDER
export const COMMUNICATION_KIND = {
  [COMMUNICATION_KIND_EMAIL]: 'email',
  [COMMUNICATION_KIND_PUSH_NOTIFICATION]: 'push_notification',
  [COMMUNICATION_KIND_SMS]: 'sms',
};

// ----------INBOX THREADS------------

export const INBOX_THREAD_PAGE_SIZE = 15;

// FILTERING

export const INBOX_ALL_MESSAGES = 0;
export const INBOX_UNREAD_MESSAGES = 1;
export const INBOX_FAVORITE_MESSAGES = 2;
export const INBOX_MUTED_MESSAGES = 3;
export const INBOX_DISABLED_MESSAGES = 4;

export const MAP_THREAD_KIND_TO_CONTEXT_IDENTIFIER = {
  [ChatThreadKinds.Member]: CONTEXT_MEMBER,
  [ChatThreadKinds.Offer]: CONTEXT_OFFER,
  [ChatThreadKinds.Smartlist]: CONTEXT_SMARTLIST,
};

// ------------ COMMUNICATION SCHEDULED ------------
export const COMMUNICATION_SCHEDULED_LIST_PAGINATION = 5;
export const MINUTE_LIMIT_TO_SCHEDULE_COMMUNICATION = 5;
export const HOUR_LIMIT_AFTER_SCHEDULED_COMMUNICATION = 12;

// ------------ COMMUNICATION DRAWER MODE ------------
export const COMMUNICATION_DRAWER_READ_ONLY_MODE = 'read-only';
export const COMMUNICATION_DRAWER_WRITE_ONLY_MODE = 'write-only';
export const COMMUNICATION_DRAWER_READ_WRITE_MODE = 'read-write';

// ------------ COMMUNICATION DRAWER ANIMATION ------------
export const WAIT_FOR_MESSAGE_SCHEDULER_ANIMATION = 500;
export const WAIT_FOR_AUTOMATED_CAMPAIGN_LIMIT_ANIMATION = 500;
export const WAIT_DRAWER_ANIMATION_TO_RESET_LIMIT = 300;
