export const API_URL = "book/";
export const API_V1_URL = `${API_URL}v1/`;

export enum BookableStatus {
  BOOKABLE = 0,
  CLOSE_TOO_SOON = 1,
  CLOSE_TOO_LATE = 2,
  FULL = 3,
  LOCKED = 4,
  ALREADY_BOOKED = 5,
  TOO_MANY_MALE = 6,
  TOO_MANY_FEMALE = 7,
  TOO_MANY_IN_FUTURE = 9,
  BLOCKED_BY_TAG = 10,
  BLOCKED_BY_ALL_OFFERS_FULL = 11,
  BLOCKED_BY_ONLY_FULL_GROUP_BOOKING = 12,
  GROUP_BLOCKED_MUST_BOOK_ALL_FUTURE_OFFERS = 13,
  BLOCKED_BY_HOST_HAS_NO_BOOKING = 14,
  NO_ANONYMOUS_USER = 15,
}

export enum WaitingListStatus {
  OPEN = 0,
  FULL = 6002,
  ALREADY_BOOKED = 6003,
  CONVERTIBLE = 6004,
  BY_PENDING_BOOKINGS = 6005,
}
