import type { Command } from "commander";
import path from "path";
import { writeFileSync } from "fs";
import {
  getAffectedProjectsPackageJsons,
  getProjectsPackageJsons,
  getMonorepoBasePath,
} from "@bsport/typescript-monorepo-utils";
import fs from "fs-extra";

enum FormatType {
  JSON = "json",
  TEXT = "text",
  MARKDOWN = "markdown",
  YAML = "yaml",
}

enum TargetType {
  CLI = "cli",
  PR = "pr",
  DEPLOYMENT = "deployment",
  GH_ACTIONS = "gh-actions",
}

type Project = Awaited<ReturnType<typeof getProjectsPackageJsons>>[string];

const DEPLOYMENT_SCRIPT = "ci:build-image";
const GH_ACTION_START_MARKER =
  "# <-- DO NOT REMOVE: START AUTOGENERATED OPTIONS -->";
const GH_ACTION_END_MARKER =
  "# <-- DO NOT REMOVE: END AUTOGENERATED OPTIONS -->";
const GH_ACTIONS_PATHS = [
  ".github/workflows/non-prod-build-single.yaml",
  ".github/workflows/prod-build-single.yaml",
];

/**
 * Runs the command.
 * @param options.format Format of the output.
 * @param options.target Target where the string should be printed.
 * @param options.affected Defines if the command should only print affected projects or all projects.
 */
async function action(options: {
  affected: boolean;
  base: string;
  format: FormatType;
  target: TargetType;
}) {
  try {
    validateInput(options);
    const groupedProjects = options.affected
      ? await getAffectedProjectsPackageJsons({ base: options.base })
      : await getProjectsPackageJsons();
    const output = formatProject(Object.values(groupedProjects), options);

    if (options.target === TargetType.DEPLOYMENT) {
      writeFileSync(".circleci/projects.json", output);
      return;
    }

    if (options.target !== TargetType.GH_ACTIONS) {
      console.log(output);
      return;
    }

    const monorepoBasePath = await getMonorepoBasePath();

    const githubActionsAbsPaths = GH_ACTIONS_PATHS.map((p) =>
      path.resolve(monorepoBasePath, p),
    );

    githubActionsAbsPaths.forEach((p) => {
      const content = fs.readFileSync(p, "utf-8").split("\n");
      const startMarkerIndex = content.findIndex((line) =>
        line.includes(GH_ACTION_START_MARKER),
      );
      const endMarkerIndex = content.findIndex((line) =>
        line.includes(GH_ACTION_END_MARKER),
      );

      const numberOfSpacesForList =
        content[startMarkerIndex - 1].replace(/[^ ]/g, "").length + 2;
      const list = output
        .split("\n")
        .map((line) =>
          line ? " ".repeat(numberOfSpacesForList) + line : line,
        );

      const newContent = [
        ...content.slice(0, startMarkerIndex),
        " ".repeat(numberOfSpacesForList) + GH_ACTION_START_MARKER,
        ...list,
        " ".repeat(numberOfSpacesForList) + GH_ACTION_END_MARKER,
        ...content.slice(endMarkerIndex + 1),
      ];
      fs.writeFileSync(p, newContent.join("\n"));
    });
  } catch (err) {
    console.error("❌ Error while running command");
    console.error(err);
  }
}

/**
 * Returns a formatted string of the projects.
 */
function formatProject(
  projects: Project[],
  options: Parameters<typeof action>[0],
): string {
  if (options.format === FormatType.JSON) {
    return formatAsJsonString(projects);
  }
  if (options.format === FormatType.TEXT) {
    return formatAsText(projects, options);
  }
  if (options.format === FormatType.MARKDOWN) {
    return formatAsMarkdown(projects, options);
  }
  if (options.format === FormatType.YAML) {
    return formatAsYaml(projects);
  }
}

function formatAsJsonString(projects: Project[]): string {
  return JSON.stringify(
    {
      projects: projects.reduce((acc: string[], project: Project) => {
        if (!project.packageJson.scripts?.[DEPLOYMENT_SCRIPT]) {
          return acc;
        }
        return [...acc, project.name];
      }, []),
    },
    null,
    2,
  );
}

function formatAsText(
  projects: Project[],
  options: Parameters<typeof action>[0],
): string {
  const maxNameLength = projects.reduce(
    (acc, project) => Math.max(acc, project.name.length),
    0,
  );
  const maxPathLength = projects.reduce(
    (acc, project) => Math.max(acc, project.path.length),
    0,
  );

  let result = "";
  if (options.target === TargetType.CLI) {
    result += `${"Project".padEnd(maxNameLength, " ")}  Path\n`;
    result += "-".repeat(maxNameLength + maxPathLength + 3) + "\n";
  }
  projects.forEach((project) => {
    result += `${project.name.padEnd(maxNameLength, " ")}  ${project.path}\n`;
  });
  return result;
}

function formatAsMarkdown(
  projects: Project[],
  options: Parameters<typeof action>[0],
): string {
  let result = "<details>";
  if (options.target === TargetType.PR) {
    result += `<summary>${projects.length} project${
      projects.length > 1 ? "s" : ""
    } affected by this PR${projects.length > 1 ? ":" : "."}</summary>\n\n`;
  }
  if (projects.length || options.target !== TargetType.PR) {
    result += "| Project | Path |\n";
    result += "|:-------:|:----:|\n";
  }
  projects.forEach((project) => {
    const projectName =
      options.target === TargetType.PR && project.packageJson.description
        ? project.packageJson.description
        : project.name;
    result += `| ${projectName} | ${project.path} |\n`;
  });
  result += "</details>";
  return result;
}

function formatAsYaml(projects: Project[]): string {
  const projectPaths = projects.reduce((acc, project) => {
    const paths = project.path.split("/");
    const projectPath = `- '--- ${paths
      .slice(0, paths.length - 1)
      .join("/")} ---'`;
    const projectName = project.name;
    if (!project.packageJson.scripts?.[DEPLOYMENT_SCRIPT]) {
      return acc;
    }
    return [
      ...acc,
      ...(acc.includes(projectPath) ? [] : ["", projectPath]),
      `- '${projectName.replace(/'/g, "\\'")}'`,
    ];
  }, [] as string[]);
  return projectPaths.join("\n");
}

/**
 * Validates the inputs and throws an error if invalid.
 */
function validateInput(...args: Parameters<typeof action>) {
  if (!Object.values(TargetType).includes(args[0].target)) {
    throw new Error(
      `Invalid target option "${
        args[0].target
      }".\nValid values: ${Object.values(TargetType).join(", ")}`,
    );
  }
  if (!Object.values(FormatType).includes(args[0].format)) {
    throw new Error(
      `Invalid format option "${
        args[0].format
      }".\nValid values: ${Object.values(FormatType).join(", ")}`,
    );
  }
  if (
    args[0].target === TargetType.PR &&
    args[0].format !== FormatType.MARKDOWN
  ) {
    throw new Error(
      `Please set format to ${FormatType.MARKDOWN} if you want to target in PR`,
    );
  }
  if (
    args[0].target === TargetType.GH_ACTIONS &&
    args[0].format !== FormatType.YAML
  ) {
    throw new Error(
      `Please set format to ${FormatType.YAML} if you want to target in GitHub Actions`,
    );
  }
  if (args[0].target === TargetType.GH_ACTIONS && args[0].affected) {
    throw new Error(
      "Please do not set affected option if you want to target in GitHub Actions",
    );
  }
}

export default function projectAffectedList(program: Command) {
  program
    .command("project:list")
    .description("Lists all monorepository projects")
    .option(
      "-a, --affected",
      "only list projects that will be affected by the current changes (compared to base).",
      false,
    )
    .option(
      "-b, --base <base>",
      "only available if --affected is specified - base branch / commit to compare to.",
      "origin/main",
    )
    .option(
      "-f, --format <format>",
      `format of the output. Available options: ${Object.values(
        FormatType,
      ).join(", ")}`,
      FormatType.TEXT,
    )
    .option(
      "-t, --target <target>",
      `target where the output will be displayed. Available options: ${Object.values(
        TargetType,
      ).join(", ")}`,
      TargetType.CLI,
    )
    .action(action);
  return program;
}
