import React from 'react';
import { ComponentMeta, ComponentStory } from '@storybook/react';
import PriceCount, {
  PriceCountStorybook,
} from '#src/libs/checkout/components/new-checkout-flow/PriceCount';
import type { Props } from '#src/libs/checkout/components/new-checkout-flow/PriceCount';
import {
  basketFactory,
  checkoutItemFactory,
} from '#src/libs/checkout/factories';
import { BUYABLE_ITEM_COUPON } from '@bsport/common/master-data/buyable-items.js';

const PriceCountStorybookTemplate: ComponentStory<
  typeof PriceCountStorybook
> = (args) => (
  <PriceCountStorybook {...args}>{args.children}</PriceCountStorybook>
);

const defaultArgs: Props = {
  basket: {
    ...basketFactory(2, {}),
    prepaid_lines: [],
    company: 'company',
  },
  isDeleteButtonDisabled: false,
  onRemoveCheckoutItem: () => {},
  hideTotal: false,
  isExcludingTax: false,
  onRemoveInternalAccountPrepaidLine: () => {},
};

const warningArgs: Props = {
  ...defaultArgs,
  basket: {
    ...defaultArgs.basket,
    checkout_items: [
      checkoutItemFactory({
        name: 'referral discount',
        buyable_item_identifier: BUYABLE_ITEM_COUPON,
        extra_data: {
          referral_coupon_type: 'referral',
          is_applied: false,
          missing_amount_before_application: 10,
        },
      }),
    ],
  },
};

const maxUsesReachedArgs: Props = {
  ...defaultArgs,
  basket: {
    ...defaultArgs.basket,
    checkout_items: [
      checkoutItemFactory({
        name: 'referral discount',
        buyable_item_identifier: BUYABLE_ITEM_COUPON,
        extra_data: {
          referral_coupon_type: 'referral',
          is_applied: false,
          has_reached_max_uses: true,
        },
      }),
    ],
  },
};

const notAppliedArgs: Props = {
  ...defaultArgs,
  basket: {
    ...defaultArgs.basket,
    checkout_items: [
      checkoutItemFactory({
        name: 'crazy discount',
        buyable_item_identifier: BUYABLE_ITEM_COUPON,
        extra_data: {
          is_applied: false,
        },
      }),
    ],
  },
};

export const BasePriceCount = PriceCountStorybookTemplate.bind({});
BasePriceCount.args = defaultArgs;

export const PriceCountWithReferralWarning = PriceCountStorybookTemplate.bind(
  {},
);
PriceCountWithReferralWarning.args = warningArgs;

export const PriceCountReferralMaxUses = PriceCountStorybookTemplate.bind({});
PriceCountReferralMaxUses.args = maxUsesReachedArgs;

export const DiscountNotAppliedPriceCount = PriceCountStorybookTemplate.bind(
  {},
);
DiscountNotAppliedPriceCount.args = notAppliedArgs;

const componentMeta: ComponentMeta<typeof PriceCount> = {
  title: 'Library/checkout/PriceCount',
  component: PriceCount,
  argTypes: {
    prepaidLines: {
      description:
        'Generated by credit account and gift cards. Represents the money you already have on your account',
    },
    basket: {
      description:
        'Your basket. Contains checkout items, which can be discounts, referral discounts, or regular items',
    },
  },
  parameters: {
    layout: 'centered',
  },
};

export default componentMeta;
