export const PAGE_SIZE = 10;

export enum ReplacementDisplays {
  REPLACEMENT_DISPLAY_CALENDAR = 1,
  REPLACEMENT_DISPLAY_REQUEST_PENDING = 2,
  REPLACEMENT_DISPLAY_REQUEST_TEACHER_FOUND = 3,
  REPLACEMENT_DISPLAY_CONFIRM = 4,
  REPLACEMENT_DISPLAY_MARKETPLACE = 5,
  REPLACEMENT_REQUEST_MANAGER_ACTIONS = 6,
  REPLACEMENT_REQUEST_MANAGER_HISTORY = 7,
}

export enum ReplacementRequestStatus {
  REPLACEMENT_REQUEST_STATUS_WITH_NO_REPLACEMENT_PROPOSITIONS = 1,
  REPLACEMENT_REQUEST_STATUS_WITH_REPLACEMENT_PROPOSITIONS = 2,
  REPLACEMENT_REQUEST_STATUS_TEACHER_FOUND = 3,
  REPLACEMENT_REQUEST_STATUS_REFUSED_BY_MANAGER = 4,
  REPLACEMENT_REQUEST_STATUS_CANCELLED_BY_TEACHER = 5,
  REPLACEMENT_REQUEST_STATUS_CLOSED_BECAUSE_COACH_UPDATED_BY_MANAGER = 6,
  REPLACEMENT_REQUEST_STATUS_SUBSTITUTE_UNAVAILABLE = 7,
  REPLACEMENT_REQUEST_STATUS_DISPLAYED_AS_CANCELLED_BECAUSE_OFFER_IS_CANCELLED = 8,
}

export enum ReplacementRequestCoachAnswerStatus {
  REPLACEMENT_REQUEST_COACH_STATUS_YES = 1,
  REPLACEMENT_REQUEST_COACH_STATUS_RATHER_NO = 2,
  REPLACEMENT_REQUEST_COACH_STATUS_NO = 3,
}

export enum ReplacementRequestPaginationByStatus {
  Pending = 'pending',
  TeacherFound = 'teacherFound',
}

export const REPLACEMENT_REQUEST_STATUS_LABELS = {
  [ReplacementRequestStatus.REPLACEMENT_REQUEST_STATUS_WITH_NO_REPLACEMENT_PROPOSITIONS]:
    'approvedButNoReplacementPropositions',
  [ReplacementRequestStatus.REPLACEMENT_REQUEST_STATUS_WITH_REPLACEMENT_PROPOSITIONS]:
    'approvedWithReplacementPropositions',
  [ReplacementRequestStatus.REPLACEMENT_REQUEST_STATUS_TEACHER_FOUND]:
    'teacherFound',
  [ReplacementRequestStatus.REPLACEMENT_REQUEST_STATUS_DISPLAYED_AS_CANCELLED_BECAUSE_OFFER_IS_CANCELLED]:
    'offerCancelled',
};

export const REPLACEMENT_REQUEST_COACH_ANSWER_STATUS_LABELS = {
  [ReplacementRequestCoachAnswerStatus.REPLACEMENT_REQUEST_COACH_STATUS_YES]:
    'yes',
  [ReplacementRequestCoachAnswerStatus.REPLACEMENT_REQUEST_COACH_STATUS_RATHER_NO]:
    'ratherNo',
  [ReplacementRequestCoachAnswerStatus.REPLACEMENT_REQUEST_COACH_STATUS_NO]:
    'no',
};

export const REPLACEMENT_REQUEST_DISABLED_REASONS = {
  REPLACEMENT_REQUEST_DISABLED_OFFER_ALREADY_PASSED: 'alreadyPassed',
  REPLACEMENT_REQUEST_DISABLED_ALREADY_REPLACING_OFFER: 'replacing',
  REPLACEMENT_REQUEST_DISABLED_ALREADY_ASKED_FOR: 'alreadyAskedFor',
  REPLACEMENT_REQUEST_DISABLED_NO_LATE_REQUESTS_LEFT: 'noLateRequestsLeft',
  REPLACEMENT_REQUEST_DISABLED_REFUSED_BY_MANAGER: 'refusedByManager',
};

// These displays require offers for rendering
export const REPLACEMENT_DISPLAYS_OFFERS = [
  ReplacementDisplays.REPLACEMENT_DISPLAY_CALENDAR,
  ReplacementDisplays.REPLACEMENT_REQUEST_MANAGER_HISTORY,
];

// These displays require replacement requests for rendering
export const REPLACEMENT_DISPLAYS_REPLACEMENT_REQUESTS = [
  ReplacementDisplays.REPLACEMENT_DISPLAY_MARKETPLACE,
  ReplacementDisplays.REPLACEMENT_DISPLAY_REQUEST_PENDING,
  ReplacementDisplays.REPLACEMENT_DISPLAY_REQUEST_TEACHER_FOUND,
  ReplacementDisplays.REPLACEMENT_REQUEST_MANAGER_ACTIONS,
  ReplacementDisplays.REPLACEMENT_DISPLAY_CONFIRM,
];

// For the establishment/location selector with the subteacher and multilocation upsells
export enum MultilocationChoice {
  Locations = 'locations',
  Establishments = 'establishments',
}
