import Config from '#src/config';
import {
  EXPORTABLE_COMPONENT_TYPE_REFERRAL,
  EXPORTABLE_COMPONENT_TYPE_CONSUMER_BOOKING,
  EXPORTABLE_COMPONENT_TYPE_CONSUMER_PASS,
  EXPORTABLE_COMPONENT_TYPE_CONSUMER_SPACE,
} from '#src/libs/exportable-components/constants/widget_builder';
import {
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_LOGIN_BUTTON,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
  EXPORTABLE_COMPONENT_TYPE_PAYMENT_PACK_TEMPLATE,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR_V2,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER_V2,
} from '../exportable-components/constants';

const displayMemberProfileWidget = !['production'].includes(
  Config.REACT_APP_SENTRY_ENVIRONMENT,
);

export const WIDGET_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR_V2,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_LOGIN_BUTTON,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER_V2,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
  EXPORTABLE_COMPONENT_TYPE_PAYMENT_PACK_TEMPLATE,
  EXPORTABLE_COMPONENT_TYPE_REFERRAL,
  ...(displayMemberProfileWidget
    ? [
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_BOOKING,
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_PASS,
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_SPACE,
      ]
    : []),
];

export const WIDGET_NOT_FRANCHISOR_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_LOGIN_BUTTON,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER_V2,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
  EXPORTABLE_COMPONENT_TYPE_REFERRAL,
  ...(displayMemberProfileWidget
    ? [
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_BOOKING,
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_PASS,
        EXPORTABLE_COMPONENT_TYPE_CONSUMER_SPACE,
      ]
    : []),
];

export const WIDGET_FRANCHISOR_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_PAYMENT_PACK_TEMPLATE,
  EXPORTABLE_COMPONENT_TYPE_LOGIN_BUTTON,
];

export const CSS_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_NEWSLETTER_V2,
  EXPORTABLE_COMPONENT_TYPE_REFERRAL,
];
