export enum WidgetMessageType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  AUTHENTICATED_STATUS_READY = 'AUTHENTICATED_STATUS_READY',
  BASKET_COUNT_READY = 'BASKET_COUNT_READY',
  BOOKINGS_COUNT_READY = 'BOOKINGS_COUNT_READY',
  AUTHENTICATED_STATUS = 'AUTHENTICATED_STATUS',
  BASKET_COUNT = 'BASKET_COUNT',
  BOOKINGS_COUNT = 'BOOKINGS_COUNT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  GET_AUTHENTICATED_STATUS = 'GET_AUTHENTICATED_STATUS',
  GET_BASKET_COUNT = 'GET_BASKET_COUNT',
  GET_BOOKINGS_COUNT = 'GET_BOOKINGS_COUNT',
  LOGOUT = 'LOGOUT',
}
