import { ActionFunctionAny } from 'redux-actions';
import { Action } from 'redux';
import { OptionCallback, ThunkAction } from '../../state/types';

export enum WidgetMessageType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  VIDEO_REGISTERED = 'VIDEO_REGISTERED',
  AUTHENTICATED_STATUS_READY = 'AUTHENTICATED_STATUS_READY',
  BASKET_COUNT_READY = 'BASKET_COUNT_READY',
  BOOKINGS_COUNT_READY = 'BOOKINGS_COUNT_READY',
  AUTHENTICATED_STATUS = 'AUTHENTICATED_STATUS',
  BASKET_COUNT = 'BASKET_COUNT',
  BOOKINGS_COUNT = 'BOOKINGS_COUNT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  GET_AUTHENTICATED_STATUS = 'GET_AUTHENTICATED_STATUS',
  GET_BASKET_COUNT = 'GET_BASKET_COUNT',
  GET_BOOKINGS_COUNT = 'GET_BOOKINGS_COUNT',
  LOGOUT = 'LOGOUT',
  CLOSE_MODAL = 'CLOSE_MODAL',

  REQUEST_BOOKING_COUNT = 'REQUEST_BOOKING_COUNT',
  REQUEST_AUTHENTICATED_STATUS = 'REQUEST_AUTHENTICATED_STATUS',
  REQUEST_BOOKINGS_COUNT = 'REQUEST_BOOKINGS_COUNT',
  RESPONSE_LOGIN_SUCCESS = 'RESPONSE_LOGIN_SUCCESS',
  REQUEST__AUTHENTICATED_STATUS = 'REQUEST__AUTHENTICATED_STATUS',
  REQUEST_BASKET_COUNT = 'REQUEST_BASKET_COUNT',
  REQUEST_LOGOUT = 'REQUEST_LOGOUT',
  REQUEST_REGISTERED_OFFER_IDS = 'REQUEST_REGISTERED_OFFER_IDS',

  RESPONSE_PAYMENT_SUCCESS = 'RESPONSE_PAYMENT_SUCCESS',
  RESPONSE_AUTHENTICATED_STATUS = 'RESPONSE_AUTHENTICATED_STATUS',
  RESPONSE_BASKET_COUNT = 'RESPONSE_BASKET_COUNT',
  RESPONSE_BOOKINGS_COUNT = 'RESPONSE_BOOKINGS_COUNT',
  REQUEST_MEMBER_TAG = 'REQUEST_MEMBER_TAG',
  REQUEST_PLAYBACK_URL = 'REQUEST_PLAYBACK_URL',

  RESPONSE_PLAYBACK_URL_ACCESS_DENIED = 'RESPONSE_PLAYBACK_URL_ACCESS_DENIED',
  RESPONSE_PLAYBACK_URL_SUCCESS = 'RESPONSE_PLAYBACK_URL_SUCCESS',
  RESPONSE_PLAYBACK_URL_ERROR = 'RESPONSE_PLAYBACK_URL_ERROR',
  RESPONSE_REGISTERED_OFFER_IDS = 'RESPONSE_REGISTERED_OFFER_IDS',

  RESPONSE_CLOSE_SUBSCRIPTION_MODAL_ON_ERROR = 'RESPONSE_CLOSE_SUBSCRIPTION_MODAL_ON_ERROR',
}

export const widgetApiMessageTypes = [
  'MEMBERSHIP_BY_COMPANY',
  'FETCH_MEMBER_BY_ID',
  'FETCH_REFERRAL_PROGRAM_MEMBER_STATUS',
  'FETCH_REFERRAL_PROGRAM_BY_COMPANY',
  'FETCH_PAST_BOOKING_AS_MEMBER',
  'FETCH_FUTURE_BOOKING_AS_MEMBER',
  'FETCH_BOOKING_OPTION_AS_MEMBER',
  'FETCH_BOOKING_OPTION_WORKSHOP_AS_MEMBER',
  'FETCH_PAST_PRIVATE_BOOKING_AS_MEMBER',
  'FETCH_FUTURE_PRIVATE_BOOKING_AS_MEMBER',
  'FETCH_PAST_BOOKING_WORKSHOP_AS_MEMBER',
  'FETCH_FUTURE_BOOKING_WORKSHOP_AS_MEMBER',
  'FETCH_COACH_BULK',
  'FETCH_GROUP_OFFER',
  'FETCH_LEVEL_LIST',
  'FETCH_META_ACTIVITY_BULK',
  'FETCH_OFFER_BULK',
  'FETCH_ESTABLISHMENT_BULK',
  'FETCH_CONSUMER_PACK_BULK',
  'FETCH_PAYMENT_PACK_BULK',
  'FETCH_ROOM_BLUE_PRINT',
  'FETCH_SPOT_FOR_BLUEPRINT',
  'ASSETS_FOR_BLUE_PRINT',
  'PRIVATE_CONSUMER_PASS_BULK',
  'PRIVATE_SLOT_BULK',
  'PRIVATE_SERVICE_BULK',
  'CANCEL_BOOKING_AS_MEMBER',
  'CANCEL_PRIVATE_BOOKING_AS_MEMBER',
  'CANCEL_BOOKING_OPTION_AS_MEMBER',
  'FETCH_RELATED_MEMBERS_NAMES_BY_CONSUMER_PAYMENT_PACK_LINK',
  'FETCH_RELATED_MEMBERS_NAMES_BY_PRIVATE_CONSUMER_PASS_LINK',
  'FETCH_PRIVATE_PASS_BULK',
  'FETCH_PRIVATE_SERVICE_COMPATIBLE_PASS_LIST',
  'FETCH_PASSES_TABS',
  'FETCH_ACTIVE_CONSUMER_PAYMENT_PACK_AS_MEMBER',
  'FETCH_ACTIVE_PRIVATE_CONSUMER_PASS_AS_MEMBER',
  'FETCH_ACTIVE_UNIVERSAL_PASSES_AS_MEMBER',
  'FETCH_EXPIRED_CONSUMER_PAYMENT_PACK_AS_MEMBER',
  'FETCH_EXPIRED_PRIVATE_CONSUMER_PASS_AS_MEMBER',
  'FETCH_EXPIRED_UNIVERSAL_PASS_AS_MEMBER',
  'FETCH_FUTURE_CONSUMER_PAYMENT_PACK_AS_MEMBER',
  'FETCH_FUTURE_PRIVATE_CONSUMER_PASS_AS_MEMBER',
  'FETCH_FUTURE_UNIVERSAL_PASS_AS_MEMBER',
] as const;

export type WidgetApiMessageType = (typeof widgetApiMessageTypes)[number];

/**
 * @deprecated loading does not follow the boolean naming convention. Added to
 * have iso naming between widget and SaaS
 */

type LegacyApiCallActions = {
  success: ActionFunctionAny<Action<any>>;
  loading: ActionFunctionAny<Action<any>>;
  error: ActionFunctionAny<Action<any>>;
};

type CorrectApiCallActions = {
  success: ActionFunctionAny<Action<any>>;
  isLoading: ActionFunctionAny<Action<any>>;
  error: ActionFunctionAny<Action<any>>;
};

export type CallAction<A, R> = (
  args: A,
  options?: OptionCallback<R>,
) => ThunkAction;

export type ApiCallActions = CorrectApiCallActions | LegacyApiCallActions;
