export const fakeData = [
  {
    firstname: 'Academy',
    lastname: 'Ayurveda',
    name: 'Academy Ayurveda',
    gender: 'F',
    rating: '-1.00',
    id: 23667,
    birthday: null,
    photo:
      'http://testserver:8000/media/user/Ayurveda_Delight_Academy_PE_Header_27L4MWQ.jpg',
    description: '',
    color: '',
    email: 'ayurveda@delightacademy.com',
    associated_coach_id: 24844,
    associatedcoach_set: [24844],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Adela',
    lastname: 'Serrano',
    name: 'Adela Serrano',
    gender: 'F',
    rating: '-1.00',
    id: 20622,
    birthday: '1978-01-01',
    photo: 'http://testserver:8000/media/user/Adela.jpeg',
    description:
      'Adela, originally from Spain, has lived in different cities since 2000. Her Yoga journey started in New York while she was facing a major change in her life; motherhood. Practicing Yoga helped her to feel more at home with herself and her changing circumstances.  \r\n\r\n \r\n\r\nShe felt inspired to teach thanks to one of her first teachers in New York, Jenny Aurthur who as she says: "Literally pulled out the best of me and helped me in my journey." Maty Ezraty and Carrie Owerko were great sources of inspiration in her New York years. Once in Amsterdam, she became a certified Iyengar teacher with the help of Barbara Queirolo, Kristien Van Reusel and Rembert Petrus. On top of that, she likes to call her life, her family, relationships and her students her true teachers.\r\n\r\n \r\n\r\nHer classes follow the Iyengar tradition with a safe, compassionate and skilful approach. Extensive anatomy knowledge makes her teaching style very safe but also challenging for all levels. According to the old Yoga teachings, her classes bring attention to the poses and movements/actions as a way to access a more refined body and mind awareness. She also specializes in injury prevention and injury recovery.  "I like to demystify complex concepts to make the practice of Yoga applicable to everyday life, I am a devoted student and practitioner and I bring my all in every class I teach. I have been honoured to be able to teach at Delight yoga almost since they started, and you can find me in their studios for classes and workshops in Amsterdam and in Den Haag." \r\n\r\n \r\n\r\n "It is through your body that you realize you are a spark of divinity". B.K.S. Iyengar',
    phone: '+31 6 45659198',
    color: '',
    email: 'adelasp@hotmail.com',
    associated_coach_id: 21378,
    associatedcoach_set: [21378],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: 'instagram.com/adelaserranoyoga/AdAdel',
    performance: {
      '0': [
        {
          session_id: 4549931,
          session_name: 'Hatha - Pre-recorded',
          date_start: '2022-01-07 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 9,
          cancelled_bookings: 1,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4549932,
          session_name: 'Hatha - Pre-recorded',
          date_start: '2022-01-14 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 16,
          cancelled_bookings: 0,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4087160,
          session_name: 'Vinyasa',
          date_start: '2022-01-17 16:00:00+00:00',
          duration_minute: 75,
          confirmed_bookings: 3,
          cancelled_bookings: 0,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '11.25',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4093381,
          session_name: 'Vinyasa',
          date_start: '2022-01-18 11:15:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 5,
          cancelled_bookings: 0,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '18.75',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4094441,
          session_name: 'Hatha',
          date_start: '2022-01-19 09:15:00+00:00',
          duration_minute: 90,
          confirmed_bookings: 8,
          cancelled_bookings: 3,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '35.64',
          coach_total_payment: '35.64',
          error: false,
        },
        {
          session_id: 4549933,
          session_name: 'Hatha - Pre-recorded',
          date_start: '2022-01-21 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 2,
          cancelled_bookings: 7,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4087161,
          session_name: 'Vinyasa',
          date_start: '2022-01-24 16:00:00+00:00',
          duration_minute: 75,
          confirmed_bookings: 6,
          cancelled_bookings: 1,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '24.38',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4094442,
          session_name: 'Hatha',
          date_start: '2022-01-26 09:15:00+00:00',
          duration_minute: 90,
          confirmed_bookings: 8,
          cancelled_bookings: 2,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '33.76',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4549934,
          session_name: 'Hatha - Pre-recorded',
          date_start: '2022-01-28 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 0,
          cancelled_bookings: 6,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4096939,
          session_name: 'Vinyasa',
          date_start: '2022-01-28 11:15:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 2,
          cancelled_bookings: 2,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '11.26',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4087162,
          session_name: 'Vinyasa',
          date_start: '2022-01-31 16:00:00+00:00',
          duration_minute: 75,
          confirmed_bookings: 6,
          cancelled_bookings: 1,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '24.38',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4087366,
          session_name: 'Hatha',
          date_start: '2022-01-31 17:45:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 5,
          cancelled_bookings: 1,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '20.63',
          coach_total_payment: '35.00',
          error: false,
        },
      ],
      '1': [
        {
          private_booking_id: 171527,
          private_service_name: 'A private Yoga Class',
          date_start: '2022-01-27 08:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 1,
          cancelled_bookings: 0,
          coach_payment_rule: null,
          base_remuneration: '0.00',
          coach_bonus: '34.17',
          coach_total_payment: '34.17',
          error: false,
        },
        {
          private_booking_id: 170189,
          private_service_name: 'A private Yoga Class',
          date_start: '2022-01-28 08:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 1,
          cancelled_bookings: 0,
          coach_payment_rule: null,
          base_remuneration: '0.00',
          coach_bonus: '34.17',
          coach_total_payment: '34.17',
          error: false,
        },
      ],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Adela Serrano',
    lastname: '& Ira Hardjosusono',
    name: 'Adela Serrano & Ira Hardjosusono',
    gender: 'F',
    rating: '-1.00',
    id: 23670,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Adela__Ira_rxCTojx.jpeg',
    description:
      'About Adela Serrano\n\nAdela, originally from Spain, has lived in different cities since 2000. Her Yoga journey started in New York while she was facing a major change in her life; motherhood. Practicing Yoga helped her to feel more at home with herself and her changing circumstances. \n\nShe felt inspired to teach thanks to one of her first teachers in New York, Jenny Aurthur who as she says: "Literally pulled out the best of me and helped me in my journey." Maty Ezraty and Carrie Owerko were great sources of inspiration in her New York years. Once in Amsterdam, she became a certified Iyengar teacher with the help of Barbara Queirolo, Kristien Van Reusel and Rembert Petrus. On top of that, she likes to call her life, her family, relationships and her students her true teachers.\n\nHer classes follow the Iyengar tradition with a safe, compassionate and skilful approach. Extensive anatomy knowledge makes her teaching style very safe but also challenging for all levels. According to the old Yoga teachings, her classes bring attention to the poses and movements/actions as a way to access a more refined body and mind awareness. She also specializes in injury prevention and injury recovery.  "I like to demystify complex concepts to make the practice of Yoga applicable to everyday life, I am a devoted student and practitioner and I bring my all in every class I teach. I have been honoured to be able to teach at Delight yoga almost since they started, and you can find me in their studios for classes and workshops in Amsterdam and in Den Haag." \n\n "It is through your body that you realize you are a spark of divinity". B.K.S. Iyengar\n\nFollow her on Instagram: @adelaserranoyoga\n\n\n\nAbout Ira Hardjosusono\n\nIra’s yoga classes are moved from simplicity and joy. The only practice is to purify the body, energy and mind all the way.\n\nVia traditional Hatha Yoga Ira met her teacher and guide Katiza Satya in 2005. Inspired and always listening to the movement of the moment she came in contact with Astanga Vinyasa Yoga, which provided a solid foundation for deepening of her practice through intensives and retreats, including Delight Sva-Dharma Teacher Training / The Body, The Mind and The Heart (all three levels of Delight Advanced studies), Vipassana meditation and Healing Yoga. \n\nIn deep trust Ira allowed her curiosity to lead her organically in the direction of meditation and Buddhism. She has received direct and indirect teachings of teachers and masters, Sri Ramana Maharshi, Ida Resi Alit, Namkai Norbu Rimpoche, Tenzin Wangyal Rimpoche, Dokt. Nida, Thich Nhat Hanh, BKS Iyengar, Tsulstrim Allione, and is moved in all ways trough a direct living relation with Satya Katiza Ivulic and Sahaj Wood. \n\nIra is a teacher at Delight Yoga. She is a registered RYT / Yoga Alliance Teacher and deeply devoted to the never-ending study of Yoga and Meditation in their many forms. From an open mind, she is able to share diverse practice in Hatha/, Healing, Mantra and /Meditation classes, Women\'s Circles and loves direct heart to heart sessions in Privates/ Guidance.\n\nIra inspires her students to move from the breath, with heart and soul In truth, simplicity and love.  A constant invitation to remember who we are, in every posture, in every situation of life, let our practice be practical and simple again and again.  ',
    color: '',
    email: null,
    associated_coach_id: 24847,
    associatedcoach_set: [24847],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Adelene',
    lastname: 'Cheong',
    name: 'Adelene Cheong',
    gender: 'F',
    rating: '-1.00',
    id: 5372,
    birthday: null,
    photo: 'http://testserver:8000/media/user/yoga-with-adelene-cheong_1.jpg',
    description:
      'E-RYT / YACEP / SYT / BWY Teacher / Adv R&R® Trainer / Certified iRest® Teacher\r\n​\r\nA practitioner, a student, a teacher and trainer of yoga... Adelene feels blessed to be on this path with many who seek love, peace and stillness. Through yoga, Adelene reconnects to being truly integrated in life and all it has to offer.\r\n\r\nHaving been diagnosed with a progressive S-curve scoliosis at age 13, some physical activities were limited within, and outside school. She was not very active in her growing up years, and experienced chronic back pain, which was possibly exacerbated by increasingly sedentary when she started college. When she was told that she may be confined to using a wheelchair should the condition deteriorate, and may have to be bed-ridden for the second half of pregnancy should she become pregnant, life ahead seemed bleak and painful. It was emotionally and mentally devastating.\r\n \r\nAdelene met yoga in her early twenties. She studied, explored, committed to her practice therapeutically and dedicatedly for years. She is now more active then ever before, manages her back condition with confidence, and reinvented life for herself. There has been a positive regression observed and confirmed with medical records, and more importantly, she feels positive and motivated by her condition. Adelene now enjoys horse-riding, scuba diving, all season hiking and some high intensity spin classes.',
    phone: '+4407717411335',
    color: '',
    email: 'yoga@adelenecheong.com',
    associated_coach_id: 21379,
    associatedcoach_set: [5561, 21379],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: 'https://www.facebook.com/adeleneyoga',
    instagram_url: 'https://www.instagram.com/adeleneyoga/',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Agnes',
    lastname: 'Vissering',
    name: 'Agnes Vissering',
    gender: 'F',
    rating: '-1.00',
    id: 20623,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Agnes.jpeg',
    description:
      'Agnes discovered yoga in 2000 in Bali. Continuing her travels through India and Scandinavia, yoga became her lifelong path. She went back to India many times to deepen her practice and eventually to teach. A regular yoga practice affected her life in such a positive way that it slowed down her turbulent lifestyle. She feels that yoga is her guidance in everyday life. She’s found more balance, strength and acceptance, not only on a physical level but also in her mental and spiritual wellbeing. To deepen her practice and understanding, she completed teacher trainings with Katiza Satya and Hilary Menting in 2007 and another one in 2009.\r\n\r\n \r\n\r\nMany studies and workshop followed with Pattabhi Jois, Petri Raisanen Shri.V.Sheshadri, Vijay Amar, Anthony ”Prem” Carlisi, Luke Jordan, David Garrigues, David Swenson and Claudia Pradella. These and many other great teachers helped and inspired her on this ever-evolving and challenging path called yoga. Agnes discovered that through her own process and practice the teacher in her came alive. She started teaching in 2007. Even though Ashtanga is her main practice, she also studied and teaches Vinyasa and Hatha.\r\n\r\n \r\n\r\nMoreover, Agnes is also a Thai Yoga masseuse. The healing power of touching people is perfectly connected to her yoga teachings. Between 2007 and 2015 she studied Ayurvedic massage in Mysore, Thai yoga massage with Sebastian Bruno, Leffelaar classical massage training, Various Thai yoga massage training with Ces Mossel, Advanced stretches Thai yoga massage with Izhak Hellman (Sunshine Network). The immemorial techniques of Thai Yoga Massage are based on traditional cures with Indian influences, which inspire Agnes very much. She softly but decisively guides you to reconnect to your body, breath, and takes you into postures, creating a new flow of energy, cultivating a sense of awareness, and peace of mind.',
    phone: '+31625021905',
    color: '',
    email: 'senga71@hotmail.com',
    associated_coach_id: 21380,
    associatedcoach_set: [21380],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [
        {
          session_id: 4737874,
          session_name: 'Ashtanga Led',
          date_start: '2022-01-18 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 0,
          cancelled_bookings: 0,
          coach_payment_rule: -1,
          base_remuneration: '-1.00',
          coach_bonus: '-1.00',
          coach_total_payment: '-1.00',
          error: true,
        },
        {
          session_id: 4001370,
          session_name: 'Vinyasa',
          date_start: '2022-01-18 07:30:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 2,
          cancelled_bookings: 0,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '7.50',
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4003461,
          session_name: 'Ashtanga Led',
          date_start: '2022-01-21 11:00:00+00:00',
          duration_minute: 75,
          confirmed_bookings: 7,
          cancelled_bookings: 1,
          coach_payment_rule: 1219,
          base_remuneration: '0.00',
          coach_bonus: '28.13',
          coach_total_payment: '35.00',
          error: false,
        },
      ],
      '1': [
        {
          private_booking_id: 171091,
          private_service_name: 'A private Yoga Class',
          date_start: '2022-01-21 07:45:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 1,
          cancelled_bookings: 0,
          coach_payment_rule: null,
          base_remuneration: '0.00',
          coach_bonus: '34.17',
          coach_total_payment: '34.17',
          error: false,
        },
        {
          private_booking_id: 171560,
          private_service_name: 'A private Yoga Class',
          date_start: '2022-01-24 09:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 1,
          cancelled_bookings: 0,
          coach_payment_rule: null,
          base_remuneration: '0.00',
          coach_bonus: '34.17',
          coach_total_payment: '34.17',
          error: false,
        },
        {
          private_booking_id: 172494,
          private_service_name: 'A private Yoga Class',
          date_start: '2022-01-28 08:30:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 1,
          cancelled_bookings: 0,
          coach_payment_rule: null,
          base_remuneration: '0.00',
          coach_bonus: '34.17',
          coach_total_payment: '34.17',
          error: false,
        },
      ],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Albert',
    lastname: 'Garcia Ordinas',
    name: 'Albert Garcia Ordinas',
    gender: 'M',
    rating: '-1.00',
    id: 20624,
    birthday: '1990-11-01',
    photo: 'http://testserver:8000/media/user/Albert.jpeg',
    description:
      'Albert is a former contemporary dancer and has been always fascinated by the power of movement and expression of emotions. During his dance career he appreciated every opportunity he had to travel around the world, exploring different cultures and learning movement and natural healing techniques from teachers and bodyworkers.\r\n\r\n\r\nHe was introduced to yoga 10 years ago, finding a deeper connection with emotions and physical awareness through the practice. Since then he started his own journey and has been working as a bodyworker with massage and reiki for the past 7 years, and sharing the gift of yoga since 4 years.\r\n\r\n\r\nAlbert’s classes have their focus on a different part of the body, organ or emotion each week, so that together we can discover how yoga and adjustments during the practice can enhance our wellbeing. \r\n\r\n \r\n\r\nHe currently teaches Yin Yang and Yin yoga, and works with different massage and reiki techniques to support and enhance wellbeing. \r\n\r\n \r\n\r\n We are all unique and special\r\n- Albert Garcia Ordinas',
    phone: '+31622302478',
    color: '',
    email: 'albertgarciaordinas@gmail.com',
    associated_coach_id: 21381,
    associatedcoach_set: [21381],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 20,
    private_slots_coach_payment_rules: [],
    facebook_url: 'https://www.facebook.com/agarciaordinas/Albert',
    instagram_url: 'https://www.instagram.com/albertgarciaordinas/',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Alejandra',
    lastname: 'Kemna',
    name: 'Alejandra Kemna',
    gender: 'F',
    rating: '-1.00',
    id: 20625,
    birthday: '1977-04-17',
    photo: 'http://testserver:8000/media/user/Alejandra.jpeg',
    description:
      'Alejandra sees yoga as a tool for life. To stay in balance, as a mom with two kids, yoga connects her to her inner strength and spirit. She is both Chilean and Dutch and has been teaching yoga for over 10 years.\r\n\r\nShe has studied with David Swensson and completed the Sva Dharma Teacher Training with Katiza Satya and Kevin Sahaj. She is deeply inspired by Ayurveda and is studying advanced studies of Ayurveda with Victoria Hyndman. She is grateful for her teachers who have given her the chance to deepen the practice, not only on the mat but also in daily life.\r\n\r\nAlejandra’s classes are from the heart, playful, fun, calming and strengthening. It gives you the chance to feel deeply connected to your inner being.',
    phone: '+31628853807',
    color: '',
    email: 'alekemna@gmail.com',
    associated_coach_id: 21382,
    associatedcoach_set: [21382],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Alixe',
    lastname: 'Van Ogtrop',
    name: 'Alixe Van Ogtrop',
    gender: 'F',
    rating: '-1.00',
    id: 20626,
    birthday: '1987-09-09',
    photo: 'http://testserver:8000/media/user/Alixe_jI0dc3e.jpeg',
    description:
      'Alixe always knew she wanted to change the world. Starting in corporate life she discovered that the real change can only be made when the change is made within.\r\n\r\n\r\nAfter a PTSD Alixe went on her own healing journey, when reconnecting with her True Self and coming back home (within) she could not, not start to guide other people back to their own Inner Being.\r\n\r\n\r\nAfter having done energetic and shamanic healing trainings and a deep dive into various healing traditions she has also started a more science based psychotherapy education focused on trauma, depression and burnout; Human Givens. In this way she can bridge the scientific mechanisms of the brain with the more intuitive and energetic work. Besides being the bridge between these healing/coaching services she is also the bridge between the business and holistic world.\r\n\r\n\r\nAlixe is guiding people by one on one sessions, by holding women circles, full moon ceremonies and by offering 10 week intensive programs to dive deep in.',
    phone: '+31652087865',
    color: '',
    email: 'alixevanogtrop@gmail.com',
    associated_coach_id: 21383,
    associatedcoach_set: [21383],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Alixe Van Ogtrop',
    lastname: '& Dolores Mae Höppener',
    name: 'Alixe Van Ogtrop & Dolores Mae Höppener',
    gender: 'F',
    rating: '-1.00',
    id: 24430,
    birthday: null,
    photo: null,
    description: '',
    color: '',
    email: null,
    associated_coach_id: 26038,
    associatedcoach_set: [26038],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Amanda',
    lastname: 'Dries',
    name: 'Amanda Dries',
    gender: 'F',
    rating: '-1.00',
    id: 20627,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Amanda.jpeg',
    description:
      'Amanda is from Wales in the UK. She worked for many years in sales, then as a purser for two main airlines, experiencing different cultures. After meeting her Dutch husband she moved to Holland and had three children. Over the last 14 years, she has taken on various studies for health. From 2010-2015 she studied at the Academy of Ayurvedic Studies to become an Ayurvedic practitioner.\r\n\r\nAfter meeting her Guru Yogi Shivan through colleague and practitioner Tory Hyndman, she became inspired to study Ayurveda and is so thankful for their guidance in this direction. Ayurveda was everything she had been looking for. It came into her life like it was meant to be and she is passionate to pass on her knowledge to others.\r\n\r\nJanuary 2015 she did her internship in Kerela, India with Doctor Vijith and Virya. They have a clinic and hospital where the students have intense practical and theoretical training, also observing the preparations of herbal remedies.\r\n\r\nAmanda wishes to continue learning and growing. She is specialised in Ayurvedic massage and detox treatments, also has cooked Ayurvedic food for wellness events and strives to give people awareness and to provide healing treatments that she has learnt through her teachers and Masters.Ama',
    phone: '+31637403812',
    color: '#f5a623',
    email: 'info@innersenses.nl',
    associated_coach_id: 21384,
    associatedcoach_set: [21384],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [
        {
          session_id: 4570678,
          session_name: 'Clear Your Head: Massage Workshop with Amanda Dries',
          date_start: '2022-01-30 13:00:00+00:00',
          duration_minute: 180,
          confirmed_bookings: 0,
          cancelled_bookings: 0,
          coach_payment_rule: -1,
          base_remuneration: '-1.00',
          coach_bonus: '-1.00',
          coach_total_payment: '-1.00',
          error: true,
        },
      ],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Amélie',
    lastname: 'Duvernay',
    name: 'Amélie Duvernay',
    gender: 'F',
    rating: '-1.00',
    id: 20628,
    birthday: '1977-08-29',
    photo: 'http://testserver:8000/media/user/Amelie.jpeg',
    description:
      'Amélie is born in France and originally comes from Burgundy. In 2008 her interest in Yoga starts in Paris, where she practices Hatha and Bikram Yoga until she discovers Astanga Yoga. In 2009, she starts a 200-hour Teacher training at Astanga Yoga Paris with Linda Munro and Gerald Disse, and follows them to Auroville, India, for workshops with them and with Monica Marinoni.  In India, she fully immersed herself in the world of Yoga in order to gain a better understanding of its roots and culture. She started to teach with Linda and Gerald in 2010 for several years.\r\n \r\n\r\nIn her path to expression, she was first active in the artistic field: at a young age, she was originally trained as a dancer and made her first steps in the Jazz performance field in London, as well as in contemporary dance creations and cabaret.   \r\n \r\n\r\nBack in France after 4 years, she felt her health decreasing and was suffering from physical injuries and dealt with signs of depression. To her, Astanga was a miracle as it put everything back into place: emotions, thoughts and physical strength. She realised her regular practice was necessary in order to keep going and to be able to open up to possibilities in life. Several Astanga workshops took her to different countries, and she followed Mysore programs that deepened her practice; with Ron Reid and Marla Meenakshi Jois in Thailand, Kino Mac Gregor, Tim Miller in California and Monica Marinoni in India.\r\n \r\n\r\nIn her daily life, she nourishes her inspirations through Ayurveda, daily practice and through contemporary dance, as she occasionally goes back to the field. She discovered The Gaga Movement Language in 2017, created by the Israelian choreographer Ohad Naharin. She attended several international intensive workshops for professional dancers with his company Batsheva.Ame',
    phone: '+31612089510',
    color: '',
    email: 'ameliedv@hotmail.fr',
    associated_coach_id: 21386,
    associatedcoach_set: [21386],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Amir',
    lastname: 'Jaan',
    name: 'Amir Jaan',
    gender: 'M',
    rating: '-1.00',
    id: 23971,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Amir_Jaan.jpg',
    description:
      'Amir is classically trained in the Spiritual Art of Kundalini Yoga under the close observations of a host of world-renowned and internationally revered Guru mentors for 10 years and is almost 2 decades on from being a novice student. Amir is now a senior mentor to hundreds of students himself, having worked for many years with members of the general public.\r\n\r\nHe also has a private client list and worldwide consultancy that compromises and includes Top-Level professional sportsmen and women, business leaders, celebrities and CEO’s of large multinational organizations. Having conducted in excess of 35,000 thousand public and private classes in London and across the world. Amir Jaan brings a reassuring calmness into any learning environment.\r\n\r\nHis specialist knowledge and extensive experience in the field of Humanolgy make him a powerful instrument to assist those with a desire or need to approach character and health reformation, in an organic, safe and self-healing way.',
    color: '',
    email: null,
    associated_coach_id: 25171,
    associatedcoach_set: [25171],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Anaisa',
    lastname: 'Seneda',
    name: 'Anaisa Seneda',
    gender: 'F',
    rating: '-1.00',
    id: 20629,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Anaisa.jpeg',
    description:
      "Anaisa Seneda is a coach, teacher, and facilitator with a passion for helping people to reconnect with their authentic truth. She is especially motivated to foster team collaboration and feminine wisdom. \r\n\r\n\r\n\r\nAlways fascinated by learning, Anaisa has studied and integrated both alternative and traditional therapeutic domains, including psychoanalysis, positive psychology, yoga, reiki, qigong, Taoist sexual arts, and tantra. She brings alchemy to her tailor-made workshops and healing sessions through guided visualization, assisted breath, healing sounds, group dynamics, inquiry, and movement.\r\n\r\n\r\n\r\nPrior to embracing her path in energy healing, Anaisa held multiple executive roles in the corporate world. Although she didn't know it at the time, her experience in business laid the foundation for her understanding of human relations. Nowadays, she invites spirituality in her business coaching practice by using shamanic healing methods for teams and organizations, especially in conflict resolution. Having worked on three continents, Anaisa is comfortable with multicultural groups from diverse backgrounds.\r\n\r\n\r\n\r\nHer mind-body certifications include Tao Tantric Arts Facilitator by the Universal Healing Tao system of Mantak Chia, Lifestyle & Business Coach by the Brazilian Association of Coaching, Yoga teacher by Delight Academy. Anaisa is currently working towards the completion of her Ayurveda Practitioner Training. ",
    color: '',
    email: 'seneda.anaisa@gmail.com',
    associated_coach_id: 21387,
    associatedcoach_set: [21387],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Anat',
    lastname: 'Geiger',
    name: 'Anat Geiger',
    gender: 'F',
    rating: '-1.00',
    id: 20630,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Anat_Geiger_iH1xbFr.jpeg',
    description:
      'Anat was born in Rio de Janeira in 1965, when the Beatles were at their highest point, grew up in Copacabana and started dancing very early on. She got a university degree in Advertising, but was already doing theatre by the time she finished, and never even went back to get her diploma. Starting as Shakespeare\'s Julia at age 21 was so much fun she never looked back. {READ_MORE}\r\n\r\nIn October 1991 Anat arrived in Amsterdam, and the following years she played in more than 30 productions with the most varied companies and colleagues. "It was an incredibly rich and fulfilling journey, there was much drama, immense satisfaction and a whole lot of fun". \r\n\r\nAnat took her first yoga class in 1996 and immediately found something that she, without knowing it, had always been looking for. After studying intensively with Teresa Caldas and Dona Holleman, she found Paul and Suzee Grilley who remain her teachers today.\r\n\r\nBased in Amsterdam, Anat is now a well-respected Functional Yoga teacher herself, teaching both students and teacher around the world and 1/2 of The Fat Yogis duo alongside Marcel van de Vis Heil. ',
    color: '',
    email: null,
    associated_coach_id: 21388,
    associatedcoach_set: [21388],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Andrei',
    lastname: 'Ram',
    name: 'Andrei Ram',
    gender: 'M',
    rating: '-1.00',
    id: 20631,
    birthday: null,
    photo: 'http://testserver:8000/media/user/Andrei.jpeg',
    description:
      'Andrei Ram is a world renowned yoga teacher who maintains and offers the benefits of the timeless yogi way of living. He spent over ten years serving the great yoga master Sri Dharma Mittra, from whom he received acharya initiation in the yoga linage and its ancient wisdom.\r\n\r\nFrom an early age Andrei has gifted insights and realizations about the non-physical aspects of reality, which have evolved after many years of intense yoga practice. His teachings offer a transformative experience to learn about the energy system and how to apply it, both to the yoga practice and to the daily living. \r\n\r\nHe travels worldwide sharing his unique yoga approach and making accesible to all the most mystical aspects of the Yoga Science. An honest contribution to assist the Consciousness’ evolution and the collective Self-Realization.\r\n\r\nFor more information about Andrei Ram please visit www.innerparadise.orgAndrei',
    color: '',
    email: 'andreiram@icloud.com',
    associated_coach_id: 21389,
    associatedcoach_set: [21389],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: 'https://www.instagram.com/andreiram1/',
    performance: {
      '0': [],
      '1': [],
      performanceLoading: false,
    },
  },
  {
    firstname: 'Anna Scott',
    lastname: 'Miller',
    name: 'Anna Scott Miller',
    gender: 'F',
    rating: '-1.00',
    id: 20632,
    birthday: '1980-07-06',
    photo: 'http://testserver:8000/media/user/Anna_Scott.jpeg',
    description:
      'Always attracted to people and the possibilities of the physical body, Anna first started to study Physical Education to become a PE teacher. She started teaching gymnastics in her teens and after college PE. Always eager to learn she also expanded her knowledge in (sport)massages, the endocrine system, coaching and nutrition.\r\n\r\n\r\nIn 2009 she started to teach PE & Personal development at the Hogeschool van Amsterdam (HvA).  As of 2011 she began teaching beginner yoga classes too. She found this was so wonderful to share, that her focus started shifting.\r\nIn 2014 she finished her RYT-200 Vinyasa training and from then started to work less as a teacher at the HvA and more as a yoga teacher. Summer 2015 she stopped working as a PE teacher, to fully focus on teaching yoga and attending Teacher Trainings and workshops.\r\n\r\n\r\nShe followed many workshops and trainings with a variety of teachers like Claudia Pradella, Marlene Henny, Shiva Rea, David Swenson, Clayton Horton, Kino MacGregor, Petri Raisanen & Laruga Glaser.\r\nClaudia made her really connect and fall in love with Ashtanga, which is her daily practice. \r\nYoga is connecting the dots. She can combine all her knowledge and interests in the holistic philosophy of yoga and she loves to share this beautiful practice as much as possible.\r\n\r\n\r\nIn her classes you’ll find a combination of flexibility and power movements all linked by the breath. Focusing on making you understand the internal processes to find your core strength (physically & mentally).\r\n\r\n\r\n“Be the change you want to see in the world” – Mahatma Gandhi ',
    phone: '+31624265545',
    color: '',
    email: 'annascott_miller@hotmail.com',
    associated_coach_id: 21390,
    associatedcoach_set: [21390],
    disabled: false,
    default_payment_rule_id: null,
    coach_payment_rule_id: null,
    workshop_coach_payment_rule_id: null,
    private_coach_payment_rule_id: null,
    coach_payment_rule_group_id: 41,
    private_slots_coach_payment_rules: [],
    facebook_url: '',
    instagram_url: '',
    performance: {
      '0': [
        {
          session_id: 4549259,
          session_name: 'Ashtanga Led - Pre-recorded',
          date_start: '2022-01-04 06:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 9,
          cancelled_bookings: 1,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
        {
          session_id: 4549816,
          session_name: 'Ashtanga Led - Pre-recorded',
          date_start: '2022-01-13 11:00:00+00:00',
          duration_minute: 60,
          confirmed_bookings: 14,
          cancelled_bookings: 0,
          coach_payment_rule: 1221,
          base_remuneration: '35.00',
          coach_bonus: null,
          coach_total_payment: '35.00',
          error: false,
        },
      ],
      '1': [],
      performanceLoading: false,
    },
  },
];
