import Immutable from 'seamless-immutable';

import Config from '../../config';

import {
  MARKETPLACE_OFFER_CARD_CONFIGURATION,
  MARKETPLACE_OFFER_CARD_PREVIEW,
} from '#marketplacecomponents/@Offer/MarketplaceCardOfferCSSOnly';

import {
  MARKETPLACE_BOOKER_MODULE_OFFER_SUMMARY_CONFIGURATION,
  MARKETPLACE_BOOKER_MODULE_OFFER_SUMMARY_PREVIEW,
} from '#marketplacecomponents/@Offer/BookerModuleOfferSummary';

import {
  MARKETPLACE_PAYMENT_COMBO_CARD_CONFIGURATION,
  MARKETPLACE_PAYMENT_COMBO_CARD_PREVIEW,
} from '#marketplacecomponents/@PaymentCombo/MarketplacePaymentComboCard/custom_css_variant';
import {
  MARKETPLACE_PAYMENT_PACK_CARD_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_CARD_PREVIEW,
} from '#marketplacecomponents/@PaymentPack/MarketplacePaymentPackCard/custom_css_variant';
import {
  MARKETPLACE_PAYMENT_PACK_COMPATIBILITY_MODAL_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_COMPATIBILITY_MODAL_PREVIEW,
} from '#marketplacecomponents/@PaymentPack/MarketplacePaymentPackCompatibilityModal/custom_css_variant';
import {
  MARKETPLACE_PAYMENT_PACK_RESTRICTION_MODAL_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_RESTRICTION_MODAL_PREVIEW,
} from '#marketplacecomponents/@PaymentPack/MarketplacePaymentPackRestrictionModal/custom_css_variant';
import {
  MARKETPLACE_PRIVATE_PASS_CARD_CONFIGURATION,
  MARKETPLACE_PRIVATE_PASS_CARD_PREVIEW,
} from '#marketplacecomponents/@PrivatePass/MarketplacePrivatePassCard/custom_css_variant';
import {
  MARKETPLACE_PRIVATE_PASS_COMPATIBILITY_MODAL_CONFIGURATION,
  MARKETPLACE_PRIVATE_PASS_COMPATIBILITY_MODAL_PREVIEW,
} from '#marketplacecomponents/@PrivatePass/MarketplacePrivatePassCompatibilityModal/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_CARD_CONFIGURATION,
  MARKETPLACE_CONTRACT_CARD_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractCard/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_CHECKOUT_CONFIGURATION,
  MARKETPLACE_CONTRACT_CHECKOUT_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractCheckout/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_DETAIL_CONFIGURATION,
  MARKETPLACE_CONTRACT_DETAIL_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractDetail/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_DETAIL_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_DETAIL_MODAL_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractDetailModal/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_TERMS_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_TERMS_MODAL_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractTermsModal/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_COOLDOWN_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_COOLDOWN_MODAL_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractCooldownModal/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_COUPON_FORM_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_COUPON_FORM_MODAL_PREVIEW,
} from '#marketplacecomponents/@Coupon/MarketplaceCouponFormModal/custom_css_variant';
import {
  MARKETPLACE_PAYMENT_PACK_OFFPEAK_RESTRICTION_MODAL_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_OFFPEAK_RESTRICTION_MODAL_PREVIEW,
} from '#marketplacecomponents/@PaymentPack/MarketplacePaymentPackOffPeakRestrictionModal/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_NOT_FOUND_CONFIGURATION,
  MARKETPLACE_CONTRACT_NOT_FOUND_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractNotFound/custom_css_variant';
import {
  MARKETPLACE_CONTRACT_PAYMENT_CONFIGURATION,
  MARKETPLACE_CONTRACT_PAYMENT_PREVIEW,
} from '#marketplacecomponents/@Payment/MarketplaceContractPayment/custom_css_variant';
import {
  MARKETPLACE_COLLECT_PAYMENT_METHOD_CONFIGURATION,
  MARKETPLACE_COLLECT_PAYMENT_METHOD_PREVIEW,
} from '#marketplacecomponents/@Payment/MarketplaceCollectPaymentMethod/custom_css_variant';
import {
  MARKETPLACE_CALENDAR_FILTER_CONFIGURATION,
  MARKETPLACE_CALENDAR_FILTER_PREVIEW,
} from '#marketplacecomponents/@RessourceFilter/MarketplaceFilterCSSOnly/custom_css_variant';
import {
  MARKETPLACE_OFFER_LIST_ITEM_CONFIGURATION,
  MARKETPLACE_OFFER_LIST_ITEM_PREVIEW,
} from '#marketplacecomponents/@Offer/MarketplaceOfferListItemCSSOnly/custom_css_variant';
import {
  MARKETPLACE_WEEK_TIME_TABLE_CONFIGURATION,
  MARKETPLACE_WEEK_TIME_TABLE_PREVIEW,
} from '#marketplacecomponents/@Calendar/MarketplaceWeekTimeTableCSSOnly/custom_css_variant';
import {
  MARKETPLACE_SEARCH_CONFIGURATION,
  MARKETPLACE_SEARCH_PREVIEW,
} from '#components/css-only/Search/custom_css_variant';
import {
  MARKETPLACE_FILTER_CONFIGURATION,
  MARKETPLACE_FILTER_PREVIEW,
} from '#marketplacecomponents/@RessourceFilter/MarketplaceFilter/custom_css_variant';
import {
  MARKETPLACE_DATE_PICKER_CONFIGURATION,
  MARKETPLACE_DATE_PICKER_PREVIEW,
} from '#marketplacecomponents/@Date/MarketplaceDatePicker/custom_css_variant';
import {
  MARKETPLACE_SELECT_CONFIGURATION,
  MARKETPLACE_SELECT_PREVIEW,
} from '#components/css-only/Select/custom_css_variant';

import {
  MARKETPLACE_ACTIVITY_CONFIGURATION,
  MARKETPLACE_ACTIVITY_PREVIEW,
} from '#marketplacecomponents/@Activity/MarketplaceActivityCSSOnly';

import {
  MARKETPLACE_ACTIVITY_DIALOG_CONFIGURATION,
  MARKETPLACE_ACTIVITY_DIALOG_PREVIEW,
} from '#marketplacecomponents/@Activity/MarketplaceActivityDialogCSSOnly';

import {
  MARKETPLACE_BOOKING_BUTTON_CONFIGURATION,
  MARKETPLACE_BOOKING_BUTTON_PREVIEW,
} from '#marketplacecomponents/@Booking/MarketplaceBookButton';

import {
  MARKETPLACE_BOOKING_BLOCKED_CONFIGURATION,
  MARKETPLACE_BOOKING_BLOCKED_PREVIEW,
} from '#marketplacecomponents/@Booking/MarketplaceBookingBlockedReason';

import {
  MARKETPLACE_ITEM_QUANTITY_CONFIGURATION,
  MARKETPLACE_ITEM_QUANTITY_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryItemCssOnly/ItemQuantity';

import {
  MARKETPLACE_BASKET_SUMMARY_ITEM_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_ITEM_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryItemCssOnly';

import {
  MARKETPLACE_BASKET_SUMMARY_LIST_ITEM_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_LIST_ITEM_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryListCssOnly';

import {
  MARKETPLACE_BASKET_SUMMARY_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_PREVIEW,
} from '#marketplacecomponents/@Basket/BasketSummaryCssOnly';

import {
  MARKETPLACE_BASKET_SUMMARY_DIALOG_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_DIALOG_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryDialogCssOnly';
import {
  MARKETPLACE_PREPAID_LINE_ITEM_CONFIGURATION,
  MARKETPLACE_PREPAID_LINE_ITEM_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryPrepaidLineItem';
import {
  MARKETPLACE_PREPAID_LINE_LIST_CONFIGURATION,
  MARKETPLACE_PREPAID_LINE_LIST_PREVIEW,
} from '#marketplacecomponents/@Basket/MarketplaceBasketSummaryPrepaidLineList';
import {
  MARKETPLACE_MINIMAL_APPBAR_CONFIGURATION,
  MARKETPLACE_MINIMAL_APPBAR_PREVIEW,
} from '#libs/marketplace/components/@AppBar/MarketplaceAppBar/MinimalMarketplaceAppBarCSSOnly';

import {
  FABRIQUE_TYPOGRAPHY_CONFIGURATION,
  FABRIQUE_TYPOGRAPHY_PREVIEW,
} from '#components/css-only/Fabrique/Typography';
import {
  FABRIQUE_CARD_CONFIGURATION,
  FABRIQUE_CARD_PREVIEW,
} from '#components/css-only/Fabrique/Card';
import {
  AUTHENTICATION_RESET_PASSWORD_FORM_CONFIGURATION,
  AUTHENTICATION_RESET_PASSWORD_FORM_PREVIEW,
} from '#components/css-only/ResetPasswordForm';
import {
  AUTHENTICATION_CHANGE_PASSWORD_FORM_CONFIGURATION,
  AUTHENTICATION_CHANGE_PASSWORD_FORM_PREVIEW,
} from '#components/css-only/ChangePasswordForm';
import {
  AUTHENTICATION_LOGIN_FORM_CONFIGURATION,
  AUTHENTICATION_LOGIN_FORM_PREVIEW,
} from '#components/css-only/LoginForm';
import {
  AUTHENTICATION_LOGIN_CONFIGURATION,
  AUTHENTICATION_LOGIN_PREVIEW,
} from '#components/css-only/Login';
import {
  FABRIQUE_TEXTFIELD_CONFIGURATION,
  FABRIQUE_TEXTFIELD_PREVIEW,
} from '#components/css-only/Fabrique/TextFieldV2';
import {
  FABRIQUE_BUTTON_CONFIGURATION,
  FABRIQUE_BUTTON_PREVIEW,
} from '#components/css-only/Fabrique/ButtonV2';
import {
  FABRIQUE_ICON_BUTTON_CONFIGURATION,
  FABRIQUE_ICON_BUTTON_PREVIEW,
} from '#components/css-only/Fabrique/IconButton';
import {
  FABRIQUE_ACTION_TAB_PREVIEW,
  FABRIQUE_ACTION_TAB_CONFIGURATION,
} from '#components/css-only/Fabrique/ActionTab';
import {
  FABRIQUE_BLANKET_CONFIGURATION,
  FABRIQUE_BLANKET_PREVIEW,
} from '#components/css-only/Fabrique/Blanket';
import {
  FABRIQUE_TAB_CONFIGURATION,
  FABRIQUE_TAB_PREVIEW,
} from '#components/css-only/Fabrique/Tab';

import {
  CSSComponentPreviews,
  MarketplaceCSSComponentConfig,
  MarketplacePage,
} from '#libs/exportable-components/types';

import { CssComponentsVariantIdentifiers } from './constants';
import {
  FABRIQUE_BADGE_PREVIEW,
  FABRIQUE_BADGE_CONFIGURATION,
} from '#components/css-only/Fabrique/Badge/custom_css_variant';

import {
  MARKETPLACE_SPOT_SELECTOR_CONFIGURATION,
  MARKETPLACE_SPOT_SELECTOR_PREVIEW,
} from '#marketplacecomponents/@SpotScheduling/MarketplaceSpotSelector/custom_css_variant';

import {
  FABRIQUE_RADIOBUTTON_CONFIGURATION,
  FABRIQUE_RADIOBUTTON_PREVIEW,
} from '#components/css-only/Fabrique/RadioButtonV2';

import {
  BOOKER_MODULE_BUYABLE_ITEMS_LIST_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEMS_LIST_PREVIEW,
} from '#marketplacecomponents/@BuyableItem/MarketplaceBookerModuleBuyableItems';

import {
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_COMBO_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_COMBO_PREVIEW,
} from '#marketplacecomponents/@BuyableItem/MarketplacePaymentComboBuyableItem';

import {
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_PACK_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_PACK_PREVIEW,
} from '#marketplacecomponents/@BuyableItem/MarketplacePaymentPackBuyableItem';

import {
  BOOKER_MODULE_BUYABLE_ITEM_CONTRACT_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_CONTRACT_PREVIEW,
} from '#marketplacecomponents/@Subscription/MarketplaceContractBuyableItem';

import {
  CONFIRMATION_CHECKOUT_MESSAGE_CONFIGURATION,
  CONFIRMATION_CHECKOUT_MESSAGE_PREVIEW,
} from '#libs/checkout/components/ConfirmationMessage';
import { ALERT_CONFIGURATION, ALERT_PREVIEW } from '#components/css-only/Alert';

import {
  MESSAGE_WITH_ICON_CONFIGURATION,
  MESSAGE_WITH_ICON_PREVIEW,
} from '#components/css-only/StatusMessageWithIcon';

import {
  FABRIQUE_CHECKBOX_PREVIEW,
  FABRIQUE_CHECKBOX_CONFIGURATION,
} from '#components/css-only/Fabrique/Checkbox';

import {
  MINIMAL_SUBSCRIPTION_CARD_PREVIEW,
  MINIMAL_SUBSCRIPTION_CARD_CONFIGURATION,
} from '#marketplacecomponents/@Subscription/MinimalSubscriptionCard';

import {
  MARKETPLACE_PRODUCT_ITEM_CONFIGURATION,
  MARKETPLACE_PRODUCT_ITEM_PREVIEW,
} from '#marketplacecomponents/@CheckoutItem/MarketplaceProductItem';

import {
  MARKETPLACE_PRODUCT_ITEM_LIST_CONFIGURATION,
  MARKETPLACE_PRODUCT_ITEM_LIST_PREVIEW,
} from '#marketplacecomponents/@CheckoutItem/MarketplaceProductItemList';

import {
  MINIMAL_PRIVATE_PASS_CARD_CONFIGURATION,
  MINIMAL_PRIVATE_PASS_CARD_PREVIEW,
} from '#marketplacecomponents/@PrivatePass/MinimalPrivatePassCard';

import {
  MARKETPLACE_CHECKOUT_ITEMS_PRIVATE_PASS_LIST_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PRIVATE_PASS_LIST_PREVIEW,
} from '#marketplacecomponents/@CheckoutItem/MarketplaceCheckoutItemsWithPrivatePassList';

import {
  MINIMAL_PAYMENT_COMBO_CARD_CONFIGURATION,
  MINIMAL_PAYMENT_COMBO_CARD_CARD_PREVIEW,
} from '#marketplacecomponents/@PaymentCombo/MinimalPaymentComboCard';

import {
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_COMBO_LIST_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_COMBO_LIST_PREVIEW,
} from '#marketplacecomponents/@CheckoutItem/MarketplaceCheckoutItemsWithPaymentComboList';

import {
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_PACK_LIST_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_PACK_LIST_LIST_PREVIEW,
} from '#marketplacecomponents/@CheckoutItem/MarketplaceCheckoutItemsWithPaymentPackList';

import {
  MINIMAL_PAYMENT_PACK_CARD_CONFIGURATION,
  MINIMAL_PAYMENT_PACK_CARD_PREVIEW,
} from '#marketplacecomponents/@PaymentPack/MinimalPaymentPackCard';

import {
  MARKETPLACE_BOOKING_ITEM_CONFIGURATION,
  MARKETPLACE_BOOKING_ITEM_PREVIEW,
} from '#marketplacecomponents/@Booking/MarketplaceBookingItem';

import {
  MARKETPLACE_OFFER_BOOKING_LIST_CONFIGURATION,
  MARKETPLACE_OFFER_BOOKING_LIST_PREVIEW,
} from '#marketplacecomponents/@Booking/MarketplaceOfferBookingList';

/* TEMPLATE

{
  label: 'filters', "the uniq key of the component"
  css: MarketplaceFiltersCSS,  "the uniq css imported as raw string upper in the component"
  pages: ['workshop', 'calendar'], "All the page of the widget where the component is use"
  showAsFlex: true, "Boolean to display the component as center for small component"
  defaultState: { example: true },
  variations: [      "Array of configuration to modify the props send to the component"
   loadingVariation,
   variantVariation,
  ],
   },
 }
*/
export const CSS_COMPONENTS: MarketplaceCSSComponentConfig[] = [
  AUTHENTICATION_RESET_PASSWORD_FORM_CONFIGURATION,
  AUTHENTICATION_CHANGE_PASSWORD_FORM_CONFIGURATION,
  AUTHENTICATION_LOGIN_FORM_CONFIGURATION,
  AUTHENTICATION_LOGIN_CONFIGURATION,
  MARKETPLACE_SEARCH_CONFIGURATION,
  MARKETPLACE_FILTER_CONFIGURATION,
  MARKETPLACE_DATE_PICKER_CONFIGURATION,
  MARKETPLACE_SELECT_CONFIGURATION,
  MARKETPLACE_OFFER_CARD_CONFIGURATION,
  MARKETPLACE_OFFER_LIST_ITEM_CONFIGURATION,
  MARKETPLACE_CALENDAR_FILTER_CONFIGURATION,
  MARKETPLACE_PAYMENT_COMBO_CARD_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_CARD_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_COMPATIBILITY_MODAL_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_RESTRICTION_MODAL_CONFIGURATION,
  MARKETPLACE_PAYMENT_PACK_OFFPEAK_RESTRICTION_MODAL_CONFIGURATION,
  MARKETPLACE_PRIVATE_PASS_CARD_CONFIGURATION,
  MARKETPLACE_PRIVATE_PASS_COMPATIBILITY_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_CARD_CONFIGURATION,
  MARKETPLACE_CONTRACT_CHECKOUT_CONFIGURATION,
  MARKETPLACE_CONTRACT_DETAIL_CONFIGURATION,
  MARKETPLACE_CONTRACT_DETAIL_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_TERMS_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_COOLDOWN_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_COUPON_FORM_MODAL_CONFIGURATION,
  MARKETPLACE_CONTRACT_NOT_FOUND_CONFIGURATION,
  MARKETPLACE_CONTRACT_PAYMENT_CONFIGURATION,
  MARKETPLACE_COLLECT_PAYMENT_METHOD_CONFIGURATION,
  MARKETPLACE_WEEK_TIME_TABLE_CONFIGURATION,
  MARKETPLACE_ACTIVITY_CONFIGURATION,
  MARKETPLACE_ACTIVITY_DIALOG_CONFIGURATION,
  MARKETPLACE_BOOKING_BUTTON_CONFIGURATION,
  MARKETPLACE_BOOKING_BLOCKED_CONFIGURATION,
  MARKETPLACE_ITEM_QUANTITY_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_ITEM_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_LIST_ITEM_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_CONFIGURATION,
  MARKETPLACE_BASKET_SUMMARY_DIALOG_CONFIGURATION,
  MARKETPLACE_PREPAID_LINE_ITEM_CONFIGURATION,
  MARKETPLACE_PREPAID_LINE_LIST_CONFIGURATION,
  MARKETPLACE_MINIMAL_APPBAR_CONFIGURATION,
  MARKETPLACE_BOOKER_MODULE_OFFER_SUMMARY_CONFIGURATION,
  MARKETPLACE_SPOT_SELECTOR_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEMS_LIST_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_COMBO_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_PACK_CONFIGURATION,
  BOOKER_MODULE_BUYABLE_ITEM_CONTRACT_CONFIGURATION,
  CONFIRMATION_CHECKOUT_MESSAGE_CONFIGURATION,
  ALERT_CONFIGURATION,
  MESSAGE_WITH_ICON_CONFIGURATION,
  MINIMAL_SUBSCRIPTION_CARD_CONFIGURATION,
  MARKETPLACE_PRODUCT_ITEM_CONFIGURATION,
  MARKETPLACE_PRODUCT_ITEM_LIST_CONFIGURATION,
  MINIMAL_PRIVATE_PASS_CARD_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PRIVATE_PASS_LIST_CONFIGURATION,
  MINIMAL_PAYMENT_COMBO_CARD_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_COMBO_LIST_CONFIGURATION,
  MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_PACK_LIST_CONFIGURATION,
  MINIMAL_PAYMENT_PACK_CARD_CONFIGURATION,
  MARKETPLACE_BOOKING_ITEM_CONFIGURATION,
  MARKETPLACE_OFFER_BOOKING_LIST_CONFIGURATION,
  ...(Config.REACT_APP_SENTRY_ENVIRONMENT !== 'production'
    ? [
        FABRIQUE_TYPOGRAPHY_CONFIGURATION,
        FABRIQUE_CARD_CONFIGURATION,
        FABRIQUE_BADGE_CONFIGURATION,
        FABRIQUE_BUTTON_CONFIGURATION,
        FABRIQUE_ICON_BUTTON_CONFIGURATION,
        FABRIQUE_ACTION_TAB_CONFIGURATION,
        FABRIQUE_BLANKET_CONFIGURATION,
        FABRIQUE_TAB_CONFIGURATION,
        FABRIQUE_TEXTFIELD_CONFIGURATION,
        FABRIQUE_RADIOBUTTON_CONFIGURATION,
        FABRIQUE_CHECKBOX_CONFIGURATION,
      ]
    : []),
];

/*
We are using another object for the render to avoid importing unnecessary module
in the widget
Template
  key: (props: {  The render of the component for the editor ""
       theme, " Company theme ""
       setState, " implementation of a state for component where needed ""
       state,
       {...variations} " all the variations add new props needed by the components ""
     }) => {
   return (
     <MarketplaceFilters {...variations} />
   );
*/

export const CSS_COMPONENTS_BY_ID: Immutable.Immutable<CSSComponentPreviews> =
  Immutable({
    [CssComponentsVariantIdentifiers.AUTHENTICATION_RESET_PASSWORD_FORM]:
      AUTHENTICATION_RESET_PASSWORD_FORM_PREVIEW,
    [CssComponentsVariantIdentifiers.AUTHENTICATION_CHANGE_PASSWORD_FORM]:
      AUTHENTICATION_CHANGE_PASSWORD_FORM_PREVIEW,
    [CssComponentsVariantIdentifiers.AUTHENTICATION_LOGIN_FORM]:
      AUTHENTICATION_LOGIN_FORM_PREVIEW,
    [CssComponentsVariantIdentifiers.AUTHENTICATION_LOGIN]:
      AUTHENTICATION_LOGIN_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_ACTIVITY_DIALOG]:
      MARKETPLACE_ACTIVITY_DIALOG_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_ACTIVITY]:
      MARKETPLACE_ACTIVITY_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BOOKING_BLOCKED]:
      MARKETPLACE_BOOKING_BLOCKED_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BOOKING_BUTTON]:
      MARKETPLACE_BOOKING_BUTTON_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CALENDAR_FILTER]:
      MARKETPLACE_CALENDAR_FILTER_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_COLLECT_PAYMENT_METHOD]:
      MARKETPLACE_COLLECT_PAYMENT_METHOD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_CARD]:
      MARKETPLACE_CONTRACT_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_CHECKOUT]:
      MARKETPLACE_CONTRACT_CHECKOUT_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_COOLDOWN_MODAL]:
      MARKETPLACE_CONTRACT_COOLDOWN_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_COUPON_FORM_MODAL]:
      MARKETPLACE_CONTRACT_COUPON_FORM_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_DETAIL_MODAL]:
      MARKETPLACE_CONTRACT_DETAIL_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_DETAIL]:
      MARKETPLACE_CONTRACT_DETAIL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_NOT_FOUND]:
      MARKETPLACE_CONTRACT_NOT_FOUND_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_PAYMENT]:
      MARKETPLACE_CONTRACT_PAYMENT_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CONTRACT_TERMS_MODAL]:
      MARKETPLACE_CONTRACT_TERMS_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_DATE_PICKER]:
      MARKETPLACE_DATE_PICKER_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_FILTER]:
      MARKETPLACE_FILTER_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_OFFER_CARD]:
      MARKETPLACE_OFFER_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_OFFER_LIST_ITEM]:
      MARKETPLACE_OFFER_LIST_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PAYMENT_COMBO_CARD]:
      MARKETPLACE_PAYMENT_COMBO_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PAYMENT_PACK_CARD]:
      MARKETPLACE_PAYMENT_PACK_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PAYMENT_PACK_COMPATIBILITY_MODAL]:
      MARKETPLACE_PAYMENT_PACK_COMPATIBILITY_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PAYMENT_PACK_OFFPEAK_RESTRICTION_MODAL]:
      MARKETPLACE_PAYMENT_PACK_OFFPEAK_RESTRICTION_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PAYMENT_PACK_RESTRICTION_MODAL]:
      MARKETPLACE_PAYMENT_PACK_RESTRICTION_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PRIVATE_PASS_CARD]:
      MARKETPLACE_PRIVATE_PASS_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PRIVATE_PASS_COMPATIBILITY_MODAL]:
      MARKETPLACE_PRIVATE_PASS_COMPATIBILITY_MODAL_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_SEARCH]:
      MARKETPLACE_SEARCH_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_SELECT]:
      MARKETPLACE_SELECT_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_WEEK_TIME_TABLE]:
      MARKETPLACE_WEEK_TIME_TABLE_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PREPAID_LINE_ITEM]:
      MARKETPLACE_PREPAID_LINE_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PREPAID_LINE_LIST]:
      MARKETPLACE_PREPAID_LINE_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_ITEM_QUANTITY]:
      MARKETPLACE_ITEM_QUANTITY_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BASKET_SUMMARY_ITEM_PREVIEW]:
      MARKETPLACE_BASKET_SUMMARY_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BASKET_SUMMARY_LIST_ITEM_PREVIEW]:
      MARKETPLACE_BASKET_SUMMARY_LIST_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BASKET_SUMMARY_PREVIEW]:
      MARKETPLACE_BASKET_SUMMARY_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BASKET_SUMMARY_DIALOG_PREVIEW]:
      MARKETPLACE_BASKET_SUMMARY_DIALOG_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_MINIMAL_APPBAR]:
      MARKETPLACE_MINIMAL_APPBAR_PREVIEW,
    [CssComponentsVariantIdentifiers.BOOKER_MODULE_OFFER_SUMMARY]:
      MARKETPLACE_BOOKER_MODULE_OFFER_SUMMARY_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_SPOT_SELECTOR]:
      MARKETPLACE_SPOT_SELECTOR_PREVIEW,
    [CssComponentsVariantIdentifiers.BOOKER_MODULE_BUYABLE_ITEMS_LIST]:
      BOOKER_MODULE_BUYABLE_ITEMS_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_COMBO]:
      BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_COMBO_PREVIEW,
    [CssComponentsVariantIdentifiers.BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_PACK]:
      BOOKER_MODULE_BUYABLE_ITEM_PAYMENT_PACK_PREVIEW,
    [CssComponentsVariantIdentifiers.BOOKER_MODULE_BUYABLE_ITEM_CONTRACT]:
      BOOKER_MODULE_BUYABLE_ITEM_CONTRACT_PREVIEW,
    [CssComponentsVariantIdentifiers.CONFIRMATION_CHECKOUT_MESSAGE]:
      CONFIRMATION_CHECKOUT_MESSAGE_PREVIEW,
    [CssComponentsVariantIdentifiers.ALERT]: ALERT_PREVIEW,
    [CssComponentsVariantIdentifiers.MESSAGE_WITHOUT_ICON]:
      MESSAGE_WITH_ICON_PREVIEW,
    [CssComponentsVariantIdentifiers.MINIMAL_SUBSCRIPTION_CARD]:
      MINIMAL_SUBSCRIPTION_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PRODUCT_ITEM_LIST]:
      MARKETPLACE_PRODUCT_ITEM_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_PRODUCT_ITEM]:
      MARKETPLACE_PRODUCT_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MINIMAL_PRIVATE_PASS_CARD]:
      MINIMAL_PRIVATE_PASS_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CHECKOUT_ITEMS_PRIVATE_PASS_LIST]:
      MARKETPLACE_CHECKOUT_ITEMS_PRIVATE_PASS_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.MINIMAL_PAYMENT_COMBO_CARD]:
      MINIMAL_PAYMENT_COMBO_CARD_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MINIMAL_PAYMENT_PACK_CARD]:
      MINIMAL_PAYMENT_PACK_CARD_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_COMBO_LIST]:
      MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_COMBO_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_PACK_LIST]:
      MARKETPLACE_CHECKOUT_ITEMS_PAYMENT_PACK_LIST_LIST_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_BOOKING_ITEM]:
      MARKETPLACE_BOOKING_ITEM_PREVIEW,
    [CssComponentsVariantIdentifiers.MARKETPLACE_OFFER_BOOKING_LIST]:
      MARKETPLACE_OFFER_BOOKING_LIST_PREVIEW,
    ...(Config.REACT_APP_SENTRY_ENVIRONMENT !== 'production' && {
      [CssComponentsVariantIdentifiers.FABRIQUE_TYPOGRAPHY]:
        FABRIQUE_TYPOGRAPHY_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_CARD]: FABRIQUE_CARD_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_BADGE]: FABRIQUE_BADGE_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_TEXTFIELD]:
        FABRIQUE_TEXTFIELD_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_BUTTON]:
        FABRIQUE_BUTTON_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_ICON_BUTTON]:
        FABRIQUE_ICON_BUTTON_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_ACTION_TAB]:
        FABRIQUE_ACTION_TAB_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_BLANKET]:
        FABRIQUE_BLANKET_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_TAB]: FABRIQUE_TAB_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_RADIOBUTTON]:
        FABRIQUE_RADIOBUTTON_PREVIEW,
      [CssComponentsVariantIdentifiers.FABRIQUE_CHECKBOX]:
        FABRIQUE_CHECKBOX_PREVIEW,
    }),
  });

export const CSS_COMPONENT_PAGES: Immutable.Immutable<MarketplacePage[]> =
  Immutable(Array.from(new Set(CSS_COMPONENTS.flatMap((c) => c.pages))));
