export const ATTENDANCE_HISTORY_PAGE_SIZE_CHOICES = [10, 25, 50];

export const ATTENDANCE_HISTORY_PAGE_SIZE_DEFAULT = 10;

export const ATTENDANCE_HISTORY_DETAILS_PAGE_SIZE_CHOICES = [10, 25, 50];

export const ATTENDANCE_HISTORY_DETAILS_PAGE_SIZE_DEFAULT = 10;
