[tool.commitizen]
name = "cz_conventional_commits"
version = "42.6.0"
version_files = [
    "src/release.js",
    ".cz.toml:version",
    "VERSION"
]
bump_message = "ci(release): $current_version → $new_version [skip-ci]"
changelog_file="CHANGELOG.md"
