image: node:alpine

variables:
  YARN_CACHE_DIR: "$CI_PROJECT_DIR/yarn-cache"

cache:
  paths:
    #    - "$YARN_CACHE_DIR"
    - "$CI_PROJECT_DIR/node_modules"
  key: "$CI_COMMIT_REF_SLUG"

stages:
  - lint
  - test
  - build

before_script:
  - yarn config set cache-folder $YARN_CACHE_DIR
  - yarn install
  - du -hs $YARN_CACHE_DIR
  - du -hs "$CI_PROJECT_DIR/node_modules"

lint:
  stage: lint
  script:
    - yarn lint --quiet

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
    - yarn global add netlify-cli
    - $CI_PROJECT_DIR/scripts/configure_build.sh
    - netlify deploy --auth=$NETLIFY_TOKEN --site=3d93de4c-10d3-4b08-a9e1-8355d90b56d7 --dir=build
    - rm build/env.js
  artifacts:
    paths:
      - build
    expire_in: 1 month

release on sentry:
  stage: build
  script:
    - yarn add @sentry/cli --dev
    - ./scripts/make-release.sh
  only:
    refs:
      - master

# run_e2e_test:
#   stage: test
#   script:
#     - cypress run --record --key 29017f03-970c-4c8d-91cf-d62da85f8bef
