packages:
  # Common packages
  - "packages/**"

  # Applications
  - "apps/**"

  # Tools
  - "tools/**"

  # Ignore storybook builds
  - "!**/storybook-static/**"

  # Ignore dist outputs
  - "!**/dist/**"
overrides:
  unlayer-types: 1.278.0
allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@swc/core": true
  canvas: true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  fsevents: false
  javascript-obfuscator: true
  msw: true
  nx: true
  puppeteer: true
  rudder-sdk-js: true
  unrs-resolver: true
