packages:
  # Common packages
  - "packages/**"

  # Applications
  - "apps/**"

  # Tools
  - "tools/**"

  # Ignore storybook builds
  - "!**/storybook-static/**"

  # Ignore dist outputs
  - "!**/dist/**"
