export const CHANGE_EMAIL_REQUEST_LINK_ACCOUNTS = 0;
export const CHANGE_EMAIL_REQUEST_NON_EXISTING_EMAIL = 1;

export const CHANGE_EMAIL_REQUEST_LINK_ACCOUNT_KIND = 0;
export const CHANGE_EMAIL_REQUEST_MERGE_ACCOUNT_KIND = 1;
export const CHANGE_EMAIL_REQUEST_SIMPLE_EMAIL_CONFIRMATION_KIND = 2;

export const CHANGE_MEMBER_EMAIL_PENDING_STATUS = 0;
export const CHANGE_MEMBER_EMAIL_BLOCKED_BY_DELAY_EXCEEDED = 1;
export const CHANGE_EMAIL_CANCELLED_BY_MANAGER = 2;
export const CHANGE_EMAIL_CANCELLED_AND_RENEWED_BY_MANAGER = 3;
export const CHANGE_EMAIL_BLOCKED_BY_DST_MEMBER = 4;
export const CHANGE_EMAIL_BLOCKED_BY_SRC_MEMBER = 5;
export const CHANGE_EMAIL_BLOCKED_BY_NEW_USER_WITH_SAME_EMAIL = 6;
export const CHANGE_EMAIL_REQUEST_ACCEPTED = 7;
