export const PLANNED_PAYMENT_EVENT_STATUS_PENDING = 0;
export const PLANNED_PAYMENT_EVENT_STATUS_REGISTERED = 1;
export const PLANNED_PAYMENT_EVENT_STATUS_ERROR = 2;
export const PLANNED_PAYMENT_EVENT_STATUS_CANCELED = 3;
