export const BILLING_PLAN_PAYMENT_METHOD_STRIPE_CB = 0;
export const BILLING_PLAN_PAYMENT_METHOD_STRIPE_SEPA = 1;
export const BILLING_PLAN_PAYMENT_METHOD_BSPORT_CREDIT = 2;
export const BILLING_PLAN_PAYMENT_METHOD_STRIPE_BACS_DEBIT = 3;
