export const BILLING_PLAN_STATUS_NOT_STARTED = 0;
export const BILLING_PLAN_STATUS_STARTED = 1;
export const BILLING_PLAN_STATUS_STOPPED = 2;
export const BILLING_PLAN_STATUS_PAUSED = 3;
export const BILLING_PLAN_STATUS_ENDED = 4;
