export enum RoleType {
  USER_ROLE_NO_RESTRICTION = 0,
  USER_ROLE_ONLY_OFFER_MANAGEMENT = 1,
  USER_ROLE_ONLY_OFFER_MANAGEMENT_AND_MEMBER = 2,
  USER_ROLE_CHECKIN_APP = 3,
  USER_ROLE_ADMIN = 4,
  USER_ROLE_REPORTING = 5,
  USER_ROLE_QUICKSALE = -1,
}
