export const OFFER_WAITING_LIST_STATUS_OPEN = 0;
export const OFFER_WAITING_LIST_STATUS_FULL = 1;
export const OFFER_WAITING_LIST_STATUS_ALREADY_BOOKED = 2;
export const OFFER_WAITING_LIST_STATUS_CONVERTIBLE = 3;
export const OFFER_WAITING_LIST_LOCKED_BY_PENDING_BOOKINGS = 6005;
