// PAUSE
export const PAUSE_RESULT_SUCCESS = 1;
export const CONTRACT_PAUSE_RESULT_SUCCESS = 2;
export const PAUSE_NAME_MAX_LENGTH = 150;

// BILLING PLAN STATUS
export const BILLING_PLAN_STATUS_HAS_STARTED = 2;
export const BILLING_PLAN_STATUS_HAS_STOPPED = 3;
export const BILLING_PLAN_STATUS_HAS_ENDED = 4;
export const BILLING_PLAN_STATUS_IS_PAUSED = 5;
