export default {
  HAS_FETCHED_ALL_ACTIVITIES: 'HAS_FETCHED_ALL_ACTIVITIES',
  START_FETCH_ALL_ACTIVITIES: 'START_FETCH_ALL_ACTIVITIES',
  ERROR_FETCHING_ALL_ACTIVITIES: 'ERROR_FETCHING_ALL_ACTIVITIES',
  ACTIVITY_ALREADY_LOADING: 'ACTIVITY_ALREADY_LOADING',
  FETCHED_META_ACTIVITY_DETAILS: 'FETCHED_META_ACTIVITY_DETAILS',
};
