export default {
  LOGIN_INITIATED: 'LOGIN_INITIATED',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  DISCONNECT: 'DISCONNECT',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  CHECK_EMAIL_EXISTS_LOADING: 'CHECK_EMAIL_EXISTS_LOADING',
  CHECK_EMAIL_EXISTS_ERROR: 'CHECK_EMAIL_EXISTS_ERROR',
  CHECK_EMAIL_EXISTS_SUCCESS: 'CHECK_EMAIL_EXISTS_SUCCESS',
};
