export default {
  HAS_FETCHED_BOOKINGS: 'HAS_FETCHED_BOOKINGS',
  START_FETCH_BOOKINGS: 'START_FETCH_BOOKINGS',
  ERROR_FETCHING_BOOKINGS: 'ERROR_FETCHING_BOOKINGS',

  START_UPDATING_BOOKING_STATUS: 'START_UPDATING_BOOKING_STATUS',
  ERROR_UPDATING_BOOKING_STATUS: 'ERROR_UPDATING_BOOKING_STATUS',
  BOOKING_STATUS_UPDATED: 'BOOKING_STATUS_UPDATED',

  START_UPDATING_BOOKING_OPTION: 'START_UPDATING_BOOKING_OPTION',
  ERROR_UPDATING_BOOKING_OPTION: 'ERROR_UPDATING_BOOKING_OPTION',
  BOOKING_OPTION_UPDATED: 'BOOKING_OPTION_UPDATED',

  BOOKING_ADD_START: 'BOOKING_ADD_START',
  BOOKING_ADD_ERROR: 'BOOKING_ADD_ERROR',
  BOOKING_ADD_SUCCESS: 'BOOKING_ADD_SUCCESS',

  BOOKING_DELETE_START: 'BOOKING_DELETE_START',
  BOOKING_DELETE_SUCCESS: 'BOOKING_DELETE_SUCCESS',
  BOOKING_DELETE_ERROR: 'BOOKING_DELETE_ERROR',
};
