export default {
  HAS_FETCHED_BOOKINGS: 'HAS_FETCHED_BOOKINGS',
  START_FETCH_BOOKINGS: 'START_FETCH_BOOKINGS',
  ERROR_FETCHING_BOOKINGS: 'ERROR_FETCHING_BOOKINGS',

  START_UPDATING_BOOKING_STATUS: 'START_UPDATING_BOOKING_STATUS',
  ERROR_UPDATING_BOOKING_STATUS: 'ERROR_UPDATING_BOOKING_STATUS',
  BOOKING_STATUS_UPDATED: 'BOOKING_STATUS_UPDATED',

  START_UPDATING_BOOKING_OPTION: 'START_UPDATING_BOOKING_OPTION',
  ERROR_UPDATING_BOOKING_OPTION: 'ERROR_UPDATING_BOOKING_OPTION',
  BOOKING_OPTION_UPDATED: 'BOOKING_OPTION_UPDATED',
};
