export default {
  HAS_FETCHED_ASSOCIATED_COACH: 'HAS_FETCHED_ASSOCIATED_COACH',
  START_FETCH_ASSOCIATED_COACH: 'START_FETCH_ASSOCIATED_COACH',
  ERROR_FETCHING_ASSOCIATED_COACH: 'ERROR_FETCHING_ASSOCIATED_COACH',
  ASSOCIATED_COACH_ALREADY_LOADING: 'ASSOCIATED_COACH_ALREADY_LOADING',
};
