export default {
  HAS_FETCHED_ASSOCIATED_COACH: 'HAS_FETCHED_ASSOCIATED_COACH',
  START_FETCH_ASSOCIATED_COACH: 'START_FETCH_ASSOCIATED_COACH',
  ERROR_FETCHING_ASSOCIATED_COACH: 'ERROR_FETCHING_ASSOCIATED_COACH',
  ASSOCIATED_COACH_ALREADY_LOADING: 'ASSOCIATED_COACH_ALREADY_LOADING',
  HAS_FETCHED_ASSOCIATED_COACH_PERFORMANCE:
    'HAS_FETCHED_ASSOCIATED_COACH_PERFORMANCE',
  START_FETCH_ASSOCIATED_COACH_PERFORMANCE:
    'START_FETCH_ASSOCIATED_COACH_PERFORMANCE',
  ERROR_FETCHING_ASSOCIATED_COACH_PERFORMANCE:
    'ERROR_FETCHING_ASSOCIATED_COACH_PERFORMANCE',
  COACH_CREATE_OR_UPDATE: 'COACH_CREATE_OR_UDPATE',
  COACH_CREATE_OR_UPDATE_SUCCESS: 'COACH_CREATE_OR_UPDATE_SUCCESS',
  COACH_CREATE_OR_UPDATE_ERROR: 'COACH_CREATE_OR_UPDATE_ERROR',
  COACH_UPDATE: 'COACH_UPDATE',
};
