export default {
  HAS_FETCHED_ESTABLISHMENTS: 'HAS_FETCHED_ESTABLISHMENTS',
  START_FETCH_ESTABLISHMENTS: 'START_FETCH_ESTABLISHMENTS',
  ERROR_FETCHING_ESTABLISHMENTS: 'ERROR_FETCHING_ESTABLISHMENTS',
  ESTABLISHMENT_CREATE_OR_UPDATE: 'ESTABLISHMENT_CREATE_OR_UDPATE',
  ESTABLISHMENT_CREATE_OR_UPDATE_SUCCESS:
    'ESTABLISHMENT_CREATE_OR_UPDATE_SUCCESS',
  ESTABLISHMENT_CREATE_OR_UPDATE_ERROR: 'ESTABLISHMENT_CREATE_OR_UPDATE_ERROR',
  ESTABLISHMENT_UPDATE: 'ESTABLISHMENT_UPDATE',
};
