export default {
  HAS_FETCHED_ESTABLISHMENTS: 'HAS_FETCHED_ESTABLISHMENTS',
  START_FETCH_ESTABLISHMENTS: 'START_FETCH_ESTABLISHMENTS',
  ERROR_FETCHING_ESTABLISHMENTS: 'ERROR_FETCHING_ESTABLISHMENTS',
};
