export default {
  MARKETPLACE_COMPANY_FETCH_SUCCESS: 'MARKETPLACE_COMPANY_FETCH_SUCCESS',
  MARKETPLACE_COMPANY_FETCH_START: 'MARKETPLACE_COMPANY_FETCH_START',
  MARKETPLACE_COMPANY_FETCH_ERROR: 'MARKETPLACE_COMPANY_FETCH_ERROR',
  MARKETPLACE_CALENDAR_FETCH_SUCCESS: 'MARKETPLACE_CALENDAR_FETCH_SUCCESS',
  MARKETPLACE_CALENDAR_FETCH_START: 'MARKETPLACE_CALENDAR_FETCH_START',
  MARKETPLACE_CALENDAR_FETCH_ERROR: 'MARKETPLACE_CALENDAR_FETCH_ERROR',
  MARKETPLACE_OFFERS_BY_DAY_FETCH_SUCCESS:
    'MARKETPLACE_OFFERS_BY_DAY_FETCH_SUCCESS',
  MARKETPLACE_OFFERS_BY_DAY_FETCH_START:
    'MARKETPLACE_OFFERS_BY_DAY_FETCH_START',
  MARKETPLACE_OFFERS_BY_DAY_FETCH_ERROR:
    'MARKETPLACE_OFFERS_BY_DAY_FETCH_ERROR',
  MARKETPLACE_PACKS_FETCH_SUCCESS: 'MARKETPLACE_PACKS_FETCH_SUCCESS',
  MARKETPLACE_PACKS_FETCH_START: 'MARKETPLACE_PACKS_FETCH_START',
  MARKETPLACE_PACKS_FETCH_ERROR: 'MARKETPLACE_PACKS_FETCH_ERROR',
};
