export default {
  START_FETCH_MEMBERS: 'START_FETCH_MEMBERS',
  HAS_FETCHED_MEMBERS: 'HAS_FETCHED_MEMBERS',
  ERROR_FETCHING_MEMBERS: 'ERROR_FETCHING_MEMBERS',
  HAS_FETCHED_MEMBER_BOOKINGS: 'HAS_FETCHED_MEMBER_BOOKINGS',
  START_FETCH_MEMBER: 'START_FETCH_MEMBER',
  HAS_FETCHED_MEMBER: 'HAS_FETCHED_MEMBER',
  ERROR_FETCHING_MEMBER: 'ERROR_FETCHING_MEMBER',
  MEMBER_CREATE_OR_UPDATE: 'MEMBER_CREATE_OR_UDPATE',
  MEMBER_CREATE_OR_UPDATE_SUCCESS: 'MEMBER_CREATE_OR_UPDATE_SUCCESS',
  MEMBER_CREATE_OR_UPDATE_ERROR: 'MEMBER_CREATE_OR_UPDATE_ERROR',
  MEMBER_UPDATE: 'MEMBER_UPDATE',

  MEMBER_NOTE_CREATEORUPDATE_ERROR: 'MEMBER_NOTE_CREATEORUPDATE_ERROR',
  MEMBER_NOTE_CREATEORUPDATE_SUCCESS: 'MEMBER_NOTE_CREATEORUPDATE_SUCCESS',
  MEMBER_NOTE_CREATEORUPDATE_START: 'MEMBER_NOTE_CREATEORUPDATE_START',

  MEMBER_NOTE_DELETE_START: 'MEMBER_NOTE_DELETE_START',
  MEMBER_NOTE_DELETE_ERROR: 'MEMBER_NOTE_DELETE_ERROR',
  MEMBER_NOTE_DELETE_SUCCESS: 'MEMBER_NOTE_DELETE_SUCCESS',
};
