export default {
  START_FETCH_MEMBERS: 'START_FETCH_MEMBERS',
  HAS_FETCHED_MEMBERS: 'HAS_FETCHED_MEMBERS',
  ERROR_FETCHING_MEMBERS: 'ERROR_FETCHING_MEMBERS',
  HAS_FETCHED_MEMBER_BOOKINGS: 'HAS_FETCHED_MEMBER_BOOKINGS',
  START_FETCH_MEMBER: 'START_FETCH_MEMBER',
  HAS_FETCHED_MEMBER: 'HAS_FETCHED_MEMBER',
  ERROR_FETCHING_MEMBER: 'ERROR_FETCHING_MEMBER',
};
