export default {
  START_FETCH_MEMBERS: 'START_FETCH_MEMBERS',
  HAS_FETCHED_MEMBERS: 'HAS_FETCHED_MEMBERS',
  ERROR_FETCHING_MEMBERS: 'ERROR_FETCHING_MEMBERS',
  HAS_FETCHED_MEMBER_BOOKINGS: 'HAS_FETCHED_MEMBER_BOOKINGS',
}
