export default {
  HAS_FETCHED_ALL_OFFERS: 'HAS_FETCHED_ALL_OFFERS',
  START_FETCH_ALL_OFFERS: 'START_FETCH_ALL_OFFERS',
  ERROR_FETCHING_ALL_OFFERS: 'ERROR_FETCHING_ALL_OFFERS',
  OFFER_ALREADY_LOADING: 'OFFER_ALREADY_LOADING',
};
