export default {
  PAYMENT_START_FETCH_PAYMENT_PACK: 'PAYMENT_START_FETCH_PAYMENT_PACk',
  PAYMENT_HAS_FETCHED_PAYMENT_PACK: 'PAYMENT_HAS_FETCHED_PAYMENT_PACK',
  PAYMENT_ERROR_FETCHING_PAYMENT_PACK: 'PAYMENT_ERROR_FETCHING_PAYMENT_PACk',

  PAYMENT_START_FETCH_OFFER: 'PAYMENT_START_FETCH_OFFER',
  PAYMENT_HAS_FETCHED_OFFER: 'PAYMENT_HAS_FETCHED_OFFER',
  PAYMENT_ERROR_FETCHING_OFFER: 'PAYMENT_ERROR_FETCHING_OFFER',

  PAYMENT_START_FETCH_COMPATIBLE_PASS: 'PAYMENT_START_FETCH_COMPATIBLE_PASS',
  PAYMENT_HAS_FETCHED_COMPATIBLE_PASS: 'PAYMENT_HAS_FETCHED_COMPATIBLE_PASS',
  PAYMENT_ERROR_FETCHING_COMPATIBLE_PASS:
    'PAYMENT_ERROR_FETCHING_COMPATIBLE_PASS',
  PAYMENT_START_FETCH_COMPATIBLE_PAYMENT_PACKS:
    'PAYMENT_START_FETCH_COMPATIBLE_PAYMENT_PACKS',
  PAYMENT_HAS_FETCHED_COMPATIBLE_PAYMENT_PACKS:
    'PAYMENT_HAS_FETCHED_COMPATIBLE_PAYMENT_PACKS',
  PAYMENT_ERROR_FETCHING_COMPATIBLE_PAYMENT_PACKS:
  'PAYMENT_ERROR_FETCHING_COMPATIBLE_PAYMENT_PACKS',

  PAYMENT_START_FETCH_OPTION: 'PAYMENT_START_FETCH_OPTION',
  PAYMENT_HAS_FETCHED_OPTION: 'PAYMENT_HAS_FETCHED_OPTION',
  PAYMENT_ERROR_FETCHING_OPTION: 'PAYMENT_ERROR_FETCHING_OPTION',

  PAYMENT_START_CHECKING_OPTION_EXISTENCE: 'PAYMENT_START_CHECKING_OPTION_EXISTENCE',
  PAYMENT_HAS_CHECKED_OPTION_EXISTENCE: 'PAYMENT_HAS_CHECKED_OPTION_EXISTENCE',
  PAYMENT_ERROR_CHEKING_OPTION_EXISTENCE: 'PAYMENT_ERROR_CHEKING_OPTION_EXISTENCE',
};
