// @flow
export default {
  SEARCH_TEXT_START: 'SEARCH_TEXT_START',
  SEARCH_TEXT_SUCCESS: 'SEARCH_TEXT_SUCCESS',
  SEARCH_TEXT_ERROR: 'SEARCH_TEXT_ERROR',
  SEARCH_SELECT_ENTITY_START: 'SEARCH_SELECT_ENTITY_START',
  SEARCH_SELECT_ENTITY_SUCCESS: 'SEARCH_SELECT_ENTITY_SUCCESS',
  SEARCH_SELECT_ENTITY_ERROR: 'SEARCH_SELECT_ENTITY_ERROR',
  SEARCH_FINISHED: 'SEARCH_FINISHED',
};
