export default {
  SHOP_FETCH_START: 'SHOP_FETCH_START',
  SHOP_FETCH_SUCCESS: 'SHOP_FETCH_SUCCESS',
  SHOP_FETCH_ERROR: 'SHOP_FETCH_ERROR',

  SUB_SHOP_FETCH_START: 'SUB_SHOP_FETCH_START',
  SUB_SHOP_FETCH_SUCCESS: 'SUB_SHOP_FETCH_SUCCESS',
  SUB_SHOP_FETCH_ERROR: 'SUB_SHOP_FETCH_ERROR',

  SHOP_ITEM_CREATEOR_UPDATE_START: 'SHOP_ITEM_CREATEOR_UPDATE_START',
  SHOP_ITEM_CREATEOR_UPDATE_SUCCESS: 'SHOP_ITEM_CREATEOR_UPDATE_SUCCESS',
  SHOP_ITEM_CREATEOR_UPDATE_ERROR: 'SHOP_ITEM_CREATEOR_UPDATE_ERROR',

  SHOP_ITEM_DELETE_START: 'SHOP_ITEM_DELETE_START',
  SHOP_ITEM_DELETE_SUCCESS: 'SHOP_ITEM_DELETE_SUCCESS',
  SHOP_ITEM_DELETE_ERROR: 'SHOP_ITEM_DELETE_ERROR',

  SHOP_ITEM_UPDATE_PROVISIONS_START: 'SHOP_ITEM_UPDATE_PROVISIONS_START',
  SHOP_ITEM_UPDATE_PROVISIONS_SUCCESS: 'SHOP_ITEM_UPDATE_PROVISIONS_SUCCESS',
  SHOP_ITEM_UPDATE_PROVISIONS_ERROR: 'SHOP_ITEM_UPDATE_PROVISIONS_ERROR',

  SUB_SHOP_ITEM_CREATEORUPDATE_START: 'SUB_SHOP_ITEM_CREATEORUPDATE_START',
  SUB_SHOP_CREATEORUPDATE_ERROR: 'SUB_SHOP_CREATEORUPDATE_ERROR',
  SUB_SHOP_UPDATE_SUCCESS: 'SUB_SHOP_UPDATE_SUCCESS',
  SUB_SHOP_CREATE_SUCCESS: 'SUB_SHOP_CREATE_SUCCESS',

  SUB_SHOP_DELETE_START: 'SUB_SHOP_DELETE_START',
  SUB_SHOP_DELETE_SUCCESS: 'SUB_SHOP_DELETE_SUCCESS',
  SUB_SHOP_DELETE_ERROR: 'SUB_SHOP_DELETE_ERROR',
};
