export default {
  HAS_FETCHED_STATS_ACTIVITIES: 'HAS_FETCHED_STATS_ACTIVITIES',
  START_FETCH_STATS_ACTIVITIES: 'START_FETCH_STATS_ACTIVITIES',
  ERROR_FETCHING_STATS_ACTIVITIES: 'ERROR_FETCHING_STATS_ACTIVITIES',
  STATS_ALREADY_UP_TO_DATE: 'STATS_ALREADY_UP_TO_DATE',
};
