export const STORAGE_KEY_BSPORT_TOKEN = 'bsport:http:token';
export const STORAGE_KEY_LIGHT_SIGNUP_FORM_VALUES =
  'bsport:one-click-booking:lightSignupFormValues';
export const STORAGE_KEY_LIGHT_SIGNUP_MEMBER_ID =
  'bsport:one-click-booking:lightSignUpMemberId';
export const STORAGE_KEY_BSPORT_IMPERSONATED_TOKEN = 'http:token';
export const STORAGE_KEY_BSPORT_IMPERSONATED_ORIGIN_TOKEN =
  'bsport:franchise:http:token';
export const STORAGE_KEY_BSPORT_I18NEXTLNG = 'i18nextLng';
export const STORAGE_KEY_BSPORT_I18NEXTLNG_ORIGIN =
  'i18nextLng:impersonated:origin';
export const STORAGE_KEY_BSPORT_IMPERSONATED_ORIGIN_URL =
  'bsport:impersonation:url:origin';
export const STORAGE_KEY_BSPORT_IMPERSONATED_LEFT_URL =
  'bsport:impersonation:url:exited';
export const STORAGE_KEY_BSPORT_RELATED_MEMBER_TOKEN =
  'bsport:relatedMemberMaster:http:token';
export const STORAGE_KEY_BSPORT_ACCM_CHANNEL_ID = 'bsport:accm-channel:id';
export const STORAGE_KEY_BSPORT_IMPERSONATED_GOTO_URL = 'goto:url';

export const authActionTypes = {
  LOGIN_INITIATED: 'LOGIN_INITIATED',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  DISCONNECT: 'DISCONNECT',
  PASSWORD_RESET_LOADING: 'PASSWORD_RESET_LOADING',
  PASSWORD_RESET_ERROR: 'PASSWORD_RESET_ERROR',
  RESET_PASSWORD_SENT: 'RESET_PASSWORD_SENT',
  EMAIL_CONFIRMATION_SENT: 'EMAIL_CONFIRMATION_SENT',
  EMAIL_CONFIRMED: 'EMAIL_CONFIRMED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  CHECK_EMAIL_EXISTS_LOADING: 'CHECK_EMAIL_EXISTS_LOADING',
  CHECK_EMAIL_EXISTS_ERROR: 'CHECK_EMAIL_EXISTS_ERROR',
  CHECK_EMAIL_EXISTS_SUCCESS: 'CHECK_EMAIL_EXISTS_SUCCESS',
  IMPERSONATE_MANAGER_LOADING: 'IMPERSONATE_MANAGER_LOADING',
  CHECK_ACCESS_LEVEL: 'CHECK_ACCESS_LEVEL',
  RESET_STORE: 'RESET_STORE',
  UPDATE_HAS_ENABLED_REVAMPED_BACKOFFICE:
    'UPDATE_HAS_ENABLED_REVAMPED_BACKOFFICE',
  RESPONSE_AUTHENTICATED_STATUS: 'RESPONSE_AUTHENTICATED_STATUS',
};
