export const PENALTY_KIND_BLOCK_CPP = 0;
export const PENALTY_KIND_NEGATIVE_ACCOUNT = 1;

export const PENALTY_MODE_FRANCHISOR_PRORATA = 0;
export const PENALTY_MODE_FRANCHISOR_BUYER = 1;
export const PAYMENT_PACK_MASS_EXTENSION_PAGE_SIZE = 5;

export const TEMPLATE_CONSUMER_PACK_PAGINATION_SIZE = 30;

export const FRANCHISE_PAYMENT_PACK_TEMPLATE_PAGINATION_SIZE = 50;

export const ACTIVE_TEMPLATE_SEARCH_PARAMS = {
  disabled: false,
};
