/**
 * This file is a script to clean the Translation Memory file generated by Weblate.
 *
 * The issues with this file are:
 * - it mixes all projects (app, saas-legacy, frontend-revamp, backend)
 * - the file is super heavy (54Mo)
 * - it contains Translation Memory from "fr" to other languages, that are useless for our
 *   Transifex projects using "en" as source language
 * - our source language is not "en" but "af"
 *
 * What are the goals ?
 * - Separate the TM file into two TM files: one for b2b, one for b2c
 * - Drop useless Translation Memories (app, wrong source language, useless target language)
 */
import { readFileSync, writeFileSync } from "fs";
import { readJSONSync } from "fs-extra";
import path from "path";

import { getMonorepoBasePathSync } from "@bsport/typescript-monorepo-utils";

import { ensureDir } from "./utils";

// ============================================================================
// ========== CONSTANTS TO ADAPT ==========

// ----- Inputs -----

// TMX Data
const TM_FOLDER = "/home/**TO-REPLACE**";
const INPUT_TMX_FILEPATH = path.resolve(TM_FOLDER, "weblate-memory.tmx");

// Repositories
const ABSOLUTE_CODEBASE_LOCATION = "**TO-REPLACE**";

const BSPORT_DJANGO_REPOSITORY_NAME = "bsport-django";
const BSPORT_DJANGO_RELATIVE_SOURCE_PATH = "locale/en/LC_MESSAGES/django.po";
const BSPORT_DJANGO_ABSOLUTE_SOURCE_PATH = path.resolve(
  ABSOLUTE_CODEBASE_LOCATION,
  BSPORT_DJANGO_REPOSITORY_NAME,
  BSPORT_DJANGO_RELATIVE_SOURCE_PATH,
);

const SAAS_LEGACY_REPOSITORY_NAME = "gaia";
const SAAS_LEGACY_RELATIVE_SOURCE_PATH =
  "apps/applications/saas-legacy/src/i18n/source/translations.json";
const SAAS_LEGACY_ABSOLUTE_SOURCE_PATH = path.resolve(
  ABSOLUTE_CODEBASE_LOCATION,
  SAAS_LEGACY_REPOSITORY_NAME,
  SAAS_LEGACY_RELATIVE_SOURCE_PATH,
);

const SAAS_LEGACY_B2C_NAMESPACES = [
  "checkout",
  "consumerSpace",
  "marketplace",
  "membership",
  "quicksale",
];

// NB:bsport-mobile is skipped because it uses "fr" as source translation

// ----- Outputs -----
const OUTPUT_B2B_TMX = "b2b-weblate-memory.tmx";
const OUTPUT_B2C_TMX = "b2c-weblate-memory.tmx";

// ========== TYPES ==========

type Translations = {
  [key: string]: string | Translations;
};

interface KeyValuePair {
  flattenKey: string;
  value: string;
}

type TMSection = {
  srcContent: string; // content on the first seg block
  srcLang: string; // xml:lang on the first tuv block
  targetContent: string; // content on the second seg block
  targetLang: string; // xml:lang on the second tuv block
};

type TMFileContent = Array<TMSection>;

// ============================================================================

/**
 * Decode XML entities like `&amp;` or `&#x27;` into readable characters.
 */
function decodeXML(str: string): string {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&#x27;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

/**
 * Escape characters to be safe in XML.
 */
function escapeXML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/'/g, "&#x27;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Read and parse TMX file content to extract translation units (<tu>).
 *
 * @returns {TMFileContent} Parsed TM sections (source + target per entry).
 */
function getWeblateTMContent(): TMFileContent {
  const content = readFileSync(INPUT_TMX_FILEPATH, "utf-8");

  const regex = /<tu>([\s\S]*?)<\/tu>/g;
  const tuMatches = content.matchAll(regex);

  const results: TMFileContent = [];

  for (const tuMatch of tuMatches) {
    const tuContent = tuMatch[1];

    const tuvRegex =
      /<tuv xml:lang="(.*?)">[\s\S]*?<seg>([\s\S]*?)<\/seg>[\s\S]*?<\/tuv>/g;
    const tuvMatches = Array.from(tuContent.matchAll(tuvRegex));

    if (tuvMatches.length >= 2) {
      const srcLang = tuvMatches[0][1];
      const srcContent = decodeXML(tuvMatches[0][2].trim());
      const targetLang = tuvMatches[1][1];
      const targetContent = decodeXML(tuvMatches[1][2].trim());

      results.push({
        srcLang,
        srcContent,
        targetLang,
        targetContent,
      });
    }
  }

  return results;
}

/**
 * Extract source strings from repositories, grouped into B2B and B2C scopes.
 *
 * - From `bsport-django` `.po` file → all msgid entries are B2B.
 * - From `saas-legacy` JSON translations → categorized per namespace.
 *
 * @returns {{b2bSources: string[], b2cSources: string[]}}
 */
function getSourcePerScope(): {
  b2bSources: Array<string>;
  b2cSources: Array<string>;
} {
  const b2bSources: Array<string> = [];
  const b2cSources: Array<string> = [];

  // Step 1 - Extract sources from bsport-django (considered as 100% b2b)
  {
    const poContent = readFileSync(BSPORT_DJANGO_ABSOLUTE_SOURCE_PATH, "utf-8");

    // Match msgid "..."
    const msgidRegex = /^msgid\s+"(.*)"$/gm;
    let match: RegExpExecArray | null;
    while ((match = msgidRegex.exec(poContent)) !== null) {
      const msgid = match[1];
      if (msgid && msgid !== "") {
        b2bSources.push(msgid);
      }
    }
  }

  // Step 2 - Extract sources from saas-legacy
  {
    const jsonTranslations = readJSONSync(SAAS_LEGACY_ABSOLUTE_SOURCE_PATH);

    const getFlattenKeyValuePairs = (
      translations: Translations,
      parentKey: string = "",
    ): KeyValuePair[] => {
      const keyValuePairs: KeyValuePair[] = [];

      for (const key in translations) {
        if (translations.hasOwnProperty(key)) {
          const newKey = parentKey ? `${parentKey}.${key}` : key;
          if (typeof translations[key] === "object") {
            keyValuePairs.push(
              ...getFlattenKeyValuePairs(translations[key], newKey),
            );
          } else {
            keyValuePairs.push({
              flattenKey: newKey,
              value: translations[key],
            });
          }
        }
      }

      return keyValuePairs;
    };

    const flattenTranslations = getFlattenKeyValuePairs(jsonTranslations);

    for (const { flattenKey, value } of flattenTranslations) {
      const namespace = flattenKey.split(".")[0];
      if (SAAS_LEGACY_B2C_NAMESPACES.includes(namespace)) {
        b2cSources.push(value);
      } else {
        b2bSources.push(value);
      }
    }
  }

  return { b2bSources, b2cSources };
}

/**
 * Filter TMX entries into B2B and B2C scope based on matching sources.
 *
 * @param weblateTMXContent TM entries parsed from Weblate file
 * @param b2bSources Valid source strings for B2B scope
 * @param b2cSources Valid source strings for B2C scope
 */
function extractTMXEntries({
  weblateTMXContent,
  b2bSources,
  b2cSources,
}: {
  weblateTMXContent: TMFileContent;
  b2bSources: Array<string>;
  b2cSources: Array<string>;
}) {
  const b2bTMContent: TMFileContent = [];
  const b2cTMContent: TMFileContent = [];

  const acceptedSrcLang = ["af", "en"];
  const acceptedTargetLang = ["nl", "fr", "de", "it", "es"];

  const getFinalEntry = (entry: TMSection): TMSection => {
    return {
      srcContent: entry.srcContent,
      srcLang: "en", // Force source language to be en
      targetContent: entry.targetContent,
      targetLang: entry.targetLang,
    };
  };

  for (const entry of weblateTMXContent) {
    if (!acceptedSrcLang.includes(entry.srcLang)) {
      // Skip because not right source
      continue;
    }
    if (!acceptedTargetLang.includes(entry.targetLang)) {
      // Skip because we don't use this language in Transifex
      continue;
    }
    // Some caracters are transformed in the TMX file (e.g. an apostrophe in JSON file is &#x27; in TMX file)
    const sanitizedSrcContent = entry.srcContent;
    if (b2bSources.includes(sanitizedSrcContent)) {
      b2bTMContent.push(getFinalEntry(entry));
    }
    if (b2cSources.includes(sanitizedSrcContent)) {
      b2cTMContent.push(getFinalEntry(entry));
    }
  }

  return { b2bTMContent, b2cTMContent };
}

/**
 * Generate a TMX file from TMFileContent.
 *
 * @param content TM entries to write
 * @param path Output filepath
 */
function generateTMXFile({
  content,
  path,
}: {
  content: TMFileContent;
  path: string;
}) {
  const fileStart = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<tmx version="1.4">',
    '<header adminlang="en" srclang="en">',
    "</header>",
    "<body>",
  ];

  const fileEnd = ["</body>", "</tmx>"];

  const formattedEntries: Array<string> = content.map(
    (value) => `
<tu>
  <tuv xml:lang="${value.srcLang}">
    <seg>${escapeXML(value.srcContent)}</seg>
  </tuv>
  <tuv xml:lang="${value.targetLang}">
    <seg>${escapeXML(value.targetContent)}</seg>
  </tuv>
</tu>`,
  );

  const fileContent = [...fileStart, ...formattedEntries, ...fileEnd].join(
    "\n",
  );

  writeFileSync(path, fileContent, "utf-8");
  console.log("📁 File generated at path: ", path);
}

// ============================================================================
function main() {
  console.log("🌠 Start cleaning TMX file for TM migration !");
  console.time("\n🚀 Completed cleaning successfully in ");

  const ichizenBasePath = getMonorepoBasePathSync();

  let weblateTMXContent: TMFileContent = [];

  // Step 1 - getWeblateTMContent
  {
    console.log("\n⌛ Step 1 - Retrieving Weblate TMX Content...");
    try {
      weblateTMXContent = getWeblateTMContent();
    } catch (error) {
      console.error("❌ Encoutered an issue in step 1: ", error);
      return;
    }
    console.log("☑️  Successfully completed step 1");
  }

  let b2bSources: Array<string> = [];
  let b2cSources: Array<string> = [];

  // Step 2 - getSourcePerScope
  console.log("\n⌛ Step 2 - Retrieving Sources Per Scope...");
  try {
    const { b2bSources: _b2bSources, b2cSources: _b2cSources } =
      getSourcePerScope();
    b2bSources = _b2bSources;
    b2cSources = _b2cSources;
  } catch (error) {
    console.error("❌ Encoutered an issue in step 2: ", error);
    return;
  }
  console.log("☑️  Successfully completed step 2");

  let b2bTMContent: TMFileContent = [];
  let b2cTMContent: TMFileContent = [];

  // Step 3 - extractTMXEntries
  console.log("\n⌛ Step 3 - Extracting TMX Entries per Scope...");
  try {
    const { b2bTMContent: _b2bTMContent, b2cTMContent: _b2cTMContent } =
      extractTMXEntries({
        weblateTMXContent,
        b2bSources,
        b2cSources,
      });
    b2bTMContent = _b2bTMContent;
    b2cTMContent = _b2cTMContent;
  } catch (error) {
    console.error("❌ Encoutered an issue in step 3: ", error);
    return;
  }
  console.log("☑️  Successfully completed step 3");

  const tempDir = path.resolve(
    ichizenBasePath,
    "tools",
    "i18n-management",
    "__tmp__",
  );
  ensureDir(tempDir);

  // Step 4 - generateTMXFile with b2bTMContent
  console.log("\n⌛ Step 4 - Generating TMX files for B2B...");
  try {
    generateTMXFile({
      content: b2bTMContent,
      path: path.resolve(tempDir, OUTPUT_B2B_TMX),
    });
  } catch (error) {
    console.error("❌ Encoutered an issue in step 4: ", error);
    return;
  }
  console.log("☑️ Successfully completed step 4");

  // Step 5 - generateTMXFile with b2cTMContent
  console.log("\n⌛ Step 5 - Generating TMX files for B2C...");
  try {
    generateTMXFile({
      content: b2cTMContent,
      path: path.resolve(tempDir, OUTPUT_B2C_TMX),
    });
  } catch (error) {
    console.error("❌ Encoutered an issue in step 5: ", error);
    return;
  }
  console.log("☑️  Successfully completed step 5");

  console.timeEnd("\n🚀 Completed cleaning successfully in ");
}

main();
