export const LOCK_ACQUISITION_FAILURE_GENERIC = 85000;
export const LOCK_ACQUISITION_FAILURE_SPOT_SCHEDULING = 85101;
export const BASKET_LOCK_ACQUISITION_FAILURE = 15002;
export const BASKET_PROCESSING_PAYMENT_EXCEPTION = 15004;
