import type { Urls } from "#src/types";
import type { RolePermissionPath } from "#src/utils/permissions";

/**
 * Map a static Url Key to a list of Permission path
 */
export const PERMISSIONS_PATHS: Record<
  keyof Urls,
  Array<RolePermissionPath>
> = {
  accessMonitoring: ["navigationMenu.accessMonitoring"],
  accessMonitoring_monitor: ["navigationMenu.accessMonitoring.monitor"],
  accessMonitoring_perform: ["navigationMenu.accessMonitoring.perform"],
  accessMonitoring_settings: ["navigationMenu.accessMonitoring.settings"],
  activity: ["navigationMenu.myClub.activities"],
  appointment: ["navigationMenu.myClub.appointments"],
  appointmentPass: ["navigationMenu.products.privatePass"],
  attendance: ["navigationMenu.payments.clockIn"],
  audience: ["navigationMenu.marketing.cadence"],
  calendar: ["navigationMenu.calendar"],
  customForm: ["navigationMenu.calendar"],
  dashboard: ["navigationMenu.dashboard"],
  directDebit: ["navigationMenu.payments.directDebits"],
  emailTemplate: ["navigationMenu.marketing.templates"],
  establishment: ["navigationMenu.myClub.establishments"],
  expense: ["navigationMenu.payments.expenses"],
  feedback: [],
  giftcard: ["navigationMenu.products.giftcards"],
  inbox: ["navigationMenu.inbox"],
  invoice: ["navigationMenu.payments.billings"],
  member: ["navigationMenu.member"],
  memberNotification: ["navigationMenu.marketing.notifications"],
  order: ["navigationMenu.payments.orders"],
  pack: ["navigationMenu.products.packs"],
  pass: ["navigationMenu.products.paymentPack"],
  payout: [],
  payroll: ["navigationMenu.payments.teachers"],
  performanceTracking: ["navigationMenu.myClub.programs"],
  playlist: ["navigationMenu.digitalOffer.playlists"],
  promotion: ["navigationMenu.products.promotions"],
  reporting: ["navigationMenu.reporting"],
  schedule: ["navigationMenu.schedule"],
  search: ["navigationMenu.search"],
  settings_activeCampaign: ["navigationMenu.settings.activeCampaign"],
  settings_billing: ["navigationMenu.settings.billing"],
  settings_company: ["navigationMenu.settings.company"],
  settings_companyOnboarding: ["navigationMenu.settings.company"],
  settings_bsportSubscription: ["navigationMenu.settings.subscription"],
  settings_general: ["navigationMenu.settings.generals"],
  settings_livestreaming: ["navigationMenu.settings.liveStreaming"],
  settings_marketplace: ["navigationMenu.settings.marketplace"],
  settings_memberForm: ["navigationMenu.settings.memberForms"],
  settings_mobilePersonalization: [
    "navigationMenu.settings.mobilePersonalization",
  ],
  settings_partnership: ["navigationMenu.settings.partnership"],
  settings_paymentFacility: ["navigationMenu.payments.installments"],
  settings_paymentMethod: ["navigationMenu.settings.paymentMethods"],
  settings_payroll: ["navigationMenu.settings.teacherPayrollRules"],
  settings_quickbook: ["navigationMenu.settings.quickBooks"],
  settings_quicksale: ["navigationMenu.settings.quicksale"],
  settings_referral: ["navigationMenu.settings.referral"],
  settings_permission: ["navigationMenu.settings.staffs"],
  settings_teacherView: ["navigationMenu.settings.coachUserspace"],
  settings_personalization: ["navigationMenu.settings.personalization"],
  settings_transactionalNotification: [
    "navigationMenu.settings.transactionnalEmail",
  ],
  settings_waitlist: ["navigationMenu.settings.waitingList"],
  settings_webhook: ["navigationMenu.settings.webHook"],
  settings_webshop: ["navigationMenu.settings.webShop"],
  settings_widgets: ["navigationMenu.settings.widgets"],
  smartlist: ["navigationMenu.marketing.smartlists"],
  subscription: ["navigationMenu.products.contracts"],
  substitution: ["navigationMenu.myClub.replacement"],
  tag: ["navigationMenu.marketing.tags"],
  teacher: ["navigationMenu.myClub.teachers"],
  tutorial: ["navigationMenu.tutorial"],
  video: ["navigationMenu.digitalOffer.videos"],
  webshop: ["navigationMenu.products.shopReworked"],
  webshop_products: ["navigationMenu.products.shopReworked.products"],
  webshop_settings: ["navigationMenu.products.shopReworked.settings"],
  webshopOld: ["navigationMenu.products.shop"],
  workshop: ["navigationMenu.myClub.workshops"],
};
