export const GROUPED_OFFERS_RECURSIVE_WEEKLY_FREQUENCY = 0;
export const GROUPED_OFFERS_RECURSIVE_MONTHLY_FREQUENCY = 1;
export const GROUPED_OFFERS_RECURSIVE_YEARLY_FREQUENCE = 2;

export const REDIRECTED_TO_FIRST_OFFER_TO_BE_BOOKED =
  'redirectedToFirstOfferToBeBooked=true';
