export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_FILE_TOO_LARGE_ERROR =
  'fileTooLargeError';
export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_NOT_CSV_FILE_ERROR =
  'notCsvFileError';
export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_INCORRECT_DATA_ERROR =
  'incorrectDataError';

export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_ALL_ERRORS = [
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_FILE_TOO_LARGE_ERROR,
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_NOT_CSV_FILE_ERROR,
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_INCORRECT_DATA_ERROR,
];

export const VOUCHER_CODE_CSV_FILE_SIZE_LIMIT_IN_BYTES = 1000000;

export const VOUCHER_CODE_CHARACTERS_NUMBER_LIMIT = 100;

export const VOUCHER_CODE_CSV_FILE_MIME_TYPE = 'text/csv';

export const VOUCHER_CODE_TABLE_PAGE_SIZE = 9;
