import type { Example } from "@bsport/types";
import Head from "next/head";
import { Inter } from "next/font/google";
import { wow } from "@bsport/constants";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const ex: Example = {
    start: `Never ${wow.NEVER}`,
    end: `Give ${wow.GIVE}`,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Never: {ex.start}</p>
          <p>Give: {ex.end}</p>
        </div>
      </main>
    </>
  );
}
