import "@bsport/kaizen-primitive/style.css";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@bsport/kaizen-primitive";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.description}>
          <Button
            label="Button"
            loading={true}
            onClick={() => {
              console.log("clicked");
            }}
            intent="cta"
            size="md"
            color="onstrong"
          />
        </div>
      </main>
    </>
  );
}
