export enum GymAvailabilityReasonCode {
  VALID_GYM_EXISTS = 'VALID_GYM_EXISTS',
  DISABLED_GYM_EXISTS = 'DISABLED_GYM_EXISTS',
  RECENT_INTEGRATION_REQUEST = 'RECENT_INTEGRATION_REQUEST',
  ENABLED_GYM_FROM_API = 'ENABLED_GYM_FROM_API',
  DISABLED_GYM_FROM_API = 'DISABLED_GYM_FROM_API',
  ACCESS_NOT_GRANTED = 'ACCESS_NOT_GRANTED',
}

export const GymAvailabilityReasonCodeChoices = Object.values(
  GymAvailabilityReasonCode,
);
