export const PRIVATE_BOOKING_CREATED_BY_STAFF = 20;
export const PRIVATE_BOOKING_CANCELLED_BY_STAFF = 21;
export const PRIVATE_BOOKING_DATE_TIME_MODIFIED_BY_STAFF = 22;
export const PRIVATE_BOOKING_COACH_MODIFIED_BY_STAFF = 23;
export const PRIVATE_BOOKING_RESTORED_BY_STAFF = 24;

export const RECURRENT_PRIVATE_BOOKING_CANCELLED_BY_STAFF = 31;

export const ActionStaffHistoryKindTranslationDict = {
  [PRIVATE_BOOKING_CANCELLED_BY_STAFF]: 'cancelled',
  [PRIVATE_BOOKING_DATE_TIME_MODIFIED_BY_STAFF]: 'dateModified',
  [PRIVATE_BOOKING_COACH_MODIFIED_BY_STAFF]: 'coachModified',
  [PRIVATE_BOOKING_RESTORED_BY_STAFF]: 'restored',
  [RECURRENT_PRIVATE_BOOKING_CANCELLED_BY_STAFF]: 'cancelledByRecurrence',
};
