export const EMAIL_TEMPLATE_FAKE_ITEMS = [
  {
    id: 1,
    company_id: 2,
    title: "Modèle 1",
    subject: "JF",
    date_modified: "2025-02-27T12:03:16.122000+01:00",
    available_for_companies: [],
    ordering_in_category: 1,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 68,
    company_id: 2,
    title: "waitinglist",
    subject: "waitinglist",
    date_modified: "2022-11-10T15:38:13.225000+01:00",
    available_for_companies: [],
    ordering_in_category: -20,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 118,
    company_id: 2,
    title: "invoice_sum_up variable",
    subject: "invoice_sum_up variable",
    date_modified: "2025-04-11T14:44:04.474000+02:00",
    available_for_companies: [],
    ordering_in_category: -45,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 26,
    company_id: 2,
    title: "bleblele",
    subject: "eee",
    date_modified: "2025-03-07T17:19:42.577000+01:00",
    available_for_companies: [],
    ordering_in_category: -1,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 86,
    company_id: 2,
    title: "Reset PWD",
    subject: "Custom - {reset_password_url}",
    date_modified: "2023-05-11T11:36:17.718000+02:00",
    available_for_companies: [],
    ordering_in_category: -33,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 81,
    company_id: null,
    title: "Reset password correct",
    subject: "tetsts",
    date_modified: "2023-04-13T17:53:05+02:00",
    available_for_companies: [],
    ordering_in_category: 3,
    category: null,
    available: true,
    is_default_bsport_template: true,
  },
  {
    id: 96,
    company_id: 2,
    title: "Template canada company (copie)",
    subject: "Template canada company",
    date_modified: "2024-02-13T10:55:47.457000+01:00",
    available_for_companies: [],
    ordering_in_category: -37,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 62,
    company_id: 2,
    title: "Plateforme uniquement (copie)",
    subject: "Plateforme uniquement",
    date_modified: "2022-09-27T11:04:04.577000+02:00",
    available_for_companies: [],
    ordering_in_category: -16,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 29,
    company_id: 2,
    title: "je test",
    subject: "je te",
    date_modified: "2025-02-04T15:29:02.384000+01:00",
    available_for_companies: [],
    ordering_in_category: -4,
    category: 8,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 129,
    company_id: 2,
    title: "Test changement email BO (copy)",
    subject: "Custom - {new_email}",
    date_modified: "2025-04-10T14:54:35.887000+02:00",
    available_for_companies: [],
    ordering_in_category: -53,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 127,
    company_id: 2,
    title: "Spot available",
    subject: "Waitlist",
    date_modified: "2025-01-20T16:04:02.278000+01:00",
    available_for_companies: [],
    ordering_in_category: -51,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 38,
    company_id: null,
    title: "paretag",
    subject: "azeaze",
    date_modified: "2025-04-11T18:51:17.784000+02:00",
    available_for_companies: [33, 24, 18, 17, 8, 61, 59, 2, 35, 6],
    ordering_in_category: -17,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 75,
    company_id: 2,
    title: "Feedback after workshop/training",
    subject: "We want your feedback",
    date_modified: "2023-02-21T11:10:31.794000+01:00",
    available_for_companies: [],
    ordering_in_category: -26,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 82,
    company_id: null,
    title: "Giftcard correct",
    subject: "kbh",
    date_modified: "2023-04-13T17:56:13+02:00",
    available_for_companies: [],
    ordering_in_category: 4,
    category: null,
    available: true,
    is_default_bsport_template: true,
  },
  {
    id: 88,
    company_id: 2,
    title: "Test changement email BO",
    subject: "Custom - {new_email}",
    date_modified: "2023-05-04T17:17:28.336000+02:00",
    available_for_companies: [],
    ordering_in_category: -35,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 117,
    company_id: 2,
    title: "azert",
    subject: "zert",
    date_modified: "2024-04-18T14:38:10.422000+02:00",
    available_for_companies: [],
    ordering_in_category: -48,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 70,
    company_id: 2,
    title: "template variable communication chat",
    subject: "template variable communication chat",
    date_modified: "2025-02-17T15:23:01.724000+01:00",
    available_for_companies: [],
    ordering_in_category: -22,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 31,
    company_id: 2,
    title: "refrf",
    subject: "dfgdfg",
    date_modified: "2022-02-04T12:39:29.564000+01:00",
    available_for_companies: [],
    ordering_in_category: 2,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 28,
    company_id: 2,
    title: "bleblele (copie)",
    subject: "eee",
    date_modified: "2024-12-11T18:16:16.981000+01:00",
    available_for_companies: [],
    ordering_in_category: -8,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 47,
    company_id: 2,
    title: "tret",
    subject: "tretre",
    date_modified: "2022-05-18T16:22:52.560000+02:00",
    available_for_companies: [],
    ordering_in_category: -10,
    category: 25,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 124,
    company_id: 2,
    title: "Modified Session (for teacher)",
    subject: "Modified Session (for teacher)",
    date_modified: "2024-07-19T10:10:47.402000+02:00",
    available_for_companies: [],
    ordering_in_category: -49,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 130,
    company_id: 2,
    title: "Newgen",
    subject: "Ehhhhhhhh ui",
    date_modified: "2025-02-27T12:04:19.376000+01:00",
    available_for_companies: [],
    ordering_in_category: -54,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 133,
    company_id: 2,
    title: "This is a title",
    subject: "This the new subject",
    date_modified: "2025-04-10T16:54:06.097000+02:00",
    available_for_companies: [],
    ordering_in_category: -55,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 53,
    company_id: 2,
    title: "Template canada company",
    subject: "Template canada company",
    date_modified: "2022-08-25T15:57:08.862000+02:00",
    available_for_companies: [33, 24, 18, 17, 8, 2, 35, 6],
    ordering_in_category: -11,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 41,
    company_id: 2,
    title: "bleblele (copie)",
    subject: "eee",
    date_modified: "2023-04-03T18:03:41.592000+02:00",
    available_for_companies: [],
    ordering_in_category: -9,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 136,
    company_id: 2,
    title: "adzzad",
    subject: "zadazda",
    date_modified: "2025-04-11T15:03:41.316000+02:00",
    available_for_companies: [],
    ordering_in_category: -58,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 116,
    company_id: 2,
    title: "Referring",
    subject: "referral grant",
    date_modified: "2024-04-17T10:59:36.382000+02:00",
    available_for_companies: [],
    ordering_in_category: -44,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 27,
    company_id: 2,
    title: "test catégorie (copie)",
    subject: "Ceci est lesujet du mail {data}",
    date_modified: "2025-02-04T15:04:21.023000+01:00",
    available_for_companies: [],
    ordering_in_category: -2,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 140,
    company_id: 2,
    title: "On va voir si ça update tout",
    subject: "dazdadza",
    date_modified: "2025-04-11T15:40:00.599000+02:00",
    available_for_companies: [],
    ordering_in_category: -62,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 69,
    company_id: 2,
    title: "test balises",
    subject: "test balises",
    date_modified: "2022-11-23T16:56:23.874000+01:00",
    available_for_companies: [],
    ordering_in_category: -21,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 72,
    company_id: 2,
    title: "test 13/12",
    subject: "test 13/12",
    date_modified: "2022-12-13T09:42:46.816000+01:00",
    available_for_companies: [],
    ordering_in_category: -23,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 89,
    company_id: 2,
    title: "Fusion 2 comptes interne",
    subject: "Custom - {new_email} {old_email}",
    date_modified: "2023-05-08T11:20:21.732000+02:00",
    available_for_companies: [],
    ordering_in_category: -32,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 79,
    company_id: 2,
    title: "Direct link to download invoice",
    subject: "Direct link to download invoice",
    date_modified: "2023-04-13T12:21:18.852000+02:00",
    available_for_companies: [],
    ordering_in_category: -30,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 67,
    company_id: 2,
    title: "josuée",
    subject: "eeazrezr",
    date_modified: "2024-12-11T11:21:37.235000+01:00",
    available_for_companies: [],
    ordering_in_category: -19,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 106,
    company_id: 2,
    title: "Reset password correct (copy)",
    subject: "tetsts",
    date_modified: "2024-03-25T15:56:58.752000+01:00",
    available_for_companies: [],
    ordering_in_category: -40,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 120,
    company_id: 2,
    title: "az'rt",
    subject: "aaa",
    date_modified: "2024-06-21T16:25:53.582000+02:00",
    available_for_companies: [],
    ordering_in_category: -46,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 66,
    company_id: 2,
    title: "test next billing date",
    subject: "next billing date",
    date_modified: "2022-11-09T16:04:04.943000+01:00",
    available_for_companies: [],
    ordering_in_category: -18,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 40,
    company_id: 2,
    title: "bleblele (copie) (copie)",
    subject: "eee",
    date_modified: "2025-02-05T17:45:54.694000+01:00",
    available_for_companies: [],
    ordering_in_category: -6,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 128,
    company_id: 2,
    title: "aaaaaa",
    subject: "aaaaTest sujet {email}",
    date_modified: "2025-04-10T12:57:07.531000+02:00",
    available_for_companies: [],
    ordering_in_category: -52,
    category: 21,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 50,
    company_id: 2,
    title: "transac",
    subject: "ddd",
    date_modified: "2023-09-15T11:13:04.483000+02:00",
    available_for_companies: [],
    ordering_in_category: -13,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 55,
    company_id: 2,
    title: "test avec balise",
    subject: "balise ouai ouai ouai",
    date_modified: "2022-09-01T19:43:32.386000+02:00",
    available_for_companies: [],
    ordering_in_category: -14,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 74,
    company_id: 2,
    title: "votre facture",
    subject: "votres factire",
    date_modified: "2023-01-12T11:24:48.617000+01:00",
    available_for_companies: [],
    ordering_in_category: -25,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 135,
    company_id: 2,
    title: "dazdazd",
    subject: "aazaaazdada",
    date_modified: "2025-04-11T14:45:33.772000+02:00",
    available_for_companies: [],
    ordering_in_category: -57,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 134,
    company_id: 2,
    title: "This is a new test",
    subject: "subject test",
    date_modified: "2025-04-14T17:50:58.377000+02:00",
    available_for_companies: [],
    ordering_in_category: -56,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 113,
    company_id: 2,
    title: "Reset password correct (copy)",
    subject: "tetsts",
    date_modified: "2024-03-25T15:56:46.601192+01:00",
    available_for_companies: [],
    ordering_in_category: -41,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 73,
    company_id: 2,
    title: "Liste d'attente 13/12",
    subject: "Liste d'attente 13/12",
    date_modified: "2022-12-13T09:57:54.300000+01:00",
    available_for_companies: [],
    ordering_in_category: -24,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 115,
    company_id: 2,
    title: "Referred",
    subject: "referral activated",
    date_modified: "2024-09-13T19:01:01.280000+02:00",
    available_for_companies: [],
    ordering_in_category: -43,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 5,
    company_id: 2,
    title: "mail de bienvenue",
    subject: "Bienvenue !",
    date_modified: "2023-02-06T16:51:24.938000+01:00",
    available_for_companies: [],
    ordering_in_category: -3,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 78,
    company_id: 2,
    title: "Remaining credits",
    subject: "a",
    date_modified: "2023-03-23T11:22:00.652000+01:00",
    available_for_companies: [],
    ordering_in_category: -29,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 87,
    company_id: 2,
    title: "Test validation email",
    subject: "Custom - {email_confirmation_url}",
    date_modified: "2023-05-04T17:17:58.753000+02:00",
    available_for_companies: [],
    ordering_in_category: -34,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 114,
    company_id: 2,
    title: "Booking canceled Antoine",
    subject: "Booking canceled Antoine",
    date_modified: "2025-04-14T17:28:10.726000+02:00",
    available_for_companies: [],
    ordering_in_category: -42,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 103,
    company_id: 2,
    title: "w",
    subject: "w",
    date_modified: "2024-05-16T11:02:59.106000+02:00",
    available_for_companies: [],
    ordering_in_category: -38,
    category: 16,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 25,
    company_id: 2,
    title: "test catégorie",
    subject: "eee",
    date_modified: "2025-02-27T18:16:21.384000+01:00",
    available_for_companies: [],
    ordering_in_category: 3,
    category: 7,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 90,
    company_id: 2,
    title: "Test giftcard",
    subject: "ddddddme}, {message_is_for}",
    date_modified: "2025-01-29T09:22:11.419000+01:00",
    available_for_companies: [],
    ordering_in_category: -36,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 125,
    company_id: 2,
    title: "BS-4871",
    subject: "Test TB",
    date_modified: "2025-04-14T14:32:57.537000+02:00",
    available_for_companies: [],
    ordering_in_category: -50,
    category: 33,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 30,
    company_id: 2,
    title: "je test (copie)",
    subject: "je te",
    date_modified: "2025-04-07T18:24:23.304000+02:00",
    available_for_companies: [],
    ordering_in_category: -5,
    category: 8,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 61,
    company_id: 2,
    title: "Franchise (copie)",
    subject: "Franchise",
    date_modified: "2025-04-04T16:34:47.637000+02:00",
    available_for_companies: [],
    ordering_in_category: -15,
    category: null,
    available: true,
    is_default_bsport_template: false,
  },
  {
    id: 119,
    company_id: 2,
    title: "luxon",
    subject: "datessssssssssss",
    date_modified: "2024-07-11T10:33:27.580000+02:00",
    available_for_companies: [],
    ordering_in_category: -47,
    category: 18,
    available: true,
    is_default_bsport_template: false,
  },
];

export const EMAIL_TEMPLATE_CATEGORY_FAKE_ITEMS = [
  {
    id: 33,
    name: "Transactional email",
    company_id: 2,
    category_ordering: -19,
  },
  {
    id: 21,
    name: "9",
    company_id: 2,
    category_ordering: -18,
  },
  {
    id: 16,
    name: "4",
    company_id: 2,
    category_ordering: -17,
  },
  {
    id: 7,
    name: "la catégorie de test",
    company_id: 2,
    category_ordering: -16,
  },
  {
    id: 19,
    name: "7",
    company_id: 2,
    category_ordering: -15,
  },
  {
    id: 18,
    name: "6",
    company_id: 2,
    category_ordering: -14,
  },
  {
    id: 24,
    name: "12",
    company_id: 2,
    category_ordering: -13,
  },
  {
    id: 23,
    name: "11",
    company_id: 2,
    category_ordering: -12,
  },
  {
    id: 15,
    name: "3",
    company_id: 2,
    category_ordering: -11,
  },
  {
    id: 22,
    name: "10",
    company_id: 2,
    category_ordering: -10,
  },
  {
    id: 13,
    name: "1",
    company_id: 2,
    category_ordering: -9,
  },
  {
    id: 28,
    name: "16",
    company_id: 2,
    category_ordering: -8,
  },
  {
    id: 27,
    name: "15",
    company_id: 2,
    category_ordering: -7,
  },
  {
    id: 26,
    name: "14",
    company_id: 2,
    category_ordering: -6,
  },
  {
    id: 25,
    name: "13",
    company_id: 2,
    category_ordering: -5,
  },
  {
    id: 14,
    name: "2",
    company_id: 2,
    category_ordering: -4,
  },
  {
    id: 31,
    name: ";,n;,,;n",
    company_id: 2,
    category_ordering: -3,
  },
  {
    id: 8,
    name: "autre cat de test",
    company_id: 2,
    category_ordering: -2,
  },
  {
    id: 20,
    name: "8",
    company_id: 2,
    category_ordering: -1,
  },
];
