// DO NOT REMOVE - AUTOGENERATED

// Export i18n utilities for consuming applications
export {
  i18nNamespacePrefix,
  i18nNamespaces,
  inMemoryTranslationsLoader,
} from "./i18n";
export type { Translations } from "./i18n";
