import {
  COACH_PAYMENT_RULE_FOR_SESSION,
  COACH_PAYMENT_RULE_FOR_GROUP_ACTIVITY,
  COACH_PAYMENT_RULE_FOR_WORKSHOP,
} from '@bsport/common/master-data/coach_payment_rule.js';

export const DISSOCIATED_COACH_PAYMENT_RULE = -9999;
export const DISSOCIATED_COACH_PAYMENT_RULE_GROUP = -8000;
export const ASSOCIATED_COACH_WITH_COACH_PAYMENT_RULE_GROUP = -8001;

export const COACH_PAYMENT_RULE_FOR_ACTIVITIES = [
  COACH_PAYMENT_RULE_FOR_SESSION,
  COACH_PAYMENT_RULE_FOR_GROUP_ACTIVITY,
  COACH_PAYMENT_RULE_FOR_WORKSHOP,
];
