image: 672633452901.dkr.ecr.eu-west-3.amazonaws.com/bsport-infra/gitlab-build-frontend:14

variables:
  AWS_REGION: eu-west-3
  REGISTRY_ENDPOINT: 672633452901.dkr.ecr.eu-west-3.amazonaws.com

stages:
  - build-deploy-feature-branch
  - static-analysis
  - bump-version
  - deploy
  - build-widget
  # - storybook
  - tag-releases

before_script:
  - OLD_VERSION=`echo "$(cat ./VERSION)"`

include:
  # - local: '/ci_/storybook.yml'
  - local: '/ci/widget.yml'
  - local: '/ci/static-analysis.yml'
  - local: '/ci/build.yml'
  - local: '/ci/tag-releases.yml'
  - local: '/ci/build-retro.yaml'
# sonarcloud-check:
#   stage: static-analysis
#   allow_failure: true
#   tags:
#     - deployment
#   before_script:
#     - echo 'drop pnpm run install'
#   image:
#     name: sonarsource/sonar-scanner-cli:latest
#     entrypoint: [""]
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - sonar-scanner
#   only:
#     - merge_requests
#     - dev
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

# .Auto Bump Version Base:
#   image: 672633452901.dkr.ecr.eu-west-3.amazonaws.com/bsport-infra/gitlab-build-docker:latest
#   stage: bump-version
#   tags:
#     - light
#     - cluster:bsport-tooling
#   allow_failure: true
#   only:
#     - master
#     - production
#   before_script:
#     - echo 'Overriding default before_script instruction relying on pnpm run'
#
#   script:
#     - echo $CI_COMMIT_REF_NAME
#     - envsubst "$(printf '${%s} ' $(env | sed 's/=.*//'))"  > .cz < .cz
#     - cat .cz
#     - git remote -v
#     - git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@gitlab.com/bsport/bsport-saas.git
#     - git config --global user.email "contact@bsport.io"
#     - git config --global user.name "bsport-bot"
#     - git fetch --tags
#     - 'exists=`git show-ref refs/heads/${CI_COMMIT_REF_NAME}` && if [ -n "$exists" ]; then git branch -D ${CI_COMMIT_REF_NAME}; fi'
#     - git checkout -b $CI_COMMIT_REF_NAME
#
#     - '[[ $PRERELEASE ]] && cz bump --check-consistency --yes --changelog --prerelease $PRERELEASE && SHOULD_PUSH=1 || SHOULD_PUSH=0;'
#     - 'cz bump --check-consistency --yes --changelog --prerelease $PRERELEASE && SHOULD_PUSH=1 || SHOULD_PUSH=0;'
#     - VERSION=`echo "$(cat ./VERSION)"`
#     - echo $VERSION
#     - echo "#!/bin/sh" >> variables
#     - echo "export TAG='$VERSION'" >> variables
#
#     - 'git push origin $CI_COMMIT_REF_NAME:$CI_COMMIT_REF_NAME --follow-tags || echo "no code to push"'
#     - ./scripts/release-gitlab.sh $VERSION  $CI_PROJECT_ID
#
#   artifacts:
#     paths:
#       - variables

#Auto Bump Dev:
#  extends: .Auto Bump Version Base
#  only:
#    refs:
#      - dev
#  variables:
#    PRERELEASE: alpha

# Auto Bump Staging:
#   extends: .Auto Bump Version Base
#   only:
#     refs:
#       - master
#   variables:
#     PRERELEASE: beta
#
# Auto Bump Production:
#   extends: .Auto Bump Version Base
#   only:
#     refs:
#       - production

# release on sentry:
#   stage: build
#   script:
#     - pnpm run add @sentry/cli --dev
#     - ./scripts/make-release.sh
#   only:
#     refs:
#       - master

# End To End Tests
# Install Cypress binary and run end to end tests using Cypress
# ui tests:
#   # pick up cypress dockerhub image
#   image: cypress/base:10
#   # stage decla
#   stage: e2e_tests
#
#   before_script:
#     - pnpm run config set cache-folder $YARN_CACHE_DIR
#
#     - pnpm run install --frozen-lockfile
#     # Confirm Cypress is ready to use
#     - $(npm bin)/cypress verify
#     # add wait-on package
#     - pnpm run global add wait-on
#     # add serve package that will serve our static files (build)
#     - pnpm run global add serve
#
#   script:
#     # server our build through the port 3000 (same as cypress dev conf)
#     - serve -s build --listen 3000 & wait-on http://localhost:3000
#     # Create environment specific test config including auth token
#     # (saved to cypress.env.json) then run E2E Tests through Cypress in load balancing mode
#     - $(npm bin)/cypress run --record --key 29017f03-970c-4c8d-91cf-d62da85f8bef -- --parallel
#   artifacts:
#     name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
#     expire_in: 1 weeks
#     when: always
#     paths:
#       - cypress/videos
#       - cypress/screenshots
