image: 672633452901.dkr.ecr.eu-west-3.amazonaws.com/bsport-infra/gitlab-build-frontend:node-14

variables:
  AWS_REGION: eu-west-3
  REGISTRY_ENDPOINT: 672633452901.dkr.ecr.eu-west-3.amazonaws.com

#Cache dependencies across all jobs

stages:
  # - static-analysis
  - deploy

include:
  # - local: '/ci/lint.yml'
  - local: '/ci/build.yml'
