export const STREAMLINED_COMMUNICATION_STATUS_SCHEDULED = "scheduled";
export const STREAMLINED_COMMUNICATION_STATUS_FAILED = "failed";
export const STREAMLINED_COMMUNICATION_STATUS_DELIVERED = "delivered";
export const STREAMLINED_COMMUNICATION_STATUS_PROCESSING = "processing";
export const STREAMLINED_COMMUNICATION_STATUS_OPENED = "opened";

export type StreamlinedCommunicationStatus =
  | typeof STREAMLINED_COMMUNICATION_STATUS_SCHEDULED
  | typeof STREAMLINED_COMMUNICATION_STATUS_FAILED
  | typeof STREAMLINED_COMMUNICATION_STATUS_DELIVERED
  | typeof STREAMLINED_COMMUNICATION_STATUS_PROCESSING
  | typeof STREAMLINED_COMMUNICATION_STATUS_OPENED;
