import type { TeamUrlConfiguration } from '#src/sentry/types';

const VERTICAL_URL_CONFIGURATIONS: TeamUrlConfiguration[] = [
  {
    team: 'customer-data-platform',
    urlPatterns: [
      /^\/email-template(?:\/[^/]+)?$/,
      /^\/email-template\/create$/,
      /^\/email-template\/[^/]+\/edit$/,
      /^\/custom-form$/,
      /^\/custom-form\/details\/[^/]+\/(?:general|statistics|layout)$/,
      /^\/smart-list(?:\/[^/]+)?$/,
      /^\/smart-list\/[^/]+\/(?:member|campaign)$/,
      /^\/smart-list\/[^/]+\/campaign\/[^/]+$/,
      /^\/marketing\/notifications(?:\/[^/]+)?$/,
      /^\/marketing\/tags(?:\/[^/]+)?$/,
      /^\/audience(?:\/[^/]+)?$/,
      /^\/inbox\/thread(?:\/[^/]+)?$/,
      /^\/settings\/forms$/,
      /^\/settings\/notification-rule(?:\/(?:booking|member|private_booking|recurrent_private_booking|invoice|giftcard|payment_pack|subscription|offer|replacement_request|waiting_list|referral))?$/,
      /^\/settings\/webhook$/,
      /^\/settings\/referral$/,
      /^\/settings\/active-campaign$/,
      /^\/f\/email-template(?:\/[^/]+)?$/,
      /^\/f\/marketing\/tags$/,
      /^\/f\/marketing\/campaign(?:\/[^/]+)?$/,
      /^\/f\/marketing\/campaign\/[^/]+\/(?:general|history)$/,
      /^\/f\/marketing\/campaign\/[^/]+\/history\/report\/[^/]+$/,
      /^\/f\/settings\/notification-rule(?:\/[^/]+)?$/,
    ],
  },
  {
    team: 'book',
    urlPatterns: [
      /^\/add-offers\/[^/]+$/,
      /^\/calendar\/\d{4}\/\d{1,2}\/\d{1,2}$/,
      /^\/schedule$/,
      /^\/activity$/,
      /^\/activity\/[^/]+\/general$/,
      /^\/activity\/[^/]+\/pack$/,
      /^\/activity\/[^/]+\/pack\/[^/]+$/,
      /^\/workshop-activity\/tabs\/list$/,
      /^\/workshop-activity\/tabs\/groups$/,
      /^\/workshop-activity\/tabs\/groups\/[^/]+$/,
      /^\/workshop-activity\/[^/]+\/general$/,
      /^\/workshop-activity\/[^/]+\/pack$/,
      /^\/workshop-activity\/[^/]+\/pack\/[^/]+$/,
      /^\/workshop-activity\/[^/]+\/group$/,
      /^\/workshop-activity\/[^/]+\/group\/[^/]+$/,
      /^\/offer\/[^/]+$/,
      /^\/private-service\/service\/$/,
      /^\/private-service\/service\/[^/]+\/general$/,
      /^\/private-service\/service\/[^/]+\/calendar$/,
      /^\/settings\/broadcast$/,
      /^\/settings\/waiting-list$/,
    ],
  },
  {
    team: 'core-data',
    urlPatterns: [
      /^\/coach(?:\/[^/]+)?$/,
      /^\/coach\/[^/]+\/private-calendar$/,
      /^\/coach\/edit\/[^/]+$/,
      /^\/coach\/[^/]+\/performance$/,
      /^\/establishment\/room$/,
      /^\/establishment\/details\/[^/]+$/,
      /^\/establishment\/details\/[^/]+\/calendar$/,
      /^\/establishment\/edit\/[^/]+$/,
      /^\/establishment\/add$/,
      /^\/spot-scheduling\/[^/]+$/,
      /^\/performance-tracking(?:\/[^/]+)?$/,
      /^\/replacement\/(?:management|discipline-group)$/,
      /^\/access-monitoring\/(?:monitor|settings|history)$/,
      /^\/clock-in\/(?:real-time|history)$/,
      /^\/member(?:\/[^/]+)?$/,
      /^\/search\/results$/,
      /^\/member\/[^/]+\/(?:info|bookings|vod|performance_tracking|pass|payment|contact|relation|private_booking|giftcard|private-consumer-pass|form|basket)$/,
      /^\/member\/[^/]+\/bookings\/[^/]+$/,
      /^\/member\/[^/]+\/performance-tracking\/[^/]+$/,
      /^\/member\/[^/]+\/pass\/[^/]+\/$/,
      /^\/member\/[^/]+\/relation\/[^/]+$/,
      /^\/member\/[^/]+\/private-consumer-pass\/[^/]+$/,
      /^\/member\/[^/]+\/basket\/[^/]+$/,
      /^\/member\/[^/]+\/private-booking\/[^/]+$/,
      /^\/member\/[^/]+\/vod\/[^/]+$/,
      /^\/member\/[^/]+\/giftcard\/[^/]+$/,
      /^\/member\/edit\/[^/]+$/,
      /^\/member\/add$/,
      /^\/settings\/(?:general|role|coach-userspace|company)$/,
      /^\/tutorial$/,
      /^\/f\/franchises(?:\/[^/]+)?$/,
      /^\/f\/members(?:\/[^/]+\/member\/(?:info|pass|private-consumer-pass|giftcard|subscription))?$/,
      /^\/f\/members\/[^/]+\/member\/(?:pass|private-consumer-pass|giftcard|subscription)\/[^/]+$/,
      /^\/f\/staffrole\/(?:staff|role)$/,
      /^\/f\/settings\/theme$/,
      /^\/login(?:\/(?:signup|reset_password|company_onboarding\/(?:welcome|form|validation)))?$/,
    ],
  },
  {
    team: 'buyable',
    urlPatterns: [
      /^\/payment-pack(?:\/[^/]+)?$/,
      /^\/private-service\/pass(?:\/[^/]+)?$/,
      /^\/shop(?:\/[^/]+)?$/,
      /^\/combo(?:\/[^/]+)?$/,
      /^\/giftcard(?:\/[^/]+)?$/,
      /^\/coupon\/[^/]+$/,
      /^\/subscription\/contract(?:\/[^/]+)?$/,
      /^\/vod\/video(?:\/[^/]+)?$/,
      /^\/vod\/playlist\/[^/]+$/,
      /^\/vod\/playlist\/[^/]+\/video\/[^/]+$/,
      /^\/settings\/shop$/,
      /^\/f\/shop(?:\/[^/]+)?$/,
      /^\/f\/giftcard-template(?:\/[^/]+)?$/,
      /^\/f\/payment-pack-template(?:\/[^/]+)?$/,
      /^\/f\/private-pass-template(?:\/[^/]+)?$/,
      /^\/f\/universal-pass-template(?:\/[^/]+)?$/,
      /^\/f\/coupon-template(?:\/[^/]+)?$/,
      /^\/f\/subscription\/contract-template(?:\/[^/]+)?$/,
    ],
  },
  {
    team: 'financial-services',
    urlPatterns: [
      /^\/invoice$/,
      /^\/invoice\/[^/]+$/,
      /^\/subscription$/,
      /^\/subscription\/[^/]+$/,
      /^\/coach\/performance$/,
      /^\/order\/$/,
      /^\/order\/[^/]+$/,
      /^\/expense\/$/,
      /^\/instalment-payment\/$/,
      /^\/instalment-payment\/[^/]+$/,
      /^\/invoice\/bill-member\/[^/]+$/,
      /^\/settings\/payment-rules$/,
      /^\/settings\/payment-methods$/,
      /^\/settings\/invoice$/,
      /^\/settings\/platform-billing$/,
    ],
  },
  {
    team: 'member-experience',
    urlPatterns: [
      /^\/settings\/marketplace-settings$/,
      /^\/settings\/widget\/customize$/,
      /^\/settings\/widget\/customize-css\/$/,
      /^\/settings\/personalization\/general$/,
      /^\/settings\/mobile-personalisation\/links$/,
      /^\/settings\/mobile-personalisation\/popups$/,
      /^\/settings\/mobile-personalisation\/customize$/,
      /^\/f\/settings\/widget$/,
      /^\/c\/[^/]+(?:\/[^/]+)*$/,
      /^\/m\/[^/]+(?:\/[^/]+)*$/,
      /^\/checkout-s\/[^/]+$/,
      /^\/checkout-s\/[^/]+\/validation$/,
      /^\/checkout\/[^/]+\/giftcard\/[^/]+$/,
      /^\/booker-module-s\/[^/]+\/[^/]+$/,
    ],
  },
  {
    team: 'business-insight',
    urlPatterns: [
      /^\/reporting\/categories$/,
      /^\/reporting\/detail\/(?:basket|billing_plan|members_purchase|members|activities|activityByEst|activityByCoach|workshop|offers|subscription|privateService|referral_grant|cashbook|credit|expense|invoices|unpaid_invoices|payments|payment_sumup|on_spot_payments|dispute|payment_installments|video_purchase|dayBookings|first_booking|bookings|first_attendance|first_privatebooking|private_bookings|unpaid_private_bookings|private_cpasses_expired|memberships|expired_pass|private_cpasses|universal_passes|discount|giftcard|consumer_giftcard|shop|video)\/[^/]+$/,
      /^\/reporting\/views$/,
      /^\/f\/reporting\/categories$/,
      /^\/f\/reporting\/detail\/(?:basket|billing_plan|members_purchase|members|activities|activityByEst|activityByCoach|workshop|offers|subscription|privateService|referral_grant|cashbook|credit|expense|invoices|unpaid_invoices|payments|payment_sumup|on_spot_payments|dispute|payment_installments|video_purchase|dayBookings|first_booking|bookings|first_attendance|first_privatebooking|private_bookings|unpaid_private_bookings|private_cpasses_expired|memberships|expired_pass|private_cpasses|universal_passes|discount|giftcard|consumer_giftcard|shop|video)\/[^/]+$/,
      /^\/f\/reporting\/views$/,
    ],
  },
];

/**
 * Determine the team responsible for the current URL
 * @param url - The URL to match against team configurations
 * @returns The name of the team responsible for the URL
 */
export const getVerticalOwnerByPageUrl = (url: string): string => {
  // Find the first team with a matching URL pattern
  const matchedTeam = VERTICAL_URL_CONFIGURATIONS.find((teamConfig) =>
    teamConfig.urlPatterns.some((pattern) => pattern.test(url)),
  );

  // Return the matched team or a default
  return matchedTeam ? matchedTeam.team : 'unnasigned';
};
