import type { Establishment } from '#src/libs/establishment/types';

export const ESTABLISHMENT_LIST: Establishment[] = [
  {
    associatedestablishment_set: [2, 3],
    capacity: 50,
    cover: 'http://testserver:8000/media/etablissement/Barca_unsplash.jpg',
    disabled: false,
    easy_access: {
      id: 1,
      lines: ['Line 1', 'Line 3'],
      name: 'Easy Access Line A',
    },
    establishment_billing_group_id: 1001,
    has_next_slots: true,
    id: 852,
    location: {
      address: '123 Fitness Street',
      latitude: '48.858844',
      longitude: '2.294351',
    },
    practical_info: 'Open 24/7',
    related_company: 10,
    specific_info: 'Yoga and Pilates available',
    title: 'Main Gym',
    tzname: 'Europe/Paris',
  },
  {
    associatedestablishment_set: [2, 3],
    capacity: 30,
    cover: '',
    disabled: false,
    easy_access: {
      id: 1,
      lines: ['Line 1', 'Line 3'],
      name: 'Easy Access Line A',
    },
    establishment_billing_group_id: 1001,
    has_next_slots: true,
    id: 39,
    location: {
      address: '123bis Fitness Street',
      latitude: '48.858844',
      longitude: '2.294351',
    },
    practical_info: 'Open 24/7',
    related_company: 10,
    specific_info: 'Reformer Pilates available',
    title: 'Special Gym',
    tzname: 'Europe/Paris',
  },
  {
    associatedestablishment_set: [4],
    capacity: 70,
    cover:
      'http://testserver:8000/media/etablissement/miguel-angel-hernandez-Nwc-Z3_aEvw-unsplash.jpg',
    disabled: true,
    easy_access: {
      id: 2,
      lines: ['Line 2', 'Line 5'],
      name: 'Easy Access Line B',
    },
    establishment_billing_group_id: null,
    has_next_slots: false,
    id: 157,
    location: {
      address: '456 Muscle Avenue',
      latitude: '40.712776',
      longitude: '-74.005974',
    },
    practical_info: 'Closed on Sundays',
    related_company: 20,
    specific_info: 'Specialized in weightlifting',
    title: 'Powerhouse Studio',
    tzname: 'America/New_York',
  },
  {
    associatedestablishment_set: [5, 6],
    capacity: 40,
    cover: '',
    disabled: false,
    easy_access: {
      id: 3,
      lines: ['Line 4', 'Line 6'],
      name: 'Easy Access Line C',
    },
    establishment_billing_group_id: 1003,
    has_next_slots: true,
    id: 210,
    location: {
      address: '789 Health Road',
      latitude: '34.052235',
      longitude: '-118.243683',
    },
    practical_info: 'Family-friendly environment',
    related_company: 30,
    specific_info: 'Includes swimming pool and sauna',
    title: 'Wellness Hub',
    tzname: 'America/Los_Angeles',
  },
  {
    associatedestablishment_set: [101, 102],
    capacity: 50,
    cover: 'http://testserver:8000/media/etablissement/Barca_unsplash.jpg',
    disabled: false,
    easy_access: { id: 1, lines: ['Line A', 'Line B'], name: 'Access 1' },
    establishment_billing_group_id: 10,
    has_next_slots: true,
    id: 832,
    location: {
      address: '789 Maple Ave',
      latitude: '40.7128',
      longitude: '-74.0060',
    },
    practical_info: 'Open 9am to 5pm',
    related_company: 1001,
    specific_info: 'Near Central Park',
    title: 'Establishment One',
    tzname: 'America/New_York',
  },
  {
    associatedestablishment_set: [103, 104],
    cover: '',
    disabled: true,
    easy_access: { id: 2, lines: ['Line C', 'Line D'], name: 'Access 2' },
    establishment_billing_group_id: 20,
    id: 544,
    location: {
      address: '123 Fitness Street',
      latitude: '34.0522',
      longitude: '-118.2437',
    },
    specific_info: 'Downtown LA',
    title: 'Establishment Two',
    tzname: 'America/Los_Angeles',
  },
  {
    associatedestablishment_set: [105, 106],
    capacity: 75,
    cover:
      'http://testserver:8000/media/etablissement/miguel-angel-hernandez-Nwc-Z3_aEvw-unsplash.jpg',
    disabled: false,
    easy_access: { id: 3, lines: ['Line E', 'Line F'], name: 'Access 3' },
    establishment_billing_group_id: 30,
    has_next_slots: false,
    id: 143,
    location: {
      address: '789 Maple Ave',
      latitude: '41.8781',
      longitude: '-87.6298',
    },
    practical_info: 'Open 8am to 6pm',
    related_company: 1002,
    specific_info: 'Near Millennium Park',
    title: 'Establishment Three',
    tzname: 'America/Chicago',
  },
];
