export type CompanyTheme = {
  id: number;
  has_partnership: boolean;
  franchisor: number;
  primary_color: string;
  payment_method_available: number[];
  payment_method_available_recurringly: number[];
  payment_method_available_manager: number[];
  payment_method_available_basket: number[];
  payment_method_available_subscription: number[];
  secondary_color: string;
  online_payment_enabled: boolean;
  allow_guest: boolean;
  allow_guest_activatable: boolean;
  allow_guest_max_number: number;
  allow_guest_frequency: string;
  hidden_from_marketplace: boolean;
  show_offers_filling: boolean;
  currency: string;
  currency_display: string;
  stripe_region: string;
  is_whereby_integration_allowed: boolean;
  payment_method_missing: boolean;
  is_whereby_integration_enabled: boolean;
  default_booking_ordering: string;
  general_terms_and_conditions: string;
  general_terms_of_use: string;
  waiver: string;
  email_sender_address: string;
  websiteURL: string;
  scheduleURL: string;
  instagramURL: string;
  facebookURL: string;
  android_app_url: string;
  hideCoach: boolean;
  ios_app_url: string;
  show_cancelled_offers_customer: boolean;
  show_cancelled_offers_manager: boolean;
  show_workshops_customer: boolean;
  max_future_booking: number;
  max_future_workshop: number;
  booking_option_included_in_max_future_booking: boolean;
  cover: string;
  mobile_cover: string;
  company: number;
  company_name: string;
  timezone_name: string;
  hide_least_specific_payment_pack: boolean;
  default_attendance: boolean;
  consumer_regularize_debt: boolean;
  allow_consumer_to_use_internal_account: boolean;
  accept_double_booking: boolean;
  accept_double_booking_workshop: boolean;
  gtmId: string;
  facebookPixelId: string;
  extra_info: string;
  stripe_pk_key: string;
  stripe_id: string;
  vod: boolean;
  locale: string;
  basket_expiration_days: number;
  show_booked_gender_offer: boolean;
  is_checking_balance: boolean;
  nb_to_check_balance: number;
  vod_providers: number[];
  gender_max_shift_for_booking: number;
  is_premium: boolean;
  enable_multi_localization: boolean;
  hide_intercom: boolean;
  is_quickbook_integration_allowed: boolean;
  is_quickbook_integration_enabled: boolean;
  schedule_timerange_begin: string;
  schedule_timerange_end: string;
  coach_can_edit_attendance: boolean;
  autotag_rule_extended: boolean;
  performance_tracking: boolean;
  provincial_tax_name: null;
  provincial_tax_value: null;
  is_tax_excluded_in_marketplace: boolean;
  hide_unnecessary_compatible_purchase_method: boolean;
  hide_sessions_with_tags_when_not_eligible: boolean;
  hide_member_details_in_app_private_booking_for_coach: boolean;
  is_coach_access_enabled_by_default: boolean;
  has_stripe_location: boolean;
  widget_theme: WidgetTheme;
  has_coach_access_to_calendar: boolean;
  has_coach_access_to_compensation: boolean;
  has_coach_access_to_compensation_downloading: boolean;
  has_coach_access_to_replacement_request: boolean;
  requires_email_confirmation_when_signing_up: boolean;
  confirm_email_url_redirection: string;
  reset_password_url_redirection: string;
  is_two_way_email_activated: boolean;
  no_show_validated_number_of_hours: number;
  no_show_email_sent_number_of_hours: number;
  is_roll_call_mandatory: boolean;
  show_establishment: boolean;
  show_level: boolean;
  show_activity_color: boolean;
  session_time_display: number;
  coach_display: number;
  days_format_display: number;
  is_auto_debit_activated: boolean;
  is_referral_program_activated: boolean;
  churn_last_paid_month: null;
  refund_blocking_limit: string;
  show_free_session_label: boolean;
  hide_book_button: boolean;
  display_new_checkout_flow: boolean;
  hide_credits_for_customers: boolean;
  is_sequential_marketing_active: boolean;
  pass_credit_factor: number;
  force_billing_details_on_cards: boolean;
  display_bubble_background: boolean;
  show_past_sessions_calendar: boolean;
  start_calendar_week_on_today: boolean;
  mobile_app_default_page: string;
  use_company_email_sender_address_for_reset_password: boolean;
  checkin_tablet_visible_session_cutoff_minute: number;
  first_warning_payment_method_expiration_days: number;
  second_warning_payment_method_expiration_days: number;
  earliest_hour_to_send_communications: number;
  latest_hour_to_send_communications: number;
  show_member_account_balance: boolean;
  show_barcode_button: boolean;
  show_membership_number: boolean;
  is_paypal_available_in_country: boolean;
  is_fiskaly_operational: boolean;
  display_credit_price_for_offer: boolean;
  display_new_webshop: boolean;
  zoho_member_import_enabled: boolean;
  one_click_checkout_enabled: boolean;
  invoice_exporter_id: null;
  revamped_passes_page_enabled: boolean;
  display_stop_subscription_from_member_side: boolean;
  revamped_backoffice_enabled: boolean;
};

type CompanyThemePatchKey =
  | "primary_color"
  | "payment_method_available_manager"
  | "payment_method_available_basket"
  | "payment_method_available_subscription"
  | "secondary_color"
  | "allow_guest"
  | "allow_guest_max_number"
  | "hidden_from_marketplace"
  | "show_offers_filling"
  | "is_whereby_integration_allowed"
  | "payment_method_missing"
  | "is_whereby_integration_enabled"
  | "general_terms_and_conditions"
  | "general_terms_of_use"
  | "waiver"
  | "websiteURL"
  | "scheduleURL"
  | "instagramURL"
  | "facebookURL"
  | "android_app_url"
  | "hideCoach"
  | "ios_app_url"
  | "show_cancelled_offers_customer"
  | "show_cancelled_offers_manager"
  | "show_workshops_customer"
  | "max_future_booking"
  | "max_future_workshop"
  | "booking_option_included_in_max_future_booking"
  | "timezone_name"
  | "hide_least_specific_payment_pack"
  | "default_attendance"
  | "consumer_regularize_debt"
  | "allow_consumer_to_use_internal_account"
  | "accept_double_booking"
  | "accept_double_booking_workshop"
  | "gtmId"
  | "facebookPixelId"
  | "extra_info"
  | "basket_expiration_days"
  | "show_booked_gender_offer"
  | "is_checking_balance"
  | "nb_to_check_balance"
  | "gender_max_shift_for_booking"
  | "enable_multi_localization"
  | "hide_intercom"
  | "is_quickbook_integration_allowed"
  | "is_quickbook_integration_enabled"
  | "schedule_timerange_begin"
  | "schedule_timerange_end"
  | "coach_can_edit_attendance"
  | "autotag_rule_extended"
  | "performance_tracking"
  | "is_tax_excluded_in_marketplace"
  | "hide_unnecessary_compatible_purchase_method"
  | "hide_sessions_with_tags_when_not_eligible"
  | "hide_member_details_in_app_private_booking_for_coach"
  | "is_coach_access_enabled_by_default"
  | "has_coach_access_to_calendar"
  | "has_coach_access_to_compensation"
  | "has_coach_access_to_compensation_downloading"
  | "has_coach_access_to_replacement_request"
  | "requires_email_confirmation_when_signing_up"
  | "confirm_email_url_redirection"
  | "reset_password_url_redirection"
  | "no_show_validated_number_of_hours"
  | "no_show_email_sent_number_of_hours"
  | "is_roll_call_mandatory"
  | "show_establishment"
  | "show_level"
  | "show_activity_color"
  | "is_referral_program_activated"
  | "show_free_session_label"
  | "hide_book_button"
  | "hide_credits_for_customers"
  | "pass_credit_factor"
  | "force_billing_details_on_cards"
  | "show_past_sessions_calendar"
  | "start_calendar_week_on_today"
  | "checkin_tablet_visible_session_cutoff_minute"
  | "first_warning_payment_method_expiration_days"
  | "second_warning_payment_method_expiration_days"
  | "show_member_account_balance"
  | "show_barcode_button"
  | "show_membership_number"
  | "display_credit_price_for_offer"
  | "one_click_checkout_enabled";

export type UpdateCompanyThemeData = Partial<
  Pick<CompanyTheme, CompanyThemePatchKey>
> & {
  allow_guest_frequency?: "every_week" | "every_month" | "every_year";
  default_booking_ordering?:
    | "-date_created"
    | "member_first_name"
    | "member_last_name";
  session_time_display?: 1 | 2 | 3;
  coach_display?: 1 | 2 | 3 | 4;
  days_format_display?: 1 | 2 | 3;
  mobile_app_default_page?:
    | "Membership"
    | "Bookings"
    | "Home"
    | "Marketplace"
    | "Profile";
  provincial_tax_name?: string | null;
  provincial_tax_value?: number | string | null;
  widget_theme?: Partial<WidgetTheme>;
  stop_subscription_from_member_side_enabled?: boolean;
  is_marketing_double_opt_in_enabled?: boolean;
};

export type UpdateCompanyThemeParams = {
  companyId: number;
  data: UpdateCompanyThemeData;
};

export type WidgetTheme = {
  grey: string;
  border: number;
  spacing: number;
  greyDark: string;
  background: string;
  fontFamily: string;
  borderColor: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundPaper: string;
  secondaryBackgroundPaper: string;
};
