import {
  EXPORTABLE_COMPONENTS,
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
} from '../exportable-components/constants';

export const MARKETPLACE_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
];

export const MARKETPLACE_COMPONENTS = EXPORTABLE_COMPONENTS.filter((ec) =>
  MARKETPLACE_SUPPORTED_EXPORTABLE_COMPONENTS.includes(ec.identifier),
);

export const MARKETPLACE_COMPONENT_TYPE_LIST = MARKETPLACE_COMPONENTS.map(
  (mc) => mc.identifier,
);

export const getMarketplaceDefaultConfig = () =>
  MARKETPLACE_COMPONENTS.map((mc, index) => ({
    component_type: mc.identifier,
    title: '',
    config: { [mc.identifier]: mc.defaultConfig },
    index,
  }));

export const MARKETPLACE_PATH_TAB_CALENDAR = 'calendar';
export const MARKETPLACE_PATH_TAB_PASS = 'pass';
export const MARKETPLACE_PATH_TAB_VOD = 'vod';
export const MARKETPLACE_PATH_TAB_CONTRACT = 'subscription';
export const MARKETPLACE_PATH_TAB_WORKSHOP = 'workshop';
export const MARKETPLACE_PATH_TAB_PRIVATE_SERVICE = 'private-service';
export const MARKETPLACE_PATH_TAB_SHOP = 'shop';
export const MARKETPLACE_PATH_TAB_GIFTCARD = 'giftcard';

export const AVAILABLE_BOOKING_ELEMENTS_IDS = [
  'book-button',
  'book-button__icon',
  'book-button__inner',
  'book-button-card__inner',
  'book-button__inner__text',
  'book-button-offer-list-item',
];

export enum MARKETPLACE_BREAKPOINT {
  XS = 425,
  SM = 750,
  MD = 1100,
  LG = 1475,
}
