import {
  EXPORTABLE_COMPONENTS,
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
} from '../exportable-components/constants';

export const MARKETPLACE_SUPPORTED_EXPORTABLE_COMPONENTS = [
  EXPORTABLE_COMPONENT_TYPE_VOD,
  EXPORTABLE_COMPONENT_TYPE_CALENDAR,
  EXPORTABLE_COMPONENT_TYPE_WORKSHOP,
  EXPORTABLE_COMPONENT_TYPE_PASS,
  EXPORTABLE_COMPONENT_TYPE_PRIVATE_SERVICE,
  EXPORTABLE_COMPONENT_TYPE_PLAYLIST,
  EXPORTABLE_COMPONENT_TYPE_SHOP,
  EXPORTABLE_COMPONENT_TYPE_SUBSCRIPTION,
  EXPORTABLE_COMPONENT_TYPE_GIFTCARD,
];

export const MARKETPLACE_COMPONENTS = EXPORTABLE_COMPONENTS.filter((ec) =>
  MARKETPLACE_SUPPORTED_EXPORTABLE_COMPONENTS.includes(ec.identifier),
);

export const MARKETPLACE_COMPONENT_TYPE_LIST = MARKETPLACE_COMPONENTS.map(
  (mc) => mc.identifier,
);

export const getMarketplaceDefaultConfig = () =>
  MARKETPLACE_COMPONENTS.map((mc, index) => ({
    component_type: mc.identifier,
    title: '',
    config: { [mc.identifier]: mc.defaultConfig },
    index,
  }));
