import asyncComponent from '../../../AsyncComponent';
import '@material-ui/icons';

const muiIconNames = {
  AccessAlarm: asyncComponent(() => import('@material-ui/icons/AccessAlarm')),
  AccessAlarms: asyncComponent(() => import('@material-ui/icons/AccessAlarms')),
  Accessibility: asyncComponent(
    () => import('@material-ui/icons/Accessibility'),
  ),
  AccessibilityNew: asyncComponent(
    () => import('@material-ui/icons/AccessibilityNew'),
  ),
  Accessible: asyncComponent(() => import('@material-ui/icons/Accessible')),
  AccessibleForward: asyncComponent(
    () => import('@material-ui/icons/AccessibleForward'),
  ),
  AccessTime: asyncComponent(() => import('@material-ui/icons/AccessTime')),
  AccountBalance: asyncComponent(
    () => import('@material-ui/icons/AccountBalance'),
  ),
  AccountBalanceWallet: asyncComponent(
    () => import('@material-ui/icons/AccountBalanceWallet'),
  ),
  AccountBox: asyncComponent(() => import('@material-ui/icons/AccountBox')),
  AccountCircle: asyncComponent(
    () => import('@material-ui/icons/AccountCircle'),
  ),
  AccountTree: asyncComponent(() => import('@material-ui/icons/AccountTree')),
  AcUnit: asyncComponent(() => import('@material-ui/icons/AcUnit')),
  Adb: asyncComponent(() => import('@material-ui/icons/Adb')),
  Add: asyncComponent(() => import('@material-ui/icons/Add')),
  AddAlarm: asyncComponent(() => import('@material-ui/icons/AddAlarm')),
  AddAlert: asyncComponent(() => import('@material-ui/icons/AddAlert')),
  AddAPhoto: asyncComponent(() => import('@material-ui/icons/AddAPhoto')),
  AddBox: asyncComponent(() => import('@material-ui/icons/AddBox')),
  AddCircle: asyncComponent(() => import('@material-ui/icons/AddCircle')),
  AddCircleOutline: asyncComponent(
    () => import('@material-ui/icons/AddCircleOutline'),
  ),
  AddComment: asyncComponent(() => import('@material-ui/icons/AddComment')),
  AddIcCall: asyncComponent(() => import('@material-ui/icons/AddIcCall')),
  AddLocation: asyncComponent(() => import('@material-ui/icons/AddLocation')),
  AddPhotoAlternate: asyncComponent(
    () => import('@material-ui/icons/AddPhotoAlternate'),
  ),
  AddShoppingCart: asyncComponent(
    () => import('@material-ui/icons/AddShoppingCart'),
  ),
  AddToHomeScreen: asyncComponent(
    () => import('@material-ui/icons/AddToHomeScreen'),
  ),
  AddToPhotos: asyncComponent(() => import('@material-ui/icons/AddToPhotos')),
  AddToQueue: asyncComponent(() => import('@material-ui/icons/AddToQueue')),
  Adjust: asyncComponent(() => import('@material-ui/icons/Adjust')),
  AirlineSeatFlat: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatFlat'),
  ),
  AirlineSeatFlatAngled: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatFlatAngled'),
  ),
  AirlineSeatIndividualSuite: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatIndividualSuite'),
  ),
  AirlineSeatLegroomExtra: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatLegroomExtra'),
  ),
  AirlineSeatLegroomNormal: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatLegroomNormal'),
  ),
  AirlineSeatLegroomReduced: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatLegroomReduced'),
  ),
  AirlineSeatReclineExtra: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatReclineExtra'),
  ),
  AirlineSeatReclineNormal: asyncComponent(
    () => import('@material-ui/icons/AirlineSeatReclineNormal'),
  ),
  AirplanemodeActive: asyncComponent(
    () => import('@material-ui/icons/AirplanemodeActive'),
  ),
  AirplanemodeInactive: asyncComponent(
    () => import('@material-ui/icons/AirplanemodeInactive'),
  ),
  Airplay: asyncComponent(() => import('@material-ui/icons/Airplay')),
  AirportShuttle: asyncComponent(
    () => import('@material-ui/icons/AirportShuttle'),
  ),
  Alarm: asyncComponent(() => import('@material-ui/icons/Alarm')),
  AlarmAdd: asyncComponent(() => import('@material-ui/icons/AlarmAdd')),
  AlarmOff: asyncComponent(() => import('@material-ui/icons/AlarmOff')),
  AlarmOn: asyncComponent(() => import('@material-ui/icons/AlarmOn')),
  Album: asyncComponent(() => import('@material-ui/icons/Album')),
  AllInbox: asyncComponent(() => import('@material-ui/icons/AllInbox')),
  AllInclusive: asyncComponent(() => import('@material-ui/icons/AllInclusive')),
  AllOut: asyncComponent(() => import('@material-ui/icons/AllOut')),
  AlternateEmail: asyncComponent(
    () => import('@material-ui/icons/AlternateEmail'),
  ),
  AmpStories: asyncComponent(() => import('@material-ui/icons/AmpStories')),
  Android: asyncComponent(() => import('@material-ui/icons/Android')),
  Announcement: asyncComponent(() => import('@material-ui/icons/Announcement')),
  Apartment: asyncComponent(() => import('@material-ui/icons/Apartment')),
  Apple: asyncComponent(() => import('@material-ui/icons/Apple')),
  Apps: asyncComponent(() => import('@material-ui/icons/Apps')),
  Archive: asyncComponent(() => import('@material-ui/icons/Archive')),
  ArrowBack: asyncComponent(() => import('@material-ui/icons/ArrowBack')),
  ArrowBackIos: asyncComponent(() => import('@material-ui/icons/ArrowBackIos')),
  ArrowDownward: asyncComponent(
    () => import('@material-ui/icons/ArrowDownward'),
  ),
  ArrowDropDown: asyncComponent(
    () => import('@material-ui/icons/ArrowDropDown'),
  ),
  ArrowDropDownCircle: asyncComponent(
    () => import('@material-ui/icons/ArrowDropDownCircle'),
  ),
  ArrowDropUp: asyncComponent(() => import('@material-ui/icons/ArrowDropUp')),
  ArrowForward: asyncComponent(() => import('@material-ui/icons/ArrowForward')),
  ArrowForwardIos: asyncComponent(
    () => import('@material-ui/icons/ArrowForwardIos'),
  ),
  ArrowLeft: asyncComponent(() => import('@material-ui/icons/ArrowLeft')),
  ArrowRight: asyncComponent(() => import('@material-ui/icons/ArrowRight')),
  ArrowRightAlt: asyncComponent(
    () => import('@material-ui/icons/ArrowRightAlt'),
  ),
  ArrowUpward: asyncComponent(() => import('@material-ui/icons/ArrowUpward')),
  ArtTrack: asyncComponent(() => import('@material-ui/icons/ArtTrack')),
  AspectRatio: asyncComponent(() => import('@material-ui/icons/AspectRatio')),
  Assessment: asyncComponent(() => import('@material-ui/icons/Assessment')),
  Assignment: asyncComponent(() => import('@material-ui/icons/Assignment')),
  AssignmentInd: asyncComponent(
    () => import('@material-ui/icons/AssignmentInd'),
  ),
  AssignmentLate: asyncComponent(
    () => import('@material-ui/icons/AssignmentLate'),
  ),
  AssignmentReturn: asyncComponent(
    () => import('@material-ui/icons/AssignmentReturn'),
  ),
  AssignmentReturned: asyncComponent(
    () => import('@material-ui/icons/AssignmentReturned'),
  ),
  AssignmentTurnedIn: asyncComponent(
    () => import('@material-ui/icons/AssignmentTurnedIn'),
  ),
  Assistant: asyncComponent(() => import('@material-ui/icons/Assistant')),
  AssistantPhoto: asyncComponent(
    () => import('@material-ui/icons/AssistantPhoto'),
  ),
  Atm: asyncComponent(() => import('@material-ui/icons/Atm')),
  AttachFile: asyncComponent(() => import('@material-ui/icons/AttachFile')),
  Attachment: asyncComponent(() => import('@material-ui/icons/Attachment')),
  AttachMoney: asyncComponent(() => import('@material-ui/icons/AttachMoney')),
  Audiotrack: asyncComponent(() => import('@material-ui/icons/Audiotrack')),
  Autorenew: asyncComponent(() => import('@material-ui/icons/Autorenew')),
  AvTimer: asyncComponent(() => import('@material-ui/icons/AvTimer')),
  Backspace: asyncComponent(() => import('@material-ui/icons/Backspace')),
  Backup: asyncComponent(() => import('@material-ui/icons/Backup')),
  Ballot: asyncComponent(() => import('@material-ui/icons/Ballot')),
  BarChart: asyncComponent(() => import('@material-ui/icons/BarChart')),
  Bathtub: asyncComponent(() => import('@material-ui/icons/Bathtub')),
  Battery20: asyncComponent(() => import('@material-ui/icons/Battery20')),
  Battery30: asyncComponent(() => import('@material-ui/icons/Battery30')),
  Battery50: asyncComponent(() => import('@material-ui/icons/Battery50')),
  Battery60: asyncComponent(() => import('@material-ui/icons/Battery60')),
  Battery80: asyncComponent(() => import('@material-ui/icons/Battery80')),
  Battery90: asyncComponent(() => import('@material-ui/icons/Battery90')),
  BatteryAlert: asyncComponent(() => import('@material-ui/icons/BatteryAlert')),
  BatteryCharging20: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging20'),
  ),
  BatteryCharging30: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging30'),
  ),
  BatteryCharging50: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging50'),
  ),
  BatteryCharging60: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging60'),
  ),
  BatteryCharging80: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging80'),
  ),
  BatteryCharging90: asyncComponent(
    () => import('@material-ui/icons/BatteryCharging90'),
  ),
  BatteryChargingFull: asyncComponent(
    () => import('@material-ui/icons/BatteryChargingFull'),
  ),
  BatteryFull: asyncComponent(() => import('@material-ui/icons/BatteryFull')),
  BatteryStd: asyncComponent(() => import('@material-ui/icons/BatteryStd')),
  BatteryUnknown: asyncComponent(
    () => import('@material-ui/icons/BatteryUnknown'),
  ),
  BeachAccess: asyncComponent(() => import('@material-ui/icons/BeachAccess')),
  Beenhere: asyncComponent(() => import('@material-ui/icons/Beenhere')),
  Block: asyncComponent(() => import('@material-ui/icons/Block')),
  Bluetooth: asyncComponent(() => import('@material-ui/icons/Bluetooth')),
  BluetoothAudio: asyncComponent(
    () => import('@material-ui/icons/BluetoothAudio'),
  ),
  BluetoothConnected: asyncComponent(
    () => import('@material-ui/icons/BluetoothConnected'),
  ),
  BluetoothDisabled: asyncComponent(
    () => import('@material-ui/icons/BluetoothDisabled'),
  ),
  BluetoothSearching: asyncComponent(
    () => import('@material-ui/icons/BluetoothSearching'),
  ),
  BlurCircular: asyncComponent(() => import('@material-ui/icons/BlurCircular')),
  BlurLinear: asyncComponent(() => import('@material-ui/icons/BlurLinear')),
  BlurOff: asyncComponent(() => import('@material-ui/icons/BlurOff')),
  BlurOn: asyncComponent(() => import('@material-ui/icons/BlurOn')),
  Book: asyncComponent(() => import('@material-ui/icons/Book')),
  Bookmark: asyncComponent(() => import('@material-ui/icons/Bookmark')),
  BookmarkBorder: asyncComponent(
    () => import('@material-ui/icons/BookmarkBorder'),
  ),
  Bookmarks: asyncComponent(() => import('@material-ui/icons/Bookmarks')),
  BorderAll: asyncComponent(() => import('@material-ui/icons/BorderAll')),
  BorderBottom: asyncComponent(() => import('@material-ui/icons/BorderBottom')),
  BorderClear: asyncComponent(() => import('@material-ui/icons/BorderClear')),
  BorderColor: asyncComponent(() => import('@material-ui/icons/BorderColor')),
  BorderHorizontal: asyncComponent(
    () => import('@material-ui/icons/BorderHorizontal'),
  ),
  BorderInner: asyncComponent(() => import('@material-ui/icons/BorderInner')),
  BorderLeft: asyncComponent(() => import('@material-ui/icons/BorderLeft')),
  BorderOuter: asyncComponent(() => import('@material-ui/icons/BorderOuter')),
  BorderRight: asyncComponent(() => import('@material-ui/icons/BorderRight')),
  BorderStyle: asyncComponent(() => import('@material-ui/icons/BorderStyle')),
  BorderTop: asyncComponent(() => import('@material-ui/icons/BorderTop')),
  BorderVertical: asyncComponent(
    () => import('@material-ui/icons/BorderVertical'),
  ),
  BrandingWatermark: asyncComponent(
    () => import('@material-ui/icons/BrandingWatermark'),
  ),
  Brightness1: asyncComponent(() => import('@material-ui/icons/Brightness1')),
  Brightness2: asyncComponent(() => import('@material-ui/icons/Brightness2')),
  Brightness3: asyncComponent(() => import('@material-ui/icons/Brightness3')),
  Brightness4: asyncComponent(() => import('@material-ui/icons/Brightness4')),
  Brightness5: asyncComponent(() => import('@material-ui/icons/Brightness5')),
  Brightness6: asyncComponent(() => import('@material-ui/icons/Brightness6')),
  Brightness7: asyncComponent(() => import('@material-ui/icons/Brightness7')),
  BrightnessAuto: asyncComponent(
    () => import('@material-ui/icons/BrightnessAuto'),
  ),
  BrightnessHigh: asyncComponent(
    () => import('@material-ui/icons/BrightnessHigh'),
  ),
  BrightnessLow: asyncComponent(
    () => import('@material-ui/icons/BrightnessLow'),
  ),
  BrightnessMedium: asyncComponent(
    () => import('@material-ui/icons/BrightnessMedium'),
  ),
  BrokenImage: asyncComponent(() => import('@material-ui/icons/BrokenImage')),
  Brush: asyncComponent(() => import('@material-ui/icons/Brush')),
  BubbleChart: asyncComponent(() => import('@material-ui/icons/BubbleChart')),
  BugReport: asyncComponent(() => import('@material-ui/icons/BugReport')),
  Build: asyncComponent(() => import('@material-ui/icons/Build')),
  BurstMode: asyncComponent(() => import('@material-ui/icons/BurstMode')),
  Business: asyncComponent(() => import('@material-ui/icons/Business')),
  BusinessCenter: asyncComponent(
    () => import('@material-ui/icons/BusinessCenter'),
  ),
  Cached: asyncComponent(() => import('@material-ui/icons/Cached')),
  Cake: asyncComponent(() => import('@material-ui/icons/Cake')),
  CalendarToday: asyncComponent(
    () => import('@material-ui/icons/CalendarToday'),
  ),
  CalendarViewDay: asyncComponent(
    () => import('@material-ui/icons/CalendarViewDay'),
  ),
  Call: asyncComponent(() => import('@material-ui/icons/Call')),
  CallEnd: asyncComponent(() => import('@material-ui/icons/CallEnd')),
  CallMade: asyncComponent(() => import('@material-ui/icons/CallMade')),
  CallMerge: asyncComponent(() => import('@material-ui/icons/CallMerge')),
  CallMissed: asyncComponent(() => import('@material-ui/icons/CallMissed')),
  CallMissedOutgoing: asyncComponent(
    () => import('@material-ui/icons/CallMissedOutgoing'),
  ),
  CallReceived: asyncComponent(() => import('@material-ui/icons/CallReceived')),
  CallSplit: asyncComponent(() => import('@material-ui/icons/CallSplit')),
  CallToAction: asyncComponent(() => import('@material-ui/icons/CallToAction')),
  Camera: asyncComponent(() => import('@material-ui/icons/Camera')),
  CameraAlt: asyncComponent(() => import('@material-ui/icons/CameraAlt')),
  CameraEnhance: asyncComponent(
    () => import('@material-ui/icons/CameraEnhance'),
  ),
  CameraFront: asyncComponent(() => import('@material-ui/icons/CameraFront')),
  CameraRear: asyncComponent(() => import('@material-ui/icons/CameraRear')),
  CameraRoll: asyncComponent(() => import('@material-ui/icons/CameraRoll')),
  Cancel: asyncComponent(() => import('@material-ui/icons/Cancel')),
  CancelPresentation: asyncComponent(
    () => import('@material-ui/icons/CancelPresentation'),
  ),
  CancelScheduleSend: asyncComponent(
    () => import('@material-ui/icons/CancelScheduleSend'),
  ),
  CardGiftcard: asyncComponent(() => import('@material-ui/icons/CardGiftcard')),
  CardMembership: asyncComponent(
    () => import('@material-ui/icons/CardMembership'),
  ),
  CardTravel: asyncComponent(() => import('@material-ui/icons/CardTravel')),
  Casino: asyncComponent(() => import('@material-ui/icons/Casino')),
  Cast: asyncComponent(() => import('@material-ui/icons/Cast')),
  CastConnected: asyncComponent(
    () => import('@material-ui/icons/CastConnected'),
  ),
  CastForEducation: asyncComponent(
    () => import('@material-ui/icons/CastForEducation'),
  ),
  Category: asyncComponent(() => import('@material-ui/icons/Category')),
  CellWifi: asyncComponent(() => import('@material-ui/icons/CellWifi')),
  CenterFocusStrong: asyncComponent(
    () => import('@material-ui/icons/CenterFocusStrong'),
  ),
  CenterFocusWeak: asyncComponent(
    () => import('@material-ui/icons/CenterFocusWeak'),
  ),
  ChangeHistory: asyncComponent(
    () => import('@material-ui/icons/ChangeHistory'),
  ),
  Chat: asyncComponent(() => import('@material-ui/icons/Chat')),
  ChatBubble: asyncComponent(() => import('@material-ui/icons/ChatBubble')),
  ChatBubbleOutline: asyncComponent(
    () => import('@material-ui/icons/ChatBubbleOutline'),
  ),
  Check: asyncComponent(() => import('@material-ui/icons/Check')),
  CheckBox: asyncComponent(() => import('@material-ui/icons/CheckBox')),
  CheckBoxOutlineBlank: asyncComponent(
    () => import('@material-ui/icons/CheckBoxOutlineBlank'),
  ),
  CheckCircle: asyncComponent(() => import('@material-ui/icons/CheckCircle')),
  CheckCircleOutline: asyncComponent(
    () => import('@material-ui/icons/CheckCircleOutline'),
  ),
  ChevronLeft: asyncComponent(() => import('@material-ui/icons/ChevronLeft')),
  ChevronRight: asyncComponent(() => import('@material-ui/icons/ChevronRight')),
  ChildCare: asyncComponent(() => import('@material-ui/icons/ChildCare')),
  ChildFriendly: asyncComponent(
    () => import('@material-ui/icons/ChildFriendly'),
  ),
  ChromeReaderMode: asyncComponent(
    () => import('@material-ui/icons/ChromeReaderMode'),
  ),
  Class: asyncComponent(() => import('@material-ui/icons/Class')),
  Clear: asyncComponent(() => import('@material-ui/icons/Clear')),
  ClearAll: asyncComponent(() => import('@material-ui/icons/ClearAll')),
  Close: asyncComponent(() => import('@material-ui/icons/Close')),
  ClosedCaption: asyncComponent(
    () => import('@material-ui/icons/ClosedCaption'),
  ),
  Cloud: asyncComponent(() => import('@material-ui/icons/Cloud')),
  CloudCircle: asyncComponent(() => import('@material-ui/icons/CloudCircle')),
  CloudDone: asyncComponent(() => import('@material-ui/icons/CloudDone')),
  CloudDownload: asyncComponent(
    () => import('@material-ui/icons/CloudDownload'),
  ),
  CloudOff: asyncComponent(() => import('@material-ui/icons/CloudOff')),
  CloudQueue: asyncComponent(() => import('@material-ui/icons/CloudQueue')),
  CloudUpload: asyncComponent(() => import('@material-ui/icons/CloudUpload')),
  Code: asyncComponent(() => import('@material-ui/icons/Code')),
  Collections: asyncComponent(() => import('@material-ui/icons/Collections')),
  CollectionsBookmark: asyncComponent(
    () => import('@material-ui/icons/CollectionsBookmark'),
  ),
  Colorize: asyncComponent(() => import('@material-ui/icons/Colorize')),
  ColorLens: asyncComponent(() => import('@material-ui/icons/ColorLens')),
  Comment: asyncComponent(() => import('@material-ui/icons/Comment')),
  Commute: asyncComponent(() => import('@material-ui/icons/Commute')),
  Compare: asyncComponent(() => import('@material-ui/icons/Compare')),
  CompareArrows: asyncComponent(
    () => import('@material-ui/icons/CompareArrows'),
  ),
  CompassCalibration: asyncComponent(
    () => import('@material-ui/icons/CompassCalibration'),
  ),
  Computer: asyncComponent(() => import('@material-ui/icons/Computer')),
  ConfirmationNumber: asyncComponent(
    () => import('@material-ui/icons/ConfirmationNumber'),
  ),
  Contactless: asyncComponent(() => import('@material-ui/icons/Contactless')),
  ContactMail: asyncComponent(() => import('@material-ui/icons/ContactMail')),
  ContactPhone: asyncComponent(() => import('@material-ui/icons/ContactPhone')),
  Contacts: asyncComponent(() => import('@material-ui/icons/Contacts')),
  ContactSupport: asyncComponent(
    () => import('@material-ui/icons/ContactSupport'),
  ),
  ControlCamera: asyncComponent(
    () => import('@material-ui/icons/ControlCamera'),
  ),
  ControlPoint: asyncComponent(() => import('@material-ui/icons/ControlPoint')),
  ControlPointDuplicate: asyncComponent(
    () => import('@material-ui/icons/ControlPointDuplicate'),
  ),
  Copyright: asyncComponent(() => import('@material-ui/icons/Copyright')),
  Create: asyncComponent(() => import('@material-ui/icons/Create')),
  CreateNewFolder: asyncComponent(
    () => import('@material-ui/icons/CreateNewFolder'),
  ),
  CreditCard: asyncComponent(() => import('@material-ui/icons/CreditCard')),
  Crop: asyncComponent(() => import('@material-ui/icons/Crop')),
  Crop169: asyncComponent(() => import('@material-ui/icons/Crop169')),
  Crop32: asyncComponent(() => import('@material-ui/icons/Crop32')),
  Crop54: asyncComponent(() => import('@material-ui/icons/Crop54')),
  Crop75: asyncComponent(() => import('@material-ui/icons/Crop75')),
  CropDin: asyncComponent(() => import('@material-ui/icons/CropDin')),
  CropFree: asyncComponent(() => import('@material-ui/icons/CropFree')),
  CropLandscape: asyncComponent(
    () => import('@material-ui/icons/CropLandscape'),
  ),
  CropOriginal: asyncComponent(() => import('@material-ui/icons/CropOriginal')),
  CropPortrait: asyncComponent(() => import('@material-ui/icons/CropPortrait')),
  CropRotate: asyncComponent(() => import('@material-ui/icons/CropRotate')),
  CropSquare: asyncComponent(() => import('@material-ui/icons/CropSquare')),
  Dashboard: asyncComponent(() => import('@material-ui/icons/Dashboard')),
  DataUsage: asyncComponent(() => import('@material-ui/icons/DataUsage')),
  DateRange: asyncComponent(() => import('@material-ui/icons/DateRange')),
  Deck: asyncComponent(() => import('@material-ui/icons/Deck')),
  Dehaze: asyncComponent(() => import('@material-ui/icons/Dehaze')),
  Delete: asyncComponent(() => import('@material-ui/icons/Delete')),
  DeleteForever: asyncComponent(
    () => import('@material-ui/icons/DeleteForever'),
  ),
  DeleteOutline: asyncComponent(
    () => import('@material-ui/icons/DeleteOutline'),
  ),
  DeleteSweep: asyncComponent(() => import('@material-ui/icons/DeleteSweep')),
  DepartureBoard: asyncComponent(
    () => import('@material-ui/icons/DepartureBoard'),
  ),
  Description: asyncComponent(() => import('@material-ui/icons/Description')),
  DesktopAccessDisabled: asyncComponent(
    () => import('@material-ui/icons/DesktopAccessDisabled'),
  ),

  DesktopMac: asyncComponent(() => import('@material-ui/icons/DesktopMac')),
  DesktopWindows: asyncComponent(
    () => import('@material-ui/icons/DesktopWindows'),
  ),
  Details: asyncComponent(() => import('@material-ui/icons/Details')),
  DeveloperBoard: asyncComponent(
    () => import('@material-ui/icons/DeveloperBoard'),
  ),
  DeveloperMode: asyncComponent(
    () => import('@material-ui/icons/DeveloperMode'),
  ),
  DeviceHub: asyncComponent(() => import('@material-ui/icons/DeviceHub')),
  Devices: asyncComponent(() => import('@material-ui/icons/Devices')),
  DevicesOther: asyncComponent(() => import('@material-ui/icons/DevicesOther')),
  DeviceUnknown: asyncComponent(
    () => import('@material-ui/icons/DeviceUnknown'),
  ),
  DialerSip: asyncComponent(() => import('@material-ui/icons/DialerSip')),
  Dialpad: asyncComponent(() => import('@material-ui/icons/Dialpad')),
  Directions: asyncComponent(() => import('@material-ui/icons/Directions')),
  DirectionsBike: asyncComponent(
    () => import('@material-ui/icons/DirectionsBike'),
  ),
  DirectionsBoat: asyncComponent(
    () => import('@material-ui/icons/DirectionsBoat'),
  ),
  DirectionsBus: asyncComponent(
    () => import('@material-ui/icons/DirectionsBus'),
  ),
  DirectionsCar: asyncComponent(
    () => import('@material-ui/icons/DirectionsCar'),
  ),
  DirectionsRailway: asyncComponent(
    () => import('@material-ui/icons/DirectionsRailway'),
  ),

  DirectionsRun: asyncComponent(
    () => import('@material-ui/icons/DirectionsRun'),
  ),
  DirectionsSubway: asyncComponent(
    () => import('@material-ui/icons/DirectionsSubway'),
  ),
  DirectionsTransit: asyncComponent(
    () => import('@material-ui/icons/DirectionsTransit'),
  ),

  DirectionsWalk: asyncComponent(
    () => import('@material-ui/icons/DirectionsWalk'),
  ),
  DiscFull: asyncComponent(() => import('@material-ui/icons/DiscFull')),
  Dns: asyncComponent(() => import('@material-ui/icons/Dns')),
  Dock: asyncComponent(() => import('@material-ui/icons/Dock')),
  Domain: asyncComponent(() => import('@material-ui/icons/Domain')),
  DomainDisabled: asyncComponent(
    () => import('@material-ui/icons/DomainDisabled'),
  ),
  Done: asyncComponent(() => import('@material-ui/icons/Done')),
  DoneAll: asyncComponent(() => import('@material-ui/icons/DoneAll')),
  DoneOutline: asyncComponent(() => import('@material-ui/icons/DoneOutline')),
  DonutLarge: asyncComponent(() => import('@material-ui/icons/DonutLarge')),
  DonutSmall: asyncComponent(() => import('@material-ui/icons/DonutSmall')),
  DoubleArrow: asyncComponent(() => import('@material-ui/icons/DoubleArrow')),
  Drafts: asyncComponent(() => import('@material-ui/icons/Drafts')),
  DragHandle: asyncComponent(() => import('@material-ui/icons/DragHandle')),
  DragIndicator: asyncComponent(
    () => import('@material-ui/icons/DragIndicator'),
  ),
  DriveEta: asyncComponent(() => import('@material-ui/icons/DriveEta')),
  Duo: asyncComponent(() => import('@material-ui/icons/Duo')),
  Dvr: asyncComponent(() => import('@material-ui/icons/Dvr')),
  DynamicFeed: asyncComponent(() => import('@material-ui/icons/DynamicFeed')),
  Eco: asyncComponent(() => import('@material-ui/icons/Eco')),
  Edit: asyncComponent(() => import('@material-ui/icons/Edit')),
  EditAttributes: asyncComponent(
    () => import('@material-ui/icons/EditAttributes'),
  ),
  EditLocation: asyncComponent(() => import('@material-ui/icons/EditLocation')),
  Eject: asyncComponent(() => import('@material-ui/icons/Eject')),
  Email: asyncComponent(() => import('@material-ui/icons/Email')),
  EmojiEmotions: asyncComponent(
    () => import('@material-ui/icons/EmojiEmotions'),
  ),
  EmojiEvents: asyncComponent(() => import('@material-ui/icons/EmojiEvents')),
  EmojiFlags: asyncComponent(() => import('@material-ui/icons/EmojiFlags')),
  EmojiFoodBeverage: asyncComponent(
    () => import('@material-ui/icons/EmojiFoodBeverage'),
  ),
  EmojiNature: asyncComponent(() => import('@material-ui/icons/EmojiNature')),
  EmojiObjects: asyncComponent(() => import('@material-ui/icons/EmojiObjects')),
  EmojiPeople: asyncComponent(() => import('@material-ui/icons/EmojiPeople')),
  EmojiSymbols: asyncComponent(() => import('@material-ui/icons/EmojiSymbols')),
  EmojiTransportation: asyncComponent(
    () => import('@material-ui/icons/EmojiTransportation'),
  ),
  EnhancedEncryption: asyncComponent(
    () => import('@material-ui/icons/EnhancedEncryption'),
  ),
  Equalizer: asyncComponent(() => import('@material-ui/icons/Equalizer')),
  Error: asyncComponent(() => import('@material-ui/icons/Error')),
  ErrorOutline: asyncComponent(() => import('@material-ui/icons/ErrorOutline')),
  Euro: asyncComponent(() => import('@material-ui/icons/Euro')),
  EuroSymbol: asyncComponent(() => import('@material-ui/icons/EuroSymbol')),
  Event: asyncComponent(() => import('@material-ui/icons/Event')),
  EventAvailable: asyncComponent(
    () => import('@material-ui/icons/EventAvailable'),
  ),
  EventBusy: asyncComponent(() => import('@material-ui/icons/EventBusy')),
  EventNote: asyncComponent(() => import('@material-ui/icons/EventNote')),
  EventSeat: asyncComponent(() => import('@material-ui/icons/EventSeat')),
  EvStation: asyncComponent(() => import('@material-ui/icons/EvStation')),
  ExitToApp: asyncComponent(() => import('@material-ui/icons/ExitToApp')),
  ExpandLess: asyncComponent(() => import('@material-ui/icons/ExpandLess')),
  ExpandMore: asyncComponent(() => import('@material-ui/icons/ExpandMore')),
  Explicit: asyncComponent(() => import('@material-ui/icons/Explicit')),
  Explore: asyncComponent(() => import('@material-ui/icons/Explore')),
  ExploreOff: asyncComponent(() => import('@material-ui/icons/ExploreOff')),
  Exposure: asyncComponent(() => import('@material-ui/icons/Exposure')),
  ExposureNeg1: asyncComponent(() => import('@material-ui/icons/ExposureNeg1')),
  ExposureNeg2: asyncComponent(() => import('@material-ui/icons/ExposureNeg2')),
  ExposurePlus1: asyncComponent(
    () => import('@material-ui/icons/ExposurePlus1'),
  ),
  ExposurePlus2: asyncComponent(
    () => import('@material-ui/icons/ExposurePlus2'),
  ),
  ExposureZero: asyncComponent(() => import('@material-ui/icons/ExposureZero')),
  Extension: asyncComponent(() => import('@material-ui/icons/Extension')),
  Face: asyncComponent(() => import('@material-ui/icons/Face')),
  Facebook: asyncComponent(() => import('@material-ui/icons/Facebook')),
  Fastfood: asyncComponent(() => import('@material-ui/icons/Fastfood')),
  FastForward: asyncComponent(() => import('@material-ui/icons/FastForward')),
  FastRewind: asyncComponent(() => import('@material-ui/icons/FastRewind')),
  Favorite: asyncComponent(() => import('@material-ui/icons/Favorite')),
  FavoriteBorder: asyncComponent(
    () => import('@material-ui/icons/FavoriteBorder'),
  ),
  FeaturedPlayList: asyncComponent(
    () => import('@material-ui/icons/FeaturedPlayList'),
  ),
  FeaturedVideo: asyncComponent(
    () => import('@material-ui/icons/FeaturedVideo'),
  ),
  Feedback: asyncComponent(() => import('@material-ui/icons/Feedback')),
  FiberDvr: asyncComponent(() => import('@material-ui/icons/FiberDvr')),
  FiberManualRecord: asyncComponent(
    () => import('@material-ui/icons/FiberManualRecord'),
  ),
  FiberNew: asyncComponent(() => import('@material-ui/icons/FiberNew')),
  FiberPin: asyncComponent(() => import('@material-ui/icons/FiberPin')),
  FiberSmartRecord: asyncComponent(
    () => import('@material-ui/icons/FiberSmartRecord'),
  ),
  FileCopy: asyncComponent(() => import('@material-ui/icons/FileCopy')),
  Filter: asyncComponent(() => import('@material-ui/icons/Filter')),
  Filter1: asyncComponent(() => import('@material-ui/icons/Filter1')),
  Filter2: asyncComponent(() => import('@material-ui/icons/Filter2')),
  Filter3: asyncComponent(() => import('@material-ui/icons/Filter3')),
  Filter4: asyncComponent(() => import('@material-ui/icons/Filter4')),
  Filter5: asyncComponent(() => import('@material-ui/icons/Filter5')),
  Filter6: asyncComponent(() => import('@material-ui/icons/Filter6')),
  Filter7: asyncComponent(() => import('@material-ui/icons/Filter7')),
  Filter8: asyncComponent(() => import('@material-ui/icons/Filter8')),
  Filter9: asyncComponent(() => import('@material-ui/icons/Filter9')),
  Filter9Plus: asyncComponent(() => import('@material-ui/icons/Filter9Plus')),
  FilterBAndW: asyncComponent(() => import('@material-ui/icons/FilterBAndW')),
  FilterCenterFocus: asyncComponent(
    () => import('@material-ui/icons/FilterCenterFocus'),
  ),
  FilterDrama: asyncComponent(() => import('@material-ui/icons/FilterDrama')),
  FilterFrames: asyncComponent(() => import('@material-ui/icons/FilterFrames')),
  FilterHdr: asyncComponent(() => import('@material-ui/icons/FilterHdr')),
  FilterList: asyncComponent(() => import('@material-ui/icons/FilterList')),
  FilterNone: asyncComponent(() => import('@material-ui/icons/FilterNone')),
  FilterTiltShift: asyncComponent(
    () => import('@material-ui/icons/FilterTiltShift'),
  ),
  FilterVintage: asyncComponent(
    () => import('@material-ui/icons/FilterVintage'),
  ),
  FindInPage: asyncComponent(() => import('@material-ui/icons/FindInPage')),
  FindReplace: asyncComponent(() => import('@material-ui/icons/FindReplace')),
  Fingerprint: asyncComponent(() => import('@material-ui/icons/Fingerprint')),
  Fireplace: asyncComponent(() => import('@material-ui/icons/Fireplace')),
  FirstPage: asyncComponent(() => import('@material-ui/icons/FirstPage')),
  FitnessCenter: asyncComponent(
    () => import('@material-ui/icons/FitnessCenter'),
  ),
  Flag: asyncComponent(() => import('@material-ui/icons/Flag')),
  Flare: asyncComponent(() => import('@material-ui/icons/Flare')),
  FlashAuto: asyncComponent(() => import('@material-ui/icons/FlashAuto')),
  FlashOff: asyncComponent(() => import('@material-ui/icons/FlashOff')),
  FlashOn: asyncComponent(() => import('@material-ui/icons/FlashOn')),
  Flight: asyncComponent(() => import('@material-ui/icons/Flight')),
  FlightLand: asyncComponent(() => import('@material-ui/icons/FlightLand')),
  FlightTakeoff: asyncComponent(
    () => import('@material-ui/icons/FlightTakeoff'),
  ),
  Flip: asyncComponent(() => import('@material-ui/icons/Flip')),
  FlipCameraAndroid: asyncComponent(
    () => import('@material-ui/icons/FlipCameraAndroid'),
  ),
  FlipCameraIos: asyncComponent(
    () => import('@material-ui/icons/FlipCameraIos'),
  ),
  FlipToBack: asyncComponent(() => import('@material-ui/icons/FlipToBack')),
  FlipToFront: asyncComponent(() => import('@material-ui/icons/FlipToFront')),
  Folder: asyncComponent(() => import('@material-ui/icons/Folder')),
  FolderOpen: asyncComponent(() => import('@material-ui/icons/FolderOpen')),
  FolderShared: asyncComponent(() => import('@material-ui/icons/FolderShared')),
  FolderSpecial: asyncComponent(
    () => import('@material-ui/icons/FolderSpecial'),
  ),
  FontDownload: asyncComponent(() => import('@material-ui/icons/FontDownload')),
  FormatAlignCenter: asyncComponent(
    () => import('@material-ui/icons/FormatAlignCenter'),
  ),
  FormatAlignJustify: asyncComponent(
    () => import('@material-ui/icons/FormatAlignJustify'),
  ),
  FormatAlignLeft: asyncComponent(
    () => import('@material-ui/icons/FormatAlignLeft'),
  ),
  FormatAlignRight: asyncComponent(
    () => import('@material-ui/icons/FormatAlignRight'),
  ),
  FormatBold: asyncComponent(() => import('@material-ui/icons/FormatBold')),
  FormatClear: asyncComponent(() => import('@material-ui/icons/FormatClear')),
  FormatColorFill: asyncComponent(
    () => import('@material-ui/icons/FormatColorFill'),
  ),
  FormatColorReset: asyncComponent(
    () => import('@material-ui/icons/FormatColorReset'),
  ),
  FormatColorText: asyncComponent(
    () => import('@material-ui/icons/FormatColorText'),
  ),
  FormatIndentDecrease: asyncComponent(
    () => import('@material-ui/icons/FormatIndentDecrease'),
  ),
  FormatIndentIncrease: asyncComponent(
    () => import('@material-ui/icons/FormatIndentIncrease'),
  ),
  FormatItalic: asyncComponent(() => import('@material-ui/icons/FormatItalic')),
  FormatLineSpacing: asyncComponent(
    () => import('@material-ui/icons/FormatLineSpacing'),
  ),
  FormatListBulleted: asyncComponent(
    () => import('@material-ui/icons/FormatListBulleted'),
  ),
  FormatListNumbered: asyncComponent(
    () => import('@material-ui/icons/FormatListNumbered'),
  ),
  FormatListNumberedRtl: asyncComponent(
    () => import('@material-ui/icons/FormatListNumberedRtl'),
  ),
  FormatPaint: asyncComponent(() => import('@material-ui/icons/FormatPaint')),
  FormatQuote: asyncComponent(() => import('@material-ui/icons/FormatQuote')),
  FormatShapes: asyncComponent(() => import('@material-ui/icons/FormatShapes')),
  FormatSize: asyncComponent(() => import('@material-ui/icons/FormatSize')),
  FormatStrikethrough: asyncComponent(
    () => import('@material-ui/icons/FormatStrikethrough'),
  ),
  FormatTextdirectionLToR: asyncComponent(
    () => import('@material-ui/icons/FormatTextdirectionLToR'),
  ),
  FormatTextdirectionRToL: asyncComponent(
    () => import('@material-ui/icons/FormatTextdirectionRToL'),
  ),
  FormatUnderlined: asyncComponent(
    () => import('@material-ui/icons/FormatUnderlined'),
  ),
  Forum: asyncComponent(() => import('@material-ui/icons/Forum')),
  Forward: asyncComponent(() => import('@material-ui/icons/Forward')),
  Forward10: asyncComponent(() => import('@material-ui/icons/Forward10')),
  Forward30: asyncComponent(() => import('@material-ui/icons/Forward30')),
  Forward5: asyncComponent(() => import('@material-ui/icons/Forward5')),
  FourK: asyncComponent(() => import('@material-ui/icons/FourK')),
  FreeBreakfast: asyncComponent(
    () => import('@material-ui/icons/FreeBreakfast'),
  ),
  Fullscreen: asyncComponent(() => import('@material-ui/icons/Fullscreen')),
  FullscreenExit: asyncComponent(
    () => import('@material-ui/icons/FullscreenExit'),
  ),
  Functions: asyncComponent(() => import('@material-ui/icons/Functions')),
  Gamepad: asyncComponent(() => import('@material-ui/icons/Gamepad')),
  Games: asyncComponent(() => import('@material-ui/icons/Games')),
  Gavel: asyncComponent(() => import('@material-ui/icons/Gavel')),
  Gesture: asyncComponent(() => import('@material-ui/icons/Gesture')),
  GetApp: asyncComponent(() => import('@material-ui/icons/GetApp')),
  Gif: asyncComponent(() => import('@material-ui/icons/Gif')),
  GitHub: asyncComponent(() => import('@material-ui/icons/GitHub')),
  GolfCourse: asyncComponent(() => import('@material-ui/icons/GolfCourse')),
  GpsFixed: asyncComponent(() => import('@material-ui/icons/GpsFixed')),
  GpsNotFixed: asyncComponent(() => import('@material-ui/icons/GpsNotFixed')),
  GpsOff: asyncComponent(() => import('@material-ui/icons/GpsOff')),
  Grade: asyncComponent(() => import('@material-ui/icons/Grade')),
  Gradient: asyncComponent(() => import('@material-ui/icons/Gradient')),
  Grain: asyncComponent(() => import('@material-ui/icons/Grain')),
  GraphicEq: asyncComponent(() => import('@material-ui/icons/GraphicEq')),
  GridOff: asyncComponent(() => import('@material-ui/icons/GridOff')),
  GridOn: asyncComponent(() => import('@material-ui/icons/GridOn')),
  Group: asyncComponent(() => import('@material-ui/icons/Group')),
  GroupAdd: asyncComponent(() => import('@material-ui/icons/GroupAdd')),
  GroupWork: asyncComponent(() => import('@material-ui/icons/GroupWork')),
  GTranslate: asyncComponent(() => import('@material-ui/icons/GTranslate')),
  Hd: asyncComponent(() => import('@material-ui/icons/Hd')),
  HdrOff: asyncComponent(() => import('@material-ui/icons/HdrOff')),
  HdrOn: asyncComponent(() => import('@material-ui/icons/HdrOn')),
  HdrStrong: asyncComponent(() => import('@material-ui/icons/HdrStrong')),
  HdrWeak: asyncComponent(() => import('@material-ui/icons/HdrWeak')),
  Headset: asyncComponent(() => import('@material-ui/icons/Headset')),
  HeadsetMic: asyncComponent(() => import('@material-ui/icons/HeadsetMic')),
  Healing: asyncComponent(() => import('@material-ui/icons/Healing')),
  Hearing: asyncComponent(() => import('@material-ui/icons/Hearing')),
  Height: asyncComponent(() => import('@material-ui/icons/Height')),
  Help: asyncComponent(() => import('@material-ui/icons/Help')),
  HelpOutline: asyncComponent(() => import('@material-ui/icons/HelpOutline')),
  Highlight: asyncComponent(() => import('@material-ui/icons/Highlight')),
  HighlightOff: asyncComponent(() => import('@material-ui/icons/HighlightOff')),
  HighQuality: asyncComponent(() => import('@material-ui/icons/HighQuality')),
  History: asyncComponent(() => import('@material-ui/icons/History')),
  Home: asyncComponent(() => import('@material-ui/icons/Home')),
  HomeWork: asyncComponent(() => import('@material-ui/icons/HomeWork')),
  HorizontalSplit: asyncComponent(
    () => import('@material-ui/icons/HorizontalSplit'),
  ),
  Hotel: asyncComponent(() => import('@material-ui/icons/Hotel')),
  HotTub: asyncComponent(() => import('@material-ui/icons/HotTub')),
  HourglassEmpty: asyncComponent(
    () => import('@material-ui/icons/HourglassEmpty'),
  ),
  HourglassFull: asyncComponent(
    () => import('@material-ui/icons/HourglassFull'),
  ),
  House: asyncComponent(() => import('@material-ui/icons/House')),
  HowToReg: asyncComponent(() => import('@material-ui/icons/HowToReg')),
  HowToVote: asyncComponent(() => import('@material-ui/icons/HowToVote')),
  Http: asyncComponent(() => import('@material-ui/icons/Http')),
  Https: asyncComponent(() => import('@material-ui/icons/Https')),
  Image: asyncComponent(() => import('@material-ui/icons/Image')),
  ImageAspectRatio: asyncComponent(
    () => import('@material-ui/icons/ImageAspectRatio'),
  ),
  ImageSearch: asyncComponent(() => import('@material-ui/icons/ImageSearch')),
  ImportantDevices: asyncComponent(
    () => import('@material-ui/icons/ImportantDevices'),
  ),
  ImportContacts: asyncComponent(
    () => import('@material-ui/icons/ImportContacts'),
  ),
  ImportExport: asyncComponent(() => import('@material-ui/icons/ImportExport')),
  Inbox: asyncComponent(() => import('@material-ui/icons/Inbox')),
  IndeterminateCheckBox: asyncComponent(
    () => import('@material-ui/icons/IndeterminateCheckBox'),
  ),
  Info: asyncComponent(() => import('@material-ui/icons/Info')),
  Input: asyncComponent(() => import('@material-ui/icons/Input')),
  InsertChart: asyncComponent(() => import('@material-ui/icons/InsertChart')),
  InsertComment: asyncComponent(
    () => import('@material-ui/icons/InsertComment'),
  ),
  InsertDriveFile: asyncComponent(
    () => import('@material-ui/icons/InsertDriveFile'),
  ),
  InsertEmoticon: asyncComponent(
    () => import('@material-ui/icons/InsertEmoticon'),
  ),
  InsertInvitation: asyncComponent(
    () => import('@material-ui/icons/InsertInvitation'),
  ),
  InsertLink: asyncComponent(() => import('@material-ui/icons/InsertLink')),
  InsertPhoto: asyncComponent(() => import('@material-ui/icons/InsertPhoto')),
  Instagram: asyncComponent(() => import('@material-ui/icons/Instagram')),
  InvertColors: asyncComponent(() => import('@material-ui/icons/InvertColors')),
  InvertColorsOff: asyncComponent(
    () => import('@material-ui/icons/InvertColorsOff'),
  ),
  Iso: asyncComponent(() => import('@material-ui/icons/Iso')),
  Keyboard: asyncComponent(() => import('@material-ui/icons/Keyboard')),
  KeyboardArrowDown: asyncComponent(
    () => import('@material-ui/icons/KeyboardArrowDown'),
  ),
  KeyboardArrowLeft: asyncComponent(
    () => import('@material-ui/icons/KeyboardArrowLeft'),
  ),
  KeyboardArrowRight: asyncComponent(
    () => import('@material-ui/icons/KeyboardArrowRight'),
  ),
  KeyboardArrowUp: asyncComponent(
    () => import('@material-ui/icons/KeyboardArrowUp'),
  ),
  KeyboardBackspace: asyncComponent(
    () => import('@material-ui/icons/KeyboardBackspace'),
  ),
  KeyboardCapslock: asyncComponent(
    () => import('@material-ui/icons/KeyboardCapslock'),
  ),
  KeyboardHide: asyncComponent(() => import('@material-ui/icons/KeyboardHide')),
  KeyboardReturn: asyncComponent(
    () => import('@material-ui/icons/KeyboardReturn'),
  ),
  KeyboardTab: asyncComponent(() => import('@material-ui/icons/KeyboardTab')),
  KeyboardVoice: asyncComponent(
    () => import('@material-ui/icons/KeyboardVoice'),
  ),
  KingBed: asyncComponent(() => import('@material-ui/icons/KingBed')),
  Kitchen: asyncComponent(() => import('@material-ui/icons/Kitchen')),
  Label: asyncComponent(() => import('@material-ui/icons/Label')),
  LabelImportant: asyncComponent(
    () => import('@material-ui/icons/LabelImportant'),
  ),
  LabelOff: asyncComponent(() => import('@material-ui/icons/LabelOff')),
  Landscape: asyncComponent(() => import('@material-ui/icons/Landscape')),
  Language: asyncComponent(() => import('@material-ui/icons/Language')),
  Laptop: asyncComponent(() => import('@material-ui/icons/Laptop')),
  LaptopChromebook: asyncComponent(
    () => import('@material-ui/icons/LaptopChromebook'),
  ),
  LaptopMac: asyncComponent(() => import('@material-ui/icons/LaptopMac')),
  LaptopWindows: asyncComponent(
    () => import('@material-ui/icons/LaptopWindows'),
  ),
  LastPage: asyncComponent(() => import('@material-ui/icons/LastPage')),
  Launch: asyncComponent(() => import('@material-ui/icons/Launch')),
  Layers: asyncComponent(() => import('@material-ui/icons/Layers')),
  LayersClear: asyncComponent(() => import('@material-ui/icons/LayersClear')),
  LeakAdd: asyncComponent(() => import('@material-ui/icons/LeakAdd')),
  LeakRemove: asyncComponent(() => import('@material-ui/icons/LeakRemove')),
  Lens: asyncComponent(() => import('@material-ui/icons/Lens')),
  LibraryAdd: asyncComponent(() => import('@material-ui/icons/LibraryAdd')),
  LibraryAddCheck: asyncComponent(
    () => import('@material-ui/icons/LibraryAddCheck'),
  ),
  LibraryBooks: asyncComponent(() => import('@material-ui/icons/LibraryBooks')),
  LibraryMusic: asyncComponent(() => import('@material-ui/icons/LibraryMusic')),
  LinearScale: asyncComponent(() => import('@material-ui/icons/LinearScale')),
  LineStyle: asyncComponent(() => import('@material-ui/icons/LineStyle')),
  LineWeight: asyncComponent(() => import('@material-ui/icons/LineWeight')),
  Link: asyncComponent(() => import('@material-ui/icons/Link')),
  LinkedCamera: asyncComponent(() => import('@material-ui/icons/LinkedCamera')),
  LinkedIn: asyncComponent(() => import('@material-ui/icons/LinkedIn')),
  LinkOff: asyncComponent(() => import('@material-ui/icons/LinkOff')),
  List: asyncComponent(() => import('@material-ui/icons/List')),
  ListAlt: asyncComponent(() => import('@material-ui/icons/ListAlt')),
  LiveHelp: asyncComponent(() => import('@material-ui/icons/LiveHelp')),
  LiveTv: asyncComponent(() => import('@material-ui/icons/LiveTv')),
  LocalActivity: asyncComponent(
    () => import('@material-ui/icons/LocalActivity'),
  ),
  LocalAirport: asyncComponent(() => import('@material-ui/icons/LocalAirport')),
  LocalAtm: asyncComponent(() => import('@material-ui/icons/LocalAtm')),
  LocalBar: asyncComponent(() => import('@material-ui/icons/LocalBar')),
  LocalCafe: asyncComponent(() => import('@material-ui/icons/LocalCafe')),
  LocalCarWash: asyncComponent(() => import('@material-ui/icons/LocalCarWash')),
  LocalConvenienceStore: asyncComponent(
    () => import('@material-ui/icons/LocalConvenienceStore'),
  ),
  LocalDining: asyncComponent(() => import('@material-ui/icons/LocalDining')),
  LocalDrink: asyncComponent(() => import('@material-ui/icons/LocalDrink')),
  LocalFlorist: asyncComponent(() => import('@material-ui/icons/LocalFlorist')),
  LocalGasStation: asyncComponent(
    () => import('@material-ui/icons/LocalGasStation'),
  ),
  LocalGroceryStore: asyncComponent(
    () => import('@material-ui/icons/LocalGroceryStore'),
  ),
  LocalHospital: asyncComponent(
    () => import('@material-ui/icons/LocalHospital'),
  ),
  LocalHotel: asyncComponent(() => import('@material-ui/icons/LocalHotel')),
  LocalLaundryService: asyncComponent(
    () => import('@material-ui/icons/LocalLaundryService'),
  ),
  LocalLibrary: asyncComponent(() => import('@material-ui/icons/LocalLibrary')),
  LocalMall: asyncComponent(() => import('@material-ui/icons/LocalMall')),
  LocalMovies: asyncComponent(() => import('@material-ui/icons/LocalMovies')),
  LocalOffer: asyncComponent(() => import('@material-ui/icons/LocalOffer')),
  LocalParking: asyncComponent(() => import('@material-ui/icons/LocalParking')),
  LocalPharmacy: asyncComponent(
    () => import('@material-ui/icons/LocalPharmacy'),
  ),
  LocalPhone: asyncComponent(() => import('@material-ui/icons/LocalPhone')),
  LocalPizza: asyncComponent(() => import('@material-ui/icons/LocalPizza')),
  LocalPlay: asyncComponent(() => import('@material-ui/icons/LocalPlay')),
  LocalPostOffice: asyncComponent(
    () => import('@material-ui/icons/LocalPostOffice'),
  ),
  LocalPrintshop: asyncComponent(
    () => import('@material-ui/icons/LocalPrintshop'),
  ),
  LocalSee: asyncComponent(() => import('@material-ui/icons/LocalSee')),
  LocalShipping: asyncComponent(
    () => import('@material-ui/icons/LocalShipping'),
  ),
  LocalTaxi: asyncComponent(() => import('@material-ui/icons/LocalTaxi')),
  LocationCity: asyncComponent(() => import('@material-ui/icons/LocationCity')),
  LocationDisabled: asyncComponent(
    () => import('@material-ui/icons/LocationDisabled'),
  ),
  LocationOff: asyncComponent(() => import('@material-ui/icons/LocationOff')),
  LocationOn: asyncComponent(() => import('@material-ui/icons/LocationOn')),
  LocationSearching: asyncComponent(
    () => import('@material-ui/icons/LocationSearching'),
  ),
  Lock: asyncComponent(() => import('@material-ui/icons/Lock')),
  LockOpen: asyncComponent(() => import('@material-ui/icons/LockOpen')),
  Looks: asyncComponent(() => import('@material-ui/icons/Looks')),
  Looks3: asyncComponent(() => import('@material-ui/icons/Looks3')),
  Looks4: asyncComponent(() => import('@material-ui/icons/Looks4')),
  Looks5: asyncComponent(() => import('@material-ui/icons/Looks5')),
  Looks6: asyncComponent(() => import('@material-ui/icons/Looks6')),
  LooksOne: asyncComponent(() => import('@material-ui/icons/LooksOne')),
  LooksTwo: asyncComponent(() => import('@material-ui/icons/LooksTwo')),
  Loop: asyncComponent(() => import('@material-ui/icons/Loop')),
  Loupe: asyncComponent(() => import('@material-ui/icons/Loupe')),
  LowPriority: asyncComponent(() => import('@material-ui/icons/LowPriority')),
  Loyalty: asyncComponent(() => import('@material-ui/icons/Loyalty')),
  Mail: asyncComponent(() => import('@material-ui/icons/Mail')),
  MailOutline: asyncComponent(() => import('@material-ui/icons/MailOutline')),
  Map: asyncComponent(() => import('@material-ui/icons/Map')),
  Markunread: asyncComponent(() => import('@material-ui/icons/Markunread')),
  MarkunreadMailbox: asyncComponent(
    () => import('@material-ui/icons/MarkunreadMailbox'),
  ),
  Maximize: asyncComponent(() => import('@material-ui/icons/Maximize')),
  MeetingRoom: asyncComponent(() => import('@material-ui/icons/MeetingRoom')),
  Memory: asyncComponent(() => import('@material-ui/icons/Memory')),
  Menu: asyncComponent(() => import('@material-ui/icons/Menu')),
  MenuBook: asyncComponent(() => import('@material-ui/icons/MenuBook')),
  MenuOpen: asyncComponent(() => import('@material-ui/icons/MenuOpen')),
  MergeType: asyncComponent(() => import('@material-ui/icons/MergeType')),
  Message: asyncComponent(() => import('@material-ui/icons/Message')),
  Mic: asyncComponent(() => import('@material-ui/icons/Mic')),
  MicNone: asyncComponent(() => import('@material-ui/icons/MicNone')),
  MicOff: asyncComponent(() => import('@material-ui/icons/MicOff')),
  Minimize: asyncComponent(() => import('@material-ui/icons/Minimize')),
  MissedVideoCall: asyncComponent(
    () => import('@material-ui/icons/MissedVideoCall'),
  ),
  Mms: asyncComponent(() => import('@material-ui/icons/Mms')),
  MobileFriendly: asyncComponent(
    () => import('@material-ui/icons/MobileFriendly'),
  ),
  MobileOff: asyncComponent(() => import('@material-ui/icons/MobileOff')),
  MobileScreenShare: asyncComponent(
    () => import('@material-ui/icons/MobileScreenShare'),
  ),
  ModeComment: asyncComponent(() => import('@material-ui/icons/ModeComment')),
  MonetizationOn: asyncComponent(
    () => import('@material-ui/icons/MonetizationOn'),
  ),
  Money: asyncComponent(() => import('@material-ui/icons/Money')),
  MoneyOff: asyncComponent(() => import('@material-ui/icons/MoneyOff')),
  MonochromePhotos: asyncComponent(
    () => import('@material-ui/icons/MonochromePhotos'),
  ),
  Mood: asyncComponent(() => import('@material-ui/icons/Mood')),
  MoodBad: asyncComponent(() => import('@material-ui/icons/MoodBad')),
  More: asyncComponent(() => import('@material-ui/icons/More')),
  MoreHoriz: asyncComponent(() => import('@material-ui/icons/MoreHoriz')),
  MoreVert: asyncComponent(() => import('@material-ui/icons/MoreVert')),
  Motorcycle: asyncComponent(() => import('@material-ui/icons/Motorcycle')),
  Mouse: asyncComponent(() => import('@material-ui/icons/Mouse')),
  MoveToInbox: asyncComponent(() => import('@material-ui/icons/MoveToInbox')),
  Movie: asyncComponent(() => import('@material-ui/icons/Movie')),
  MovieCreation: asyncComponent(
    () => import('@material-ui/icons/MovieCreation'),
  ),
  MovieFilter: asyncComponent(() => import('@material-ui/icons/MovieFilter')),
  MultilineChart: asyncComponent(
    () => import('@material-ui/icons/MultilineChart'),
  ),
  Museum: asyncComponent(() => import('@material-ui/icons/Museum')),
  MusicNote: asyncComponent(() => import('@material-ui/icons/MusicNote')),
  MusicOff: asyncComponent(() => import('@material-ui/icons/MusicOff')),
  MusicVideo: asyncComponent(() => import('@material-ui/icons/MusicVideo')),
  MyLocation: asyncComponent(() => import('@material-ui/icons/MyLocation')),
  Nature: asyncComponent(() => import('@material-ui/icons/Nature')),
  NaturePeople: asyncComponent(() => import('@material-ui/icons/NaturePeople')),
  NavigateBefore: asyncComponent(
    () => import('@material-ui/icons/NavigateBefore'),
  ),
  NavigateNext: asyncComponent(() => import('@material-ui/icons/NavigateNext')),
  Navigation: asyncComponent(() => import('@material-ui/icons/Navigation')),
  NearMe: asyncComponent(() => import('@material-ui/icons/NearMe')),
  NetworkCell: asyncComponent(() => import('@material-ui/icons/NetworkCell')),
  NetworkCheck: asyncComponent(() => import('@material-ui/icons/NetworkCheck')),
  NetworkLocked: asyncComponent(
    () => import('@material-ui/icons/NetworkLocked'),
  ),
  NetworkWifi: asyncComponent(() => import('@material-ui/icons/NetworkWifi')),
  NewReleases: asyncComponent(() => import('@material-ui/icons/NewReleases')),
  NextWeek: asyncComponent(() => import('@material-ui/icons/NextWeek')),
  Nfc: asyncComponent(() => import('@material-ui/icons/Nfc')),
  NightsStay: asyncComponent(() => import('@material-ui/icons/NightsStay')),
  NoEncryption: asyncComponent(() => import('@material-ui/icons/NoEncryption')),
  NoMeetingRoom: asyncComponent(
    () => import('@material-ui/icons/NoMeetingRoom'),
  ),
  NoSim: asyncComponent(() => import('@material-ui/icons/NoSim')),
  Note: asyncComponent(() => import('@material-ui/icons/Note')),
  NoteAdd: asyncComponent(() => import('@material-ui/icons/NoteAdd')),
  Notes: asyncComponent(() => import('@material-ui/icons/Notes')),
  NotificationImportant: asyncComponent(
    () => import('@material-ui/icons/NotificationImportant'),
  ),
  Notifications: asyncComponent(
    () => import('@material-ui/icons/Notifications'),
  ),
  NotificationsActive: asyncComponent(
    () => import('@material-ui/icons/NotificationsActive'),
  ),
  NotificationsNone: asyncComponent(
    () => import('@material-ui/icons/NotificationsNone'),
  ),
  NotificationsOff: asyncComponent(
    () => import('@material-ui/icons/NotificationsOff'),
  ),
  NotificationsPaused: asyncComponent(
    () => import('@material-ui/icons/NotificationsPaused'),
  ),
  NotInterested: asyncComponent(
    () => import('@material-ui/icons/NotInterested'),
  ),
  NotListedLocation: asyncComponent(
    () => import('@material-ui/icons/NotListedLocation'),
  ),
  OfflineBolt: asyncComponent(() => import('@material-ui/icons/OfflineBolt')),
  OfflinePin: asyncComponent(() => import('@material-ui/icons/OfflinePin')),
  OndemandVideo: asyncComponent(
    () => import('@material-ui/icons/OndemandVideo'),
  ),
  Opacity: asyncComponent(() => import('@material-ui/icons/Opacity')),
  OpenInBrowser: asyncComponent(
    () => import('@material-ui/icons/OpenInBrowser'),
  ),
  OpenInNew: asyncComponent(() => import('@material-ui/icons/OpenInNew')),
  OpenWith: asyncComponent(() => import('@material-ui/icons/OpenWith')),
  OutdoorGrill: asyncComponent(() => import('@material-ui/icons/OutdoorGrill')),
  Pages: asyncComponent(() => import('@material-ui/icons/Pages')),
  Pageview: asyncComponent(() => import('@material-ui/icons/Pageview')),
  Palette: asyncComponent(() => import('@material-ui/icons/Palette')),
  Panorama: asyncComponent(() => import('@material-ui/icons/Panorama')),
  PanoramaFishEye: asyncComponent(
    () => import('@material-ui/icons/PanoramaFishEye'),
  ),
  PanoramaHorizontal: asyncComponent(
    () => import('@material-ui/icons/PanoramaHorizontal'),
  ),
  PanoramaVertical: asyncComponent(
    () => import('@material-ui/icons/PanoramaVertical'),
  ),
  PanoramaWideAngle: asyncComponent(
    () => import('@material-ui/icons/PanoramaWideAngle'),
  ),
  PanTool: asyncComponent(() => import('@material-ui/icons/PanTool')),
  PartyMode: asyncComponent(() => import('@material-ui/icons/PartyMode')),
  Pause: asyncComponent(() => import('@material-ui/icons/Pause')),
  PauseCircleFilled: asyncComponent(
    () => import('@material-ui/icons/PauseCircleFilled'),
  ),
  PauseCircleOutline: asyncComponent(
    () => import('@material-ui/icons/PauseCircleOutline'),
  ),
  PausePresentation: asyncComponent(
    () => import('@material-ui/icons/PausePresentation'),
  ),
  Payment: asyncComponent(() => import('@material-ui/icons/Payment')),
  People: asyncComponent(() => import('@material-ui/icons/People')),
  PeopleAlt: asyncComponent(() => import('@material-ui/icons/PeopleAlt')),
  PeopleOutline: asyncComponent(
    () => import('@material-ui/icons/PeopleOutline'),
  ),
  PermCameraMic: asyncComponent(
    () => import('@material-ui/icons/PermCameraMic'),
  ),
  PermContactCalendar: asyncComponent(
    () => import('@material-ui/icons/PermContactCalendar'),
  ),
  PermDataSetting: asyncComponent(
    () => import('@material-ui/icons/PermDataSetting'),
  ),
  PermDeviceInformation: asyncComponent(
    () => import('@material-ui/icons/PermDeviceInformation'),
  ),
  PermIdentity: asyncComponent(() => import('@material-ui/icons/PermIdentity')),
  PermMedia: asyncComponent(() => import('@material-ui/icons/PermMedia')),
  PermPhoneMsg: asyncComponent(() => import('@material-ui/icons/PermPhoneMsg')),
  PermScanWifi: asyncComponent(() => import('@material-ui/icons/PermScanWifi')),
  Person: asyncComponent(() => import('@material-ui/icons/Person')),
  PersonAdd: asyncComponent(() => import('@material-ui/icons/PersonAdd')),
  PersonAddDisabled: asyncComponent(
    () => import('@material-ui/icons/PersonAddDisabled'),
  ),
  PersonalVideo: asyncComponent(
    () => import('@material-ui/icons/PersonalVideo'),
  ),
  PersonOutline: asyncComponent(
    () => import('@material-ui/icons/PersonOutline'),
  ),
  PersonPin: asyncComponent(() => import('@material-ui/icons/PersonPin')),
  PersonPinCircle: asyncComponent(
    () => import('@material-ui/icons/PersonPinCircle'),
  ),
  Pets: asyncComponent(() => import('@material-ui/icons/Pets')),
  Phone: asyncComponent(() => import('@material-ui/icons/Phone')),
  PhoneAndroid: asyncComponent(() => import('@material-ui/icons/PhoneAndroid')),
  PhoneBluetoothSpeaker: asyncComponent(
    () => import('@material-ui/icons/PhoneBluetoothSpeaker'),
  ),
  PhoneCallback: asyncComponent(
    () => import('@material-ui/icons/PhoneCallback'),
  ),
  PhoneDisabled: asyncComponent(
    () => import('@material-ui/icons/PhoneDisabled'),
  ),
  PhoneEnabled: asyncComponent(() => import('@material-ui/icons/PhoneEnabled')),
  PhoneForwarded: asyncComponent(
    () => import('@material-ui/icons/PhoneForwarded'),
  ),
  PhoneInTalk: asyncComponent(() => import('@material-ui/icons/PhoneInTalk')),
  PhoneIphone: asyncComponent(() => import('@material-ui/icons/PhoneIphone')),
  Phonelink: asyncComponent(() => import('@material-ui/icons/Phonelink')),
  PhonelinkErase: asyncComponent(
    () => import('@material-ui/icons/PhonelinkErase'),
  ),
  PhonelinkLock: asyncComponent(
    () => import('@material-ui/icons/PhonelinkLock'),
  ),
  PhonelinkOff: asyncComponent(() => import('@material-ui/icons/PhonelinkOff')),
  PhonelinkRing: asyncComponent(
    () => import('@material-ui/icons/PhonelinkRing'),
  ),
  PhonelinkSetup: asyncComponent(
    () => import('@material-ui/icons/PhonelinkSetup'),
  ),
  PhoneLocked: asyncComponent(() => import('@material-ui/icons/PhoneLocked')),
  PhoneMissed: asyncComponent(() => import('@material-ui/icons/PhoneMissed')),
  PhonePaused: asyncComponent(() => import('@material-ui/icons/PhonePaused')),
  Photo: asyncComponent(() => import('@material-ui/icons/Photo')),
  PhotoAlbum: asyncComponent(() => import('@material-ui/icons/PhotoAlbum')),
  PhotoCamera: asyncComponent(() => import('@material-ui/icons/PhotoCamera')),
  PhotoFilter: asyncComponent(() => import('@material-ui/icons/PhotoFilter')),
  PhotoLibrary: asyncComponent(() => import('@material-ui/icons/PhotoLibrary')),
  PhotoSizeSelectActual: asyncComponent(
    () => import('@material-ui/icons/PhotoSizeSelectActual'),
  ),
  PhotoSizeSelectLarge: asyncComponent(
    () => import('@material-ui/icons/PhotoSizeSelectLarge'),
  ),
  PhotoSizeSelectSmall: asyncComponent(
    () => import('@material-ui/icons/PhotoSizeSelectSmall'),
  ),
  PictureAsPdf: asyncComponent(() => import('@material-ui/icons/PictureAsPdf')),
  PictureInPicture: asyncComponent(
    () => import('@material-ui/icons/PictureInPicture'),
  ),
  PictureInPictureAlt: asyncComponent(
    () => import('@material-ui/icons/PictureInPictureAlt'),
  ),
  PieChart: asyncComponent(() => import('@material-ui/icons/PieChart')),
  PinDrop: asyncComponent(() => import('@material-ui/icons/PinDrop')),
  Pinterest: asyncComponent(() => import('@material-ui/icons/Pinterest')),
  Place: asyncComponent(() => import('@material-ui/icons/Place')),
  PlayArrow: asyncComponent(() => import('@material-ui/icons/PlayArrow')),
  PlayCircleFilled: asyncComponent(
    () => import('@material-ui/icons/PlayCircleFilled'),
  ),
  PlayCircleFilledWhite: asyncComponent(
    () => import('@material-ui/icons/PlayCircleFilledWhite'),
  ),
  PlayCircleOutline: asyncComponent(
    () => import('@material-ui/icons/PlayCircleOutline'),
  ),
  PlayForWork: asyncComponent(() => import('@material-ui/icons/PlayForWork')),
  PlaylistAdd: asyncComponent(() => import('@material-ui/icons/PlaylistAdd')),
  PlaylistAddCheck: asyncComponent(
    () => import('@material-ui/icons/PlaylistAddCheck'),
  ),
  PlaylistPlay: asyncComponent(() => import('@material-ui/icons/PlaylistPlay')),
  PlusOne: asyncComponent(() => import('@material-ui/icons/PlusOne')),
  Policy: asyncComponent(() => import('@material-ui/icons/Policy')),
  Poll: asyncComponent(() => import('@material-ui/icons/Poll')),
  Polymer: asyncComponent(() => import('@material-ui/icons/Polymer')),
  Pool: asyncComponent(() => import('@material-ui/icons/Pool')),
  PortableWifiOff: asyncComponent(
    () => import('@material-ui/icons/PortableWifiOff'),
  ),
  Portrait: asyncComponent(() => import('@material-ui/icons/Portrait')),
  PostAdd: asyncComponent(() => import('@material-ui/icons/PostAdd')),
  Power: asyncComponent(() => import('@material-ui/icons/Power')),
  PowerInput: asyncComponent(() => import('@material-ui/icons/PowerInput')),
  PowerOff: asyncComponent(() => import('@material-ui/icons/PowerOff')),
  PowerSettingsNew: asyncComponent(
    () => import('@material-ui/icons/PowerSettingsNew'),
  ),
  PregnantWoman: asyncComponent(
    () => import('@material-ui/icons/PregnantWoman'),
  ),
  PresentToAll: asyncComponent(() => import('@material-ui/icons/PresentToAll')),
  Print: asyncComponent(() => import('@material-ui/icons/Print')),
  PrintDisabled: asyncComponent(
    () => import('@material-ui/icons/PrintDisabled'),
  ),
  PriorityHigh: asyncComponent(() => import('@material-ui/icons/PriorityHigh')),
  Public: asyncComponent(() => import('@material-ui/icons/Public')),
  Publish: asyncComponent(() => import('@material-ui/icons/Publish')),
  QueryBuilder: asyncComponent(() => import('@material-ui/icons/QueryBuilder')),
  QuestionAnswer: asyncComponent(
    () => import('@material-ui/icons/QuestionAnswer'),
  ),
  Queue: asyncComponent(() => import('@material-ui/icons/Queue')),
  QueueMusic: asyncComponent(() => import('@material-ui/icons/QueueMusic')),
  QueuePlayNext: asyncComponent(
    () => import('@material-ui/icons/QueuePlayNext'),
  ),
  Radio: asyncComponent(() => import('@material-ui/icons/Radio')),
  RadioButtonChecked: asyncComponent(
    () => import('@material-ui/icons/RadioButtonChecked'),
  ),
  RadioButtonUnchecked: asyncComponent(
    () => import('@material-ui/icons/RadioButtonUnchecked'),
  ),
  RateReview: asyncComponent(() => import('@material-ui/icons/RateReview')),
  Receipt: asyncComponent(() => import('@material-ui/icons/Receipt')),
  RecentActors: asyncComponent(() => import('@material-ui/icons/RecentActors')),
  RecordVoiceOver: asyncComponent(
    () => import('@material-ui/icons/RecordVoiceOver'),
  ),
  Reddit: asyncComponent(() => import('@material-ui/icons/Reddit')),
  Redeem: asyncComponent(() => import('@material-ui/icons/Redeem')),
  Redo: asyncComponent(() => import('@material-ui/icons/Redo')),
  Refresh: asyncComponent(() => import('@material-ui/icons/Refresh')),
  Remove: asyncComponent(() => import('@material-ui/icons/Remove')),
  RemoveCircle: asyncComponent(() => import('@material-ui/icons/RemoveCircle')),
  RemoveCircleOutline: asyncComponent(
    () => import('@material-ui/icons/RemoveCircleOutline'),
  ),
  RemoveFromQueue: asyncComponent(
    () => import('@material-ui/icons/RemoveFromQueue'),
  ),
  RemoveRedEye: asyncComponent(() => import('@material-ui/icons/RemoveRedEye')),
  RemoveShoppingCart: asyncComponent(
    () => import('@material-ui/icons/RemoveShoppingCart'),
  ),
  Reorder: asyncComponent(() => import('@material-ui/icons/Reorder')),
  Repeat: asyncComponent(() => import('@material-ui/icons/Repeat')),
  RepeatOne: asyncComponent(() => import('@material-ui/icons/RepeatOne')),
  Replay: asyncComponent(() => import('@material-ui/icons/Replay')),
  Replay10: asyncComponent(() => import('@material-ui/icons/Replay10')),
  Replay30: asyncComponent(() => import('@material-ui/icons/Replay30')),
  Replay5: asyncComponent(() => import('@material-ui/icons/Replay5')),
  Reply: asyncComponent(() => import('@material-ui/icons/Reply')),
  ReplyAll: asyncComponent(() => import('@material-ui/icons/ReplyAll')),
  Report: asyncComponent(() => import('@material-ui/icons/Report')),
  ReportOff: asyncComponent(() => import('@material-ui/icons/ReportOff')),
  ReportProblem: asyncComponent(
    () => import('@material-ui/icons/ReportProblem'),
  ),
  Restaurant: asyncComponent(() => import('@material-ui/icons/Restaurant')),
  RestaurantMenu: asyncComponent(
    () => import('@material-ui/icons/RestaurantMenu'),
  ),
  Restore: asyncComponent(() => import('@material-ui/icons/Restore')),
  RestoreFromTrash: asyncComponent(
    () => import('@material-ui/icons/RestoreFromTrash'),
  ),
  RestorePage: asyncComponent(() => import('@material-ui/icons/RestorePage')),
  RingVolume: asyncComponent(() => import('@material-ui/icons/RingVolume')),
  Room: asyncComponent(() => import('@material-ui/icons/Room')),
  RoomService: asyncComponent(() => import('@material-ui/icons/RoomService')),
  Rotate90DegreesCcw: asyncComponent(
    () => import('@material-ui/icons/Rotate90DegreesCcw'),
  ),
  RotateLeft: asyncComponent(() => import('@material-ui/icons/RotateLeft')),
  RotateRight: asyncComponent(() => import('@material-ui/icons/RotateRight')),
  Router: asyncComponent(() => import('@material-ui/icons/Router')),
  Rowing: asyncComponent(() => import('@material-ui/icons/Rowing')),
  RssFeed: asyncComponent(() => import('@material-ui/icons/RssFeed')),
  RvHookup: asyncComponent(() => import('@material-ui/icons/RvHookup')),
  Satellite: asyncComponent(() => import('@material-ui/icons/Satellite')),
  Save: asyncComponent(() => import('@material-ui/icons/Save')),
  SaveAlt: asyncComponent(() => import('@material-ui/icons/SaveAlt')),
  Scanner: asyncComponent(() => import('@material-ui/icons/Scanner')),
  ScatterPlot: asyncComponent(() => import('@material-ui/icons/ScatterPlot')),
  Schedule: asyncComponent(() => import('@material-ui/icons/Schedule')),
  School: asyncComponent(() => import('@material-ui/icons/School')),
  Score: asyncComponent(() => import('@material-ui/icons/Score')),
  ScreenLockLandscape: asyncComponent(
    () => import('@material-ui/icons/ScreenLockLandscape'),
  ),
  ScreenLockPortrait: asyncComponent(
    () => import('@material-ui/icons/ScreenLockPortrait'),
  ),
  ScreenLockRotation: asyncComponent(
    () => import('@material-ui/icons/ScreenLockRotation'),
  ),
  ScreenRotation: asyncComponent(
    () => import('@material-ui/icons/ScreenRotation'),
  ),
  ScreenShare: asyncComponent(() => import('@material-ui/icons/ScreenShare')),
  SdCard: asyncComponent(() => import('@material-ui/icons/SdCard')),
  SdStorage: asyncComponent(() => import('@material-ui/icons/SdStorage')),
  Search: asyncComponent(() => import('@material-ui/icons/Search')),
  Security: asyncComponent(() => import('@material-ui/icons/Security')),
  SelectAll: asyncComponent(() => import('@material-ui/icons/SelectAll')),
  Send: asyncComponent(() => import('@material-ui/icons/Send')),
  SentimentDissatisfied: asyncComponent(
    () => import('@material-ui/icons/SentimentDissatisfied'),
  ),
  SentimentSatisfied: asyncComponent(
    () => import('@material-ui/icons/SentimentSatisfied'),
  ),
  SentimentSatisfiedAlt: asyncComponent(
    () => import('@material-ui/icons/SentimentSatisfiedAlt'),
  ),
  SentimentVeryDissatisfied: asyncComponent(
    () => import('@material-ui/icons/SentimentVeryDissatisfied'),
  ),
  SentimentVerySatisfied: asyncComponent(
    () => import('@material-ui/icons/SentimentVerySatisfied'),
  ),
  Settings: asyncComponent(() => import('@material-ui/icons/Settings')),
  SettingsApplications: asyncComponent(
    () => import('@material-ui/icons/SettingsApplications'),
  ),
  SettingsBackupRestore: asyncComponent(
    () => import('@material-ui/icons/SettingsBackupRestore'),
  ),
  SettingsBluetooth: asyncComponent(
    () => import('@material-ui/icons/SettingsBluetooth'),
  ),
  SettingsBrightness: asyncComponent(
    () => import('@material-ui/icons/SettingsBrightness'),
  ),
  SettingsCell: asyncComponent(() => import('@material-ui/icons/SettingsCell')),
  SettingsEthernet: asyncComponent(
    () => import('@material-ui/icons/SettingsEthernet'),
  ),
  SettingsInputAntenna: asyncComponent(
    () => import('@material-ui/icons/SettingsInputAntenna'),
  ),
  SettingsInputComponent: asyncComponent(
    () => import('@material-ui/icons/SettingsInputComponent'),
  ),
  SettingsInputComposite: asyncComponent(
    () => import('@material-ui/icons/SettingsInputComposite'),
  ),
  SettingsInputHdmi: asyncComponent(
    () => import('@material-ui/icons/SettingsInputHdmi'),
  ),
  SettingsInputSvideo: asyncComponent(
    () => import('@material-ui/icons/SettingsInputSvideo'),
  ),
  SettingsOverscan: asyncComponent(
    () => import('@material-ui/icons/SettingsOverscan'),
  ),
  SettingsPhone: asyncComponent(
    () => import('@material-ui/icons/SettingsPhone'),
  ),
  SettingsPower: asyncComponent(
    () => import('@material-ui/icons/SettingsPower'),
  ),
  SettingsRemote: asyncComponent(
    () => import('@material-ui/icons/SettingsRemote'),
  ),
  SettingsSystemDaydream: asyncComponent(
    () => import('@material-ui/icons/SettingsSystemDaydream'),
  ),
  SettingsVoice: asyncComponent(
    () => import('@material-ui/icons/SettingsVoice'),
  ),
  Share: asyncComponent(() => import('@material-ui/icons/Share')),
  Shop: asyncComponent(() => import('@material-ui/icons/Shop')),
  ShoppingBasket: asyncComponent(
    () => import('@material-ui/icons/ShoppingBasket'),
  ),
  ShoppingCart: asyncComponent(() => import('@material-ui/icons/ShoppingCart')),
  ShopTwo: asyncComponent(() => import('@material-ui/icons/ShopTwo')),
  ShortText: asyncComponent(() => import('@material-ui/icons/ShortText')),
  ShowChart: asyncComponent(() => import('@material-ui/icons/ShowChart')),
  Shuffle: asyncComponent(() => import('@material-ui/icons/Shuffle')),
  ShutterSpeed: asyncComponent(() => import('@material-ui/icons/ShutterSpeed')),
  SignalCellular0Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellular0Bar'),
  ),
  SignalCellular1Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellular1Bar'),
  ),
  SignalCellular2Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellular2Bar'),
  ),
  SignalCellular3Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellular3Bar'),
  ),
  SignalCellular4Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellular4Bar'),
  ),
  SignalCellularAlt: asyncComponent(
    () => import('@material-ui/icons/SignalCellularAlt'),
  ),
  SignalCellularConnectedNoInternet0Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellularConnectedNoInternet0Bar'),
  ),
  SignalCellularConnectedNoInternet1Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellularConnectedNoInternet1Bar'),
  ),
  SignalCellularConnectedNoInternet2Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellularConnectedNoInternet2Bar'),
  ),
  SignalCellularConnectedNoInternet3Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellularConnectedNoInternet3Bar'),
  ),
  SignalCellularConnectedNoInternet4Bar: asyncComponent(
    () => import('@material-ui/icons/SignalCellularConnectedNoInternet4Bar'),
  ),
  SignalCellularNoSim: asyncComponent(
    () => import('@material-ui/icons/SignalCellularNoSim'),
  ),
  SignalCellularNull: asyncComponent(
    () => import('@material-ui/icons/SignalCellularNull'),
  ),
  SignalCellularOff: asyncComponent(
    () => import('@material-ui/icons/SignalCellularOff'),
  ),
  SignalWifi0Bar: asyncComponent(
    () => import('@material-ui/icons/SignalWifi0Bar'),
  ),
  SignalWifi1Bar: asyncComponent(
    () => import('@material-ui/icons/SignalWifi1Bar'),
  ),
  SignalWifi1BarLock: asyncComponent(
    () => import('@material-ui/icons/SignalWifi1BarLock'),
  ),
  SignalWifi2Bar: asyncComponent(
    () => import('@material-ui/icons/SignalWifi2Bar'),
  ),
  SignalWifi2BarLock: asyncComponent(
    () => import('@material-ui/icons/SignalWifi2BarLock'),
  ),
  SignalWifi3Bar: asyncComponent(
    () => import('@material-ui/icons/SignalWifi3Bar'),
  ),
  SignalWifi3BarLock: asyncComponent(
    () => import('@material-ui/icons/SignalWifi3BarLock'),
  ),
  SignalWifi4Bar: asyncComponent(
    () => import('@material-ui/icons/SignalWifi4Bar'),
  ),
  SignalWifi4BarLock: asyncComponent(
    () => import('@material-ui/icons/SignalWifi4BarLock'),
  ),
  SignalWifiOff: asyncComponent(
    () => import('@material-ui/icons/SignalWifiOff'),
  ),
  SimCard: asyncComponent(() => import('@material-ui/icons/SimCard')),
  SingleBed: asyncComponent(() => import('@material-ui/icons/SingleBed')),
  SkipNext: asyncComponent(() => import('@material-ui/icons/SkipNext')),
  SkipPrevious: asyncComponent(() => import('@material-ui/icons/SkipPrevious')),
  Slideshow: asyncComponent(() => import('@material-ui/icons/Slideshow')),
  SlowMotionVideo: asyncComponent(
    () => import('@material-ui/icons/SlowMotionVideo'),
  ),
  Smartphone: asyncComponent(() => import('@material-ui/icons/Smartphone')),
  SmokeFree: asyncComponent(() => import('@material-ui/icons/SmokeFree')),
  SmokingRooms: asyncComponent(() => import('@material-ui/icons/SmokingRooms')),
  Sms: asyncComponent(() => import('@material-ui/icons/Sms')),
  SmsFailed: asyncComponent(() => import('@material-ui/icons/SmsFailed')),
  Snooze: asyncComponent(() => import('@material-ui/icons/Snooze')),
  Sort: asyncComponent(() => import('@material-ui/icons/Sort')),
  SortByAlpha: asyncComponent(() => import('@material-ui/icons/SortByAlpha')),
  Spa: asyncComponent(() => import('@material-ui/icons/Spa')),
  SpaceBar: asyncComponent(() => import('@material-ui/icons/SpaceBar')),
  Speaker: asyncComponent(() => import('@material-ui/icons/Speaker')),
  SpeakerGroup: asyncComponent(() => import('@material-ui/icons/SpeakerGroup')),
  SpeakerNotes: asyncComponent(() => import('@material-ui/icons/SpeakerNotes')),
  SpeakerNotesOff: asyncComponent(
    () => import('@material-ui/icons/SpeakerNotesOff'),
  ),
  SpeakerPhone: asyncComponent(() => import('@material-ui/icons/SpeakerPhone')),
  Speed: asyncComponent(() => import('@material-ui/icons/Speed')),
  Spellcheck: asyncComponent(() => import('@material-ui/icons/Spellcheck')),
  Sports: asyncComponent(() => import('@material-ui/icons/Sports')),
  SportsBaseball: asyncComponent(
    () => import('@material-ui/icons/SportsBaseball'),
  ),
  SportsBasketball: asyncComponent(
    () => import('@material-ui/icons/SportsBasketball'),
  ),
  SportsCricket: asyncComponent(
    () => import('@material-ui/icons/SportsCricket'),
  ),
  SportsEsports: asyncComponent(
    () => import('@material-ui/icons/SportsEsports'),
  ),
  SportsFootball: asyncComponent(
    () => import('@material-ui/icons/SportsFootball'),
  ),
  SportsGolf: asyncComponent(() => import('@material-ui/icons/SportsGolf')),
  SportsHandball: asyncComponent(
    () => import('@material-ui/icons/SportsHandball'),
  ),
  SportsHockey: asyncComponent(() => import('@material-ui/icons/SportsHockey')),
  SportsKabaddi: asyncComponent(
    () => import('@material-ui/icons/SportsKabaddi'),
  ),
  SportsMma: asyncComponent(() => import('@material-ui/icons/SportsMma')),
  SportsMotorsports: asyncComponent(
    () => import('@material-ui/icons/SportsMotorsports'),
  ),
  SportsRugby: asyncComponent(() => import('@material-ui/icons/SportsRugby')),
  SportsSoccer: asyncComponent(() => import('@material-ui/icons/SportsSoccer')),
  SportsTennis: asyncComponent(() => import('@material-ui/icons/SportsTennis')),
  SportsVolleyball: asyncComponent(
    () => import('@material-ui/icons/SportsVolleyball'),
  ),
  SquareFoot: asyncComponent(() => import('@material-ui/icons/SquareFoot')),
  Star: asyncComponent(() => import('@material-ui/icons/Star')),
  StarBorder: asyncComponent(() => import('@material-ui/icons/StarBorder')),
  StarHalf: asyncComponent(() => import('@material-ui/icons/StarHalf')),
  StarOutline: asyncComponent(() => import('@material-ui/icons/StarOutline')),
  StarRate: asyncComponent(() => import('@material-ui/icons/StarRate')),
  Stars: asyncComponent(() => import('@material-ui/icons/Stars')),
  StayCurrentLandscape: asyncComponent(
    () => import('@material-ui/icons/StayCurrentLandscape'),
  ),
  StayCurrentPortrait: asyncComponent(
    () => import('@material-ui/icons/StayCurrentPortrait'),
  ),
  StayPrimaryLandscape: asyncComponent(
    () => import('@material-ui/icons/StayPrimaryLandscape'),
  ),
  StayPrimaryPortrait: asyncComponent(
    () => import('@material-ui/icons/StayPrimaryPortrait'),
  ),
  Stop: asyncComponent(() => import('@material-ui/icons/Stop')),
  StopScreenShare: asyncComponent(
    () => import('@material-ui/icons/StopScreenShare'),
  ),
  Storage: asyncComponent(() => import('@material-ui/icons/Storage')),
  Store: asyncComponent(() => import('@material-ui/icons/Store')),
  Storefront: asyncComponent(() => import('@material-ui/icons/Storefront')),
  StoreMallDirectory: asyncComponent(
    () => import('@material-ui/icons/StoreMallDirectory'),
  ),
  Straighten: asyncComponent(() => import('@material-ui/icons/Straighten')),
  Streetview: asyncComponent(() => import('@material-ui/icons/Streetview')),
  StrikethroughS: asyncComponent(
    () => import('@material-ui/icons/StrikethroughS'),
  ),
  Style: asyncComponent(() => import('@material-ui/icons/Style')),
  SubdirectoryArrowLeft: asyncComponent(
    () => import('@material-ui/icons/SubdirectoryArrowLeft'),
  ),
  SubdirectoryArrowRight: asyncComponent(
    () => import('@material-ui/icons/SubdirectoryArrowRight'),
  ),
  Subject: asyncComponent(() => import('@material-ui/icons/Subject')),
  Subscriptions: asyncComponent(
    () => import('@material-ui/icons/Subscriptions'),
  ),
  Subtitles: asyncComponent(() => import('@material-ui/icons/Subtitles')),
  Subway: asyncComponent(() => import('@material-ui/icons/Subway')),
  SupervisedUserCircle: asyncComponent(
    () => import('@material-ui/icons/SupervisedUserCircle'),
  ),
  SupervisorAccount: asyncComponent(
    () => import('@material-ui/icons/SupervisorAccount'),
  ),
  SurroundSound: asyncComponent(
    () => import('@material-ui/icons/SurroundSound'),
  ),
  SwapCalls: asyncComponent(() => import('@material-ui/icons/SwapCalls')),
  SwapHoriz: asyncComponent(() => import('@material-ui/icons/SwapHoriz')),
  SwapHorizontalCircle: asyncComponent(
    () => import('@material-ui/icons/SwapHorizontalCircle'),
  ),
  SwapVert: asyncComponent(() => import('@material-ui/icons/SwapVert')),
  SwapVerticalCircle: asyncComponent(
    () => import('@material-ui/icons/SwapVerticalCircle'),
  ),
  SwitchCamera: asyncComponent(() => import('@material-ui/icons/SwitchCamera')),
  SwitchVideo: asyncComponent(() => import('@material-ui/icons/SwitchVideo')),
  Sync: asyncComponent(() => import('@material-ui/icons/Sync')),
  SyncAlt: asyncComponent(() => import('@material-ui/icons/SyncAlt')),
  SyncDisabled: asyncComponent(() => import('@material-ui/icons/SyncDisabled')),
  SyncProblem: asyncComponent(() => import('@material-ui/icons/SyncProblem')),
  SystemUpdate: asyncComponent(() => import('@material-ui/icons/SystemUpdate')),
  SystemUpdateAlt: asyncComponent(
    () => import('@material-ui/icons/SystemUpdateAlt'),
  ),
  Tab: asyncComponent(() => import('@material-ui/icons/Tab')),
  TableChart: asyncComponent(() => import('@material-ui/icons/TableChart')),
  Tablet: asyncComponent(() => import('@material-ui/icons/Tablet')),
  TabletAndroid: asyncComponent(
    () => import('@material-ui/icons/TabletAndroid'),
  ),
  TabletMac: asyncComponent(() => import('@material-ui/icons/TabletMac')),
  TabUnselected: asyncComponent(
    () => import('@material-ui/icons/TabUnselected'),
  ),
  TagFaces: asyncComponent(() => import('@material-ui/icons/TagFaces')),
  TapAndPlay: asyncComponent(() => import('@material-ui/icons/TapAndPlay')),
  Telegram: asyncComponent(() => import('@material-ui/icons/Telegram')),
  Terrain: asyncComponent(() => import('@material-ui/icons/Terrain')),
  TextFields: asyncComponent(() => import('@material-ui/icons/TextFields')),
  TextFormat: asyncComponent(() => import('@material-ui/icons/TextFormat')),
  TextRotateUp: asyncComponent(() => import('@material-ui/icons/TextRotateUp')),
  TextRotateVertical: asyncComponent(
    () => import('@material-ui/icons/TextRotateVertical'),
  ),
  TextRotationAngledown: asyncComponent(
    () => import('@material-ui/icons/TextRotationAngledown'),
  ),
  TextRotationAngleup: asyncComponent(
    () => import('@material-ui/icons/TextRotationAngleup'),
  ),
  TextRotationDown: asyncComponent(
    () => import('@material-ui/icons/TextRotationDown'),
  ),
  TextRotationNone: asyncComponent(
    () => import('@material-ui/icons/TextRotationNone'),
  ),
  Textsms: asyncComponent(() => import('@material-ui/icons/Textsms')),
  Texture: asyncComponent(() => import('@material-ui/icons/Texture')),
  Theaters: asyncComponent(() => import('@material-ui/icons/Theaters')),
  ThreeDRotation: asyncComponent(
    () => import('@material-ui/icons/ThreeDRotation'),
  ),
  ThreeSixty: asyncComponent(() => import('@material-ui/icons/ThreeSixty')),
  ThumbDown: asyncComponent(() => import('@material-ui/icons/ThumbDown')),
  ThumbDownAlt: asyncComponent(() => import('@material-ui/icons/ThumbDownAlt')),
  ThumbsUpDown: asyncComponent(() => import('@material-ui/icons/ThumbsUpDown')),
  ThumbUp: asyncComponent(() => import('@material-ui/icons/ThumbUp')),
  ThumbUpAlt: asyncComponent(() => import('@material-ui/icons/ThumbUpAlt')),
  Timelapse: asyncComponent(() => import('@material-ui/icons/Timelapse')),
  Timeline: asyncComponent(() => import('@material-ui/icons/Timeline')),
  Timer: asyncComponent(() => import('@material-ui/icons/Timer')),
  Timer10: asyncComponent(() => import('@material-ui/icons/Timer10')),
  Timer3: asyncComponent(() => import('@material-ui/icons/Timer3')),
  TimerOff: asyncComponent(() => import('@material-ui/icons/TimerOff')),
  TimeToLeave: asyncComponent(() => import('@material-ui/icons/TimeToLeave')),
  Title: asyncComponent(() => import('@material-ui/icons/Title')),
  Toc: asyncComponent(() => import('@material-ui/icons/Toc')),
  Today: asyncComponent(() => import('@material-ui/icons/Today')),
  ToggleOff: asyncComponent(() => import('@material-ui/icons/ToggleOff')),
  ToggleOn: asyncComponent(() => import('@material-ui/icons/ToggleOn')),
  Toll: asyncComponent(() => import('@material-ui/icons/Toll')),
  Tonality: asyncComponent(() => import('@material-ui/icons/Tonality')),
  TouchApp: asyncComponent(() => import('@material-ui/icons/TouchApp')),
  Toys: asyncComponent(() => import('@material-ui/icons/Toys')),
  TrackChanges: asyncComponent(() => import('@material-ui/icons/TrackChanges')),
  Traffic: asyncComponent(() => import('@material-ui/icons/Traffic')),
  Train: asyncComponent(() => import('@material-ui/icons/Train')),
  Tram: asyncComponent(() => import('@material-ui/icons/Tram')),
  TransferWithinAStation: asyncComponent(
    () => import('@material-ui/icons/TransferWithinAStation'),
  ),
  Transform: asyncComponent(() => import('@material-ui/icons/Transform')),
  TransitEnterexit: asyncComponent(
    () => import('@material-ui/icons/TransitEnterexit'),
  ),
  Translate: asyncComponent(() => import('@material-ui/icons/Translate')),
  TrendingDown: asyncComponent(() => import('@material-ui/icons/TrendingDown')),
  TrendingFlat: asyncComponent(() => import('@material-ui/icons/TrendingFlat')),
  TrendingUp: asyncComponent(() => import('@material-ui/icons/TrendingUp')),
  TripOrigin: asyncComponent(() => import('@material-ui/icons/TripOrigin')),
  Tune: asyncComponent(() => import('@material-ui/icons/Tune')),
  TurnedIn: asyncComponent(() => import('@material-ui/icons/TurnedIn')),
  TurnedInNot: asyncComponent(() => import('@material-ui/icons/TurnedInNot')),
  Tv: asyncComponent(() => import('@material-ui/icons/Tv')),
  TvOff: asyncComponent(() => import('@material-ui/icons/TvOff')),
  Twitter: asyncComponent(() => import('@material-ui/icons/Twitter')),
  TwoWheeler: asyncComponent(() => import('@material-ui/icons/TwoWheeler')),
  Unarchive: asyncComponent(() => import('@material-ui/icons/Unarchive')),
  Undo: asyncComponent(() => import('@material-ui/icons/Undo')),
  UnfoldLess: asyncComponent(() => import('@material-ui/icons/UnfoldLess')),
  UnfoldMore: asyncComponent(() => import('@material-ui/icons/UnfoldMore')),
  Unsubscribe: asyncComponent(() => import('@material-ui/icons/Unsubscribe')),
  Update: asyncComponent(() => import('@material-ui/icons/Update')),
  Usb: asyncComponent(() => import('@material-ui/icons/Usb')),
  VerifiedUser: asyncComponent(() => import('@material-ui/icons/VerifiedUser')),
  VerticalAlignBottom: asyncComponent(
    () => import('@material-ui/icons/VerticalAlignBottom'),
  ),
  VerticalAlignCenter: asyncComponent(
    () => import('@material-ui/icons/VerticalAlignCenter'),
  ),
  VerticalAlignTop: asyncComponent(
    () => import('@material-ui/icons/VerticalAlignTop'),
  ),
  VerticalSplit: asyncComponent(
    () => import('@material-ui/icons/VerticalSplit'),
  ),
  Vibration: asyncComponent(() => import('@material-ui/icons/Vibration')),
  VideoCall: asyncComponent(() => import('@material-ui/icons/VideoCall')),
  Videocam: asyncComponent(() => import('@material-ui/icons/Videocam')),
  VideocamOff: asyncComponent(() => import('@material-ui/icons/VideocamOff')),
  VideogameAsset: asyncComponent(
    () => import('@material-ui/icons/VideogameAsset'),
  ),
  VideoLabel: asyncComponent(() => import('@material-ui/icons/VideoLabel')),
  VideoLibrary: asyncComponent(() => import('@material-ui/icons/VideoLibrary')),
  ViewAgenda: asyncComponent(() => import('@material-ui/icons/ViewAgenda')),
  ViewArray: asyncComponent(() => import('@material-ui/icons/ViewArray')),
  ViewCarousel: asyncComponent(() => import('@material-ui/icons/ViewCarousel')),
  ViewColumn: asyncComponent(() => import('@material-ui/icons/ViewColumn')),
  ViewComfy: asyncComponent(() => import('@material-ui/icons/ViewComfy')),
  ViewCompact: asyncComponent(() => import('@material-ui/icons/ViewCompact')),
  ViewDay: asyncComponent(() => import('@material-ui/icons/ViewDay')),
  ViewHeadline: asyncComponent(() => import('@material-ui/icons/ViewHeadline')),
  ViewList: asyncComponent(() => import('@material-ui/icons/ViewList')),
  ViewModule: asyncComponent(() => import('@material-ui/icons/ViewModule')),
  ViewQuilt: asyncComponent(() => import('@material-ui/icons/ViewQuilt')),
  ViewStream: asyncComponent(() => import('@material-ui/icons/ViewStream')),
  ViewWeek: asyncComponent(() => import('@material-ui/icons/ViewWeek')),
  Vignette: asyncComponent(() => import('@material-ui/icons/Vignette')),
  Visibility: asyncComponent(() => import('@material-ui/icons/Visibility')),
  VisibilityOff: asyncComponent(
    () => import('@material-ui/icons/VisibilityOff'),
  ),
  VoiceChat: asyncComponent(() => import('@material-ui/icons/VoiceChat')),
  Voicemail: asyncComponent(() => import('@material-ui/icons/Voicemail')),
  VoiceOverOff: asyncComponent(() => import('@material-ui/icons/VoiceOverOff')),
  VolumeDown: asyncComponent(() => import('@material-ui/icons/VolumeDown')),
  VolumeMute: asyncComponent(() => import('@material-ui/icons/VolumeMute')),
  VolumeOff: asyncComponent(() => import('@material-ui/icons/VolumeOff')),
  VolumeUp: asyncComponent(() => import('@material-ui/icons/VolumeUp')),
  VpnKey: asyncComponent(() => import('@material-ui/icons/VpnKey')),
  VpnLock: asyncComponent(() => import('@material-ui/icons/VpnLock')),
  Wallpaper: asyncComponent(() => import('@material-ui/icons/Wallpaper')),
  Warning: asyncComponent(() => import('@material-ui/icons/Warning')),
  Watch: asyncComponent(() => import('@material-ui/icons/Watch')),
  WatchLater: asyncComponent(() => import('@material-ui/icons/WatchLater')),
  Waves: asyncComponent(() => import('@material-ui/icons/Waves')),
  WbAuto: asyncComponent(() => import('@material-ui/icons/WbAuto')),
  WbCloudy: asyncComponent(() => import('@material-ui/icons/WbCloudy')),
  WbIncandescent: asyncComponent(
    () => import('@material-ui/icons/WbIncandescent'),
  ),
  WbIridescent: asyncComponent(() => import('@material-ui/icons/WbIridescent')),
  WbSunny: asyncComponent(() => import('@material-ui/icons/WbSunny')),
  Wc: asyncComponent(() => import('@material-ui/icons/Wc')),
  Web: asyncComponent(() => import('@material-ui/icons/Web')),
  WebAsset: asyncComponent(() => import('@material-ui/icons/WebAsset')),
  Weekend: asyncComponent(() => import('@material-ui/icons/Weekend')),
  WhatsApp: asyncComponent(() => import('@material-ui/icons/WhatsApp')),
  Whatshot: asyncComponent(() => import('@material-ui/icons/Whatshot')),
  WhereToVote: asyncComponent(() => import('@material-ui/icons/WhereToVote')),
  Widgets: asyncComponent(() => import('@material-ui/icons/Widgets')),
  Wifi: asyncComponent(() => import('@material-ui/icons/Wifi')),
  WifiLock: asyncComponent(() => import('@material-ui/icons/WifiLock')),
  WifiOff: asyncComponent(() => import('@material-ui/icons/WifiOff')),
  WifiTethering: asyncComponent(
    () => import('@material-ui/icons/WifiTethering'),
  ),
  Work: asyncComponent(() => import('@material-ui/icons/Work')),
  WorkOff: asyncComponent(() => import('@material-ui/icons/WorkOff')),
  WorkOutline: asyncComponent(() => import('@material-ui/icons/WorkOutline')),
  WrapText: asyncComponent(() => import('@material-ui/icons/WrapText')),
  YouTube: asyncComponent(() => import('@material-ui/icons/YouTube')),
  YoutubeSearchedFor: asyncComponent(
    () => import('@material-ui/icons/YoutubeSearchedFor'),
  ),
  ZoomIn: asyncComponent(() => import('@material-ui/icons/ZoomIn')),
  ZoomOut: asyncComponent(() => import('@material-ui/icons/ZoomOut')),
  ZoomOutMap: asyncComponent(() => import('@material-ui/icons/ZoomOutMap')),
};

export const NUMBER_OF_MUI_ICONS = Object.keys(muiIconNames).length;

export default muiIconNames;
