---
inject: true
to: src/index.ts
before: // DO NOT REMOVE - AUTOGENERATED
---
export { default as <%= h.inflection.camelize(name, false) %>, type <%= h.inflection.camelize(name, false) %>Props } from "./components/<%= h.inflection.camelize(name, false) %>";