---
inject: true
to: src/index.ts
before: // DO NOT REMOVE - AUTOGENERATED
---
<%
const componentName = name.split('/').pop();
const ComponentName = h.inflection.camelize(componentName, false);
-%>
export { default as <%= ComponentName %>, type <%= ComponentName %>Props } from "./components/<%= name %>";

