export const EXCEPTION_BOOKING_GUEST_GENERIC = 19050;
export const EXCEPTION_BOOKING_GUEST_OVERCOME_LIMIT = 19051;
export const EXCEPTION_BOOKING_GUEST_REACHED_LIMIT = 19052;
export const EXCEPTION_BOOKING_GUEST_IS_UNAVAILABLE_IN_SETTINGS = 19053;
export const EXCEPTION_BOOKING_GUEST_IS_UNAVAILABLE_IN_OFFER = 19054;
export const EXCEPTION_BOOKING_GUEST_IS_UNAVAILABLE_IN_PASS = 19055;
export const EXCEPTION_BOOKING_GUEST_NOT_ENOUGH_SPOT = 19057;

export const BASKET_INCONSISTENT = 'basketInconsistent';
export const PAYMENT_PACK_CAN_NOT_BOOK_ALL_OFFERS = 2128;
export const PAYMENT_COMBO_CAN_NOT_BOOK_ALL_OFFERS = 1123;

export enum FlowTypes {
  ONE_CLICK_CHECKOUT = 'one_click_checkout',
  NORMAL = 'normal',
}
