import {
  // CONSUMER PAYMENT PACK
  CONSUMER_PAYMENT_PACK_EVENTS,

  // PRIVATE CONSUMER PACK
  PRIVATE_CONSUMER_PACK_EVENTS,

  // GIFTCARD
  GIFTCARD_EVENTS,

  // SHOP ITEMS
  SHOP_ITEMS_EVENTS,

  // BOOKING
  BOOKING_EVENTS,

  // PRIVATE BOOKING
  PRIVATE_BOOOKING_EVENTS,

  // BASKET
  BASKET_ADD_ITEM,
  BASKET_FINALIZED,

  // INVOICE
  INVOICE_EVENTS,

  // BILLING PLAN
  EVENT_BILLING_PLAN_CREATE,
  EVENT_BILLING_PLAN_PAUSE,
  EVENT_BILLING_PLAN_STOP,
  EVENT_BILLING_PLAN_RENEW,

  // MEMBER
  EVENT_LEAD_FORM_SUBMITTED,
} from '@bsport/common/lib/master-data/events.js';

export enum Events {
  // PURCHASE
  CADENCE_EVENT_PURCHASE_PAYMENT_PACK = CONSUMER_PAYMENT_PACK_EVENTS.CREATE,
  CADENCE_EVENT_PURCHASE_PRIVATE_PACK = PRIVATE_CONSUMER_PACK_EVENTS.CREATE,
  CADENCE_EVENT_PURCHASE_SHOP_ITEM = SHOP_ITEMS_EVENTS.CREATE,
  CADENCE_EVENT_PURCHASE_GIFT_CARD = GIFTCARD_EVENTS.CREATE,

  // BOOKING & RIVATE BOOKING
  CADENCE_EVENT_BOOK_OFFER = BOOKING_EVENTS.CREATE,
  CADENCE_EVENT_ATTENDANCE_BOOKING = BOOKING_EVENTS.ATTENDANCE,
  CADENCE_EVENT_BOOK_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CREATE,
  CADENCE_EVENT_CANCELLED_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CANCEL,

  // BASKET
  CADENCE_EVENT_BASKET_ADD_ITEM = BASKET_ADD_ITEM,
  CADENCE_EVENT_BASKET_FINALIZED = BASKET_FINALIZED,

  // INVOICE
  CADENCE_EVENT_INVOICE_CREATED = INVOICE_EVENTS.CREATE,

  // BILLING PLAN
  CADENCE_EVENT_BILLING_PLAN_CREATED = EVENT_BILLING_PLAN_CREATE,
  CADENCE_EVENT_BILLING_PLAN_PAUSED = EVENT_BILLING_PLAN_PAUSE,
  CADENCE_EVENT_BILLING_PLAN_STOPPED = EVENT_BILLING_PLAN_STOP,
  CADENCE_EVENT_BILLING_PLAN_RENEWED = EVENT_BILLING_PLAN_RENEW,

  // MEMBER
  CADENCE_EVENT_LEAD_FORM_SUBMITTED = EVENT_LEAD_FORM_SUBMITTED,
}

export enum EventsCategory {
  // PURCHASE
  CADENCE_EVENT_PURCHASE_CATEGORY = 100,

  // BOOKING
  CADENCE_EVENT_BOOKING_CATEGORY = 101,

  // BASKET
  CADENCE_EVENT_BASKET_CATEGORY = 102,

  // INVOICE
  CADENCE_EVENT_INVOICE_CATEGORY = 103,

  // BILLING PLAN
  CADENCE_EVENT_BILLING_PLAN_CATEGORY = 104,

  // MEMBER
  CADENCE_EVENT_MEMBER_CATEGORY = 105,
}

export const CADENCE_EVENT_ALL_CHOICES: Events[] = [
  Events.CADENCE_EVENT_PURCHASE_PAYMENT_PACK,
  Events.CADENCE_EVENT_PURCHASE_PRIVATE_PACK,
  Events.CADENCE_EVENT_PURCHASE_SHOP_ITEM,
  Events.CADENCE_EVENT_PURCHASE_GIFT_CARD,
  Events.CADENCE_EVENT_BOOK_OFFER,
  Events.CADENCE_EVENT_ATTENDANCE_BOOKING,
  Events.CADENCE_EVENT_BOOK_APPOINTMENT,
  Events.CADENCE_EVENT_CANCELLED_APPOINTMENT,
  Events.CADENCE_EVENT_BASKET_ADD_ITEM,
  Events.CADENCE_EVENT_BASKET_FINALIZED,
  Events.CADENCE_EVENT_INVOICE_CREATED,
  Events.CADENCE_EVENT_BILLING_PLAN_CREATED,
  Events.CADENCE_EVENT_BILLING_PLAN_PAUSED,
  Events.CADENCE_EVENT_BILLING_PLAN_STOPPED,
  Events.CADENCE_EVENT_BILLING_PLAN_RENEWED,
  Events.CADENCE_EVENT_LEAD_FORM_SUBMITTED,
];

export const CADENCE_EVENT_CATEGORY_CHOICES = [
  EventsCategory.CADENCE_EVENT_PURCHASE_CATEGORY,
  EventsCategory.CADENCE_EVENT_BOOKING_CATEGORY,
  EventsCategory.CADENCE_EVENT_BASKET_CATEGORY,
  EventsCategory.CADENCE_EVENT_INVOICE_CATEGORY,
  EventsCategory.CADENCE_EVENT_BILLING_PLAN_CATEGORY,
  EventsCategory.CADENCE_EVENT_MEMBER_CATEGORY,
];

export const CADENCE_EVENT_GROUPED_BY_CATEGORY: Record<
  EventsCategory,
  Events[]
> = {
  [EventsCategory.CADENCE_EVENT_PURCHASE_CATEGORY]: [
    Events.CADENCE_EVENT_PURCHASE_PAYMENT_PACK,
    Events.CADENCE_EVENT_PURCHASE_PRIVATE_PACK,
    Events.CADENCE_EVENT_PURCHASE_SHOP_ITEM,
    Events.CADENCE_EVENT_PURCHASE_GIFT_CARD,
  ],
  [EventsCategory.CADENCE_EVENT_BOOKING_CATEGORY]: [
    Events.CADENCE_EVENT_BOOK_OFFER,
    Events.CADENCE_EVENT_ATTENDANCE_BOOKING,
    Events.CADENCE_EVENT_BOOK_APPOINTMENT,
    Events.CADENCE_EVENT_CANCELLED_APPOINTMENT,
  ],
  [EventsCategory.CADENCE_EVENT_BASKET_CATEGORY]: [
    Events.CADENCE_EVENT_BASKET_ADD_ITEM,
    Events.CADENCE_EVENT_BASKET_FINALIZED,
  ],
  [EventsCategory.CADENCE_EVENT_INVOICE_CATEGORY]: [
    Events.CADENCE_EVENT_INVOICE_CREATED,
  ],
  [EventsCategory.CADENCE_EVENT_BILLING_PLAN_CATEGORY]: [
    Events.CADENCE_EVENT_BILLING_PLAN_CREATED,
    Events.CADENCE_EVENT_BILLING_PLAN_PAUSED,
    Events.CADENCE_EVENT_BILLING_PLAN_STOPPED,
    Events.CADENCE_EVENT_BILLING_PLAN_RENEWED,
  ],
  [EventsCategory.CADENCE_EVENT_MEMBER_CATEGORY]: [
    Events.CADENCE_EVENT_LEAD_FORM_SUBMITTED,
  ],
};

export const CADENCE_FINER_GRAIN_ALLOWED_EVENTS_LIST: Events[] = [
  Events.CADENCE_EVENT_PURCHASE_PAYMENT_PACK,
  Events.CADENCE_EVENT_PURCHASE_PRIVATE_PACK,
  Events.CADENCE_EVENT_PURCHASE_SHOP_ITEM,
  Events.CADENCE_EVENT_PURCHASE_GIFT_CARD,
  Events.CADENCE_EVENT_BILLING_PLAN_CREATED,
];

export enum RuleBetweenEntryEvent {
  AND_RULE_BETWEEN_ENTRY_EVENT = 1,
  OR_RULE_BETWEEN_ENTRY_EVENT = 2,
}
