export const OFFER_BOOKABLE_STATUS_BOOKABLE = 0;
export const OFFER_BOOKABLE_STATUS_CLOSE_TOO_SOON = 1;
export const OFFER_BOOKABLE_STATUS_CLOSE_TOO_LATE = 2;
export const OFFER_BOOKABLE_STATUS_FULL = 3;
export const OFFER_BOOKABLE_STATUS_LOCKED = 4;
