// see the other filters in communication-kind
// ---------- CHANNEL FITLERS ----------
export const COMMUNICATION_CHANNEL_SESSION = 10;
export const COMMUNICATION_CHANNEL_MESSAGE_DIRECT = 11;
export const COMMUNICATION_CHANNEL_SMARTLIST = 12;
export const COMMUNICATION_CHANNEL_MARKETING_NOTIFICATION = 13;
export const COMMUNICATION_CHANNEL_NOTIFICATION_RULE = 14;
export const COMMUNICATION_CHANNEL_CADENCE = 15;
export const COMMUNICATION_CHANNEL_FRANCHISE = 16;

// ---------- RECIPIENT FITLERS ----------
export const COMMUNICATION_RECIPIENT_BOOKINGS = 30;
export const COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED = 31;
export const COMMUNICATION_RECIPIENT_WAITING_LIST = 32;
// ---------- SEND PARAMETER FOR SMARTLIST FITLERS ----------
export const COMMUNICATION_SEND_PARAMETER_AUTO = 50;
export const COMMUNICATION_SEND_PARAMETER_MANUAL = 51;
// ---------- SENT OR RECEIVED MESSAGES FITLERS ----------
export const COMMUNICATION_SRC_OR_DST_SENT = 70;
export const COMMUNICATION_SRC_OR_DST_RECEIVED = 71;
