export const COUPON_SUBSCRIPTION_MODE_RECURRENT_PRICE = 0;
export const COUPON_SUBSCRIPTION_MODE_FIRST_INVOICE = 1;
export const COUPON_SUBSCRIPTION_MODE_ALL_INVOICES = 2;
export const COUPON_SUBSCRIPTION_MODE_NONE = 3;
