export enum MEMBER_STATUS {
  HAS_NEGATIVE_CREDIT_ACCOUNT = 0,
  HAS_UNPAID_INVOICE = 1,
  HAS_ON_GOING_SUBSCRIPTION = 2,
  HAS_AUTO_RENEW_SUBSCRIPTION = 3,
  HAS_FUTURE_BOOKINGS = 4,
  HAS_RECCURENT_BOOKING = 5,
  HAS_PRIVATE_BOOKING = 6,
}

export type MemberStatuses = MEMBER_STATUS;
