export enum BillingPlanMetadataIdentifierEnum {
  BILLING_PLAN_PK = 'billingplan_pk',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  CONTRACT_NAME = 'contract_name',
  PRODUCTS_NAME = 'product_names',
  DATE_START = 'plan_date_start',
  NB_PLANNED_INVOICES = 'nb_planned_invoices',
  TOTAL_PAYMENTS_MADE = 'total_payments_made',
  DATE_END = 'plan_date_end',
  RECURRENT_PRICE = 'plan_recurrent_price',
  TOTAL_DISCOUNT = 'total_discount',
  PAYMENT_METHOD = 'billing_plan_payment_method',
  LAST_INVOICE_STATUS = 'last_invoice_status',
  AUTO_RENEWAL = 'plan_auto_renewal',
  STATUS = 'plan_status',
  FLAT_FEE = 'plan_flat_fee',
  NEW_MEMBER_ONLY = 'new_member_only',
  SECOND_BILLING_PLAN = 'second_billing_plan',
}

export enum BasketMetadataIdentifierEnum {
  BASKET_ID = 'basket_id',
  MEMBER_PK = 'member_pk',
  NAME = 'name',
  TOTAL_PRICE = 'total_price',
  CHECKOUT_ITEMS = 'checkout_items',
  EMAIL = 'email',
  PHONE_NUMBER = 'phonenumber',
  LAST_BOOKING = 'last_booking',
  NEXT_BOOKING = 'next_booking',
  GENDER = 'gender',
  DATE_JOINED = 'date_joined',
  COMPANY_NAME = 'company_name',
}

export enum DayBookingsMetadataIdentifierEnum {
  DATE_START_DATE = 'date_start_date',
  NB_BOOKINGS = 'nb_bookings',
  CANCELED_BOOKINGS = 'canceled_bookings',
  ATTENDANCE = 'attendance',
  SUM_NON_ATTENDANCE = 'sum__non_attendance',
  RATE_ATTENDANCE = 'rate_attendance',
  COMPANY_NAME = 'company_name',
}

export enum CashbookMetadataIdentifierEnum {
  DATE_LAST_UPDATE = 'date_last_update',
  TODAY_START_AMOUNT = 'today_start_amount',
  AMOUNT = 'amount',
  TODAY_END_AMOUNT = 'today_end_amount',
  COMPANY_NAME = 'company_name',
}
export enum FirstBookingMetadataIdentifierEnum {
  FIRST_BOOKING_ID = 'first_booking_id',
  MEMBER_PK = 'member_pk',
  IDENTIFIER = 'identifier',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  DATE_OFFER = 'date_offer',
  ACTIVITY = 'activity',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  TOTAL_PAYMENTS = 'total_payments',
  DATE_JOINED = 'date_joined',
  COMPANY_NAME = 'company_name',
}
export enum BookingMetadataIdentifierEnum {
  BOOKING_PK = 'booking_pk',
  MEMBER_PK = 'member_pk',
  ACTIVITY = 'activity',
  ACTIVITY_KIND = 'activity_kind',
  IS_WORKSHOP = 'is_workshop',
  ATTENDANCE = 'attendance',
  IS_NO_SHOW = 'is_no_show',
  PAYMENT_PACK = 'payment_pack',
  SOURCE_DEVICE = 'source_device',
  NB_BOOKINGS_SAME_PASS = 'nb_bookings_same_pass',
  DATE_START = 'date_start',
  DATE_CREATED = 'date_created',
  DATE_START_DATE = 'date_start_date',
  DATE_START_TIME = 'date_start_time',
  OFFER_PK = 'offer_pk',
  PASS = 'pass',
  MARGIN_VALUE = 'margin_value',
  REMAINING_CREDITS = 'remaining_credits',
  BOOKING_STATUS_CODE = 'booking_status_code',
  WAS_REFUNDED = 'was_refunded',
  GENDER = 'gender',
  COACH = 'coach',
  IS_RECURRENT_BOOKING = 'is_recurrent_booking',
  ESTABLISHMENT = 'establishment',
  DURATION = 'duration',
  CREDIT_CONSUMED = 'credit_consumed',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  COMPANY_NAME = 'company_name',
  BILLING_GROUP = 'billing_group',
  BILLING_ESTABLISHMENT = 'billing_establishment',
}

export enum FranchiseSharedPassMetadataIdentifierEnum {
  SRC_COMPANY = 'src_company',
  DST_COMPANY = 'dst_company',
  TOTAL_MIXED_FROM_SRC = 'total_mixed_from_src',
  SHARED_PASS_RATIO = 'shared_pass_ratio',
}
export enum PrivateConsumerPassMetadataIdentifierEnum {
  PK = 'pk',
  MEMBER_PK = 'member_pk',
  MEMBERSHIP_NAME = 'membership_name',
  START_DATE = 'start_date',
  END_DATE = 'end_date',
  NB_BOOKINGS = 'nb_bookings',
  AVAILABLE_CREDITS = 'available_credits',
  CREDITS = 'credits',
  PRICE = 'price',
  APPLIED_TAX = 'applied_tax',
  AMORTIZED_PRICE = 'amortized_price',
  DISABLED = 'disabled',
  MEMBERSHIP_ID = 'membership_ID',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  COMPANY_NAME = 'company_name',
}
export enum ExpiredConsumerPaymentPackMetadataIdentifierEnum {
  MEMBERSHIP_NAME = 'membership_name',
  PK = 'pk',
  START_DATE = 'start_date',
  END_DATE = 'end_date',
  PRICE = 'price',
  AMORTIZED_PRICE = 'amortized_price',
  NB_BOOKINGS = 'nb_bookings',
  REMAINING_CREDITS_ANNOTATED = 'remaining_credits_annotated',
  CREDITS = 'credits',
  DISABLED = 'disabled',
  MEMBERSHIP_ID = 'membership_ID',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  COMPANY_NAME = 'company_name',
  MEMBER_PK = 'member_pk',
}
export enum ConsumerPaymentPackMetadataIdentifierEnum {
  MEMBERSHIP_NAME = 'membership_name',
  START_DATE = 'start_date',
  NB_BOOKINGS = 'nb_bookings',
  REMAINING_CREDITS_ANNOTATED = 'remaining_credits_annotated',
  END_DATE = 'end_date',
  REMAINING_DAYS = 'remaining_days',
  PRICE = 'price',
  CREDITS = 'credits',
  AMORTIZED_PRICE = 'amortized_price',
  AVAILABLE_CREDITS = 'available_credits',
  FIRST_NAME = 'first_name',
  PK = 'pk',
  MEMBER_PK = 'member_pk',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  MEMBERSHIP_ID = 'membership_ID',
  DISABLED = 'disabled',
  COMPANY_NAME = 'company_name',
}
export enum UniversalPassMetadataIdentifierEnum {
  MEMBERSHIP_NAME = 'membership_name',
  PK = 'pk',
  MEMBER_PK = 'member_pk',
  START_DATE = 'start_date',
  NB_BOOKINGS = 'nb_bookings',
  REMAINING_CREDITS_ANNOTATED = 'remaining_credits_annotated',
  END_DATE = 'end_date',
  REMAINING_DAYS = 'remaining_days',
  PRICE = 'price',
  CREDITS = 'credits',
  AMORTIZED_PRICE = 'amortized_price',
  AVAILABLE_CREDITS = 'available_credits',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  MEMBERSHIP_ID = 'membership_ID',
  DISABLED = 'disabled',
  COMPANY_NAME = 'company_name',
}
export enum CreditMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  CREDITS = 'credits',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  DATE_JOINED = 'date_joined',
  LAST_BOOKING = 'last_booking',
  NEXT_BOOKING = 'next_booking',
  COMPANY_NAME = 'company_name',
}
export enum DiscountMetadataIdentifierEnum {
  COUPON_NAME = 'couponName',
  COUPON_PK = 'coupon_pk',
  NEGATIVE_VOUCHER = 'negative_voucher',
  PAYMENT_IDENTIFIER = 'payment_identifier',
  TOTAL_BASKET = 'total_basket',
  MEMBER = 'member',
  EMAIL = 'email',
  PRODUCTS = 'products',
  DATE = 'date',
  TIME = 'time',
  PERCENT_OFF = 'percent_off',
  AMOUNT_OFF = 'amount_off',
  COMPANY_NAME = 'company_name',
}
export enum DisputeMetadataIdentifierEnum {
  PAYMENT_PK = 'payment_pk',
  PAYMENT_IDENTIFIER = 'payment_identifier',
  AUTHOR = 'author',
  PAYMENT_DATE = 'payment_date',
  PAYMENT_DATE_DATE = 'payment_date_date',
  PAYMENT_DATE_TIME = 'payment_date_time',
  PAYMENT_PRICE = 'payment_price',
  BSPORT_FEE = 'bsport_fee',
  DISPUTE_STATUS = 'dispute_status',
  PRODUCT_NAMES = 'product_names',
  PAYOUT_IDENTIFIER = 'payout_identifier',
  PAYOUT_DATE_CREATED = 'payout_date_created',
  PAYOUT_STATUS = 'payout_status',
  PAYMENT_NOTE = 'payment_note',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  ESTABLISHMENT = 'establishment',
  BILLING_ESTABLISHMENT = 'billing_establishment',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
  PAYMENT_LEGAL_IDENTIFIER = 'payment_legal_identifier',
}
export enum ExpenseMetadataIdentifierEnum {
  EXPENSE_PK = 'expense_pk',
  DESCRIPTION = 'description',
  AMOUNT_EXPENSE = 'amount_expense',
  DUE_DATE = 'due_date',
  AUTHOR = 'author',
  DATE_CREATED = 'date_created',
  SUPPLIER = 'supplier',
  CATEGORY = 'category',
  IS_RECURRING = 'is_recurring',
  COMPANY_NAME = 'company_name',
}
export enum FirstAttendanceMetadataIdentifierEnum {
  IDENTIFIER = 'identifier',
  MEMBER_PK = 'member_pk',
  BOOKING_ID = 'booking_id',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  DATE_OFFER = 'date_offer',
  ACTIVITY = 'activity',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  TOTAL_PAYMENTS = 'total_payments',
  DATE_JOINED = 'date_joined',
  COMPANY_NAME = 'company_name',
}
export enum FirstPrivateBookingMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  PRIVATEBOOKING_PK = 'privatebooking_pk',
  PRIVATE_SERVICE_NAME = 'private_service_name',
  IDENTIFIER = 'identifier',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  DATE_FIRST_PRIVATEBOOKING = 'date_first_privatebooking',
  PRIVATE_SLOT = 'private_slot',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  TOTAL_PAYMENTS = 'total_payments',
  DATE_JOINED = 'date_joined',
  COMPANY_NAME = 'company_name',
}
export enum GiftcardMetadataIdentifierEnum {
  ID = 'id',
  NAME = 'name',
  DATE_CREATED = 'date_created',
  PRICE = 'price',
  NB_PURCHASE = 'nb_purchase',
  NB_ACTIVATED = 'nb_activated',
  NB_NON_ACTIVATED = 'nb_non_activated',
  NB_EXPIRED = 'nb_expired',
  SUM_CONSUMED_AMOUNT = 'sum_consumed_amount',
  SUM_AVAILABLE_AMOUNT_EXPIRED = 'sum_available_amount_expired',
  SUM_AVAILABLE_AMOUNT_NON_EXPIRED = 'sum_available_amount_non_expired',
  COMPANY_NAME = 'company_name',
}
export enum ConsumerGiftcardMetadataIdentifierEnum {
  KIND = 'kind',
  PK = 'pk',
  MEMBER_PK = 'member_pk',
  NAME = 'name',
  PRICE = 'price',
  DATE_CREATED = 'date_created',
  SRC_FIRSTNAME = 'src_firstname',
  SRC_LASTNAME = 'src_lastname',
  SRC_EMAIL = 'src_email',
  SRC_PHONENUMBER = 'src_phonenumber',
  DST_FIRSTNAME = 'dst_firstname',
  DST_LASTNAME = 'dst_lastname',
  DST_EMAIL = 'dst_email',
  DST_PHONENUMBER = 'dst_phonenumber',
  DST_GENDER = 'dst_gender',
  CONSUMED_AMOUNT_GIFTED = 'consumed_amount_gifted',
  COMPANY_NAME = 'company_name',
  REVERTED = 'reverted',
}
export enum InvoiceMetadataIdentifierEnum {
  PAYMENT_IDENTIFIER = 'payment_identifier',
  PAYMENT_LEGAL_IDENTIFIER = 'payment_legal_identifier',
  AUTHOR = 'author',
  INVOICE_DATETIME = 'invoice_datetime',
  INVOICE_DATE_CREATED = 'invoice_date_created',
  INVOICE_TIME = 'invoice_time',
  PRODUCT_PRICE = 'product_price',
  TAX = 'tax',
  VOUCHER = 'voucher',
  VOUCHER_REASON = 'voucher_reason',
  TOTAL_PRICE = 'total_price',
  TOTAL_PRICE_NOTAX = 'total_price_notax',
  PAYMENT_METHOD = 'payment_method',
  PRODUCT = 'product',
  PRODUCT_TYPE = 'product_type',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  LAST_PAYMENT_DATE = 'last_payment_date',
  PAYMENT_AMOUNT_BY_PAYMENT_METHOD = 'payment_amount_by_payment_method',
  BILLING_ESTABLISHMENT = 'billing_establishment',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
  STAFF_COMMISSION_AMOUNT_NOTAX = 'staff_commission_amount_notax',
  STAFF_COMMISION_AMOUNT = 'staff_commission_amount',
  FRANCHISOR_COMMISSION_AMOUNT = 'franchisor_commission_amount',
  FRANCHISOR_COMMISSION_AMOUNT_NOTAX = 'franchisor_commission_amount_notax',
}
export enum UnpaidInvoiceMetadataIdentifierEnum {
  PAYMENT_IDENTIFIER = 'payment_identifier',
  PAYMENT_LEGAL_IDENTIFIER = 'payment_legal_identifier',
  AUTHOR_NAME = 'author_name',
  DATE = 'date',
  AMOUNT_DUE_CTS = 'amount_due_cts',
  AMOUNT_PAID_CTS = 'amount_paid_cts',
  AMOUNT_UNPAID_REMAINING_CTS = 'amount_unpaid_remaining_cts',
  PRODUCT_NAMES = 'product_names',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  STRIPE_INVOICE_PDF = 'stripe_invoice_pdf',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  ADDRESS = 'address',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
}
export enum MemberMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  IDENTIFIER = 'identifier',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  BIRTHDAY = 'birthday',
  FULL_ADDRESS = 'full_address',
  TOTAL_PAYMENTS = 'total_payments',
  NB_BOOKINGS = 'nb_bookings',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  DATE_JOINED = 'date_joined',
  CONCATENATED_NOTES = 'concatenated_notes',
  CREDITS = 'credits',
  UNPAID_AMOUNT = 'unpaid_amount',
  ACCEPT_EMAIL = 'accept_email',
  ACCEPT_SMS = 'accept_sms',
  COMPANY_NAME = 'company_name',
}
export enum MembersPurchaseMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  IDENTIFIER = 'identifier',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  TOTAL_PAYMENTS = 'total_payments',
  NB_INVOICE_ITEMS = 'nb_invoice_items',
  PRICE_INVOICE_ITEMS = 'price_invoice_items',
  NB_BOOKINGS = 'nb_bookings',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  DATE_JOINED = 'date_joined',
  COMPANY_NAME = 'company_name',
}
export enum MetaActivityMetadataIdentifierEnum {
  META_ACTIVITY_PK = 'meta_activity_pk',
  NAME = 'name',
  ARCHIVED = 'archived',
  NB_BOOKINGS = 'nb_bookings',
  NB_ATTENDANCE = 'nb_attendance',
  NB_NON_ATTENDANCE = 'nb_non_attendance',
  RATE_ATTENDANCE = 'rate_attendance',
  RATE_NON_ATTENDANCE = 'rate_non_attendance',
  CANCELED_BOOKINGS = 'canceled_bookings',
  CANCEL_RATE = 'cancel_rate',
  COMPANY_NAME = 'company_name',
}
export enum MetaActivityCoachMetadataIdentifierEnum {
  META_ACTIVITY_PK = 'meta_activity_pk',
  NAME = 'name',
  COACH = 'coach',
  NB_BOOKINGS = 'nb_bookings',
  NB_ATTENDANCE = 'nb_attendance',
  NB_NON_ATTENDANCE = 'nb_non_attendance',
  RATE_NON_ATTENDANCE = 'rate_non_attendance',
  RATE_ATTENDANCE = 'rate_attendance',
  CANCEL_RATE = 'cancel_rate',
  COMPANY_NAME = 'company_name',
}
export enum MetaActivityEstablishmentMetadataIdentifierEnum {
  META_ACTIVITY_PK = 'meta_activity_pk',
  NAME = 'name',
  ESTABLISHMENT = 'establishment',
  NB_BOOKINGS = 'nb_bookings',
  NB_ATTENDANCE = 'nb_attendance',
  NB_NON_ATTENDANCE = 'nb_non_attendance',
  RATE_NON_ATTENDANCE = 'rate_non_attendance',
  RATE_ATTENDANCE = 'rate_attendance',
  CANCEL_RATE = 'cancel_rate',
  COMPANY_NAME = 'company_name',
}
export enum OfferMetadataIdentifierEnum {
  OFFER_ID = 'offer_id',
  NAME = 'name',
  DATE_START = 'date_start',
  SUM_MARGIN_VALUE = 'sum_margin_value',
  DATE_START_DOW = 'date_start_dow',
  DATE_START_DATE = 'date_start_date',
  DISABLED = 'disabled',
  DATE_START_TIME = 'date_start_time',
  DURATION_MINUTE = 'duration_minute',
  COACH = 'coach',
  EMAIL = 'email',
  ESTABLISHMENT_TITLE = 'establishment_title',
  EFFECTIF = 'effectif',
  NB_ATTENDANCE = 'nb_attendance',
  NB_NON_ATTENDANCE = 'nb_non_attendance',
  COMPANY_NAME = 'company_name',
  ROLL_CALL_NEEDS_VALIDATION = 'roll_call_needs_validation',
  DATE_ROLL_CALL_LAST_MODIFIED = 'date_roll_call_last_modified',
}
export enum OnSpotPaymentMetadataIdentifierEnum {
  PAYMENT_IDENTIFIER = 'payment_identifier',
  PAYMENT_LEGAL_IDENTIFIER = 'payment_legal_identifier',
  AUTHOR = 'author',
  PAYMENT_DATE = 'payment_date',
  PAYMENT_DATE_DATE = 'payment_date_date',
  PAYMENT_DATE_TIME = 'payment_date_time',
  PAYMENT_PRICE = 'payment_price',
  PAYMENT_METHOD_READABLE_IDENTIFIER = 'payment_method_readable_identifier',
  PRODUCT_NAMES = 'product_names',
  PAYMENT_NOTE = 'payment_note',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  INVOICE_DATE_CREATED = 'invoice_date_created',
  BILLING_ESTABLISHMENT = 'billing_establishment',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
}
export enum PaymentSumupMetadataIdentifierEnum {
  INVOICE_PK = 'invoice_pk',
  DATE_SUMUP = 'date_sumup',
  PAYMENT_METHOD_TOTAL = 'payment_method_total',
  COMPANY_NAME = 'company_name',
}
export enum PaymentMetadataIdentifierEnum {
  PAYMENT_PK = 'payment_pk',
  PAYMENT_IDENTIFIER = 'payment_identifier',
  AUTHOR = 'author',
  PAYMENT_DATE = 'payment_date',
  PAYMENT_DATE_DATE = 'payment_date_date',
  PAYMENT_DATE_TIME = 'payment_date_time',
  PAYMENT_PRICE = 'payment_price',
  BSPORT_FEE = 'bsport_fee',
  PAYMENT_METHOD_READABLE_IDENTIFIER = 'payment_method_readable_identifier',
  PAYMENT_METHOD = 'payment_method',
  PRODUCT_NAMES = 'product_names',
  PAYOUT_IDENTIFIER = 'payout_identifier',
  PAYOUT_DATE_CREATED = 'payout_date_created',
  PAYMENT_ENGINE = 'payment_engine',
  PAYOUT_STATUS = 'payout_status',
  PAYMENT_NOTE = 'payment_note',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  ESTABLISHMENT = 'establishment',
  BILLING_ESTABLISHMENT = 'billing_establishment',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
  PAYMENT_LEGAL_IDENTIFIER = 'payment_legal_identifier',
}
export enum SubscriptionMetadataIdentifierEnum {
  INVOICE_PK = 'invoice_pk',
  PLANNEDINVOICE_PK = 'plannedinvoice_pk',
  FIRST_NAME = 'first_name',
  NOTE = 'note',
  LAST_NAME = 'last_name',
  PHONENUMBER = 'phonenumber',
  EMAIL = 'email',
  DATE = 'date',
  CONTRACT = 'contract',
  PAYMENT_PACK = 'payment_pack',
  PRICE = 'price',
  CREDITS = 'credits',
  PAYMENT_METHOD = 'payment_method',
  PAYMENT_STATUS = 'payment_status',
  NB_INTERVAL = 'nb_interval',
  BILLING_DATE_START_ANNOTATED = 'billing_date_start_annotated',
  DUE_DATE = 'due_date',
  PAID = 'paid',
  AMOUNT_DUE = 'amount_due',
  LAST_PAYMENT_DATE = 'last_payment_date',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
}
export enum PaymentByInstalmentsMetadataIdentifierEnum {
  PAYMENT_IDENTIFIER = 'payment_identifier',
  AUTHOR = 'author',
  INVOICE_DATE_CREATED = 'invoice_date_created',
  DUE_DATE = 'due_date',
  PAYMENT_PRICE = 'payment_price',
  BSPORT_FEE = 'bsport_fee',
  PAYMENT_STATUS = 'payment_status',
  PAYMENT_METHOD_READABLE_IDENTIFIER = 'payment_method_readable_identifier',
  PRODUCT_NAMES = 'product_names',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  COMPANY_NAME = 'company_name',
  BILLING_ESTABLISHMENT = 'billing_establishment',
  BILLING_GROUP = 'billing_group',
}
export enum PrivateBookingMetadataIdentifierEnum {
  PRIVATEBOOKING_PK = 'privatebooking_pk',
  MEMBER_PK = 'member_pk',
  SOURCE_DEVICE = 'source_device',
  PRIVATE_SERVICE_NAME = 'private_service_name',
  PRIVATE_SLOT_NAME = 'private_slot_name',
  DATE_START = 'date_start',
  IS_RECURRENT_BOOKING = 'is_recurrent_booking',
  DATE_CREATED = 'date_created',
  SLOT_DATE_END = 'slot_date_end',
  DATE_START_DATE = 'date_start_date',
  DATE_START_TIME = 'date_start_time',
  IS_UNPAID = 'is_unpaid',
  PRIVATE_PASS = 'private_pass',
  MARGIN_VALUE = 'margin_value',
  REMAINING_CREDITS = 'remaining_credits',
  BOOKING_STATUS_CODE = 'booking_status_code',
  WAS_REFUNDED = 'was_refunded',
  GENDER = 'gender',
  COACH = 'coach',
  ADDRESS = 'address',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  ESTABLISHMENT = 'establishment',
  COMPANY_NAME = 'company_name',
  BILLING_GROUP = 'billing_group',
  BILLING_ESTABLISHMENT = 'billing_establishment',
}
export enum PrivateServiceMetadataIdentifierEnum {
  PRIVATE_SERVICE_PK = 'private_service_pk',
  NAME = 'name',
  COACHES = 'coaches',
  NB_BOOKINGS = 'nb_bookings',
  CANCELED_BOOKINGS = 'canceled_bookings',
  COMPANY_NAME = 'company_name',
}
export enum ReferralGrantMetadataIdentifierEnum {
  REFERRING_MEMBER_PK = 'referring_member_pk',
  REFERRING_MEMBER_LAST_NAME = 'referring_member_last_name',
  REFERRING_MEMBER_FIRST_NAME = 'referring_member_first_name',
  REFERRING_MEMBER_EMAIL = 'referring_member_email',
  REFERRED_MEMBER_PK = 'referred_member_pk',
  REFERRED_MEMBER_LAST_NAME = 'referred_member_last_name',
  REFERRED_MEMBER_FIRST_NAME = 'referred_member_first_name',
  REFERRED_MEMBER_EMAIL = 'referred_member_email',
  REFERRED_MEMBER_REGISTRATION_DATE = 'referred_member_registration_date',
  REFERRED_DISCOUNT_USE_DATE = 'referred_discount_use_date',
  PURCHASED_PRODUCTS = 'purchased_products',
  REFERRED_DISCOUNT_APPLIED = 'referred_discount_applied',
  REFERRING_MEMBER_TOTAL_REWARD = 'referring_member_total_reward',
}
export enum ShopItemMetadataIdentifierEnum {
  SHOPITEM_PK = 'shopitem_pk',
  NAME = 'name',
  SUBSHOP_NAME = 'subshop_name',
  PRICE = 'price',
  SUPPLIER_PRICE = 'supplier_price',
  SALES = 'sales',
  CA = 'ca',
  STOCK_VARIATION = 'stock_variation',
  STOCK = 'stock',
  STOCK_AT_START = 'stock_at_start',
  STOCK_AT_END = 'stock_at_end',
  MARKETPLACE_ENABLED = 'marketplace_enabled',
  DESCRIPTION = 'description',
  COMPANY_NAME = 'company_name',
  SUBTITLE = 'subtitle',
  COLOR = 'color',
  SIZE = 'size',
  SKU = 'stock_keeping_unit',
  BARCODE = 'barcode',
  SUPPLIER_NAME = 'supplier_name',
  COST_OF_STOCK = 'cost_of_stock',
  COST_OF_SALE = 'cost_of_sale',
  GROSS_PROFIT = 'gross_profit',
}
export enum UnpaidPrivateBookingMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  PRIVATE_BOOKING_PK = 'private_booking_pk',
  PRIVATE_SERVICE_NAME = 'private_service_name',
  PRIVATE_SLOT_NAME = 'private_slot_name',
  DATE_START = 'date_start',
  SLOT_DATE_END = 'slot_date_end',
  DATE_START_DATE = 'date_start_date',
  DATE_START_TIME = 'date_start_time',
  COACH = 'coach',
  ADDRESS = 'address',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  GENDER = 'gender',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  COMPANY_NAME = 'company_name',
  BILLING_GROUP = 'billing_group',
  BILLING_ESTABLISHMENT = 'billing_establishment',
}
export enum VideoPurchaseMetadataIdentifierEnum {
  MEMBER_PK = 'member_pk',
  PK = 'pk',
  VIDEO_TITLE = 'video_title',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  EMAIL = 'email',
  PHONENUMBER = 'phonenumber',
  GENDER = 'gender',
  PAYMENT_PACK = 'payment_pack',
  PRICE = 'price',
  REMAINING_CREDITS = 'remaining_credits',
  COACH = 'coach',
  SCT_NAME = 'sct_name',
  CREDIT_PRICE = 'credit_price',
  DURATION_SECOND = 'duration_second',
  LAST_VIEW = 'last_view',
  VIEWS_UNIQUE = 'views_unique',
  IS_RENT = 'is_rent',
  INVOICE_DATE = 'invoice_date',
  EXPIRATION_DATE = 'expiration_date',
  ADDRESS = 'address',
  BILLING_GROUP = 'billing_group',
  COMPANY_NAME = 'company_name',
}

export enum VideoMetadataIdentifierEnum {
  VIDEO_PK = 'video_pk',
  NAME = 'name',
  SCT_NAME = 'sct_name',
  DURATION_SECOND = 'duration_second',
  COACH = 'coach',
  LEVEL_ACTIVITY = 'level_activity',
  VIDEO_STATUS = 'video_status',
  DATE_CREATED = 'date_created',
  VIEWS_TOTAL = 'views_total',
  VIEWS_UNIQUE = 'views_unique',
  CREDIT_PRICE = 'credit_price',
  PURCHASES = 'purchases',
  IS_RENT = 'is_rent',
  COMPANY_NAME = 'company_name',
}

export enum AccessMonitoringMetadataIdentifierEnum {
  MEMBER_FIRST_NAME = 'member_first_name',
  MEMBER_LAST_NAME = 'member_last_name',
  MEMBER_EMAIL = 'member_email',
  MEMBER_PHONENUMBER = 'member_phonenumber',
  MEMBER_GENDER = 'member_gender',
  VISIT_TIME = 'visit_time',
  VISIT_DATE = 'visit_date',
  MEMBER_MEMBERSHIP_ID = 'member_membership_id',
  LOCATION = 'location',
  ADDRESS = 'address',
  ADMISSION = 'admission',
  VISIT_REASON = 'visit_reason',
  UPDATED_STATUS = 'updated_status',
  INITIAL_STATUS = 'initial_status',
  ESTABLISHMENTS_NAMES = 'establishments_names',
  COMPANY_NAME = 'company_name',
  DOOR_ID = 'door_id',
  DOOR_DISTANCE = 'door_distance',
}
