export const STRIPE_CHECKOUT = 1;
export const NOTIFICATION_BOOKING_CANCELLED_BY_MANAGER = 3;
export const NOTIFICATION_CONSUMER_PAYMENT_PACK_CHECKOUT = 5;
export const NOTIFICATION_MEMBERSHIP_CREATION_WEB = 6;
export const NOTIFICATION_BOOKING_PASS_CHECKOUT = 7;
export const NOTIFICATION_BOOKING_PLUS_PASS_STRIPE_CHECKOUT = 8;
export const NOTIFICATION_BOOKING_OPTION_CONVERTIBLE = 9;
export const NOTIFICATION_BOOKING_OPTION_NOT_CONVERTIBLE_ANYMORE = 10;
export const NOTIFICATION_BOOKING_OPTION_CREATED = 12;
export const NOTIFICATION_BOOKING_OPTION_CANCELLED_BY_CONSUMER = 13;
export const NOTIFICATION_BOOKING_OPTION_CANCELLED_BY_MANAGER = 14;
export const NOTIFICATION_BOOKING_OPTION_KICKED = 300;
export const NOTIFICATION_OFFER_IN_BOOKING_MODIFIED = 16;
export const NOTIFICATION_BOOKING_NOT_REFUNDED = 17;
export const NOTIFICATION_BOOKING_REFUNDED = 18;
export const NOTIFICATION_BOOKING_CREATED = 21;
export const NOTIFICATION_BOOKING_CREATED_FOR_INVITEE_SEND_TO_HOST = 30;
export const NOTIFICATION_BOOKING_CREATED_FOR_INVITEE_SEND_TO_INVITEE = 31;
export const NOTIFICATION_MEMBERSHIP_CREATION_SAAS = 19;
export const NOTIFICATION_MEMBERSHIP_CREATION_LIGHT_SIGNUP = 32;
export const NOTIFICATION_SUBSCRIPTION_PAID_WITH_INTERNAL_ACCOUNT_BALANCE = 23;
export const NOTIFICATION_SUBSCRIPTION_CREATE = 24;
export const NOTIFICATION_SUBSCRIPTION_UPDATE_PAYMENT_METHOD = 25;
export const NOTIFICATION_SUBSCRIPTION_PAUSE = 26;
export const NOTIFICATION_SUBSCRIPTION_STOP = 27;
export const NOTIFICATION_SUBSCRIPTION_PAYMENT_RECEIVED = 28;
export const NOTIFICATION_BOOKING_BROADCAST = 29;

export const NOTIFICATION_PAYMENT_METHOD_EXPIRED_FIRST_WARNING = 200;
export const NOTIFICATION_PAYMENT_METHOD_EXPIRED_SECOND_WARNING = 201;

export const NOTIFICATION_MEMBERSHIP_PASSWORD_RESET = 301;
export const NOTIFICATION_MEMBERSHIP_EMAIL_VALIDATION = 302;
export const NOTIFICATION_MEMBERSHIP_ACCOUNTS_FUSION = 303;
export const NOTIFICATION_MEMBERSHIP_EMAIL_MODIFICATION_BY_MANAGER = 305;
export const NOTIFICATION_MEMBERSHIP_FUSION_ACCOUNTS_DIFFERENT_STUDIOS_FOR_NEW_EMAIL = 306;
export const NOTIFICATION_MEMBERSHIP_FUSION_ACCOUNTS_DIFFERENT_STUDIOS_FOR_OLD_EMAIL = 307;

export const NOTIFICATION_PRIVATE_BOOKING_CANCEL_NOT_REFUNDED_COACH = 400;
export const NOTIFICATION_PRIVATE_BOOKING_CANCEL_NOT_REFUNDED_CONSUMER = 450;
export const NOTIFICATION_PRIVATE_BOOKING_CANCEL_REFUNDED_COACH = 401;
export const NOTIFICATION_PRIVATE_BOOKING_CANCEL_REFUNDED_CONSUMER = 451;
export const NOTIFICATION_PRIVATE_BOOKING_CREATE_COACH = 402;
export const NOTIFICATION_PRIVATE_BOOKING_CREATE_CONSUMER = 452;
export const NOTIFICATION_PRIVATE_BOOKING_UPDATETIME_COACH = 403;
export const NOTIFICATION_PRIVATE_BOOKING_UPDATETIME_CONSUMER = 453;

export const NOTIFICATION_SUBSCRIPTION_FAILED_PAYMENT = 501;
export const NOTIFICATION_SUBSCRIPTION_PAYMENT_DISPUTED = 530;
export const NOTIFICATION_SUBSCRIPTION_PASS_AUTO_DISABLED = 515;
export const NOTIFICATION_SUBSCRIPTION_PAYMENT_FAILED_NO_RETRY = 510;
export const NOTIFICATION_SUBSCRIPTION_PAYMENT_FAIL_WILL_RETRY = 520;

export const NOTIFICATION_INVOICE_CREATE = 22;
export const NOTIFICATION_INVOICE_PDF_REQUESTED_BY_MEMBER = 20;

export const NOTIFICATION_GIFT_CARD_BUY_PRINTABLE = 801;

export const NOTIFICATION_PAYMENT_INSTALMENT_PREPARED = 987;
export const NOTIFICATION_RECURRENT_PRIVATE_BOOKING_NO_AVAILABILITY_COACH = 480;
export const NOTIFICATION_RECURRENT_PRIVATE_BOOKING_NO_AVAILABILITY_CONSUMER = 481;

export const NOTIFICATION_REPLACEMENT_REQUEST_TEACHER_FOUND = 901;
export const NOTIFICATION_REPLACEMENT_REQUEST_CLOSED = 902;
export const NOTIFICATION_REPLACEMENT_REQUEST_HAS_ANSWERED_BUT_OTHER_TEACHER_FOUND = 903;
export const NOTIFICATION_REPLACEMENT_REQUEST_CREATE_ON_TIME = 904;
export const NOTIFICATION_REPLACEMENT_REQUEST_CREATE_LATE = 905;
export const NOTIFICATION_REPLACEMENT_REQUEST_CLOSING_DATE_POSTPONED = 906;
export const NOTIFICATION_REPLACEMENT_REQUEST_ANWSER_HAS_BEEN_ACCEPTED = 907;

export const NOTIFICATION_OFFER_AUTO_DISCARD = 601;
export const NOTIFICATION_OFFER_AUTO_DISCARD_TO_STUDENT = 602;

export const NOTIFICATION_GROUPED_OFFERS_CANCELLED = 801;

export const NOTIFICATION_CONSUMER_PAYMENT_PACK_PENALTY_BLOCK_CPP = 701;
export const NOTIFICATION_CONSUMER_PAYMENT_PACK_PENALTY_ACCOUNT = 702;
export const NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_PENALTY_BLOCK = 703;
export const NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_PENALTY_CHARGE = 704;
export const NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_WARNING = 705;

export const NOTIFICATION_BOOKING_BROADCAST_TO_TEACHER = 101;
export const NOTIFICATION_BOOKING_CANCELLED_BY_MANAGER_TO_TEACHER = 102;
export const NOTIFICATION_OFFER_IN_BOOKING_MODIFIED_TO_TEACHER = 103;

export const NOTIFICATION_GIFTCARD_ACTIVATION = 304;
export const NOTIFICATION_PRINTABLE_GIFTCARD_PDF_EMAIL = 308;

export const NOTIFICATION_SPIVI_ACCOUNT_CREATED = 1001;
export const NOTIFICATION_SPIVI_PERFORMANCE = 1002;
export const NOTIFICATION_SPIVI_COACH_ACCOUNT_CREATED = 1003;

export const NOTIFICATION_REFERRAL_GRANT_CREATED = 1101;
export const NOTIFICATION_REFERRED_GRANT_CONSUMED = 1102;

export const NOTIFICATION_INSTALMENT_PAYMENT_PAYMENT_METHOD_ABOUT_TO_EXPIRE_FIRST_WARNING = 1200;
export const NOTIFICATION_INSTALMENT_PAYMENT_PAYMENT_METHOD_ABOUT_TO_EXPIRE_SECOND_WARNING = 1201;

export default {
  STRIPE_CHECKOUT,
  NOTIFICATION_BOOKING_CANCELLED_BY_MANAGER,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_CHECKOUT,
  NOTIFICATION_MEMBERSHIP_CREATION_WEB,
  NOTIFICATION_BOOKING_PASS_CHECKOUT,
  NOTIFICATION_BOOKING_PLUS_PASS_STRIPE_CHECKOUT,
  NOTIFICATION_BOOKING_OPTION_CONVERTIBLE,
  NOTIFICATION_BOOKING_OPTION_NOT_CONVERTIBLE_ANYMORE,
  NOTIFICATION_BOOKING_OPTION_CREATED,
  NOTIFICATION_BOOKING_OPTION_CANCELLED_BY_CONSUMER,
  NOTIFICATION_BOOKING_OPTION_CANCELLED_BY_MANAGER,
  NOTIFICATION_BOOKING_OPTION_KICKED,
  NOTIFICATION_OFFER_IN_BOOKING_MODIFIED,
  NOTIFICATION_INVOICE_CREATE,
  NOTIFICATION_INVOICE_PDF_REQUESTED_BY_MEMBER,
  NOTIFICATION_BOOKING_NOT_REFUNDED,
  NOTIFICATION_BOOKING_REFUNDED,
  NOTIFICATION_MEMBERSHIP_CREATION_SAAS,
  NOTIFICATION_MEMBERSHIP_CREATION_LIGHT_SIGNUP,
  NOTIFICATION_SUBSCRIPTION_CREATE,
  NOTIFICATION_SUBSCRIPTION_UPDATE_PAYMENT_METHOD,
  NOTIFICATION_SUBSCRIPTION_PAUSE,
  NOTIFICATION_SUBSCRIPTION_STOP,
  NOTIFICATION_SUBSCRIPTION_PAYMENT_RECEIVED,
  NOTIFICATION_BOOKING_BROADCAST,
  NOTIFICATION_PAYMENT_METHOD_EXPIRED_FIRST_WARNING,
  NOTIFICATION_PAYMENT_METHOD_EXPIRED_SECOND_WARNING,
  NOTIFICATION_MEMBERSHIP_PASSWORD_RESET,
  NOTIFICATION_MEMBERSHIP_EMAIL_VALIDATION,
  NOTIFICATION_MEMBERSHIP_ACCOUNTS_FUSION,
  NOTIFICATION_MEMBERSHIP_EMAIL_MODIFICATION_BY_MANAGER,
  NOTIFICATION_MEMBERSHIP_FUSION_ACCOUNTS_DIFFERENT_STUDIOS_FOR_NEW_EMAIL,
  NOTIFICATION_MEMBERSHIP_FUSION_ACCOUNTS_DIFFERENT_STUDIOS_FOR_OLD_EMAIL,
  NOTIFICATION_PRIVATE_BOOKING_CANCEL_NOT_REFUNDED_COACH,
  NOTIFICATION_PRIVATE_BOOKING_CANCEL_NOT_REFUNDED_CONSUMER,
  NOTIFICATION_PRIVATE_BOOKING_CANCEL_REFUNDED_COACH,
  NOTIFICATION_PRIVATE_BOOKING_CANCEL_REFUNDED_CONSUMER,
  NOTIFICATION_PRIVATE_BOOKING_CREATE_COACH,
  NOTIFICATION_PRIVATE_BOOKING_CREATE_CONSUMER,
  NOTIFICATION_PRIVATE_BOOKING_UPDATETIME_COACH,
  NOTIFICATION_PRIVATE_BOOKING_UPDATETIME_CONSUMER,
  NOTIFICATION_SUBSCRIPTION_FAILED_PAYMENT,
  NOTIFICATION_SUBSCRIPTION_PAYMENT_DISPUTED,
  NOTIFICATION_SUBSCRIPTION_PASS_AUTO_DISABLED,
  NOTIFICATION_SUBSCRIPTION_PAYMENT_FAILED_NO_RETRY,
  NOTIFICATION_SUBSCRIPTION_PAYMENT_FAIL_WILL_RETRY,
  NOTIFICATION_GIFT_CARD_BUY_PRINTABLE,
  NOTIFICATION_PAYMENT_INSTALMENT_PREPARED,
  NOTIFICATION_RECURRENT_PRIVATE_BOOKING_NO_AVAILABILITY_COACH,
  NOTIFICATION_RECURRENT_PRIVATE_BOOKING_NO_AVAILABILITY_CONSUMER,
  NOTIFICATION_REPLACEMENT_REQUEST_TEACHER_FOUND,
  NOTIFICATION_REPLACEMENT_REQUEST_CLOSED,
  NOTIFICATION_REPLACEMENT_REQUEST_HAS_ANSWERED_BUT_OTHER_TEACHER_FOUND,
  NOTIFICATION_REPLACEMENT_REQUEST_CREATE_ON_TIME,
  NOTIFICATION_REPLACEMENT_REQUEST_CREATE_LATE,
  NOTIFICATION_REPLACEMENT_REQUEST_CLOSING_DATE_POSTPONED,
  NOTIFICATION_REPLACEMENT_REQUEST_ANWSER_HAS_BEEN_ACCEPTED,
  NOTIFICATION_OFFER_AUTO_DISCARD,
  NOTIFICATION_OFFER_AUTO_DISCARD_TO_STUDENT,
  NOTIFICATION_GROUPED_OFFERS_CANCELLED,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_PENALTY_BLOCK_CPP,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_PENALTY_ACCOUNT,
  NOTIFICATION_BOOKING_BROADCAST_TO_TEACHER,
  NOTIFICATION_BOOKING_CANCELLED_BY_MANAGER_TO_TEACHER,
  NOTIFICATION_OFFER_IN_BOOKING_MODIFIED_TO_TEACHER,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_PENALTY_BLOCK,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_PENALTY_CHARGE,
  NOTIFICATION_CONSUMER_PAYMENT_PACK_NO_SHOW_WARNING,
  NOTIFICATION_GIFTCARD_ACTIVATION,
  NOTIFICATION_PRINTABLE_GIFTCARD_PDF_EMAIL,
  NOTIFICATION_SPIVI_ACCOUNT_CREATED,
  NOTIFICATION_SPIVI_PERFORMANCE,
  NOTIFICATION_SPIVI_COACH_ACCOUNT_CREATED,
  NOTIFICATION_REFERRAL_GRANT_CREATED,
  NOTIFICATION_REFERRED_GRANT_CONSUMED,
};

export enum NOTIFICATION_KIND {
  BIRTHDAY = 0,
  PRIVATE_BOOKING_CREATION = 1,
  BOOKING_CREATION = 2,
  CONSUMER_PAYMENT_PACK_TIME = 3,
  CONSUMER_PAYMENT_PACK_CREDIT = 4,
  PRIVATE_CONSUMER_PASS_TIME = 5,
  PRIVATE_CONSUMER_PASS_CREDIT = 6,
  SUBSCRIPTION_NOTIFICATION_CREATION = 7,
  SUBSCRIPTION_NOTIFICATION_FIRST_BILLING = 8,
  SUBSCRIPTION_NOTIFICATION_END = 9,
}

export enum PRIVATEBOOKING_EVENT_RULES {
  VALID = 0,
  CANCELLED_REFUNDED = 1,
  CANCELLED_NOT_REFUNDED = 2,
}

export enum BOOKING_EVENT_RULES {
  BOOKING_DEPRECATED = 0,
  ATTENDANCE_DEPRECATED = 1,
  CANCELLATION_DEPRECATED = 2,
  VALID_ATTENDANCE = 3,
  VALID_ABSENCE = 4,
  CANCELLED_REFUNDED = 5,
  CANCELLED_NOT_REFUNDED = 6,
}

export enum PAYMENT_PACK_EVENT_RULE {
  NOTIFICATION_TIME = 3,
  NOTIFICATION_CREDIT = 4,
}
