export const PAYMENT_ENGINE_BSPORT = 0;
export const PAYMENT_ENGINE_STRIPE = 1;
export const PAYMENT_ENGINE_PAYPAL = 2;

export const PAYMENT_GROUP_METHOD_IDENTIFIER_CASH = 0;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_CB = 1;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_SEPA = 2;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_CHECK = 3;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_HOLIDAY_CHECK = 4;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_AMEX = 5;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_DISPUTE = 6;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_TRANSFER = 7;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_OTHER = 8;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_BANCONTACT = 9;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_IDEAL = 10;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_SOFORT = 11;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_EPS = 12;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_GIROPAY = 13;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_MOBILEPAY = 14;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_CB_MANUAL = 15;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_DEBT = 14;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_BACS_DEBIT = 16;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_PAYPAL_WALLET = 17;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_TWINT = 18;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_APPLE_PAY = 19;
export const PAYMENT_GROUP_METHOD_IDENTIFIER_GOOGLE_PAY = 20;

export const REVERSE_ON_PAYMENT_METHOD = 0;
export const REVERSE_ON_DEBT = 1;
export const REVERSE_ON_NEW_PAYMENT_METHOD = 2;

// BE CAREEFULL TO PUT THE VALUE AND NOT THE CONSTANT as it break the widget
export const PAYMENT_GROUP_METHOD_BY_ENGINE = {
  // [PAYMENT_ENGINE_STRIPE]
  1: [
    1, // PAYMENT_GROUP_METHOD_IDENTIFIER_CB
    18, // PAYMENT_GROUP_METHOD_IDENTIFIER_TWINT
    2, // PAYMENT_GROUP_METHOD_IDENTIFIER_SEPA
    9, // PAYMENT_GROUP_METHOD_IDENTIFIER_BANCONTACT
    10, // PAYMENT_GROUP_METHOD_IDENTIFIER_IDEAL
    11, // PAYMENT_GROUP_METHOD_IDENTIFIER_SOFORT
    16, // PAYMENT_GROUP_METHOD_IDENTIFIER_BACS_DEBIT
  ],

  // PAYMENT_ENGINE_BSPORT
  0: [
    15, // PAYMENT_GROUP_METHOD_IDENTIFIER_CB_MANUAL
    0, // PAYMENT_GROUP_METHOD_IDENTIFIER_CASH
    3, // PAYMENT_GROUP_METHOD_IDENTIFIER_CHECK
    4, // PAYMENT_GROUP_METHOD_IDENTIFIER_HOLIDAY_CHECK
    5, // PAYMENT_GROUP_METHOD_IDENTIFIER_AMEX
    7, // PAYMENT_GROUP_METHOD_IDENTIFIER_TRANSFER
    8, // PAYMENT_GROUP_METHOD_IDENTIFIER_OTHER
    14, // PAYMENT_GROUP_METHOD_IDENTIFIER_OTHER
  ],
};

export const PAYMENT_INTENT_TYPE_INVOICE = 0;
export const PAYMENT_INTENT_TYPE_DEBT = 1;
export const PAYMENT_INTENT_TYPE_BASKET = 2;

export const PAYMENT_INTENT_STATUS_DRAFT = 0;
export const PAYMENT_INTENT_STATUS_PENDING_ACTION = 100;
export const PAYMENT_INTENT_STATUS_SUCCESS = 200;
export const PAYMENT_INTENT_STATUS_DISPUTED = 600;
export const PAYMENT_INTENT_STATUS_CANCELED = 300;
export const PAYMENT_INTENT_STATUS_PROCESSING = 400;
export const PAYMENT_INTENT_STATUS_PLANNED = 500;
export const PAYMENT_INTENT_STATUS_REQUIRES_ACTION = 150;

export const PENDING_PAYMENT_INTENT_OF_PAYMENT_GROUP_BLOCKS_OTHER_PAYMENT_GROUP_CREATION = 12102;
