export const EMAIL_RECIPIENT_UNKNOWN = -1;
export const EMAIL_RECIPIENT_PENDING = 0;
export const EMAIL_RECIPIENT_PROCESSED = 1;
export const EMAIL_RECIPIENT_DROPPED = 2;
export const EMAIL_RECIPIENT_DEFERRED = 3;
export const EMAIL_RECIPIENT_DELIVERED = 4;
export const EMAIL_RECIPIENT_BOUNCED = 5;
