export const REFERRED_AND_REFERRING_MEMBERS_INCOMPATIBLE = 33000;
export const REFERRING_MEMBER_UNEXISTING = 33001;
export const COMPANY_MEMBER_ALREADY_EXISTING = 33002;
export const TOO_HIGH_REFERRING_VOUCHER_CONSUMED = 33003;
export const REFERRAL_GRANT_LOCK_ACQUISITION_ERROR = 33004;
export const REFERRAL_GRANT_ASSIGNMENT_LOCK_ACQUISITION_ERROR = 33005;
export const REFERRAL_PROGRAM_DEACTIVATED = 33006;
export const WRONG_APPLICATION_TIME_LIMIT_UNIT = 33007;
