import {
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
  COMMUNICATION_KIND_SMS,
} from '@bsport/common/lib/master-data/communication-kind';
import {
  COMMUNICATION_CHANNEL_MESSAGE_DIRECT,
  COMMUNICATION_CHANNEL_NOTIFICATION,
  COMMUNICATION_CHANNEL_SESSION,
  COMMUNICATION_CHANNEL_SMARTLIST,
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
  COMMUNICATION_SEND_PARAMETER_AUTO,
  COMMUNICATION_SEND_PARAMETER_MANUAL,
} from '@bsport/common/lib/master-data/communication-filters';

// FILTER IDENTIFIERS
export const FILTER_IDENTIFIER_KIND = 100;
export const FILTER_IDENTIFIER_RECIPIENT = 101;
export const FILTER_IDENTIFIER_CHANNEL = 102;
export const FILTER_IDENTIFIER_SEND_PARAMETER = 103;

// ACTION TYPE
export const WRITE_EMAIL = 0;
export const WRITE_SMS = 1;
export const WRITE_PUSH_NOTIFICATION = 2;

// SEND MESSAGE ENABLING
export const CAN_NOT_SEND_BECAUSE_MISSING_RECIPIENTS = 0;
export const CAN_NOT_SEND_BECAUSE_MISSING_CONTENT = 1;
export const CAN_SEND_MESSAGE = 2;

// TEXTFIELD CONTAINER IDENTIFIER
export const TEXTFIELD_MAIL_TITLE = 0;
export const TEXTFIELD_MAIL_CONTENT = 1;
export const TEXTFIELD_SMS_CONTENT = 2;
export const TEXTFIELD_NOTIFICATION_TITLE = 3;
export const TEXTFIELD_NOTIFICATION_CONTENT = 4;

// PAGE CONTEXT
export const CONTEXT_COMMUNICATION = 200;
export const CONTEXT_NOTIFICATION = 201;
export const CONTEXT_SMARTLIST = 202;
export const CONTEXT_OFFER = 203;
export const CONTEXT_MEMBER = 204;

// PAGINATION
export const PAGINATION_SIZE = 8;

// CONSTANTS GATHERED BY CATEGORY
export const CHANNELS = [
  { key: COMMUNICATION_CHANNEL_SESSION, value: 'Session' },
  { key: COMMUNICATION_CHANNEL_NOTIFICATION, value: 'Notification' },
  { key: COMMUNICATION_CHANNEL_SMARTLIST, value: 'Smartlist' },
  { key: COMMUNICATION_CHANNEL_MESSAGE_DIRECT, value: 'Message direct' },
];

export const FILTER_CHANNELS = [
  COMMUNICATION_CHANNEL_SESSION,
  COMMUNICATION_CHANNEL_MESSAGE_DIRECT,
  COMMUNICATION_CHANNEL_NOTIFICATION,
  COMMUNICATION_CHANNEL_SMARTLIST,
];

export const FILTER_KINDS = [
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
  COMMUNICATION_KIND_SMS,
];

export const FILTER_RECIPIENTS = [
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
];

export const FILTER_SEND_PARAMETERS = [
  COMMUNICATION_SEND_PARAMETER_AUTO,
  COMMUNICATION_SEND_PARAMETER_MANUAL,
];
