// FILTER IDENTIFIERS
export const FILTER_IDENTIFIER_KIND = 100;
export const FILTER_IDENTIFIER_RECIPIENT = 101;
export const FILTER_IDENTIFIER_CHANNEL = 102;
export const FILTER_IDENTIFIER_SEND_PARAMETER = 103;
