import {
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
  COMMUNICATION_KIND_SMS,
} from '@bsport/common/lib/master-data/communication-kind';
import {
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
  COMMUNICATION_CHANNEL_SESSION,
  COMMUNICATION_CHANNEL_MARKETING_NOTIFICATION,
  COMMUNICATION_CHANNEL_NOTIFICATION_RULE,
  COMMUNICATION_CHANNEL_SMARTLIST,
  COMMUNICATION_CHANNEL_MESSAGE_DIRECT,
  COMMUNICATION_SEND_PARAMETER_AUTO,
  COMMUNICATION_SEND_PARAMETER_MANUAL,
  COMMUNICATION_SRC_OR_DST_SENT,
  COMMUNICATION_SRC_OR_DST_RECEIVED,
} from '@bsport/common/lib/master-data/communication-filters';

// CONTEXT
export const CONTEXT_NOTIFICATION = 201;
export const CONTEXT_SMARTLIST = 202;
export const CONTEXT_OFFER = 203;
export const CONTEXT_MEMBER = 204;

// AVATAR GROUP DISPLAY
export const MAX_DISPLAY = 4;

// --------- TO SEND MESSAGE ---------

// ACTION TYPE
export const WRITE_EMAIL = COMMUNICATION_KIND_EMAIL;
export const WRITE_SMS = COMMUNICATION_KIND_SMS;
export const WRITE_PUSH_NOTIFICATION = COMMUNICATION_KIND_PUSH_NOTIFICATION;

// SEND MESSAGE ENABLING
export const CAN_NOT_SEND_BECAUSE_MISSING_RECIPIENTS = 0;
export const CAN_NOT_SEND_BECAUSE_MISSING_CONTENT = 1;
export const CAN_NOT_SEND_BECAUSE_DIRECT_MEMBER_HAS_NOT_AN_EMAIL = 2;
export const CAN_NOT_SEND_BECAUSE_DIRECT_MEMBER_HAS_NOT_A_PHONE_NUMBER = 3;
export const CAN_SEND_MESSAGE = 4;

// SEND MESSAGE STATUS
export const COMMUNICATION_SENT_SENDING_PROCESSING = 1;
export const COMMUNICATION_SENT_SENDING_FAIL = 2;
export const COMMUNICATION_SENT_SENDING_SUCCESS = 3;

// TEXTFIELD CONTAINER IDENTIFIER
export const TEXTFIELD_MAIL_TITLE = 0;
export const TEXTFIELD_MAIL_CONTENT = 1;
export const TEXTFIELD_SMS_CONTENT = 2;
export const TEXTFIELD_NOTIFICATION_TITLE = 3;
export const TEXTFIELD_NOTIFICATION_CONTENT = 4;

// FILTERS IDENTIFIER
export const FILTER_IDENTIFIER_KIND = 100;
export const FILTER_IDENTIFIER_RECIPIENT = 101;
export const FILTER_IDENTIFIER_CHANNEL = 102;
export const FILTER_IDENTIFIER_SEND_PARAMETER = 103;
export const FILTER_IDENTIFIER_SRC_OR_DST = 104;

// PAGINATION
export const PAGINATION_SIZE_RECIPIENTS = 8;

// MAX LENGTH OF WRITERS
export const MAX_LENGTH_SMS = 160;
export const MAX_LENGTH_AUTOMATIC_SMS = 70;
export const MAX_LENGTH_PUSH_CONTENT = 200;
export const MAX_LENGTH_PUSH_TITLE = 25;

// -----------------------------------

// --------- TO FILTER THREAD ---------

export const FILTER_CHANNELS = {
  [COMMUNICATION_CHANNEL_SESSION]: 'offer_id',
  [COMMUNICATION_CHANNEL_MARKETING_NOTIFICATION]: 'marketing_notification_id',
  [COMMUNICATION_CHANNEL_SMARTLIST]: 'smartlist_id',
  [COMMUNICATION_CHANNEL_MESSAGE_DIRECT]: 'member_id',
  [COMMUNICATION_CHANNEL_NOTIFICATION_RULE]: 'notification_rule',
};

export const FILTER_KINDS = [
  COMMUNICATION_KIND_EMAIL,
  COMMUNICATION_KIND_SMS,
  COMMUNICATION_KIND_PUSH_NOTIFICATION,
];

export const FILTER_SEND_PARAMETERS = [
  COMMUNICATION_SEND_PARAMETER_MANUAL,
  COMMUNICATION_SEND_PARAMETER_AUTO,
];

export const FILTER_RECIPIENTS = [
  COMMUNICATION_RECIPIENT_BOOKINGS,
  COMMUNICATION_RECIPIENT_BOOKINGS_CANCELLED,
  COMMUNICATION_RECIPIENT_WAITING_LIST,
];

export const FILTER_SRC_OR_DST = [
  COMMUNICATION_SRC_OR_DST_SENT,
  COMMUNICATION_SRC_OR_DST_RECEIVED,
];
// ------------------------------------
