// @ts-nocheck
import {
  // CONSUMER PAYMENT PACK
  CONSUMER_PAYMENT_PACK_EVENTS,

  // BOOKING
  BOOKING_EVENTS,

  // PRIVATE BOOKING
  PRIVATE_BOOOKING_EVENTS,

  // BASKET
  BASKET_CREATED,
  BASKET_ADD_ITEM,
  BASKET_FINALIZED,

  // INVOICE
  INVOICE_EVENTS,
  // BILLING PLAN
  EVENT_BILLING_PLAN_CREATE,
  EVENT_BILLING_PLAN_PAUSE,
  EVENT_BILLING_PLAN_STOP,
  EVENT_BILLING_PLAN_RENEW,
} from '@bsport/common/lib/master-data/events';

export enum CadenceEventsEnum {
  // PURCHASE
  CADENCE_EVENT_PURCHASE_PAYMENT_PACK = CONSUMER_PAYMENT_PACK_EVENTS.CREATE,
  // CADENCE_EVENT_PURCHASE_PRIVATE_PASS = 2;

  // BOOKING & RIVATE BOOKING
  CADENCE_EVENT_BOOK_OFFER = BOOKING_EVENTS.CREATE,
  CADENCE_EVENT_ATTENDANCE_BOOKING = BOOKING_EVENTS.ATTENDANCE,
  CADENCE_EVENT_BOOK_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CREATE,
  CADENCE_EVENT_CANCELLED_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CANCEL,

  // BASKET
  CADENCE_EVENT_BASKET_CREATION = BASKET_CREATED,
  CADENCE_EVENT_BASKET_ADD_ITEM = BASKET_ADD_ITEM,
  CADENCE_EVENT_BASKET_FINALIZED = BASKET_FINALIZED,

  // INVOICE
  CADENCE_EVENT_INVOICE_CREATED = INVOICE_EVENTS.CREATE,

  // BILLING PLAN
  CADENCE_EVENT_BILLING_PLAN_CREATED = EVENT_BILLING_PLAN_CREATE,
  CADENCE_EVENT_BILLING_PLAN_PAUSED = EVENT_BILLING_PLAN_PAUSE,
  CADENCE_EVENT_BILLING_PLAN_STOPPED = EVENT_BILLING_PLAN_STOP,
  CADENCE_EVENT_BILLING_PLAN_RENEWED = EVENT_BILLING_PLAN_RENEW,
}

export enum CadenceEventCategoryEnum {
  // PURCHASE
  CADENCE_EVENT_PURCHASE_CATEGORY = 100,

  // BOOKING
  CADENCE_EVENT_BOOKING_CATEGORY = 101,

  // BASKET
  CADENCE_EVENT_BASKET_CATEGORY = 102,

  // INVOICE
  CADENCE_EVENT_INVOICE_CATEGORY = 103,

  // BILLING PLAN
  CADENCE_EVENT_BILLING_PLAN_CATEGORY = 104,
}

export const CADENCE_EVENT_ALL_CHOICES = Object.values(CadenceEventsEnum);

export const CADENCE_EVENT_GROUPED_BY_CATEGORY = {
  [CadenceEventCategoryEnum.CADENCE_EVENT_PURCHASE_CATEGORY]: [
    CadenceEventsEnum.CADENCE_EVENT_PURCHASE_PAYMENT_PACK,
    // CadenceEventsEnum.CADENCE_EVENT_PURCHASE_PRIVATE_PASS,
  ],
  [CadenceEventCategoryEnum.CADENCE_EVENT_BOOKING_CATEGORY]: [
    CadenceEventsEnum.CADENCE_EVENT_BOOK_OFFER,
    CadenceEventsEnum.CADENCE_EVENT_ATTENDANCE_BOOKING,
    CadenceEventsEnum.CADENCE_EVENT_BOOK_APPOINTMENT,
    CadenceEventsEnum.CADENCE_EVENT_CANCELLED_APPOINTMENT,
  ],
  [CadenceEventCategoryEnum.CADENCE_EVENT_BASKET_CATEGORY]: [
    CadenceEventsEnum.CADENCE_EVENT_BASKET_CREATION,
    CadenceEventsEnum.CADENCE_EVENT_BASKET_ADD_ITEM,
    CadenceEventsEnum.CADENCE_EVENT_BASKET_FINALIZED,
  ],
  [CadenceEventCategoryEnum.CADENCE_EVENT_INVOICE_CATEGORY]: [
    CadenceEventsEnum.CADENCE_EVENT_INVOICE_CREATED,
  ],
  [CadenceEventCategoryEnum.CADENCE_EVENT_BILLING_PLAN_CATEGORY]: [
    CadenceEventsEnum.CADENCE_EVENT_BILLING_PLAN_CREATED,
    CadenceEventsEnum.CADENCE_EVENT_BILLING_PLAN_PAUSED,
    CadenceEventsEnum.CADENCE_EVENT_BILLING_PLAN_STOPPED,
    CadenceEventsEnum.CADENCE_EVENT_BILLING_PLAN_RENEWED,
  ],
};

export enum RuleBetweenEntryEvent {
  AND_RULE_BETWEEN_ENTRY_EVENT = 1,
  OR_RULE_BETWEEN_ENTRY_EVENT = 2,
}
