import {
  // CONSUMER PAYMENT PACK
  CONSUMER_PAYMENT_PACK_EVENTS,

  // BOOKING
  BOOKING_EVENTS,

  // PRIVATE BOOKING
  PRIVATE_BOOOKING_EVENTS,

  // BASKET
  BASKET_CREATED,
  BASKET_ADD_ITEM,
  BASKET_FINALIZED,

  // INVOICE
  INVOICE_EVENTS,
  // BILLING PLAN
  EVENT_BILLING_PLAN_CREATE,
  EVENT_BILLING_PLAN_PAUSE,
  EVENT_BILLING_PLAN_STOP,
  EVENT_BILLING_PLAN_RENEW,
} from '@bsport/common/lib/master-data/events';

// Edge case below regarding string enums with computed values - Issue : https://gitlab.com/bsport/bsport-saas/-/issues/1714
// And ts-ignore not available by block : https://gitlab.com/bsport/bsport-saas/-/issues/1713
export enum Events {
  // PURCHASE
  // @ts-ignore
  CADENCE_EVENT_PURCHASE_PAYMENT_PACK = CONSUMER_PAYMENT_PACK_EVENTS.CREATE,

  // BOOKING & RIVATE BOOKING
  // @ts-ignore
  CADENCE_EVENT_BOOK_OFFER = BOOKING_EVENTS.CREATE,
  // @ts-ignore
  CADENCE_EVENT_ATTENDANCE_BOOKING = BOOKING_EVENTS.ATTENDANCE,
  // @ts-ignore
  CADENCE_EVENT_BOOK_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CREATE,
  // @ts-ignore
  CADENCE_EVENT_CANCELLED_APPOINTMENT = PRIVATE_BOOOKING_EVENTS.CANCEL,

  // BASKET
  // @ts-ignore
  CADENCE_EVENT_BASKET_CREATION = BASKET_CREATED,
  // @ts-ignore
  CADENCE_EVENT_BASKET_ADD_ITEM = BASKET_ADD_ITEM,
  // @ts-ignore
  CADENCE_EVENT_BASKET_FINALIZED = BASKET_FINALIZED,

  // INVOICE
  // @ts-ignore
  CADENCE_EVENT_INVOICE_CREATED = INVOICE_EVENTS.CREATE,

  // BILLING PLAN
  // @ts-ignore
  CADENCE_EVENT_BILLING_PLAN_CREATED = EVENT_BILLING_PLAN_CREATE,
  // @ts-ignore
  CADENCE_EVENT_BILLING_PLAN_PAUSED = EVENT_BILLING_PLAN_PAUSE,
  // @ts-ignore
  CADENCE_EVENT_BILLING_PLAN_STOPPED = EVENT_BILLING_PLAN_STOP,
  // @ts-ignore
  CADENCE_EVENT_BILLING_PLAN_RENEWED = EVENT_BILLING_PLAN_RENEW,
}

export enum EventsCategory {
  // PURCHASE
  CADENCE_EVENT_PURCHASE_CATEGORY = 100,

  // BOOKING
  CADENCE_EVENT_BOOKING_CATEGORY = 101,

  // BASKET
  CADENCE_EVENT_BASKET_CATEGORY = 102,

  // INVOICE
  CADENCE_EVENT_INVOICE_CATEGORY = 103,

  // BILLING PLAN
  CADENCE_EVENT_BILLING_PLAN_CATEGORY = 104,
}

export const CADENCE_EVENT_ALL_CHOICES = Object.values(Events);

export const CADENCE_EVENT_GROUPED_BY_CATEGORY: Record<
  EventsCategory,
  Events[]
> = {
  [EventsCategory.CADENCE_EVENT_PURCHASE_CATEGORY]: [
    Events.CADENCE_EVENT_PURCHASE_PAYMENT_PACK,
  ],
  [EventsCategory.CADENCE_EVENT_BOOKING_CATEGORY]: [
    Events.CADENCE_EVENT_BOOK_OFFER,
    Events.CADENCE_EVENT_ATTENDANCE_BOOKING,
    Events.CADENCE_EVENT_BOOK_APPOINTMENT,
    Events.CADENCE_EVENT_CANCELLED_APPOINTMENT,
  ],
  [EventsCategory.CADENCE_EVENT_BASKET_CATEGORY]: [
    Events.CADENCE_EVENT_BASKET_CREATION,
    Events.CADENCE_EVENT_BASKET_ADD_ITEM,
    Events.CADENCE_EVENT_BASKET_FINALIZED,
  ],
  [EventsCategory.CADENCE_EVENT_INVOICE_CATEGORY]: [
    Events.CADENCE_EVENT_INVOICE_CREATED,
  ],
  [EventsCategory.CADENCE_EVENT_BILLING_PLAN_CATEGORY]: [
    Events.CADENCE_EVENT_BILLING_PLAN_CREATED,
    Events.CADENCE_EVENT_BILLING_PLAN_PAUSED,
    Events.CADENCE_EVENT_BILLING_PLAN_STOPPED,
    Events.CADENCE_EVENT_BILLING_PLAN_RENEWED,
  ],
};

export enum RuleBetweenEntryEvent {
  AND_RULE_BETWEEN_ENTRY_EVENT = 1,
  OR_RULE_BETWEEN_ENTRY_EVENT = 2,
}
