import {
  CADENCE_EVENT_GROUPED_BY_CATEGORY,
  RuleBetweenEntryEvent,
  CADENCE_EVENT_ALL_CHOICES,
  CADENCE_EVENT_CATEGORY_CHOICES,
  Events,
  EventsCategory,
} from './event';

import {
  CADENCE_MARKETING_ACTION_CHOICES,
  CADENCE_MARKETING_ACTION_MAX_NUMBER,
  MarketingActions,
  MarketingActionKind,
} from './marketing_actions';

import {
  TriggerIdentifier,
  DestinationKind,
  DestinationStatus,
  TriggerKind,
  DESTINATION_KIND_CHOICES,
  DESTINATION_STATUS_CHOICES,
  LOST_OUTPUT_TIMEOUT_TRIGGER_ID,
  TIMEOUT_TRIGGER_INPUT_WIDTH,
  TRIGGER_DEFAULT_ICON,
  TRIGGER_DEFAULT_TIMEOUT_DAYS,
  TRIGGER_FORM_DEFAULT_HEIGHT,
  TRIGGER_KIND_CHOICES,
  TRIGGER_TEMPORARY_ID,
} from './triggers';

import {
  HandleTypeChoices,
  DEFAULT_X_FOR_ENTRYSTEP,
  DEFAULT_X_FOR_EXIT,
  DEFAULT_X_FOR_INNERSTEP,
  DEFAULT_X_FOR_TRIGGER,
  MAX_LENGTH_CADENCE_STEP_NAME,
  RIGHT_HANDLE_STYLE,
} from './steps';

import {
  InitialConfigurationStep,
  DEFAULT_NODE_GAP,
  ELEMENT_MAX_WIDTH,
  ELEMENT_WIDTH,
  HEADER_HEIGHT,
  OUTPUT_SECTION_HEIGHT,
  OUTPUT_SECTION_WIDTH,
} from './graph';

import { FilterIdentifier } from './filters';

import { CadencePanelMode } from './panel';

import { SequentialMarketingColors } from './colors';

import { SequentialMarketingWorkflowMetricsSizes } from './workflowMetrics';

import {
  AUDIENCE_FEATURE_NAME,
  AUDIENCE_WORKFLOW_NAME,
  AUDIENCE_WORKFLOW_NAME_PLURAL,
} from './keywords';

export {
  // EVENT
  EventsCategory,
  Events,
  RuleBetweenEntryEvent,
  CADENCE_EVENT_GROUPED_BY_CATEGORY,
  CADENCE_EVENT_ALL_CHOICES,
  CADENCE_EVENT_CATEGORY_CHOICES,
  // MARKETING ACTIONS
  MarketingActions,
  MarketingActionKind,
  CADENCE_MARKETING_ACTION_CHOICES,
  CADENCE_MARKETING_ACTION_MAX_NUMBER,
  // TRIGGER
  TriggerIdentifier,
  DestinationKind,
  DestinationStatus,
  TriggerKind,
  DESTINATION_KIND_CHOICES,
  DESTINATION_STATUS_CHOICES,
  LOST_OUTPUT_TIMEOUT_TRIGGER_ID,
  TIMEOUT_TRIGGER_INPUT_WIDTH,
  TRIGGER_DEFAULT_ICON,
  TRIGGER_DEFAULT_TIMEOUT_DAYS,
  TRIGGER_FORM_DEFAULT_HEIGHT,
  TRIGGER_KIND_CHOICES,
  TRIGGER_TEMPORARY_ID,
  // FILTER
  FilterIdentifier,
  // PANEL
  CadencePanelMode,
  // COLORS
  SequentialMarketingColors,
  // WORKFLOW ANALYISIS
  SequentialMarketingWorkflowMetricsSizes,
  // STEPS
  HandleTypeChoices,
  DEFAULT_X_FOR_ENTRYSTEP,
  DEFAULT_X_FOR_EXIT,
  DEFAULT_X_FOR_INNERSTEP,
  DEFAULT_X_FOR_TRIGGER,
  MAX_LENGTH_CADENCE_STEP_NAME,
  RIGHT_HANDLE_STYLE,
  // GRAPH
  InitialConfigurationStep,
  DEFAULT_NODE_GAP,
  ELEMENT_MAX_WIDTH,
  ELEMENT_WIDTH,
  HEADER_HEIGHT,
  OUTPUT_SECTION_HEIGHT,
  OUTPUT_SECTION_WIDTH,
  AUDIENCE_FEATURE_NAME,
  AUDIENCE_WORKFLOW_NAME,
  AUDIENCE_WORKFLOW_NAME_PLURAL,
};

export const SEQUENTIAL_MARKETING_AUTHORIZED_COMPANY_IDS = [498];
