export enum CadenceMarketingActionsEnum {
  CADENCE_MARKETING_ACTION_WRITTEN_EMAIL = 1,
  CADENCE_MARKETING_ACTION_SMS = 2,
  CADENCE_MARKETING_ACTION_PUSH_NOTIFICATION = 3,
  CADENCE_MARKETING_ACTION_TAG_MANAGEMENT = 4,
  CADENCE_MARKETING_ACTION_EMAIL_TEMPLATE = 5,
}

export const CADENCE_MARKETING_ACTION_CHOICES = [
  CadenceMarketingActionsEnum.CADENCE_MARKETING_ACTION_WRITTEN_EMAIL,
  CadenceMarketingActionsEnum.CADENCE_MARKETING_ACTION_SMS,
  CadenceMarketingActionsEnum.CADENCE_MARKETING_ACTION_PUSH_NOTIFICATION,
  CadenceMarketingActionsEnum.CADENCE_MARKETING_ACTION_TAG_MANAGEMENT,
  CadenceMarketingActionsEnum.CADENCE_MARKETING_ACTION_EMAIL_TEMPLATE,
];
