export enum MarketingActionKind {
  COMMUNICATION = 'COMMUNICATION',
  TAG = 'TAG',
}

export const CADENCE_MARKETING_ACTION_KIND_CHOICES = [
  MarketingActionKind.COMMUNICATION,
  MarketingActionKind.TAG,
];

export enum MarketingActions {
  CADENCE_MARKETING_ACTION_WRITTEN_EMAIL = 1,
  CADENCE_MARKETING_ACTION_SMS = 2,
  CADENCE_MARKETING_ACTION_PUSH_NOTIFICATION = 3,
  CADENCE_MARKETING_ACTION_TAG_MANAGEMENT = 4,
  CADENCE_MARKETING_ACTION_EMAIL_TEMPLATE = 5,
}

export const CADENCE_MARKETING_ACTION_CHOICES = [
  MarketingActions.CADENCE_MARKETING_ACTION_WRITTEN_EMAIL,
  MarketingActions.CADENCE_MARKETING_ACTION_SMS,
  MarketingActions.CADENCE_MARKETING_ACTION_PUSH_NOTIFICATION,
  MarketingActions.CADENCE_MARKETING_ACTION_TAG_MANAGEMENT,
  MarketingActions.CADENCE_MARKETING_ACTION_EMAIL_TEMPLATE,
];

export const CADENCE_COMMUNICATION_FIELD_HEIGHT = 5;

export const CADENCE_MARKETING_ACTION_MAX_NUMBER = 5;
