export enum CadencePanelMode {
  CADENCE_PANEL_INITIAL,
  CADENCE_PANEL_INTIAL_PARAMETERS,
  CADENCE_PANEL_ENTRY_PARAMETERS,
  CADENCE_PANEL_WIN_PARAMETERS,
  CADENCE_PANEL_LOSE_PARAMETERS,
  CADENCE_PANEL_NEW_STEP,
  CADENCE_PANEL_MARKETING_ACTIONS,
  CADENCE_PANEL_EDIT_TRIGGER,
  CADENCE_EDIT_STEP,
}
