import { BASKET_LOCK_ACQUISITION_FAILURE } from './lock';
import { OFFER_WAITING_LIST_NO_USABLE_CONSUMER_PAYMENT_PACK } from './waitinglist-can-not-be-joined';

export const OFFER_BOOKABLE_STATUS_CLOSE_TOO_SOON = 1;
export const OFFER_BOOKABLE_STATUS_CLOSE_TOO_LATE = 2;
export const OFFER_BOOKABLE_STATUS_FULL = 3;
export const OFFER_BOOKABLE_STATUS_LOCKED = 4;
export const OFFER_BOOKABLE_STATUS_ALREADY_BOOKED = 5;
export const OFFER_BOOKABLE_STATUS_TOO_MANY_MALE = 6;
export const OFFER_BOOKABLE_STATUS_TOO_MANY_FEMALE = 7;
export const OFFER_BOOKABLE_STATUS_TOO_MANY_IN_FUTURE = 9;

export const EXCEPTION_BOOKING_MEMBERS_DO_NOT_SHARE_A_RELATIONSHIP = 19058;
export const EXCEPTION_BOOKING_PAYMENT_PACK_IS_NOT_SHARED = 19059;

export const PAYMENT_COMBO_CANT_BE_BOUGHT_HAS_REACHED_MAX_PURCHASE = 1114;
export const PAYMENT_COMBO_CANT_BE_BOUGHT_NEW_ONLY_ONLY = 1113;
export const PAYMENT_COMBO_CANT_BE_BOUGHT_DATE_EXPIRED = 1122;

export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_NEW_MEMBER_ONLY = 2002;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_MAX_PURCHASE_REACHED = 2003;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_MANAGER_ONLY = 2004;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DISABLED = 2005;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_VALIDITY_DATERANGE = 2006;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_INCOMPATIBLE_WITH_OFFER = 2007;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ACTIVITY_INCOMPATIBLE = 2008;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_SCT_INCOMPATIBLE = 2009;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ESTABLISHMENT_INCOMPATIBLE = 2010;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_VOD_ONLY = 2011;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_BAD_COMPANY = 2012;

export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_MAXOUT_DAY = 2014;
export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_MAXOUT_WEEK = 2015;
export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_MAXOUT_MONTH = 2016;
export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_MAXOUT_YEAR = 2017;

export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_ENOUGH_CREDIT = 2018;
export const CONSUMER_PAYMENT_PACK_CAN_NOT_BOOK_DISABLED = 2019;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DATES_NOT_COMPATIBLE = 2020;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_BOOKING = 2021;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_ATTENDANCE = 2022;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_HAS_EXPIRED = 2023;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DATE_EXPIRED = 2025;
export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_INCOMPATIBLE_WITH_OFF_PEAK_SCHEDULE = 2027;

export const CONSUMER_PAYMENT_PACK_REFUND_AMOUNT_EXCEEDS_PURCHASE = 2029;
export const CONSUMER_PAYMENT_PACK_REFUND_CREDITS_EXCEED_PASS = 2030;
export const CONSUMER_PAYMENT_PACK_REFUND_LOCK_ACQUISITION_ERROR = 2031;

export const SPOT_NOT_AVAILABLE = 8001;

export const PRIVATE_SLOT_ALREADY_BOOKED = 11106;

export const PRIVATE_PASS_CAN_NOT_BOOK_SERVICE_NOT_COMPATIBLE = 11107;
export const PRIVATE_PASS_CAN_NOT_BOOK_ENOUGH_CREDIT = 11108;
export const PRIVATE_PASS_CAN_NOT_BOOK_LATER_FIRST_BOOKING = 11109;
export const PRIVATE_PASS_CAN_NOT_BOOK_HAS_EXPIRED = 11110;
export const PRIVATE_PASS_CAN_NOT_BOOK_DATES_NOT_COMPATIBLE = 11111;
export const PRIVATE_PASS_CAN_NOT_BE_BOUGHT_DATE_EXPIRED = 11114;
export const CONSUMER_PRIVATE_PASS_CAN_NOT_BOOK_INCOMPATIBLE_TAGS = 11116;
export const PRIVATE_PASS_CAN_NOT_BE_BOUGHT_BOOKING_HAS_INCOMPATIBLE_TAGS = 11117;
export const CONSUMER_PRIVATE_PASS_CAN_NOT_BOOK_COACH_UNAVAILABLE = 11128;
export const CONSUMER_PRIVATE_PASS_CAN_NOT_BOOK_ESTABLISHMENT_UNAVAILABLE = 11129;

export const OFFER_WAITING_LIST_STATUS_FULL = 6002;
export const OFFER_WAITING_LIST_STATUS_ALREADY_BOOKED = 6003;
export const OFFER_WAITING_LIST_STATUS_CONVERTIBLE = 6004;

export const GIFTCARD_CAN_NOT_BE_BOUGHT_DISABLED = 45004;
export const GIFTCARD_CAN_NOT_BE_BOUGHT_MANAGER_ONLY = 45005;

export const SHOP_ITEM_CAN_NOT_BE_BOUGHT_NOT_ENOUGH_STOCK = 10001;

export const OFFER_CAN_NOT_BE_BOUGHT_ERROR_CODES = [
  OFFER_BOOKABLE_STATUS_CLOSE_TOO_SOON,
  OFFER_BOOKABLE_STATUS_CLOSE_TOO_LATE,
  OFFER_BOOKABLE_STATUS_FULL,
  OFFER_BOOKABLE_STATUS_LOCKED,
  OFFER_BOOKABLE_STATUS_ALREADY_BOOKED,
  OFFER_BOOKABLE_STATUS_TOO_MANY_MALE,
  OFFER_BOOKABLE_STATUS_TOO_MANY_FEMALE,
  SPOT_NOT_AVAILABLE,
  OFFER_BOOKABLE_STATUS_TOO_MANY_IN_FUTURE,
  PRIVATE_SLOT_ALREADY_BOOKED,
];

export const PAYMENT_COMBO_CAN_NOT_BE_BOUGHT_ERROR_CODES = [
  PAYMENT_COMBO_CANT_BE_BOUGHT_HAS_REACHED_MAX_PURCHASE,
  PAYMENT_COMBO_CANT_BE_BOUGHT_NEW_ONLY_ONLY,
  PAYMENT_COMBO_CANT_BE_BOUGHT_DATE_EXPIRED,
];

export const PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ERROR_CODES = [
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_NEW_MEMBER_ONLY,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_MAX_PURCHASE_REACHED,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_MANAGER_ONLY,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DISABLED,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_VALIDITY_DATERANGE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_INCOMPATIBLE_WITH_OFFER,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ACTIVITY_INCOMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_SCT_INCOMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ESTABLISHMENT_INCOMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_VOD_ONLY,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_BAD_COMPANY,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DATES_NOT_COMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_BOOKING,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_ATTENDANCE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_HAS_EXPIRED,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_DATE_EXPIRED,
];

export const PAYMENT_PACK_INCOMPATIBLE_WITH_META_ACTIVITY = [
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ACTIVITY_INCOMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_SCT_INCOMPATIBLE,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ESTABLISHMENT_INCOMPATIBLE,
];

export const PAYMENT_PACK_INCOMPATIBLE_BEFORE_FIRST_ACTION = [
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_BOOKING,
  PAYMENT_PACK_CAN_NOT_BE_BOUGHT_LATER_FIRST_ATTENDANCE,
];

export const BOOKING_OPTION_CAN_NOT_REGISTER_ERROR_CODES = [
  OFFER_WAITING_LIST_STATUS_FULL,
  OFFER_WAITING_LIST_STATUS_ALREADY_BOOKED,
  OFFER_WAITING_LIST_STATUS_CONVERTIBLE,
];

export const GIFTCARD_CAN_NOT_BE_BOUGHT_ERROR_CODES = [
  GIFTCARD_CAN_NOT_BE_BOUGHT_DISABLED,
  GIFTCARD_CAN_NOT_BE_BOUGHT_MANAGER_ONLY,
];

export const ALL_ERROR_CODES = [
  ...OFFER_CAN_NOT_BE_BOUGHT_ERROR_CODES,
  ...PAYMENT_COMBO_CAN_NOT_BE_BOUGHT_ERROR_CODES,
  ...BOOKING_OPTION_CAN_NOT_REGISTER_ERROR_CODES,
  ...PAYMENT_PACK_CAN_NOT_BE_BOUGHT_ERROR_CODES,
  ...GIFTCARD_CAN_NOT_BE_BOUGHT_ERROR_CODES,
  SHOP_ITEM_CAN_NOT_BE_BOUGHT_NOT_ENOUGH_STOCK,
  BASKET_LOCK_ACQUISITION_FAILURE,
  PRIVATE_PASS_CAN_NOT_BE_BOUGHT_DATE_EXPIRED,
  OFFER_WAITING_LIST_NO_USABLE_CONSUMER_PAYMENT_PACK,
];

export default ALL_ERROR_CODES;
