export const NO_EDITION_OF_POS_MEMBER = 68000;
export const LEAD_MANAGEMENT_IMPORT_LOCK_ACQUISITION_ERROR = 71000;
export const LEAD_MANAGEMENT_IMPORT_WRONG_NUMBER_OF_COLUMNS_ERROR = 71001;
export const LEAD_MANAGEMENT_IMPORT_MAXIMUM_NUMBER_OF_ROWS_ERROR = 71002;
