export const EMAIL_TEMPLATE_MISSING_REQUIRED_TAGS = 19000;
export const FORM_VALIDATION_MISSING_REQUIRED_TAGS = 19001;
export const NOTIFICATION_RULE_INVALID_FIELD_VALUE = 19002;
export const FORM_VALIDATION_INVALID_FIELD_VALUE = 19003;
