export const INVOICE_NO_REFUND_ON_INTERAC_PAYMENT_ERROR_CODE = 14100;
export const INVOICE_NO_REFUND_ON_TYPE_EMPTY_CONTAINER = 14101;
export const CANNOT_REFUND_INVOICE_EXCEPTION_ERROR_CODE = 14102;
export const INVOICE_NO_REFUND_ON_SAME_PAYMENT_METHOD_IF_NO_ONLINE_PAYMENT = 14103;
export const INVOICE_NO_MANUAL_REFUND_ON_PENDING_PAYMENT = 14104;
export const INVOICE_NO_DEBT_REFUND_ON_PENDING_PAYMENT = 14105;
export const INVOICE_NO_REFUND_ON_SEPA_PAYMENT_OLDER_THAN_SIX_MONTHS = 14106;
export const CANNOT_REFUND_INVOICE_DISABLED_FOR_BO_ERROR_CODE = 14111;
export const CANNOT_REFUND_INVOICE_INSUFFICIENT_STRIPE_BALANCE_ERROR_CODE = 14112;
export const PAYMENT_DISABLED = 12909;
export const PENDING_PAYMENT_ATTEMPT_OF_PAYMENT_GROUP_BLOCKS_OTHER_PAYMENT_GROUP_CREATION = 12102;
export const PAYMENT_GROUP_UNPROCESSABLE_EXCEPTION = 12107;
export const PAYMENT_GROUP_LOCK_ACQUISITION_ERROR = 12108;
export const PAYMENT_ATTEMPT_EXECUTION_FAILED = 12109;
export const PAYMENT_GROUP_PRICE_INCONSISTENCY = 12110;
export const PAYPAL_EXCEPTION = 35000;
export const PAYPAL_PAYER_ACCOUNT_ISSUE = 35006;
export const PAYPAL_ACCOUNT_ALREADY_LINKED_TO_OTHER_COMPANY = 35009;
export const PAYPAL_PAYER_CARD_EXPIRED = 35012;
export const PAYPAL_REDIRECT_PAYER_FOR_ALTERNATE_FUNDING = 35013;
export const PAYPAL_API_EXCEPTION = 35015;
export const PAYPAL_REFUND_INSUFFICIENT_FUNDS = 35024;

export const PAYMENT_EXECUTION_ERROR_CODES = [
  PAYMENT_GROUP_UNPROCESSABLE_EXCEPTION,
  PAYMENT_GROUP_LOCK_ACQUISITION_ERROR,
  PAYMENT_ATTEMPT_EXECUTION_FAILED,
  PAYMENT_GROUP_PRICE_INCONSISTENCY,
  PAYPAL_EXCEPTION,
  PAYPAL_API_EXCEPTION,
  PENDING_PAYMENT_ATTEMPT_OF_PAYMENT_GROUP_BLOCKS_OTHER_PAYMENT_GROUP_CREATION,
  PAYPAL_PAYER_ACCOUNT_ISSUE,
  PAYPAL_PAYER_CARD_EXPIRED,
  PAYPAL_REDIRECT_PAYER_FOR_ALTERNATE_FUNDING,
];

export default {
  INVOICE_NO_REFUND_ON_INTERAC_PAYMENT_ERROR_CODE,
  INVOICE_NO_REFUND_ON_TYPE_EMPTY_CONTAINER,
  CANNOT_REFUND_INVOICE_EXCEPTION_ERROR_CODE,
  PENDING_PAYMENT_ATTEMPT_OF_PAYMENT_GROUP_BLOCKS_OTHER_PAYMENT_GROUP_CREATION,
  PAYMENT_GROUP_UNPROCESSABLE_EXCEPTION,
  PAYMENT_GROUP_LOCK_ACQUISITION_ERROR,
  PAYMENT_ATTEMPT_EXECUTION_FAILED,
  PAYMENT_GROUP_PRICE_INCONSISTENCY,
  PAYPAL_PAYER_ACCOUNT_ISSUE,
  PAYPAL_PAYER_CARD_EXPIRED,
  PAYPAL_EXCEPTION,
  PAYPAL_API_EXCEPTION,
  PAYPAL_REDIRECT_PAYER_FOR_ALTERNATE_FUNDING,
  PAYMENT_EXECUTION_ERROR_CODES,
  PAYPAL_ACCOUNT_ALREADY_LINKED_TO_OTHER_COMPANY,
};
