export const SPIVI_UPSELL_NOT_ACTIVATED_EXCEPTION = 21000;
export const NO_ROOM_PLAN_SELECTED_EXCEPTION = 21001;
export const NO_SPIVI_BOX_ID_FOR_ROOM_PLAN_EXCEPTION = 21002;
export const SPIVI_EVENT_DURATION_EXCEPTION = 21003;
export const SPIVI_DOUBLE_BOOKING_ACTIVATION_EXCEPTION = 21004;

export default {
  SPIVI_UPSELL_NOT_ACTIVATED_EXCEPTION,
  NO_ROOM_PLAN_SELECTED_EXCEPTION,
  NO_SPIVI_BOX_ID_FOR_ROOM_PLAN_EXCEPTION,
  SPIVI_EVENT_DURATION_EXCEPTION,
  SPIVI_DOUBLE_BOOKING_ACTIVATION_EXCEPTION,
};
