.Build and deploy Base:
  image: ${REGISTRY_ENDPOINT}/bsport/bsport-saas-builder:${CI_COMMIT_REF_NAME}
  stage: build-deploy
  retry:
    max: 2
  # cache:
  #   files:
  #     - yarn.lock
  #   paths:
  #       - "$YARN_CACHE_DIR"
  #       - "$CYPRESS_CACHE_FOLDER/node_modules"
  #       - node_modules
  script:
    - mv /app/node_modules .
    - yarn install --frozen-lockfile # just to be sure
    - echo "FAILED" > .job_status
    - VERSION=`echo "$(cat ./VERSION)"`
    - echo "Preparing VERSION:${VERSION} on ${ENVIRONMENT}"
    - echo "export default '`date +%F+%H+%M`';" > src/release-date.js
    - echo "export default '$VERSION';" > src/release.js
    - echo "\"$VERSION\"" > public/version.json
    - VERSION_SHA="${VERSION}-${CI_COMMIT_SHORT_SHA}"
    - echo "export default '$VERSION_SHA';" > src/release-sha.js
    - yarn updateTranslation
    - yarn build
    - mv envs/$ENVIRONMENT build/env.js
    - export SENTRY_NO_PROGRESS_BAR=1
    - ./scripts/prepare-sentry-release.sh $VERSION_SHA $FRONTEND_URL
    - rm ./build/static/js/*.js.map
    - aws s3 cp ./build/ $S3_BUCKET --recursive --only-show-errors $ACL_PARAM
    - scripts/invalidate-cloudfront.sh $CLOUDFRONT_ID $CLOUDFRONT_INVALIDATION_TOKEN $CLOUDFRONT_INVALIDATION_LAMBDA_URL
    - scripts/prepare-sentry-deploy.sh $VERSION_SHA $ENVIRONMENT
    - echo "SUCCESS" > .job_status
    - cat .job_status

  after_script:
    - STATUS=`echo "$(cat .job_status)"`
    - echo "$STATUS"
    - cat .job_status
    - export STATUS
    - '[[ "$STATUS" = "SUCCESS" ]] && COLOR="#36a64f" || COLOR="#E00201"'
    - '[[ "$STATUS" = "SUCCESS" ]] && SUCCESS_ICON="https://pluspng.com/img-png/success-png-success-icon-image-23194-400.png" || SUCCESS_ICON="http://www.pngall.com/wp-content/uploads/2016/06/Fail-Stamp-PNG-Clipart.png"'
    - export SUCCESS_ICON

    - VERSION=`echo "$(cat ./VERSION)"`
    - '[[ $VERSION != $OLD_VERSION ]] && CHANGELOG=`git grep -B 200 ${OLD_VERSION} CHANGELOG.md | grep -A ${VERSION} || echo="Unable to find release note";` || CHANGELOG="Technical release";'
    - export CHANGELOG

    - envsubst < ./slack_template.json > slack_template2.json
    - cat slack_template2.json
    - 'curl -s -d @slack_template2.json --header "Content-Type: application/json" "${SLACK_WEBHOOK_URL}" || exit 0'

Buid Deploy Staging:
  extends: .Build and deploy Base
  only:
    refs:
      - master
  variables:
    ENVIRONMENT: staging
    FRONTEND_URL: backoffice.staging.bsport.io
    S3_BUCKET: s3://backoffice-staging-sandbox
    CLOUDFRONT_ID: EPNH7BAGZLI8K
    SLACK_WEBHOOK_URL: '${SLACK_STAGING_WEBHOOK_URL}'
    CLOUDFRONT_INVALIDATION_LAMBDA_URL: 'https://m4ptvmggmplbez5dwa7gkew4xa0bxjvd.lambda-url.eu-west-3.on.aws/'
  tags:
    - build-frontend
    - cluster:bsport-tooling

Buid Deploy Production:
  extends: .Build and deploy Base
  only:
    refs:
      - production
  variables:
    ENVIRONMENT: production
    FRONTEND_URL: backoffice.bsport.io
    S3_BUCKET: s3://bsport-eu-backoffice-production/
    CLOUDFRONT_ID: E321VOI5045USU
    SLACK_WEBHOOK_URL: '${SLACK_PRODUCTION_WEBHOOK_URL}'
    CLOUDFRONT_INVALIDATION_LAMBDA_URL: 'https://6pmc3n3l2yo5krr4v3jq6qud6i0fwkqj.lambda-url.eu-west-3.on.aws/'
    ACL_PARAM: '--acl public-read'
  tags:
    - build-frontend
    - cluster:bsport-tooling

Buid Deploy Dev:
  extends: .Build and deploy Base
  only:
    refs:
      - dev
  variables:
    ENVIRONMENT: dev
    FRONTEND_URL: backoffice.dev.bsport.io
    S3_BUCKET: s3://bsport-backoffice-assets-dev/
    CLOUDFRONT_ID: E250Q872DC5CN7
    SLACK_WEBHOOK_URL: '${SLACK_DEV_WEBHOOK_URL}'
    CLOUDFRONT_INVALIDATION_LAMBDA_URL: 'https://uc7e26gvpwrprl5hubmfe4zeou0zyqyu.lambda-url.eu-west-3.on.aws/'
  tags:
    - build-frontend
    - cluster:bsport-tooling

.Build Deploy Feature Branch Generic:
  except:
    - dev
    - master
    - production
  variables:
    CLOUDFRONT_ID: E2QPTVAZWMZ5F5
    SLACK_WEBHOOK_URL: '${SLACK_FEATURE_BRANCH_WEBHOOK_URL}'
    CLOUDFRONT_INVALIDATION_LAMBDA_URL: 'https://uc7e26gvpwrprl5hubmfe4zeou0zyqyu.lambda-url.eu-west-3.on.aws/'
  tags:
    - build-frontend
    - cluster:bsport-tooling
  retry:
    max: 2

  image: ${REGISTRY_ENDPOINT}/bsport/bsport-saas-builder:${CI_COMMIT_REF_NAME}
  stage: build-deploy-feature-branch
  # cache:
  #   files:
  #     - yarn.lock
  #   paths:
  #       - "$YARN_CACHE_DIR"
  #       - "$CYPRESS_CACHE_FOLDER/node_modules"
  #       - node_modules
  script:
    - mv /app/node_modules .
    - yarn install --frozen-lockfile # just to be sure
    - echo "FAILED" > .job_status
    - VERSION=`echo "$(cat ./VERSION)"`
    - export FEATURE_BRANCH_IDENTIFIER=`echo $CI_COMMIT_MESSAGE | sed -n 's/.*deploy-\(frontend-only-\)\{0,1\}chaos-env:\([[:alnum:]]\+\).*/\2/p'`
    - export ENVIRONMENT=$FEATURE_BRANCH_IDENTIFIER
    - export S3_BUCKET="s3://bsport-backoffice-assets-feature-branch-${FEATURE_BRANCH_IDENTIFIER}/"
    - export FRONTEND_URL="backoffice-${FEATURE_BRANCH_IDENTIFIER}.chaos.bsport.io"
    - export CLOUDFRONT_ID=`grep "$FEATURE_BRANCH_IDENTIFIER " ci/feature-branch-listing.txt | cut -d' ' -f2`
    - echo "Preparing VERSION:${VERSION} on ${ENVIRONMENT}"
    - echo "export default '`date +%F+%H+%M`';" > src/release-date.js
    - echo "export default '$VERSION';" > src/release.js
    - echo "\"$VERSION\"" > public/version.json
    - VERSION_SHA="${VERSION}-${CI_COMMIT_SHORT_SHA}"
    - echo "export default '$VERSION_SHA';" > src/release-sha.js
    - yarn updateTranslation
    - yarn build
    - sed -i "s/FEATURE_BRANCH_IDENTIFIER/${FEATURE_BRANCH_IDENTIFIER}/g" envs/${ENV_TEMPLATE_FILE}
    - mv envs/${ENV_TEMPLATE_FILE} build/env.js
    - export SENTRY_NO_PROGRESS_BAR=1
    - ./scripts/prepare-sentry-release.sh $VERSION_SHA $FRONTEND_URL
    - rm ./build/static/js/*.js.map
    - aws s3 cp ./build/ $S3_BUCKET --recursive --only-show-errors $ACL_PARAM
    - scripts/invalidate-cloudfront.sh $CLOUDFRONT_ID $CLOUDFRONT_INVALIDATION_TOKEN $CLOUDFRONT_INVALIDATION_LAMBDA_URL
    - scripts/prepare-sentry-deploy.sh $VERSION_SHA $ENVIRONMENT
    - echo "SUCCESS" > .job_status
    - cat .job_status

  after_script:
    - STATUS=`echo "$(cat .job_status)"`
    - echo "$STATUS"
    - cat .job_status
    - export STATUS
    - '[[ "$STATUS" = "SUCCESS" ]] && COLOR="#36a64f" || COLOR="#E00201"'
    - '[[ "$STATUS" = "SUCCESS" ]] && SUCCESS_ICON="https://pluspng.com/img-png/success-png-success-icon-image-23194-400.png" || SUCCESS_ICON="http://www.pngall.com/wp-content/uploads/2016/06/Fail-Stamp-PNG-Clipart.png"'
    - export SUCCESS_ICON

    - VERSION=`echo "$(cat ./VERSION)"`
    - '[[ $VERSION != $OLD_VERSION ]] && CHANGELOG=`git grep -B 200 ${OLD_VERSION} CHANGELOG.md | grep -A ${VERSION} || echo="Unable to find release note";` || CHANGELOG="Technical release";'
    - export CHANGELOG

    - export FEATURE_BRANCH_IDENTIFIER=`echo $CI_COMMIT_MESSAGE | sed -n 's/.*deploy-\(frontend-only-\)\{0,1\}chaos-env:\([[:alnum:]]\+\).*/\2/p'`
    - envsubst < ./slack_template_feature-branch.json > slack_template2.json
    - cat slack_template2.json
    - 'curl -s -d @slack_template2.json --header "Content-Type: application/json" "${SLACK_WEBHOOK_URL}" || exit 0'

Build Deploy Feature Branch Backend And Frontend:
  extends: .Build Deploy Feature Branch Generic
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy-chaos-env:/
  variables:
    ENV_TEMPLATE_FILE: template-feature-branch

Build Deploy Feature Branch Frontend Only:
  extends: .Build Deploy Feature Branch Generic
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy-frontend-only-chaos-env:/
  variables:
    ENV_TEMPLATE_FILE: template-frontend-only-feature-branch
