Build Deploy Staging:
  extends: .Build and deploy Base
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - when: never
  variables:
    S3BUCKETNAME: cdn-staging-sandbox
    ENVIRONMENT: staging
    ACL_PARAM: '--acl public-read'
    CLOUDFRONT_ID: E1ZLJRXTF8O188
    SLACK_WEBHOOK_URL: "${SLACK_STAGING_WEBHOOK_URL}"
    CDN_DOMAIN: cdn.staging.bsport.io
    INVALIDATION_LAMBDA_URL: https://m4ptvmggmplbez5dwa7gkew4xa0bxjvd.lambda-url.eu-west-3.on.aws/

Build Deploy Production:
  extends: .Build and deploy Base
  rules:
    - if: $CI_COMMIT_REF_NAME == "production"
      when: always
    - when: never
  variables:
    S3BUCKETNAME: bsport-cdn
    ENVIRONMENT: production
    ACL_PARAM: '--acl public-read'
    CLOUDFRONT_ID: E3PVSAXDFQZX1T 
    SLACK_WEBHOOK_URL: "${SLACK_PRODUCTION_WEBHOOK_URL}"
    CDN_DOMAIN: cdn.bsport.io
    INVALIDATION_LAMBDA_URL: https://6pmc3n3l2yo5krr4v3jq6qud6i0fwkqj.lambda-url.eu-west-3.on.aws/
 
Build Deploy Dev:
  extends: .Build and deploy Base
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: always
    - when: never
  variables:
    ENVIRONMENT: dev
    ACL_PARAM: '--acl public-read'
    SLACK_WEBHOOK_URL: "${SLACK_DEV_WEBHOOK_URL}"
    S3BUCKETNAME: bsport-widget-assets-dev
    CLOUDFRONT_ID: E2YERBKPKQC7FE
    CDN_DOMAIN: cdn.dev.bsport.io
    INVALIDATION_LAMBDA_URL: https://uc7e26gvpwrprl5hubmfe4zeou0zyqyu.lambda-url.eu-west-3.on.aws/

Build Deploy Feature Branch:
  extends: .Build and deploy Base
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: never
    - if: $CI_COMMIT_TAG =~ /deploy-frontend-only-/
      when: always
    - when: never
  variables:
    SLACK_WEBHOOK_URL: "${SLACK_FEATURE_BRANCH_WEBHOOK_URL}"
    INVALIDATION_LAMBDA_URL: https://uc7e26gvpwrprl5hubmfe4zeou0zyqyu.lambda-url.eu-west-3.on.aws/

  script:
    - export FEATURE_BRANCH_IDENTIFIER=`echo $CI_COMMIT_TAG | sed -n 's/.*deploy-\(frontend-only-\)\{0,1\}\([[:alnum:]_-]\+\).*/\2/p'`
    - export ENVIRONMENT=$FEATURE_BRANCH_IDENTIFIER
    - export S3BUCKETNAME=bsport-widget-assets-feature-branch-$FEATURE_BRANCH_IDENTIFIER
    - export CLOUDFRONT_ID=`grep "$FEATURE_BRANCH_IDENTIFIER " ci/feature-branch-listing.txt | cut -d' ' -f2`
    - export CDN_DOMAIN=cdn-${FEATURE_BRANCH_IDENTIFIER}.chaos.bsport.io
    - mv /app/node_modules .
    - echo "FAILED" > .job_status
    - yarn install --frozen-lockfile # just to be sure (done in prepare-image)
    - ./build_prod.sh
    - echo "SUCCESS" > .job_status

.Build and deploy Base:
  image: ${REGISTRY_ENDPOINT}/bsport/bsport-widget-builder:${CI_COMMIT_REF_NAME}
  stage: build-deploy 
  tags:
    - high-ram
    - cluster:bsport-tooling
  script:
    - mv /app/node_modules .
    - echo "FAILED" > .job_status
    - yarn install --frozen-lockfile # just to be sure (done in prepare-image)
    - ./build_prod.sh
    - echo "SUCCESS" > .job_status

  after_script:
    - STATUS=`echo "$(cat .job_status)"`
    - echo "$STATUS"
    - cat .job_status
    - export STATUS
    - '[[ "$STATUS" = "SUCCESS" ]] && COLOR="#36a64f" || COLOR="#E00201"'
    - '[[ "$STATUS" = "SUCCESS" ]] && SUCCESS_ICON="https://pluspng.com/img-png/success-png-success-icon-image-23194-400.png" || SUCCESS_ICON="http://www.pngall.com/wp-content/uploads/2016/06/Fail-Stamp-PNG-Clipart.png"'
    - export SUCCESS_ICON
    - envsubst < ./slack_template.json > slack_template2.json
    - cat slack_template2.json
    - 'curl -s -d @slack_template2.json --header "Content-Type: application/json" "${SLACK_WEBHOOK_URL}" || exit 0'
