Deploy Base:
  # Temp : Prefix with monorepo as it is still store on bsport-saas-builder registry
  image: ${REGISTRY_ENDPOINT}/${REGISTRY_NAME}:monorepo-${CI_COMMIT_REF_NAME}
  stage: deploy
  tags:
    - build-frontend
    - cluster:bsport-tooling
  extends:
    - .before-script-install-node-modules
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: "never"
    - if: $CI_COMMIT_REF_NAME == $TARGET_BRANCH
      when: "on_success"
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH
      when: "on_success"
  script:
    - echo "Start deploying projects ..."
    - echo "TARGET_BRANCH ~> $TARGET_BRANCH"
    - echo "ENV ~> $ENV"
    - git fetch origin $TARGET_BRANCH
    - pnpm exec nx affected --target=ci:deploy --base=origin/$TARGET_BRANCH~1 --head=HEAD $ENV

Deploy Dev:
  extends: Deploy Base
  variables:
    TARGET_BRANCH: "dev"
    ENV: "dev"

Deploy Staging:
  extends: Deploy Base
  variables:
    TARGET_BRANCH: "staging"
    ENV: "staging"

Deploy Production:
  extends: Deploy Base
  variables:
    TARGET_BRANCH: "main"
    ENV: "production"
