Debug Deploy:
  image: node:22-alpine
  stage: deploy

  tags:
    - build-frontend
    - cluster:bsport-tooling

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: "never"
    - when: always

  script:
    - echo "Start deploying projects ..."
    - echo "List variables ~>"
    - echo "CI_PIPELINE_SOURCE ~> $CI_PIPELINE_SOURCE"
    - echo "CI_COMMIT_BRANCH ~> $CI_COMMIT_BRANCH"
    - echo "CI_COMMIT_REF_NAME ~> $CI_COMMIT_REF_NAME"
    - echo "CI_MERGE_REQUEST_ID ~> $CI_MERGE_REQUEST_ID"

Deploy Base:
  image: node:22-alpine
  stage: deploy

  tags:
    - build-frontend
    - cluster:bsport-tooling

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: "never"
    - if: $CI_COMMIT_REF_NAME == $TARGET_BRANCH
      when: "on_success"
    - when: "never"

  script:
    - echo "Start deploying projects ..."
    - echo "TARGET_BRANCH ~> $TARGET_BRANCH"
    - echo "ENV ~> $ENV"
    - git fetch origin $TARGET_BRANCH
    - pnpm exec nx affected --target=ci:deploy --base=origin/$TARGET_BRANCH~1 --head=HEAD $ENV

Deploy Dev:
  extends: Deploy Base
  interruptible: true
  variables:
    TARGET_BRANCH: $BRANCH_DEV
    ENV: $ENV_DEV

Deploy Staging:
  extends: Deploy Base
  variables:
    TARGET_BRANCH: $BRANCH_STAGING
    ENV: $ENV_STAGING

Deploy Production:
  extends: Deploy Base
  variables:
    TARGET_BRANCH: $BRANCH_PRODUCTION
    ENV: $ENV_PRODUCTION
