#!/bin/bash

. "$(dirname "$0")/_/husky.sh"

CYAN='\e[36m'
NC='\033[0m'

branch=$(git branch --show-current)

match=`echo $branch | grep -Po "^[0-9]+" || echo 0`

if [ $match -gt 0  ];
then
  
	COMMITS=$(git log --since=2.weeks dev..$branch | grep "ISSUE: #$match" | wc -l)
	if [ $COMMITS -gt 0 ]
	then
		exit
	else
	  echo "Append ticket name at the end of the message commit"
	  echo "${NC}"

	  message=$(cat $1)
	  issueNumber=$(echo $branch | grep -E -o "^[[:digit:]]+" | cat)
	  printf "$message\n\n[ISSUE: #$issueNumber]\n" > $1
  fi
fi
