import FranchiseShopItemTemplateDetailInventoryBulkUpdateForm from './FranchiseShopItemTemplateDetailInventoryBulkUpdateForm.component';

export default FranchiseShopItemTemplateDetailInventoryBulkUpdateForm;
