import CommunicationSentGroupConfigSmartlistSelectionPanel from './CommunicationSentGroupConfigSmartlistSelectionPanel.component';

export default CommunicationSentGroupConfigSmartlistSelectionPanel;
