.Deploy Base:
  image: ${REGISTRY_ENDPOINT}/${REGISTRY_NAME}:${CI_COMMIT_REF_SLUG}
  stage: deploy
  tags:
    - build-frontend
    - cluster:bsport-tooling
  extends:
    - .before-script-install-node-modules
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: "never"
    - if: $CI_COMMIT_REF_NAME == $TARGET_BRANCH
      when: "on_success"
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH
      when: "on_success"
  script:
    - echo "Start deploying projects ..."
    - echo "Target branch is $TARGET_BRANCH"
    - echo "Target environment is $ENV"
    - echo "Previous latest commit, serving as base, is $CI_COMMIT_BEFORE_SHA"
    - git fetch origin $CI_COMMIT_BEFORE_SHA
    - echo "*"
    - echo "⏳ Build translations"
    - pnpm run -w translation:update
    - echo "✅ Translations have been updated"
    - echo "*"
    - echo "⏳ Set API environment"
    - pnpm run -w api-environment:set $ENV
    - echo "✅ the API environment has been set"
    - echo "*"
    - echo "🔱 These are the affected projects :"
    - pnpm exec nx show projects --affected --base=$CI_COMMIT_BEFORE_SHA --head=HEAD
    - echo "*"
    - echo "⏳ Build affected projects and their dependencies"
    - pnpm exec nx affected --target=ci:build --base=$CI_COMMIT_BEFORE_SHA --head=HEAD $ENV
    - echo "✅ All affected projets have been rebuilt"
    - echo "*"
    - echo "⏳ Deploy affected projects builds"
    - pnpm exec nx affected --target=ci:deploy --base=$CI_COMMIT_BEFORE_SHA --head=HEAD $ENV
    - echo "✅ All affected projets have been deployed"

Deploy Dev:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "dev"
    ENV: "dev"

Deploy Staging:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "staging"
    ENV: "staging"

Deploy Production:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "production"
    ENV: "production"
