include:
  - local: tools/ci/deploy-common.yml

.Deploy Base:
  extends: .Deploy Common Base
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: "never"
    - if: $CI_COMMIT_REF_NAME == $TARGET_BRANCH
      when: "on_success"
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH
      when: "on_success"
  script:
    - echo "Target branch is $TARGET_BRANCH"
    - echo "Target environment is $ENV"
    - echo "Previous latest commit, serving as base, is $CI_COMMIT_BEFORE_SHA"
    - bash tools/scripts/deploy.sh $CI_COMMIT_BEFORE_SHA $ENV

Deploy Dev:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "dev"
    ENV: "dev"

Deploy Staging:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "staging"
    ENV: "staging"

Deploy Production:
  extends: .Deploy Base
  variables:
    TARGET_BRANCH: "production"
    ENV: "production"
