export enum COACH_PAYMENT_RULE_TYPE {
  COACH_PAYMENT_RULE_FOR_SESSION = 0,
  COACH_PAYMENT_RULE_FOR_APPOINTMENT = 1,
  COACH_PAYMENT_RULE_FOR_GROUP_ACTIVITY = 2,
  COACH_PAYMENT_RULE_FOR_WORKSHOP = 3,
}
