export const APPOINTMENT_ACTION_ATTEND = "attend";
export const APPOINTMENT_ACTION_CANCEL_ON_TIME = "cancelOnTime";
export const APPOINTMENT_ACTION_MAKES_CANCEL_TOO_LATE = "cancelTooLate";

export type AppointmentAction =
  | typeof APPOINTMENT_ACTION_ATTEND
  | typeof APPOINTMENT_ACTION_CANCEL_ON_TIME
  | typeof APPOINTMENT_ACTION_MAKES_CANCEL_TOO_LATE;

export const APPOINTMENT_ACTIONS_MAP_TO_APPOINTMENT_EVENT_KIND: Record<
  AppointmentAction,
  number
> = {
  [APPOINTMENT_ACTION_ATTEND]: 0,
  [APPOINTMENT_ACTION_CANCEL_ON_TIME]: 1,
  [APPOINTMENT_ACTION_MAKES_CANCEL_TOO_LATE]: 2,
};

export const APPOINTMENT_ACTIONS_EVENT_KIND = [0, 1, 2];

export const APPOINTMENT_EVENT_KIND_MAP_TO_APPOINTMENT_ACTIONS: Record<
  number,
  AppointmentAction
> = {
  0: APPOINTMENT_ACTION_ATTEND,
  1: APPOINTMENT_ACTION_CANCEL_ON_TIME,
  2: APPOINTMENT_ACTION_MAKES_CANCEL_TOO_LATE,
};
