exports.PAYMENT_ENGINE_BSPORT = 0;
exports.PAYMENT_ENGINE_STRIPE = 1;

exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CASH = 0;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CB = 1;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_SEPA = 2;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CHECK = 3;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_HOLIDAY_CHECK = 4;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_AMEX = 5;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_DISPUTE = 6;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_TRANSFER = 7;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_OTHER = 8;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_BANCONTACT = 9;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_IDEAL = 10;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_SOFORT = 11;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_EPS = 12;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_GIROPAY = 13;
exports.PAYMENT_GROUP_METHOD_IDENTIFIER_MOBILEPAY = 14;

exports.REVERSE_ON_PAYMENT_METHOD = 0;
exports.REVERSE_ON_DEBT = 1;
exports.REVERSE_ON_NEW_PAYMENT_METHOD = 2;

exports.PAYMENT_GROUP_METHOD_BY_ENGINE = {
  [exports.PAYMENT_ENGINE_STRIPE]: [
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_SEPA,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CB,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_BANCONTACT,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_IDEAL,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_SOFORT,
    // PAYMENT_GROUP_METHOD_IDENTIFIER_EPS,
    // PAYMENT_GROUP_METHOD_IDENTIFIER_GIROPAY,
    // PAYMENT_GROUP_METHOD_IDENTIFIER_MOBILEPAY,
  ],
  [exports.PAYMENT_ENGINE_BSPORT]: [
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_SEPA,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CB,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CASH,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_CHECK,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_HOLIDAY_CHECK,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_AMEX,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_TRANSFER,
    exports.PAYMENT_GROUP_METHOD_IDENTIFIER_OTHER,
  ],
};
