// @ts-nocheck
export const TUTORIAL_GENERIC_DIALOG_WELCOME = 1;
export const TUTORIAL_GENERIC_DIALOG_SECTION_FINISH = 2;
export const TUTORIAL_GENERIC_DIALOG_ALL_FINISH = 3;
export const TUTORIAL_GENERIC_DIALOG_SHARE_SECTION = 4;
export const TUTORIAL_GENERIC_DIALOG_SHARE_LESSON = 5;

export const ALL_TUTORIAL_LESSONS_FINISH_DIALOG_OPEN_QUERY_PARAMS =
  'finishAllDialog=true';

export const TUTORIAL_WELCOME_DIALOG_OPEN_QUERY_PARAMS =
  'withTutorialDialog=true';
