import {
  UNEVEN_INVOICE_ALERT,
  NEW_ORDER_ALERT,
  REMINDER_NOTE_ALERT_KIND,
  PRIVATE_BOOKING_INCOMPLETE_ALERT,
  UNREAD_COMMUNICATION as UNREAD_COMMUNICATION_ALERT,
  COMPANY_ONBOARDING_ALERT,
  UNPAID_PRIVATE_BOOKING_ALERT,
  NEW_TUTORIAL_SECTION_OR_LESSON as NEW_TUTORIAL_SECTION_OR_LESSON_ALERT,
  REPLACEMEMENT_REQUEST_LATE_ALERT_KIND,
} from '@bsport/common/lib/master-data/alerting_kind';

export enum AlertKind {
  UNEVEN_INVOICE = UNEVEN_INVOICE_ALERT.alert_kind,
  NEW_ORDER = NEW_ORDER_ALERT.alert_kind,
  REMINDER_NOTE = REMINDER_NOTE_ALERT_KIND.alert_kind,
  PRIVATE_BOOKING_INCOMPLETE = PRIVATE_BOOKING_INCOMPLETE_ALERT.alert_kind,
  COMPANY_ONBOARDING = COMPANY_ONBOARDING_ALERT.alert_kind,
  UNPAID_PRIVATE_BOOKING = UNPAID_PRIVATE_BOOKING_ALERT.alert_kind,
  NEW_TUTORIAL_SECTION_OR_LESSON = NEW_TUTORIAL_SECTION_OR_LESSON_ALERT.alert_kind,
  REPLACEMEMENT_REQUEST_LATE = REPLACEMEMENT_REQUEST_LATE_ALERT_KIND.alert_kind,
  UNREAD_COMMUNICATION = UNREAD_COMMUNICATION_ALERT.alert_kind,
}

export enum CompanyOnboardingTypes {
  VERIFICATION = 'verification',
  CREATION = 'creation',
  PAYOUT = 'payout',
}

export enum PayPalPendingActionType {
  PRIMARY_EMAIL_CONFIRMATION = 'primary_email_confirmation',
  REQUIRES_MORE_INFORMATION = 'requires_more_information',
  ISSUE_CHECK_ACCOUNT = 'issue_check_account',
  ISSUE_REPEAT_ONBOARDING = 'issue_repeat_onboarding',
}

export enum AlertingActions {
  EQUILIBRATE = 'equilibrate',
  FINALIZE = 'finalize',
}
