import {
  SUBSCRIPTION_NOTIFICATION_CREATION,
  SUBSCRIPTION_NOTIFICATION_END,
  SUBSCRIPTION_NOTIFICATION_FIRST_BILLING,
} from "@bsport/store-cdp-marketing-notification";

export const SUBSCRIPTION_STATUS_CREATION = "subscriptionCreation";
export const SUBSCRIPTION_STATUS_FIRST_BILLING = "subscriptionFirstBilling";
export const SUBSCRIPTION_STATUS_END = "subscriptionEnd";

export const DEFAULT_SUBSCRIPTION_EVENT_KIND =
  SUBSCRIPTION_NOTIFICATION_CREATION;

export const SUBSCRIPTIONS_EVENT_KIND_MAP_TO_SUBSCRIPTION_STATUS: Record<
  number,
  SubscriptionStatus
> = {
  [SUBSCRIPTION_NOTIFICATION_CREATION]: SUBSCRIPTION_STATUS_CREATION,
  [SUBSCRIPTION_NOTIFICATION_FIRST_BILLING]: SUBSCRIPTION_STATUS_FIRST_BILLING,
  [SUBSCRIPTION_NOTIFICATION_END]: SUBSCRIPTION_STATUS_END,
};

export const SUBSCRIPTIONS_STATUS_EVENT_KIND = [
  SUBSCRIPTION_NOTIFICATION_CREATION,
  SUBSCRIPTION_NOTIFICATION_FIRST_BILLING,
  SUBSCRIPTION_NOTIFICATION_END,
];

export type SubscriptionStatus =
  | typeof SUBSCRIPTION_STATUS_CREATION
  | typeof SUBSCRIPTION_STATUS_FIRST_BILLING
  | typeof SUBSCRIPTION_STATUS_END;

export const SUBSCRIPTION_STATUS_MAP_TO_SUBSCRIPTION_EVENT_KIND: Record<
  SubscriptionStatus,
  number
> = {
  [SUBSCRIPTION_STATUS_CREATION]: SUBSCRIPTION_NOTIFICATION_CREATION,
  [SUBSCRIPTION_STATUS_FIRST_BILLING]: SUBSCRIPTION_NOTIFICATION_FIRST_BILLING,
  [SUBSCRIPTION_STATUS_END]: SUBSCRIPTION_NOTIFICATION_END,
};
