#!/usr/bin/env sh
if [ "$ECOSYSTEM_SKIP_HOOKS" != "true" ] && [ -z "$CI" ]; then
    pnpm install --no-lockfile --ignore-scripts
    # Use Nx to rely on postinstall cache
    pnpm run -w postinstall
fi
