#!/usr/bin/env sh

# 3rd argument is a flag to indicate if we are checking out a branch
# https://git-scm.com/docs/githooks.html#_post_checkout
if [ "$3" -eq 0 ]; then
    # Not checking out a branch, so we can skip this hook
    exit 0
fi

if [ "$ECOSYSTEM_SKIP_HOOKS" != "true" ] && [ "$SKIP_INSTALL" != "true" ] && [ -z "$CI" ]; then
    exec < /dev/tty
    echo "Would you like to reinstall all dependencies? (y/N) "
    read REPLY
    if [ "$REPLY" != "y" ] && [ "$REPLY" != "Y" ]; then
        echo "Skipping dependency reinstallation"
        exit 0
    fi

    pnpm install --no-lockfile --ignore-scripts
    # Use Nx to rely on postinstall cache
    pnpm run -w postinstall
fi
