export const DATE_AFTER = 0;
export const DATE_BEFORE = 1;
export const DATE_BETWEEN = 2;
export const DATE_EXACT = 3;
export const DURATION_AFTER = 4;
export const DURATION_EXACT = 6;
export const DURATION_BETWEEN = 7;
export const DURATION_BEFORE_PAST = 9;
export const DURATION_EXACT_PAST = 10;
export const DURATION_BETWEEN_PAST = 11;

export const DURATION_LIST = [
  DURATION_AFTER,
  DURATION_EXACT,
  DURATION_BETWEEN,
  DURATION_BEFORE_PAST,
  DURATION_EXACT_PAST,
  DURATION_BETWEEN_PAST,
];

export const SMARTLIST_INCLUDE_ALL_MEMBERS = 0;
export const SMARTLIST_INCLUDE_ONLY_ACTIVE_MEMBERS = 1;
export const SMARTLIST_INCLUDE_ONLY_ARCHIVED_MEMBERS = 2;

export const SMARTLIST_MEMBERS_BASE_OPTIONS = [
  SMARTLIST_INCLUDE_ALL_MEMBERS,
  SMARTLIST_INCLUDE_ONLY_ACTIVE_MEMBERS,
  SMARTLIST_INCLUDE_ONLY_ARCHIVED_MEMBERS,
];
