export type Theme = {
  id: string;
  primary_color: string;
  secondary_color: string;
  payment_method_available: number[];
  payment_method_available_basket: number[];
  payment_method_available_subscription: number[];
  payment_method_available_manager: number[];
  show_offers_filling: boolean;
  contact_email: string;
  currency: string;
  currency_display: string;
  is_whereby_integration_allowed: boolean;
  is_whereby_integration_enabled: boolean;
  first_name_label: string;
  last_name_label: string;
  default_booking_ordering: string;
  general_terms_and_conditions: string;
  general_terms_of_use: string;
  waiver: string;
  email_sender_address: string;
  websiteURL: string;
  scheduleURL: string;
  instagramURL: string;
  facebookURL: string;
  android_app_url: string;
  ios_app_url: string;
  hideCoach: boolean;
  show_cancelled_offers_customer: boolean;
  show_cancelled_offers_manager: boolean;
  cover?: string;
  company: number;
  company_name: string;
  timezone_name: string;
  hide_least_specific_payment_pack: boolean;
  default_attendance: boolean;
  consumer_regularize_debt: boolean;
  accept_double_booking: boolean;
  gtmId?: string;
  facebookPixelId?: string;
  stripe_pk_key: string;
  vod: boolean;
  locale: string;
  basket_expiration_days: number;
  show_booked_gender_offer: boolean;
  is_checking_balance: boolean;
  nb_to_check_balance: number;
  gender_max_shift_for_booking: boolean;
  vod_providers: Array<number>;
  show_workshops_customer: boolean;
};

export type ThemeState = {
  theme: Theme;
  createOrUpdate: {
    loading: boolean;
    error?: Error;
  };
  loading: boolean;
  error?: Error;
};
