export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_FILE_TOO_LARGE_ERROR =
  'fileTooLargeError';
export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_NOT_CSV_FILE_ERROR =
  'notCsvFileError';
export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_INCORRECT_DATA_ERROR =
  'incorrectDataError';

export const UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_ALL_ERRORS = [
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_FILE_TOO_LARGE_ERROR,
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_NOT_CSV_FILE_ERROR,
  UNIQUE_CODE_PER_USAGE_COUPON_UPLOAD_INCORRECT_DATA_ERROR,
];

export enum CouponErrorCodes {
  COUPON_CODES_CONFLICTING_WITH_OTHER_COUPONS = 5000,
  UNIQUE_CODES_CANNOT_BE_APPENDED_BECAUSE_CONFLICT = 5001,
  UNIQUE_CODES_CANNOT_BE_REPLACED_BECAUSE_CONFLICT = 5003,
  COUPON_UNIQUE_CODE_CANNOT_BE_APPLIED_SEVERAL_ITEMS = 5004,
  UNIQUE_CODE_LOCKED = 5006,
  /** Provided error code for invalid (expired, not existing) giftcard codes */
  GIFTCARD_EXCEPTION = 45009,
  /** Attempting attaching a giftcard before allowed activation date */
  GIFTCARD_INVALID_ACTIVATION_DATE = 45010,
}

export const VOUCHER_CODE_CSV_FILE_SIZE_LIMIT_IN_BYTES = 1000000;

export const VOUCHER_CODE_CHARACTERS_NUMBER_LIMIT = 100;

export const VOUCHER_CODE_CSV_FILE_MIME_TYPE = 'text/csv';

export const VOUCHER_CODE_CSV_FILE_MIME_TYPE_FOR_WINDOWS_FIREFOX =
  'application/vnd.ms-excel';

export const VOUCHER_CODE_TABLE_PAGE_SIZE = 9;

export const COUPON_TYPE_FILTER_DEFAULT_VALUE = 'DEFAULT';

export const COUPON_DELETE_MODAL_COOLDOWN_SECONDS = 10;
