/**
 *  @description These error codes are used in the translations files.
 */
exports.COUPON_CODES_CONFLICTING_WITH_OTHER_COUPONS = 5000;
exports.UNIQUE_CODES_CANNOT_BE_APPENDED_BECAUSE_CONFLICT = 5001;
exports.CANNOT_REDEEM_CODE_BECAUSE_NOT_USED = 5002;
exports.UNIQUE_CODES_CANNOT_BE_REPLACED_BECAUSE_CONFLICT = 5003;
exports.COUPON_UNIQUE_CODE_CANNOT_BE_APPLIED_SEVERAL_ITEMS = 5004;
exports.COUPON_UNIQUE_CODE_NOT_AVAILABLE = 5005;
exports.UNIQUE_CODE_LOCKED = 5006;
exports.GIFTCARD_EXCEPTION = 45009;
exports.GIFTCARD_INVALID_ACTIVATION_DATE = 45010;
